import Mathlib
import PhD.TauCeti.Code.PadicFunctionalAnalysis.Operator.Examples
import PhD.TauCeti.Code.NewtonPolygons.AddVal.Discrete
open Filter Topology
open scoped ZeroAtInfty ENNReal BoundedContinuousFunction
#check @ZeroAtInftyContinuousMap.comp
#check @ZeroAtInftyContinuousMap.zero_at_infty'
#check @zero_at_infty
#check @ZeroAtInftyContinuousMapClass.zero_at_infty
#check @Summable.tsum_const_smul
#check @Summable.tsum_smul_const
#check @HasSum.mapL
#check @ContinuousLinearMap.map_tsum
#check @ULift.discreteTopology
#check @Homeomorph.ulift
#check @Equiv.toHomeomorphOfDiscrete
#check @Homeomorph.toCocompactMap
#check @CocompactMap
#check @Homeomorph.coe_toCocompactMap
#check @BoundedContinuousFunction.evalCLM
#check @BoundedContinuousFunction.norm_eq_iSup_norm
#check @ContinuousMap.norm_le
#check @ContinuousMap.norm_coe_le_norm
#check @ContinuousMap.norm_eq_iSup_norm
#check @IsCompact.exists_isMaxOn
#check @Set.Finite.toFinset
#check @Finset.max'
#check @Finset.exists_max_image
#check @Valuation.IsRankOneDiscrete.exists_isUniformizer
#check @Valuation.exists_isUniformizer_of_isRankOneDiscrete
#check @Valuation.IsRankOneDiscrete.exists_generator_lt_one
#check @Valuation.mem_valueGroup
#check @ValuativeRel.valueGroup
#check @Valuation.IsRankOneDiscrete.generator_lt_one
#check @Valuation.IsRankOneDiscrete.zpowers_generator
#check @Valuation.IsUniformizer.val
#check @NormedField.valuation_apply
#check @NormedField.toNormedField
#check @Padic.norm_eq_zpow_neg_valuation
#check @PadicComplex.norm_extends
#check @Submodule.ClosedComplemented
#check @ContinuousLinearMap.IsIdempotentElem
#check @ContinuousLinearEquiv.ofBijective
#check @LinearIsometryEquiv.trans
#check @LinearIsometryEquiv.symm
#check @LinearIsometryEquiv.refl
#check @LinearIsometryEquiv.norm_map
#check @LinearIsometry.norm_map
#check @LinearIsometryEquiv.toLinearEquiv
#check @ContinuousLinearEquiv.trans
#check @ContinuousLinearEquiv.prodCongr
#check @ContinuousLinearEquiv.piCongrRight
#check @LinearIsometryEquiv.piLpCongrRight
#check @Module.rank
#check @Module.finrank
#check @LinearEquiv.finrank_eq
#check @FiniteDimensional.of_finite_basis
#check @Module.Finite.of_basis
#check @Cardinal.mk_eq_nat_iff_finset
#check @Set.Countable.exists_eq_range
#check @Set.countable_setOf_finite_subset
#check @Set.Countable.image
#check @Countable
#check @Submodule.span_le
#check @Submodule.span_image
#check @Submodule.map_span

#check @DenseRange.comp
#check @Dense.mono
#check @Submodule.topologicalClosure_eq_top_iff
#check @Submodule.dense_iff_topologicalClosure_eq_top
#check @IsClosed.closure_eq
#check @Submodule.isClosed_topologicalClosure
#check @LinearIndependent.ne_zero
#check @linearIndependent_iff'
#check @LinearIndependent.comp
#check @Module.Basis.ofVectorSpace
#check @Module.Basis.ofVectorSpaceIndex
#check @Module.Free.exists_basis
#check @Module.Free.ChooseBasisIndex
#check @Module.Basis.reindex
#check @Module.Basis.mk
#check @Module.Basis.coe_mk
#check @Submodule.Quotient.mk_smul
#check @Submodule.Quotient.mk_add
#check @Submodule.mkQ
#check @Submodule.Quotient.mk_surjective
#check @Ideal.Quotient.mk
#check @Ideal.Quotient.field
#check @Submodule.Quotient.mk_eq_zero
#check @Submodule.mem_smul_top_iff
#check @Submodule.smul_mem_smul
#check @Submodule.span_induction
#check @Submodule.subset_span_finite_of_subset_span
#check @Fintype.linearCombination
#check @Submodule.mem_span_range_iff_exists_fun
#check @Set.InjOn
#check @LinearMap.graph
#check @ContinuousLinearMap.Ultra.exists_norm_quotKerEquivRange_symm_le
#check @ContinuousLinearMap.Ultra.quotKerEquivRangeL
#check @ContinuousLinearMap.Ultra.continuousLinearEquivOfBijective
#check @ContinuousLinearMap.Ultra.isOpenMap
#check @ContinuousLinearMap.Ultra.opNorm_pi_eq
#check @NormedRing.PseudoUniformizer.existsUnique_zpow_norm_smul_mem_Ioc
#check @Filter.Tendsto.exists_norm_eq_iSup
#check @Set.Finite.exists_maximal_wrt
#check @Finset.exists_max_image
#check @Nat.find
#check @Filter.eventually_cofinite
#check @Metric.closedBall
#check @Real.iSup_le
#check @Real.le_iSup_of_le
#check @ciSup_le
#check @le_ciSup
#check @iSup_congr
#check @Real.iSup_of_isEmpty
#check @tsum_eq_single
#check @Summable.tsum_eq_add_tsum_ite
#check @IsUltrametricDist.norm_tsum_eq_of_forall_lt
#check @IsUltrametricDist.norm_tsum_lt_of_forall_lt
#check @IsUltrametricDist.norm_add_eq_max_of_norm_ne_norm
#check @Padic.isUniformizer_p
#check @NormedField.normAddValZ
#check @NormedField.exists_norm_eq_zpow
#check @ContinuousMap.instNormedRing
#check @ContinuousMap.norm_eq_iSup_norm
#check @ContinuousMap.instCompleteSpace
#check @ContinuousMap.instNormedSpace

