import Mathlib
import PhD.TauCeti.Code.PadicFunctionalAnalysis.Operator.Examples
open Filter Topology
open scoped ZeroAtInfty ENNReal
#check @Module.Projective.of_split
#check @Module.Projective.of_lifting_property'
#check @Module.projective_lifting_property
#check @Module.Free.of_divisionRing
#check @IsField.toField
#check @Ideal.Quotient.maximal_ideal_iff_isField_quotient
#check @NormedField.valuation
#print NormedField.valuation
#check @Valuation.IsRankOneDiscrete
#check @Valuation.IsRankOneDiscrete.generator_mem_range
#check @Valuation.IsRankOneDiscrete.generator_zpowers_eq_range
#check @PadicComplex.norm_eq_norm
#check @PadicAlgCl.norm_eq_spectralNorm
#check @spectralNorm
#check @spectralNorm_eq_of_equiv
#check @IsUltrametricDist.instContinuousMap
#check @ContinuousMap.instIsUltrametricDist
#check @BoundedContinuousFunction.instIsUltrametricDist
example : IsUltrametricDist C(ℤ_[2], ℚ_[2]) := inferInstance
example : IsUltrametricDist (ℤ_[2] →ᵇ ℚ_[2]) := inferInstance
#check @PadicInt.mahlerEquiv
#check @lp.inftyNormedRing
#check @lp.instNormedRingInfty
example : NormedRing (lp (fun _ : ℕ ↦ ℚ_[2]) ∞) := inferInstance
example : NormedCommRing (lp (fun _ : ℕ ↦ ℚ_[2]) ∞) := inferInstance
example : NormOneClass (lp (fun _ : ℕ ↦ ℚ_[2]) ∞) := inferInstance
#check @lp.single
#check @lp.single_apply
#check @lp.norm_eq_ciSup
#check @memℓp_infty
#check @Memℓp.bddAbove
#check @lp.norm_le_of_forall_le
#check @lp.norm_apply_le_norm
#check @lp.coeFn_smul
#check @lp.ext
#check @ContinuousMap.liftZeroAtInfty
#check @ZeroAtInftyContinuousMap.comp
#check @ZeroAtInftyContinuousMap.coe_comp_to_continuous_fun
#check @Homeomorph.toCocompactMap
#check @CocompactMap.mk
#check @Equiv.toHomeomorphOfDiscrete
#check @Prod.norm_def
#check @Prod.nnnorm_def
#check @Pi.norm_def
#check @Pi.nnnorm_def
#check @pi_norm_le_iff_of_nonneg
#check @norm_le_pi_norm
#check @ContinuousLinearMap.Ultra.exists_bound_of_finite
#check @Submodule.ClosedComplemented
#check @Submodule.ClosedComplemented.isClosed
#check @ContinuousLinearMap.closedComplemented_ker_of_rightInverse
#check @Submodule.closedComplemented_bot
#check @LinearMap.range_eq_top
#check @ContinuousLinearMap.range_eq_top
#check @Submodule.topologicalClosure
#check @Submodule.le_topologicalClosure
#check @Submodule.topologicalClosure_minimal
#check @Submodule.closure_subset_topologicalClosure_span
#check @Submodule.span_singleton_eq_range
#check @Cardinal.mk_iUnion_le_sum_mk
#check @Cardinal.mk_biUnion_le
#check @Cardinal.mul_eq_left
#check @Cardinal.mk_le_of_injective
#check @Cardinal.mk_le_of_surjective
#check @Cardinal.eq
#check @Cardinal.mk_eq_nat_iff
#check @Set.Countable.mono
#check @Set.countable_iUnion
#check @Set.Finite.countable
#check @Cardinal.mk_set_le
#check @Cardinal.mk_le_aleph0
#check @LinearIndependent.cardinal_le_rank
#check @linearIndependent_le_finrank
#check @FiniteDimensional.finrank_eq_card_basis
#check @Module.finrank_pi
#check @Module.Finite.of_surjective
#check @Set.Countable.exists_eq_range
#check @Set.countable_setOf_finite_subset
#check @IsUltrametricDist.norm_tsum_le
#check @IsUltrametricDist.norm_tsum_le_of_forall_le
#check @NonarchimedeanAddGroup.summable_of_tendsto_cofinite_zero
#check @NonarchimedeanAddGroup.summable_iff_tendsto_cofinite_zero
#check @Summable.tendsto_cofinite_zero
#check @HasSum.tendsto_sum_nat
#check @hasSum_single
#check @hasSum_sum_of_ne_finset_zero
#check @tendsto_finset_sum
#check @Finset.sup_le_iff
#check @Finset.le_sup
#check @Finset.sup_eq_iSup
#check @Finset.exists_mem_eq_sup
#check @Finset.nnnorm_sum_le_sup_nnnorm
#check @IsUltrametricDist.nnnorm_sum_le_sup_nnnorm
#check @Finset.sup_const
#check @NNReal.coe_le_coe
#check @coe_nnnorm
#check @nnnorm_smul
#check @norm_smul
#check @norm_smul_le
#check @NormSMulClass
#check @NormSMulClass.norm_smul
#check @IsBoundedSMul.toNormSMulClass
#check @Padic.norm_eq_zpow_neg_valuation
#check @Padic.norm_p
#check @PadicInt.norm_eq_zpow_neg_valuation
#check @PadicInt.isUnit_iff
#check @PadicInt.norm_lt_one_iff_dvd
#check @ZeroAtInftyContinuousMap.instModule
#check @ZeroAtInftyContinuousMap.instNormedAddCommGroup
#check @ZeroAtInftyContinuousMap.instCompleteSpace
#check @ZeroAtInftyContinuousMap.norm_toBCF_eq_norm
#check @ZeroAtInftyContinuousMap.toBCF_injective
#check @ZeroAtInftyContinuousMap.isometry_toBCF
#check @ZeroAtInftyContinuousMap.coe_smul
#check @ZeroAtInftyContinuousMap.smul_apply
#check @ZeroAtInftyContinuousMap.coe_sum
#check @BoundedContinuousFunction.norm_eq_iSup_norm
#check @BoundedContinuousFunction.norm_coe_le_norm
#check @BoundedContinuousFunction.norm_le
#check @BoundedContinuousFunction.norm_smul_le
#check @BoundedContinuousFunction.instIsBoundedSMul
#check @BoundedContinuousFunction.instNormSMulClass
#check @BoundedContinuousFunction.norm_lt_iff_of_compact
#check @cocompact_eq_cofinite
#check @Real.mul_iSup_of_nonneg
#check @Real.iSup_mul_of_nonneg
#check @ciSup_le
#check @le_ciSup_of_le
#check @Real.sSup_le
#check @LinearIsometryEquiv.ofSurjective
#check @LinearIsometry.toLinearIsometryEquiv
#check @LinearIsometryEquiv.ofBijective
#check @LinearIsometryEquiv.toContinuousLinearEquiv
#check @ContinuousLinearEquiv.toLinearEquiv
#check @ContinuousLinearEquiv.comp_coe
#check @ContinuousLinearMap.comp_id
#check @ContinuousLinearMap.id_comp
#check @ContinuousLinearMap.ext
#check @LinearMap.mkContinuous
#check @LinearMap.mkContinuous_apply
#check @LinearMap.mkContinuous_norm_le
#check @AddMonoidHomClass.continuous_of_bound
#check @ContinuousLinearEquiv.ofBijective
#check @ContinuousLinearEquiv.equivOfInverse
#check @LinearIsometryEquiv.ofBounds
#check @IsIdempotentElem
#check @ContinuousLinearMap.isIdempotentElem_iff
#check @ContinuousLinearMap.IsIdempotentElem.range
#check @lp.instIsUltrametricDist
#check @NormedRing.not_isNoetherianRing_lp_infty
#check @NormedRing.IsTate
#check @NormedRing.IsMultiplicative
#check @NormedRing.PseudoUniformizer
#check @NormedRing.PseudoUniformizer.toUnitClosedBall
#check @NormedRing.PseudoUniformizer.ResidueRing
#check @NormedRing.PseudoUniformizer.ResidueModule
#check @NormedRing.PseudoUniformizer.mem_ideal_smul_top_iff_norm_lt_one
#check @NormedRing.PseudoUniformizer.ideal_eq_openUnitBallIdeal
#check @NormedRing.maximalIdeal_unitClosedBall
#check @NormedRing.isTate_of_normedAlgebra
#check @NormedRing.PseudoUniformizer.isBoundedSMul_rescaled
#check @NormedRing.PseudoUniformizer.exists_norm_rescaled_eq_zpow
#check @NormedRing.PseudoUniformizer.norm_toRescaled
#check @NormedRing.PseudoUniformizer.norm_le_norm_toRescaled
#check @NormedRing.PseudoUniformizer.norm_mul_norm_toRescaled_lt
#check @NormedRing.PseudoUniformizer.norm_toRescaled_eq_of_forall_exists_zpow
#check @Filter.Tendsto.exists_norm_eq_iSup
#check @Filter.Tendsto.exists_forall_norm_le
#check @Submodule.unitClosedBall
#check @Submodule.mem_unitClosedBall
#check @Subring.unitClosedBall
#check @Subring.mem_unitClosedBall
#check @NormedRing.openUnitBallIdeal
#check @NormedRing.mem_openUnitBallIdeal
#check @Submodule.Quotient.mk
#check @Submodule.Quotient.mk_eq_zero
#check @Submodule.Quotient.eq
#check @Submodule.mkQ_apply
#check @Submodule.mem_smul_top_iff
#check @Submodule.mem_ideal_smul_span_iff_exists_sum
#check @Ideal.mem_span_singleton
#check @IsUltrametricDist.norm_add_eq_max_of_norm_ne_norm
#check @IsUltrametricDist.norm_sum_le_sup
#check @IsUltrametricDist.nnnorm_add_le_max
#check @IsUltrametricDist.norm_add_le_max
#check @Finset.norm_sum_le_sup_norm
#check @Finset.sup'_le
#check @Finset.le_sup'
#check @Finset.sup'
#check @Finset.exists_mem_eq_sup'
#check @Finset.Nonempty
#check @Metric.tendsto_atTop
#check @Metric.cauchySeq_iff
#check @cauchySeq_tendsto_of_complete
#check @IsUltrametricDist.cauchySeq_of_tendsto_sub
#check @NonarchimedeanAddGroup.cauchySeq_iff
#check @cauchySeq_of_le_geometric
#check @cauchySeq_of_le_geometric_two
#check @tendsto_pow_atTop_nhds_zero_of_lt_one
#check @Equiv.ulift
#check @Equiv.sumCompl
#check @Equiv.Set.sumCompl
#check @Equiv.sumComm
#check @Equiv.prodComm
#check @Equiv.ofInjective
#check @Set.rangeFactorization
#check @Set.rangeSplitting
#check @LinearIndependent.injective
#check @Subtype.discreteTopology
#check @instDiscreteTopologySum
#check @Sum.discreteTopology
#check @Prod.discreteTopology
#check @ULift.instDiscreteTopology
example : DiscreteTopology (ULift.{3} ℕ) := inferInstance
example : DiscreteTopology (ℕ ⊕ ℕ) := inferInstance
example : DiscreteTopology (ℕ × ℕ) := inferInstance
example (S : Set ℕ) : DiscreteTopology S := inferInstance
example : DiscreteTopology Unit := inferInstance
example : DiscreteTopology (Fin 3) := inferInstance
#check @Fintype.card
#check @Nat.card
#check @ContinuousLinearMap.Ultra.opNorm_eq_iSup_div
#check @ContinuousLinearMap.Ultra.norm_le_opNorm_of_norm_le_one
