import Mathlib
import PhD.TauCeti.Code.PadicFunctionalAnalysis.Operator.Examples
open Filter Topology NormedRing
open scoped ZeroAtInfty ENNReal
#check @Submodule.closed_of_finiteDimensional
#check @exists_linearIndependent
#check @Set.countable_infinite_iff_nonempty_denumerable
#check @Set.Countable.exists_eq_range
#check @Denumerable.eqv
#check @ContinuousLinearEquiv.ofFinrankEq
#check @FiniteDimensional.nonempty_continuousLinearEquiv_of_finrank_eq
#check @Module.finrank_fin_fun
#check @Module.finrank_pi
#check @Submodule.Quotient.normedAddCommGroup
#check @Submodule.Quotient.completeSpace
#check @Submodule.Quotient.instNormedAddCommGroup
#check @AddSubgroup.normedAddCommGroupQuotient
#check @Submodule.ker_mkQ
#check @Submodule.mkQ_surjective
#check @Submodule.mkQ
#check @ContinuousLinearMap.closedComplemented_ker_of_rightInverse
#print Submodule.ClosedComplemented
#check @Submodule.ClosedComplemented.exists_isClosed_isCompl
#check @Submodule.ClosedComplemented.isClosed
#check @Submodule.ClosedComplemented.hasClosedComplement
#check @Submodule.mkQ_apply
#check @Submodule.liftQ
#check @Submodule.Quotient.norm_mk_le
#check @Submodule.Quotient.norm_mk_eq_sInf
#check @QuotientAddGroup.norm_mk_le
#check @Metric.infDist
#check @Metric.infDist_lt_iff
#check @Metric.infDist_pos_iff_notMem_closure
#check @IsClosed.notMem_iff_infDist_pos
#check @Metric.infDist_le_dist_of_mem
#check @Metric.infDist_eq_iInf
#check @FiniteDimensional.of_fintype_basis
#check @Module.Basis.ofVectorSpace
#check @Submodule.span_insert
#check @Submodule.mem_span_insert
#check @LinearIndependent.notMem_span_image
#check @LinearIndependent.not_mem_span_image
#check @Set.finite_or_infinite
#check @Set.Infinite.natEmbedding
#check @Module.Finite.of_surjective
#check @Submodule.finrank_mono
#check @LinearMap.finrank_range_le
#check @LinearIndependent.fintype_card_le_finrank
#check @finrank_span_le_card
#check @Module.Free.ChooseBasisIndex
#check @Submodule.Quotient.mk_smul
#check @Submodule.quotientRel
#check @Submodule.Quotient.mk_sub
#check @Submodule.mkQ_apply
#check @LinearMap.range_eq_top_of_surjective
#check @ContinuousLinearMap.ker
#check @ContinuousLinearMap.range
#check @ContinuousLinearMap.isClosed_ker
#check @ContinuousLinearMap.mem_ker
#check @ContinuousLinearMap.mem_range
#check @ContinuousLinearMap.coe_comp'
#check @ContinuousLinearMap.sub_apply
#check @ContinuousLinearMap.one_def
#check @ContinuousLinearMap.one_apply
#check @ContinuousLinearMap.mul_def
#check @ContinuousLinearMap.mul_apply
#check @ContinuousLinearMap.coe_mk'
#check @ContinuousLinearMap.copy
#check @LinearMap.toContinuousLinearMap
#check @ContinuousLinearMap.restrictScalars
#check @ContinuousLinearMap.codRestrict
#check @ContinuousLinearMap.subtypeL
#check @ContinuousLinearMap.projKerOfRightInverse
#check @ContinuousLinearMap.lsmul
#check @ContinuousLinearMap.pi
#check @ContinuousLinearMap.proj
#check @ContinuousLinearMap.smulRight
#check @ContinuousLinearMap.toSpanSingleton
#check @ContinuousLinearMap.inl
#check @ContinuousLinearMap.fst
#check @ContinuousLinearMap.prod
#check @ContinuousLinearMap.coprod
#check @Submodule.subtypeL
#check @Submodule.topologicalClosure_coe
#check @LinearIsometryEquiv.prodAssoc
#check @LinearIsometryEquiv.piLpCongrLeft
#check @ContinuousLinearEquiv.piCongrLeft
#check @ContinuousLinearEquiv.prodCongr
#check @LinearIsometryEquiv.prodCongr
#check @ContinuousLinearEquiv.toContinuousLinearMap
#check @ContinuousLinearEquiv.symm_apply_apply
#check @LinearIsometryEquiv.symm_apply_apply
#check @LinearIsometryEquiv.map_smul
#check @LinearIsometryEquiv.map_add
#check @LinearIsometryEquiv.coe_toLinearEquiv
#check @LinearIsometryEquiv.toLinearIsometry
#check @LinearIsometryEquiv.mk
#check @LinearIsometry.mk
#check @LinearIsometry.toContinuousLinearMap
#check @LinearIsometry.continuous
#check @LinearIsometry.isometry
#check @Isometry.injective
#check @Isometry.isClosedEmbedding
#check @Isometry.isClosed_range
#check @LinearIsometry.isComplete_range
#check @IsClosedEmbedding.isClosed_range
#check @Isometry.isUniformInducing
#check @IsUniformInducing.isComplete_range
#check @IsComplete.isClosed
#check @ContinuousLinearMap.map_tsum
#check @HasSum.mapL
#check @tsum_eq_tsum_of_hasSum_of_hasSum
#check @HasSum.unique
#check @HasSum.hasSum_iff_of_eq
#check @Summable.hasSum
#check @HasSum.smul_const
#check @HasSum.const_smul
#check @hasSum_smul_const
#check @HasSum.tsum_eq
#check @NNReal.coe_inj
#check @Finset.sup_le
#check @Finset.sup_mono
#check @Finset.sup_insert
#check @Finset.sup_singleton
#check @Finset.sup_comm
#check @Finset.sup_attach
#check @Finset.sup_map
#check @Finset.sup_image
#check @Equiv.finsetCongr
#check @Finset.sum_equiv
#check @Finset.sum_bij
#check @Finset.sum_map
#check @Fintype.sum_equiv
#check @Set.Finite.exists_finset_coe
#check @Set.Finite.subset
#check @Set.finite_iUnion
#check @Set.Finite.image
#check @Set.Finite.preimage
#check @Finset.eventually_cofinite_ne
#check @Filter.eventually_cofinite_ne
#check @Filter.tendsto_cofinite
#check @Metric.tendsto_nhds
#check @Filter.Tendsto.congr
#check @Filter.Tendsto.comp
#check @Filter.Tendsto.mono_left
#check @Filter.Tendsto.prodMk
#check @Filter.tendsto_atTop_finset_of_monotone
#check @Filter.Tendsto.finset_sum
#check @tendsto_finset_sum
#check @Finset.tendsto_sum
#check @Filter.cofinite_prod
#check @Filter.coprod_cofinite
#check @Filter.Tendsto.prod_map_coprod
#check @Filter.Tendsto.curry
#check @Set.Finite.prod
#check @Set.Finite.toFinset
#check @Set.image_subset_range
#check @Function.Injective.comp
#check @Function.Surjective.comp
#check @Module.Basis.span
#check @Module.Basis.ofRepr
#check @Submodule.span_span_of_tower
#check @Submodule.span_eq
#check @Submodule.span_le_restrictScalars
#check @Submodule.span_coe_eq_restrictScalars
#check @Submodule.restrictScalars
#check @LinearMap.range_restrictScalars
#check @Submodule.mem_restrictScalars
#check @IsLocalRing.ResidueField
#check @IsLocalRing.residue
#check @IsLocalRing.residue_surjective
#check @Ideal.Quotient.mk_surjective
#check @Submodule.Quotient.mk_surjective
#check @Ideal.Quotient.lift
#check @Ideal.quotientKerAlgEquivOfSurjective
#check @RingHom.quotientKerEquivOfSurjective
#check @Submodule.Quotient.mk_eq_zero
#check @Submodule.smul_mem_pointwise_smul
#check @Submodule.mem_smul_span
#check @Submodule.mem_ideal_smul_span_iff_exists_sum
#check @Submodule.ideal_span_singleton_smul
#check @Submodule.span_singleton_smul_eq
#check @Submodule.mem_span_singleton
#check @ULift.up
#check @ULift.down
#check @Equiv.ulift
#check @Homeomorph.ulift
#check @Equiv.toHomeomorphOfDiscrete
#check @Homeomorph.toCocompactMap
#check @CocompactMap.toContinuousMap
#check @Set.Countable.image
#check @Set.Countable.biUnion
#check @Set.Countable.iUnion
#check @Set.countable_iUnion
#check @Cardinal.mk_biUnion_le
#check @Cardinal.mk_iUnion_le_sum_mk
#check @Cardinal.sum_le_iSup
#check @Cardinal.mk_sigma
#check @Cardinal.mk_iUnion_le
#check @Cardinal.mk_iUnion_eq_sum_mk
#check @Cardinal.mul_eq_left
#check @Cardinal.mk_le_aleph0_iff
#check @Cardinal.aleph0_le_mk
#check @Cardinal.infinite_iff
#check @Cardinal.mk_eq_nat_iff_fintype
#check @Cardinal.mk_fintype
#check @Cardinal.eq
#check @Cardinal.lift_mk_eq'
#check @Cardinal.lift_mk_eq
#check @Module.rank_eq_of_equiv_equiv
#check @LinearEquiv.rank_eq
#check @Module.rank_fun'
#check @Module.rank_pi
#check @rank_fun
#check @Module.rank_fun
#check @Module.Free.rank_eq_card_chooseBasisIndex
#check @Module.Basis.mk_eq_rank
#check @Module.Basis.mk_eq_rank''
#check @ContinuousLinearEquiv.toLinearEquiv_injective
#check @ContinuousLinearEquiv.finrank_eq
#check @LinearEquiv.finrank_eq
#check @Module.finrank_eq_card_basis
#check @Module.finrank_eq_card_chooseBasisIndex
#check @FiniteDimensional.of_fintype_basis
#check @Module.Basis.reindex
#check @ContinuousLinearMap.Ultra.continuousLinearEquivOfBijective
#check @ContinuousLinearMap.Ultra.toContinuousLinearEquivOfContinuous
#check @ContinuousLinearMap.Ultra.continuous_symm
#check @ContinuousLinearMap.Ultra.quotKerEquivRangeL
#check @ContinuousLinearMap.Ultra.exists_norm_quotKerEquivRange_symm_le
#check @ContinuousLinearMap.Ultra.exists_approx_preimage_norm_le
#check @ContinuousLinearMap.Ultra.isQuotientMap
#check @ContinuousLinearMap.Ultra.norm_map_le_div_mul_of_forall_norm_le
#check @ContinuousLinearMap.Ultra.continuous_iff_exists_forall_norm_le
