/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import PhD.Jacobs.U3.Setting
import PhD.Jacobs.U3.Hurwitz

/-!
# The level structures `U₀(1)` and `U₁(9)`, and class number one

[Jacobs, Definition 1.20 pp. 15]: `U₀(1) = ∏_q X_q` with `X_q = GL₂(ℤ_q)` for `q ≠ 2`
(under the fixed identifications `θ_q`) and `X₂` the units of a maximal order of `D₂`;
`U₁(9)` refines the component at `3` to

> "W_p = {(a b; c d) ∈ GL₂(Z_p) : (a b; c d) ≡ (∗ ∗; 0 1) mod pⁿ}"  (p = 3, n = 2).

Both are `(𝓞_D ⊗ ẑ)`-unit groups away from the congruence: we define them
identification-free as the unit groups of the integral model `hurwitzOrder ⊗ 𝓞_v` inside
`D ⊗ F_v`, with the mod-`9` condition at `v₃` imposed through `toMatrix`/`Sigma1`.

The file also states the class-number-one input:

* `HClassNumberOne` — the statement `D_f^× = D^× · U₀(1)` ([Jacobs, Lemma 1.22 (1.4.4)]).
  The thesis proves it by Jacquet–Langlands ("we know that there are no cusp forms of
  weight 2"); that argument is out of scope.  FLT's `completed_units`
  (`FLT/Data/HurwitzRatHat.lean`) records the same statement with `sorry`, **and FLT is
  expected to cover it upstream — filling it is deliberately deferred here (user
  decision 2026-08-05; board tickets B06/B18)**.  Every consumer takes `HClassNumberOne`
  as an explicit hypothesis, so the tranche is complete without it; when FLT's proof
  lands, port it (re-auditing the ẐHat-vs-`FiniteAdeleRing` seam).  The in-repo
  fallback route ([Voight GTM 288]: Euclidean → principal ideals → idelic dictionary)
  is skeletonised, **unimported**, in `PhD/Jacobs/U3/ClassNumberOneFallback.lean` — the
  live chain's only CN1 declaration is the interface `hClassNumberOne` below.
-/

open Quaternion IsDedekindDomain NumberField QMF
open scoped TensorProduct

namespace Jacobs.U3

/-! ## The local integral models -/

/-- The local integral model of the Hurwitz order at a finite place `w`: the subring of
`D ⊗[ℚ] F_w` generated by the image of `hurwitzOrder` together with the local integers
`𝓞_w`.  Equivalently `𝓞_D ⊗_ℤ 𝓞_w`, presented as a `Subring.closure` so that membership
proofs go through `Subring.closure_induction` / `Subring.subset_closure`. -/
noncomputable def localOrder (w : HeightOneSpectrum (RingOfIntegers ℚ)) :
    Subring (D ⊗[ℚ] w.adicCompletion ℚ) :=
  Subring.closure
    ((Algebra.TensorProduct.includeLeftRingHom : D →+* D ⊗[ℚ] w.adicCompletion ℚ) ''
        hurwitzOrder ∪
      Set.range (fun z : w.adicCompletionIntegers ℚ =>
        Algebra.TensorProduct.includeRight (R := ℚ) (A := D) ((z : w.adicCompletion ℚ))))

/-- The generators of `localOrder` lie in it: the image of a Hurwitz quaternion. -/
theorem includeLeft_mem_localOrder {w : HeightOneSpectrum (RingOfIntegers ℚ)}
    {d : D} (hd : d ∈ hurwitzOrder) :
    (Algebra.TensorProduct.includeLeftRingHom : D →+* D ⊗[ℚ] w.adicCompletion ℚ) d
      ∈ localOrder w :=
  Subring.subset_closure (Or.inl ⟨d, hd, rfl⟩)

/-- The generators of `localOrder` lie in it: a local integer. -/
theorem includeRight_mem_localOrder {w : HeightOneSpectrum (RingOfIntegers ℚ)}
    (z : w.adicCompletionIntegers ℚ) :
    Algebra.TensorProduct.includeRight (R := ℚ) (A := D) ((z : w.adicCompletion ℚ))
      ∈ localOrder w :=
  Subring.subset_closure (Or.inr ⟨z, rfl⟩)

/-- The integral matrices over `𝓞₃` form a subring of `M₂(K₃)`.  (Stated as a `Subring`
so that `Subring.closure_induction` can land in it directly.) -/
def integralMatrices : Subring (Matrix (Fin 2) (Fin 2) K₃) where
  carrier := {g | ∀ i j, Valued.v (g i j) ≤ 1}
  zero_mem' i j := by simp
  one_mem' i j := by
    rcases eq_or_ne i j with rfl | h
    · simp [Matrix.one_apply_eq]
    · simp [Matrix.one_apply_ne h]
  add_mem' {a b} ha hb i j :=
    le_trans (Valued.v.map_add _ _) (max_le (ha i j) (hb i j))
  neg_mem' {a} ha i j := by
    simpa [Matrix.neg_apply] using ha i j
  mul_mem' {a b} ha hb i j := by
    rw [Matrix.mul_apply, Fin.sum_univ_two]
    refine le_trans (Valued.v.map_add _ _) (max_le ?_ ?_) <;>
      · rw [map_mul]
        exact mul_le_one' (by first | exact ha i 0 | exact ha i 1)
          (by first | exact hb 0 j | exact hb 1 j)

/-- Membership in `integralMatrices` is entrywise integrality. -/
theorem mem_integralMatrices_iff {g : Matrix (Fin 2) (Fin 2) K₃} :
    g ∈ integralMatrices ↔ ∀ i j, g i j ∈ v₃.adicCompletionIntegers ℚ :=
  Iff.rfl

/-- `θ₃` as a plain ring homomorphism.  Bundling it once here pins the `Algebra ℚ K₃`
instance path (`DivisionRing.toRatAlgebra` versus the adic-completion one — they are equal
by `Subsingleton.elim`, but not syntactically) so downstream statements do not have to
re-synthesise it. -/
noncomputable def theta3 :=
  RingEquivClass.toRingEquiv (RigidificationAt.equiv (F := ℚ) (D := D) (v := v₃))

/-- **B07a**: `θ₃` carries the local order into the integral matrices. -/
theorem theta_localOrder_subset :
    ∀ x ∈ localOrder v₃, theta3 x ∈ integralMatrices := by
  -- The preimage of a subring under a ring hom is a subring, so `Subring.closure_le`
  -- reduces the whole statement to the two generator families of `localOrder`.
  have key : localOrder v₃ ≤ integralMatrices.comap theta3 := by
    rw [localOrder, Subring.closure_le]
    rintro y (⟨d, hd, rfl⟩ | ⟨z, rfl⟩)
    · -- `θ₃(d ⊗ 1)` for `d` Hurwitz: entries are `ℤ`-combinations of `1, ν₃` over `2`,
      -- integral because `ν₃ ∈ 𝓞₃` and `2` is a unit at `3`.
      sorry
    · -- `θ₃(1 ⊗ z) = z • 1` for `z ∈ 𝓞₃`: diagonal with integral entries.
      sorry
  exact fun x hx => key hx

/-- At `w = v₃`, the rigidification carries the local order onto `M₂(𝓞₃)`:
`θ₃ (localOrder v₃) = Matrix.of (adicCompletionIntegers)`.  (This is what makes the
`Σ₀`-conditions at `3` express integrality; `θ₃` is integral because `ν₃, ξ₃ = 1 ∈ 𝓞₃`
and `2` is a unit at `3`.) -/
theorem theta_localOrder :
    (RigidificationAt.equiv (F := ℚ) (D := D) (v := v₃)) '' (localOrder v₃)
      = {g | ∀ i j, g i j ∈ v₃.adicCompletionIntegers ℚ} := sorry

/-! ## The adelic level subgroups -/

/-- `U₀(1) ⊆ D_f^×` [Jacobs, Def 1.20]: adelic units integral at every place — the unit
group of the integral model `hurwitzOrder ⊗ ẑ`.  Component-wise: `g_w ∈ (localOrder w)ˣ`
for every `w`. -/
noncomputable def U0 : Subgroup (Dfx ℚ D) where
  carrier := {g | ∀ w : HeightOneSpectrum (RingOfIntegers ℚ),
    toLocal ℚ D w (g : D ⊗[ℚ] FiniteAdeleRing (RingOfIntegers ℚ) ℚ) ∈ localOrder w ∧
      toLocal ℚ D w ((g⁻¹ : Dfx ℚ D) : D ⊗[ℚ] FiniteAdeleRing (RingOfIntegers ℚ) ℚ)
        ∈ localOrder w}
  one_mem' w := by
    refine ⟨?_, ?_⟩ <;>
      · simp only [Units.val_one, inv_one, map_one]
        exact (localOrder w).one_mem
  mul_mem' {g h} hg hh w := by
    refine ⟨?_, ?_⟩
    · rw [Units.val_mul, map_mul]
      exact (localOrder w).mul_mem (hg w).1 (hh w).1
    · rw [mul_inv_rev, Units.val_mul, map_mul]
      exact (localOrder w).mul_mem (hh w).2 (hg w).2
  inv_mem' {g} hg w := ⟨(hg w).2, by simpa using (hg w).1⟩

/-- `U₁(9) ⊆ U₀(1)` [Jacobs, Def 1.20]: the mod-`9` congruence `≡ (∗ ∗; 0 1)` at `3`
(in the left-handed matrix picture: `toMatrix g ∈ Σ₁(9)` together with integral
invertibility at `3`). -/
noncomputable def U1_9 : Subgroup (Dfx ℚ D) where
  carrier := {g | g ∈ U0 ∧ toMatrix ℚ D v₃ g ∈ Sigma1 ∧ toMatrix ℚ D v₃ (g⁻¹) ∈ Sigma1}
  one_mem' := by
    refine ⟨U0.one_mem, ?_, ?_⟩
    · simp
    · rw [inv_one]; simp
  mul_mem' {g h} hg hh := by
    refine ⟨U0.mul_mem hg.1 hh.1, ?_, ?_⟩
    · rw [map_mul]; exact Sigma1.mul_mem hg.2.1 hh.2.1
    · rw [mul_inv_rev, map_mul]; exact Sigma1.mul_mem hh.2.2 hg.2.2
  inv_mem' {g} hg := ⟨U0.inv_mem hg.1, hg.2.2, by simpa using hg.2.1⟩

theorem U1_9_le_U0 : U1_9 ≤ U0 := fun _ hg => hg.1

/-- The wild-level inclusion required by the `QMF` framework: `U₁(9) ⊆ Δ = levelMonoid`,
i.e. the `3`-component of a level element lies in `Σ₀(v(9))`. -/
theorem U1_9_subset_levelMonoid :
    (U1_9 : Set (Dfx ℚ D)) ⊆ levelMonoid ℚ D v₃ γ₉ γ₉_lt_one :=
  fun _ hg => sigma1_le_sigma0 hg.2.1

/-- Sharper: the `3`-component of a level element lies in `Σ₁(9) ⊆ Σ₀` (the congruence
form the `κ`-action needs). -/
theorem toMatrix_mem_sigma1_of_mem_U1_9 {g : Dfx ℚ D} (hg : g ∈ U1_9) :
    toMatrix ℚ D v₃ g ∈ Sigma1 := hg.2.1

/-- `D^× ∩ U₀(1) = 𝓞_D^×` ([Jacobs, (1.4.7)]: "One easily verifies that
`O_D^× = D^× ∩ U₀(1)`"): a global quaternion is adelically integral and adelically
integrally-invertible iff it is a unit of the Hurwitz order.  ("Integral everywhere
locally ⟹ integral" for the lattice `𝓞_D ⊆ D`.) -/
theorem unitsIncl_mem_U0_iff (x : Dˣ) :
    unitsIncl ℚ D x ∈ U0 ↔ ∃ u : (hurwitzOrder)ˣ, ((u : hurwitzOrder) : ℍ[ℚ]) = (x : D) :=
  sorry

/-! ## Class number one -/

/-- **The class-set input (1.4.4)** [Jacobs, Lemma 1.22]: `D_f^× = D^× · U₀(1)`.
Stated as a `Prop` so that downstream results can take it as an explicit hypothesis
until `hClassNumberOne` discharges it (the `T016` pattern). -/
def HClassNumberOne : Prop :=
  ∀ g : Dfx ℚ D, ∃ d ∈ globalUnits ℚ D, ∃ u ∈ U0, g = d * u

/-- **THE single external dependency of the AG-B tranche** (interface contract,
user decision 2026-08-05).

Class number one for the Hurwitz order — [Jacobs, Lemma 1.22 (1.4.4)], stated in the
live `FiniteAdeleRing` framework.  This is the content of FLT's

> `lemma completed_units (z : D^ˣ) : ∃ (u : Dˣ) (v : 𝓞^ˣ), (z : D^) = j₁ u * j₂ v`

(`FLT/Data/HurwitzRatHat.lean:96`, currently `sorry` there; ẐHat formulation), which
the FLT project is expected to prove.  **Deliberately left `sorry`; do not fill without
user direction.**

* This is the ONLY FLT-covered assumption of the tranche: every other sorry in
  `PhD/Jacobs/U3/` (excluding the unimported `ClassNumberOneFallback.lean`) is
  scheduled board work.  Endpoints consume it either as an explicit hypothesis
  (`(hcn : HClassNumberOne)` — axiom-clean, board-gradable) or through the marked
  convenience corollaries that cite this lemma (sorry-tainted with exactly this one
  source).
* At FLT-landing time the port obligations are: their `Hurwitz` structure ↔ our
  `hurwitzOrder : Subring ℍ[ℚ]`, and their formulation's ambient (`D ⊗[ℤ] ẐHat` if
  they keep the old file, or their live `FiniteAdeleRing` framework — in which case
  this statement should match near-verbatim) ↔ `Dfx ℚ D` with `𝓞^ˣ ↔ U0`.
* The in-repo fallback route ([Voight]: Euclidean → principal → dictionary) is
  skeletonised, unimported, in `PhD/Jacobs/U3/ClassNumberOneFallback.lean`
  (board B06/B18, deferred). -/
theorem hClassNumberOne : HClassNumberOne := sorry

end Jacobs.U3
