/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import Mathlib.Analysis.Normed.Operator.Banach
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.Noetherian.Defs
import Mathlib.Topology.Algebra.Ring.Ideal
import PhD.TauCeti.Code.PadicFunctionalAnalysis.UnitBall

/-!
# Ideals of a noetherian Banach algebra are closed

In a noetherian `K`-Banach algebra every ideal is closed (BGR 3.7.2/2, the direction used by
rigid geometry). The proof is BGR 3.7.2/1: the closure `J` of an ideal `I` is a finitely generated
ideal, the map `Aⁿ → J` onto the generators is open by Banach's theorem, so the generators lie in
`I + Σ 𝔫 xᵢ` where `𝔫` is the open unit ball, and the nonarchimedean Nakayama lemma (BGR 1.2.4/6,
here Mathlib's Nakayama over the unit-ball subring `A°` with its ideal `𝔫 ≤ jacobson ⊥`) gives
`J = I`.

Roadmap: `PhD/TauCeti/Roadmaps/RigidAnalyticGeometry/README.md`, §1.3 (BGR 3.7.2, the input to
3.7.5/2). Tau Ceti home: `TauCeti/Analysis/Normed/Algebra/Noetherian.lean`.

## Main results

* `Ideal.forall_mem_of_forall_exists_eq_add_sum_mul_of_norm_lt_one` — the nonarchimedean
  Nakayama lemma, BGR 1.2.4/6.
* `Ideal.exists_forall_exists_eq_sum_mul_norm_le` — Banach's open mapping theorem for a
  finitely generated closed ideal (BGR 3.7.2/1, the first half).
* `Ideal.isClosed_of_isNoetherianRing` — every ideal of a noetherian Banach algebra is closed
  (BGR 3.7.2/2).
-/

open Filter Topology Subring NormedRing

variable (K : Type*) [NontriviallyNormedField K] {A : Type*} [NormedCommRing A]
  [NormedAlgebra K A] [CompleteSpace A]

/-! ### The nonarchimedean Nakayama lemma (BGR 1.2.4/6) -/

section Nakayama

variable [IsUltrametricDist A] [NormOneClass A]

/-- **The nonarchimedean Nakayama lemma** (BGR 1.2.4/6): if generators `x₁, …, xₙ` satisfy
`xᵢ ∈ I + Σ_μ 𝔫 x_μ` with `𝔫 = {‖c‖ < 1}`, then every `xᵢ` lies in `I`. Source: BGR 1.2.4/6
("Let `N` be a submodule of `M` such that there are elements `x₁, …, xₙ` in `M` with the property
`M ⊂ N + Σ Ǎ x_μ`. Then `N = M`"), proved through Mathlib's Nakayama lemma
`Submodule.le_of_le_smul_of_le_jacobson_bot` over `A°` with
`NormedRing.openUnitBallIdeal_le_jacobson_bot`. -/
theorem Ideal.forall_mem_of_forall_exists_eq_add_sum_mul_of_norm_lt_one (I : Ideal A) {n : ℕ}
    (x : Fin n → A)
    (h : ∀ i, ∃ y ∈ I, ∃ c : Fin n → A, (∀ μ, ‖c μ‖ < 1) ∧ x i = y + ∑ μ, c μ * x μ) :
    ∀ i, x i ∈ I := by
  let N' : Submodule (unitClosedBall A) A := Submodule.span _ (Set.range x)
  let N : Submodule (unitClosedBall A) A := I.restrictScalars (unitClosedBall A)
  have hle : N' ≤ N ⊔ openUnitBallIdeal A • N' := by
    refine Submodule.span_le.2 ?_
    rintro _ ⟨i, rfl⟩
    obtain ⟨y, hy, c, hc, hxi⟩ := h i
    rw [SetLike.mem_coe, hxi]
    refine Submodule.add_mem_sup hy (Submodule.sum_mem _ fun μ _ ↦ ?_)
    have hmem : c μ ∈ unitClosedBall A := mem_unitClosedBall.2 (hc μ).le
    have hcx : c μ * x μ = (⟨c μ, hmem⟩ : unitClosedBall A) • x μ := rfl
    rw [hcx]
    exact Submodule.smul_mem_smul (mem_openUnitBallIdeal.2 (hc μ))
      (Submodule.subset_span ⟨μ, rfl⟩)
  have hN := Submodule.le_of_le_smul_of_le_jacobson_bot (Submodule.fg_span (Set.finite_range x))
    openUnitBallIdeal_le_jacobson_bot hle
  exact fun i ↦ hN (Submodule.subset_span ⟨i, rfl⟩)

end Nakayama

/-! ### Banach's open mapping theorem for finitely generated closed submodules -/

section OpenMapping

include K in
/-- A closed ideal `J` of a Banach algebra generated by `x₁, …, xₙ` admits bounded coefficients:
there is `C > 0` with every `y ∈ J` equal to `Σ aᵢ xᵢ` for some `aᵢ` with `‖aᵢ‖ ≤ C ‖y‖`, because
the continuous surjection `π : Aⁿ → J`, `(aᵢ) ↦ Σ aᵢ xᵢ`, of Banach spaces is open.
Source: BGR 3.7.2/1 ("By BANACH's Theorem, `π` is open"), through
`ContinuousLinearMap.exists_preimage_norm_le`. -/
theorem Ideal.exists_forall_exists_eq_sum_mul_norm_le {n : ℕ} (x : Fin n → A) (J : Ideal A)
    (hJ : IsClosed (J : Set A)) (hx : Ideal.span (Set.range x) = J) :
    ∃ C : ℝ, 0 < C ∧ ∀ y ∈ J, ∃ a : Fin n → A, y = ∑ i, a i * x i ∧ ∀ i, ‖a i‖ ≤ C * ‖y‖ := by
  let Jk : Submodule K A := J.restrictScalars K
  haveI : CompleteSpace Jk := (show IsClosed (Jk : Set A) from hJ).completeSpace_coe
  have hmem : ∀ a : Fin n → A, ∑ i, a i * x i ∈ J := fun a ↦
    J.sum_mem fun i _ ↦ J.mul_mem_left _ (hx ▸ Ideal.subset_span ⟨i, rfl⟩)
  let πl : (Fin n → A) →ₗ[K] Jk :=
    { toFun := fun a ↦ ⟨∑ i, a i * x i, hmem a⟩
      map_add' := fun a b ↦ Subtype.ext (by simp [add_mul, Finset.sum_add_distrib])
      map_smul' := fun c a ↦ Subtype.ext (by simp [Finset.smul_sum]) }
  have hcont : Continuous πl :=
    Continuous.subtype_mk (continuous_finsetSum _ fun i _ ↦
      (continuous_apply i).mul continuous_const) _
  let π : (Fin n → A) →L[K] Jk := ⟨πl, hcont⟩
  have hsurj : Function.Surjective π := by
    rintro ⟨y, hy⟩
    have hy' : y ∈ Ideal.span (Set.range x) := hx ▸ hy
    obtain ⟨a, ha⟩ := Ideal.mem_span_range_iff_exists_fun.1 hy'
    exact ⟨a, Subtype.ext ha⟩
  obtain ⟨C, hC0, hC⟩ := ContinuousLinearMap.exists_preimage_norm_le π hsurj
  refine ⟨C, hC0, fun y hy ↦ ?_⟩
  obtain ⟨a, ha, hna⟩ := hC ⟨y, hy⟩
  exact ⟨a, (congrArg Subtype.val ha).symm, fun i ↦ (norm_le_pi_norm a i).trans hna⟩

end OpenMapping

/-! ### Ideals of a noetherian Banach algebra are closed (BGR 3.7.2/2) -/

section Closed

variable [IsUltrametricDist A] [NormOneClass A]

omit [CompleteSpace A] [IsUltrametricDist A] [NormOneClass A] in
/-- The closure of an ideal in a normed `K`-algebra is a `K`-submodule: `Ideal.closure` restricted
to `K`-scalars. -/
theorem Ideal.isClosed_coe_closure_restrictScalars (I : Ideal A) :
    IsClosed ((I.closure.restrictScalars K : Submodule K A) : Set A) := by
  rw [Submodule.coe_restrictScalars, Ideal.coe_closure]
  exact isClosed_closure

include K in
/-- **BGR 3.7.2/1** in the form used for ideals: if the closure of an ideal `I` is finitely
generated, then `I` is closed. Source: BGR 3.7.2/1 ("Let `M` be a normed `A`-module such that the
completion `M̂` of `M` is a finite `A`-module. Then `M` is complete"). -/
theorem Ideal.isClosed_of_fg_closure (I : Ideal A) (hfg : I.closure.FG) :
    IsClosed (I : Set A) := by
  obtain ⟨n, x, hx⟩ := Submodule.fg_iff_exists_fin_generating_family.1 hfg
  have hcl : IsClosed (I.closure : Set A) := by
    rw [Ideal.coe_closure]
    exact isClosed_closure
  have hIcl : ∀ y ∈ I, y ∈ I.closure := fun y hy ↦ by
    rw [← SetLike.mem_coe, Ideal.coe_closure]
    exact subset_closure hy
  obtain ⟨C, hC0, hC⟩ := Ideal.exists_forall_exists_eq_sum_mul_norm_le K x I.closure hcl hx
  have hxI : ∀ i, x i ∈ I := by
    refine Ideal.forall_mem_of_forall_exists_eq_add_sum_mul_of_norm_lt_one I x fun i ↦ ?_
    have hxi : x i ∈ I.closure := hx ▸ Ideal.subset_span ⟨i, rfl⟩
    have hxi' : x i ∈ _root_.closure (I : Set A) := by
      rw [← Ideal.coe_closure]
      exact hxi
    obtain ⟨y, hy, hdist⟩ := Metric.mem_closure_iff.1 hxi' C⁻¹ (inv_pos.2 hC0)
    obtain ⟨c, hc, hcn⟩ := hC _ (I.closure.sub_mem hxi (hIcl y hy))
    refine ⟨y, hy, c, fun μ ↦ ?_, ?_⟩
    · calc ‖c μ‖ ≤ C * ‖x i - y‖ := hcn μ
        _ < C * C⁻¹ := mul_lt_mul_of_pos_left (by rwa [← dist_eq_norm]) hC0
        _ = 1 := mul_inv_cancel₀ hC0.ne'
    · rw [← hc]
      abel
  refine isClosed_of_closure_subset fun z hz ↦ ?_
  have hz' : z ∈ I.closure := by
    rw [← SetLike.mem_coe, Ideal.coe_closure]
    exact hz
  rw [← hx] at hz'
  exact (Ideal.span_le.2 (by rintro _ ⟨i, rfl⟩; exact hxI i)) hz'

include K in
/-- **Ideals of a noetherian Banach algebra are closed.** Source: BGR 3.7.2/2 ("the ring `A` is
Noetherian if and only if all ideals in `A` are closed"), the direction "if `A` is noetherian". -/
theorem Ideal.isClosed_of_isNoetherianRing [IsNoetherianRing A] (I : Ideal A) :
    IsClosed (I : Set A) :=
  I.isClosed_of_fg_closure K (IsNoetherian.noetherian _)

end Closed
