import PhD.TauCeti.Code.PadicFunctionalAnalysis.Tate
#print axioms NormedRing.PseudoUniformizer.coe_unit
#print axioms NormedRing.PseudoUniformizer.normOneClass_of_nontrivial
#print axioms NormedRing.PseudoUniformizer.norm_pos
#print axioms NormedRing.PseudoUniformizer.norm_inv
#print axioms NormedRing.PseudoUniformizer.norm_zpow
#print axioms NormedRing.PseudoUniformizer.log_norm_neg
#print axioms NormedRing.PseudoUniformizer.norm_smul
#print axioms NormedRing.PseudoUniformizer.norm_zpow_smul
#print axioms NormedRing.PseudoUniformizer.existsUnique_zpow_norm_smul_mem_Ioc
#print axioms NormedRing.PseudoUniformizer.existsUnique_zpow_norm_smul_mem_Ioc_one
#print axioms NormedRing.PseudoUniformizer.val
#print axioms NormedRing.PseudoUniformizer.val_zero
#print axioms NormedRing.PseudoUniformizer.val_of_ne_zero
#print axioms NormedRing.PseudoUniformizer.val_eq_top_iff
#print axioms NormedRing.PseudoUniformizer.val_self
#print axioms NormedRing.PseudoUniformizer.val_one
#print axioms NormedRing.PseudoUniformizer.val_zpow_self
#print axioms NormedRing.PseudoUniformizer.val_le_val_iff
#print axioms NormedRing.PseudoUniformizer.val_lt_val_iff
#print axioms NormedRing.PseudoUniformizer.val_nonneg_iff
#print axioms NormedRing.PseudoUniformizer.val_add_val_le_val_mul
#print axioms NormedRing.PseudoUniformizer.val_mul
#print axioms NormedRing.PseudoUniformizer.min_val_le_val_add
#print axioms NormedRing.PseudoUniformizer.norm_eq_rpow_of_val_eq
#print axioms NormedRing.PseudoUniformizer.ofNormedAlgebra
#print axioms NormedRing.PseudoUniformizer.coe_ofNormedAlgebra
#print axioms NormedRing.isTate_of_normedAlgebra
