import PhD.TauCeti.Code.PadicFunctionalAnalysis.UnitBall
#print axioms Subring.unitClosedBall
#print axioms Subring.mem_unitClosedBall
#print axioms Subring.coe_unitClosedBall
#print axioms Subring.unitClosedBall_toSubmonoid
#print axioms Subring.norm_le_one
#print axioms Subring.isOpen_unitClosedBall
#print axioms Subring.isClosed_unitClosedBall
#print axioms NormedRing.closedBallIdeal
#print axioms NormedRing.openUnitBallIdeal
#print axioms NormedRing.mem_closedBallIdeal
#print axioms NormedRing.mem_openUnitBallIdeal
#print axioms NormedRing.closedBallIdeal_mono
#print axioms NormedRing.closedBallIdeal_one
#print axioms NormedRing.closedBallIdeal_mul_le
#print axioms NormedRing.closedBallIdeal_le_openUnitBallIdeal
#print axioms NormedRing.isOpen_closedBallIdeal
#print axioms NormedRing.isOpen_openUnitBallIdeal
#print axioms NormedRing.hasBasis_nhds_zero_closedBallIdeal
#print axioms NormedRing.instIsLinearTopologyUnitClosedBall
#print axioms NormedRing.openUnitBallIdeal_le_topologicalNilradical
#print axioms NormedRing.openUnitBallIdeal_eq_topologicalNilradical
#print axioms NormedRing.norm_one_sub_of_norm_lt_one
#print axioms NormedRing.norm_tsum_geometric
#print axioms NormedRing.norm_tsum_geometric_sub_one
#print axioms NormedRing.isUnit_of_norm_one_sub_lt_one
#print axioms NormedRing.isUnit_iff_isUnit_mk
#print axioms NormedRing.openUnitBallIdeal_le_jacobson_bot
#print axioms NormedRing.isUnit_iff_norm_eq_one
#print axioms NormedRing.instIsLocalRingUnitClosedBall
#print axioms NormedRing.maximalIdeal_unitClosedBall
