import PhD.TauCeti.Code.PadicFunctionalAnalysis.Examples
import PhD.TauCeti.Code.PadicFunctionalAnalysis.NormComparison
#check @AddEquiv.completeSpace_congr_of_bounds
#check @Filter.Tendsto.exists_forall_norm_le
#check @IsTopologicallyNilpotent.of_norm_lt_one
#check @IsUltrametricDist.norm_tsum_eq_of_forall_lt
#check @IsUltrametricDist.norm_tsum_lt_of_forall_lt
#check @IsUltrametricDist.tsum_prod_eq_tsum_tsum
#check @IsUltrametricDist.tsum_prod_map₂
#check @IsUltrametricDist.tsum_tsum_comm
#check @NormedRing.PseudoUniformizer.ResidueModule
#check @NormedRing.PseudoUniformizer.ResidueRing
#check @NormedRing.PseudoUniformizer.gaugeNorm_unitClosedBall
#check @NormedRing.PseudoUniformizer.hasBasis_nhds_zero_smul_unitClosedBall
#check @NormedRing.PseudoUniformizer.ideal
#check @NormedRing.PseudoUniformizer.ideal_pow_eq_closedBallIdeal
#check @NormedRing.PseudoUniformizer.isAdic_ideal
#check @NormedRing.PseudoUniformizer.ofNormedAlgebra
#check @NormedRing.PseudoUniformizer.toRescaled
#check @NormedRing.PseudoUniformizer.toUnitClosedBall
#check @NormedRing.PseudoUniformizer.val
#check @NormedRing.exists_mul_rpow_le_norm_map
#check @NormedRing.exists_norm_le_mul_rpow_norm_map
#check @NormedRing.exists_norm_le_of_norm_map_le_one
#check @NormedRing.exists_norm_map_le_mul_rpow
#check @PowerBounded.isPowerBounded_iff_norm_le_one
#check @PowerBounded.isPowerBounded_of_norm_le_one
#check @Prod.instIsUltrametricDist
#check @QuotientAddGroup.instIsUltrametricDist
#check @Submodule.instIsBoundedSMul
#check @Subring.gaugeRingNorm
#check @TopologicalRing.isBounded_of_forall_norm_le
