import Mathlib
open Filter Topology
#check @eq_inv_of_mul_eq_one_right
#check @le_inv_mul_iff₀
#check @Int.induction_on
#check @zpow_add_one
#check @zpow_sub_one
#check @zpow_add_one₀
#check @zpow_sub_one₀
#check @Units.val_mul
#check @Prod.dist_eq
#check @dist_triangle_max
#check @dist_smul_pair
#check @dist_pair_smul
#check @IsUltrametricDist.isUltrametricDist_of_isNonarchimedean_norm
#check @QuotientAddGroup.norm_lt_iff
#check @QuotientAddGroup.norm_mk_le_norm
#check @le_of_forall_pos_lt_add
#check @max_add_add_right
#check @AddMonoidHomClass.lipschitz_of_bound
#check @UniformEquiv.isUniformEmbedding
#check @completeSpace_congr
#check @Real.log_neg
#check @exists_mem_Ioc_zpow
#check @zpow_le_zpow_right_of_le_one₀
#check @inv_zpow'
#check @div_le_iff₀
#check @lt_div_iff₀
#check @NormOneClass.nontrivial
#check @Real.log_zpow
#check @div_le_div_right_of_neg
#check @Real.log_le_log_iff
#check @Real.rpow_def_of_pos
#check @Real.exp_log
#check @Units.coe_map
#check @Units.val_mk0
#check @Algebra.smul_def
#check @norm_algebraMap'
#check @NormedField.exists_norm_lt_one
#check @Metric.continuousAt_iff
#check @Nat.ceil_lt_add_one
#check @Nat.le_ceil
#check @Real.rpow_natCast
#check @Real.rpow_add
#check @Real.rpow_le_rpow_left_iff
#check @Real.logb_pos_iff_of_base_lt_one
#check @Real.rpow_logb
#check @Real.inv_logb
#check @Real.rpow_mul
#check @Real.rpow_lt_rpow
#check @Real.zero_rpow
#check @tendsto_pow_atTop_nhds_zero_iff
#check @map_zpow
-- part 3
#check @Real.sInf_nonneg
#check @csInf_le
#check @le_csInf
#check @IsLeast.csInf_eq
#check @Real.rpow_le_rpow_left_iff_of_base_lt_one
#check @Int.floor_le
#check @Int.lt_floor_add_one
#check @Int.le_floor
#check @Real.rpow_intCast
#check @Real.logb_rpow
#check @exists_pow_lt_of_lt_one
#check @Monotone.map_max
#check @max_le_add_of_nonneg
#check @norm_le_zero_iff
#check @IsBoundedSMul.of_norm_smul_le
#check @mul_le_one₀
#check @Ideal.mem_span_singleton'
#check @Ideal.mem_span_singleton_self
#check @Ideal.span_singleton_pow
#check @Submodule.fg_span_singleton
#check @zpow_lt_one_iff_right_of_lt_one₀
#check @Submodule.smul_induction_on
#check @Submodule.smul_mem_smul
#check @isAdic_iff
#check @Metric.mem_nhds_iff
#check @Metric.nhds_basis_closedBall_pow
#check @Set.mem_smul_set
#check @Filter.HasBasis.to_hasBasis
#check @Filter.HasBasis.mem_of_mem
#check @Filter.HasBasis.mem_iff
#check @continuous_mul_right
#check @Int.exists_greatest_of_bdd
#check @zpow_le_zpow_iff_right₀
#check @zpow_lt_zpow_iff_right₀
#check @zpow_lt_zpow_iff_right_of_lt_one₀
#check @Real.sInf_smul_of_nonneg
#check @zpow_add₀
#check @isOpen_compl_singleton
#check @zpow_natCast
#check @Units.val_pow_eq_pow_val
#check @PadicInt.subring
#check @Padic.norm_eq_zpow_neg_valuation
#check @Padic.norm_p
#check @PadicInt.norm_p
#check @PadicInt.isUnit_iff
#check @PadicInt.toZMod
#check @PadicInt.ker_toZMod
#check @ZMod.ringHom_surjective
#check @RingHom.quotientKerEquivOfSurjective
#check @Ideal.quotEquivOfEq
#check @IsAlgClosed.exists_pow_nat_eq
#check @PadicComplex.norm_extends
#check @map_natCast
#check @Int.norm_eq_abs
#check @discreteTopology_iff_nhds_ne
#check @Set.zero_mul_subset
#check @isOpen_discrete
#check @abs_add_three
#check @add_eq_zero_iff_of_nonneg
#check @Nat.even_or_odd'
#check @Algebra.algebraMap_self
#check @Subring.smul_def
#check @inv_lt_one_of_one_lt₀
#check @zpow_le_one_iff_right₀
