import PhD.TauCeti.Code.RigidAnalyticGeometry.TateAlgebra.Examples

/-! Every floor, chain and board name in a "Mathlib lemmas needed" block (generated by
`extract_names.py`). -/

open MvPowerSeries MvPowerSeries.Restricted Affinoid Affinoid.TateAlgebra

#check @Restricted.norm_le_iff  -- T001
#check @Restricted.exists_achievesGaussNorm  -- T001
#check @Restricted.norm_def  -- T001
#check @Restricted.hasSum_monomial  -- T001
#check @Restricted.ext  -- T002
#check @val_zero  -- T002
#check @val_one  -- T002
#check @val_mul  -- T002
#check @val_C  -- T002
#check @MvPolynomial.toRestricted_monomial  -- T003
#check @Restricted.val_smul  -- T003
#check @Restricted.norm_lt_iff  -- T004
#check @NormedRing.maximalIdeal_unitClosedBall  -- T006
#check @NormedRing.mem_openUnitBallIdeal  -- T006
#check @Subring.norm_le_one  -- T008
#check @MvPolynomial.val_toRestricted  -- T009
#check @PowerBounded.isPowerBounded_iff_norm_le_one  -- T010
#check @isTopologicallyNilpotent_iff_norm_lt_one  -- T010
#check @Restricted.isUnit_iff  -- T011
#check @Restricted.constantCoeff_eq_coeff_zero  -- T011
#check @NormedRing.isUnit_iff_isUnit_mk  -- T011
#check @Restricted.algebraMap_apply  -- T012
#check @Restricted.val_C  -- T012
#check @IsUltrametricDist.summable_prod_map₂  -- T015
#check @MvPolynomial.toRestricted_C  -- T016
#check @MvPolynomial.toRestricted_X  -- T016
#check @NormedRing.isUnit_iff_norm_eq_one  -- T019
#check @coeff_coeffX0  -- T029
#check @coeff_ofPolynomial  -- T030
#check @coeffX0_ofPolynomial  -- T030
#check @ofPolynomial_injective  -- T030
#check @isMulDistinguishedX0_iff  -- T031
#check @weierstrassPreparation_exists  -- T034
#check @weierstrassPreparation_omega_unique  -- T034
#check @weierstrassDivision_exists  -- T035
#check @weierstrassDivision_r_unique  -- T035
#check @Restricted.norm_X  -- T041
#check @Restricted.norm_C  -- T041
#check @Restricted.isEmptyEquiv  -- T050
#check @IsOrthonormalFamily.norm_le_of_hasSum  -- T059
#check @IsOrthonormalFamily.norm_coeff_le_of_hasSum  -- T059
#check @AddSubgroup.dense_of_infDist_le  -- T061
#check @Restricted.norm_monomial  -- T063
#check @Restricted.val_sum  -- T063
#check @Restricted.val_monomial  -- T063
#check @Subring.isBald_closure_range  -- T065
#check @IsOrthonormalBasis.of_residue_basis  -- T065
#check @Filter.Tendsto.exists_forall_norm_le  -- T067
#check @IsUltrametricDist.norm_tsum_lt_of_forall_lt  -- T067
#check @IsOrthonormalFamily.summable_smul  -- T067
#check @IsOrthonormalFamily.tendsto_cofinite_of_hasSum  -- T067
#check @IsOrthonormalBasis.exists_hasSum  -- T068
#check @Restricted.norm_coeff_lt_norm_constantCoeff_of_isUnit  -- T078
