import Mathlib

/-! Mathlib names cited by the tickets of the board, checked by elaboration against the pin.
(The port cannot be imported together with `import Mathlib`: mathlib4#39583 redefines
`PowerSeries.IsRestricted`.) -/

-- Basic.lean
#check @NormMulClass.toNoZeroDivisors
#check @NoZeroDivisors.to_isDomain
#check @Real.mul_iSup_of_nonneg
#check @MvPowerSeries.coeff_smul
#check @Filter.Tendsto.eventually_lt_const
#check @Filter.eventually_cofinite
#check @RingHom.charZero
#check @norm_smul
#check @DenseRange
-- Reduction.lean
#check @IsLocalRing.residue_eq_zero_iff
#check @IsLocalRing.residue_surjective
#check @MvPolynomial.coeff_mul
#check @MvPowerSeries.coeff_mul
#check @MvPolynomial.map_surjective
#check @MvPolynomial.coeff_map
#check @Ideal.quotEquivOfEq
#check @RingHom.quotientKerEquivOfSurjective
#check @MvPolynomial.isUnit_iff_eq_C_of_isReduced
#check @Ideal.exists_le_maximal
#check @Ideal.mem_jacobson_bot
#check @NormedField.nhdsNE_neBot
#check @MvPolynomial.coeff_one
#check @Finsupp.ofSupportFinite_coe
-- Eval.lean
#check @Finset.norm_prod_le'
#check @norm_pow_le'
#check @NonarchimedeanAddGroup.summable_of_tendsto_cofinite_zero
#check @tsum_eq_single
#check @Summable.tsum_add
#check @Summable.tsum_mul_tsum_eq_tsum_sum_antidiagonal
#check @IsUltrametricDist.norm_tsum_le
#check @IsUltrametricDist.norm_tsum_le_of_forall_le_of_nonneg
#check @Finsupp.prod_add_index'
#check @MvPolynomial.ringHom_ext
#check @DenseRange.equalizer
#check @norm_algebraMap'
#check @MvPolynomial.aeval_def
#check @MvPolynomial.induction_on
#check @AddMonoidHomClass.continuous_of_bound
#check @squeeze_zero_norm'
-- EvalReduction.lean
#check @IsLocalRing.ResidueField.map
#check @IsLocalRing.ResidueField.map_residue
#check @MvPolynomial.eval₂_map
#check @MvPolynomial.eval₂_comp
#check @MvPolynomial.map_map
#check @MvPolynomial.aeval_eq_eval₂Hom
#check @RingHom.restrict
-- SupSeminorm.lean
#check @spectralValue_nonneg
#check @minpoly.zero
#check @spectralValue_X_pow
#check @Subalgebra.isField_of_algebraic
#check @Ideal.Quotient.maximal_of_isField
#check @Ideal.quotientKerAlgEquivOfSurjective
#check @Ideal.kerLiftAlg
#check @Ideal.kerLiftAlg_injective
#check @minpoly.algHom_eq
#check @NormedAlgebra.norm_eq_spectralNorm
#check @spectralNorm.spectralNorm_eq_norm_coeff_zero_rpow
#check @AdjoinRoot.minpoly_root
#check @minpoly.irreducible
#check @isUnit_one_sub_of_norm_lt_one
#check @IsUltrametricDist.exists_norm_finsetSum_le
#check @Polynomial.aeval_eq_sum_range
#check @minpoly.aeval
#check @Real.iSup_of_isEmpty
#check @ciSup_le
#check @le_ciSup
#check @minpoly.eq_zero
#check @spectralValueTerms_of_lt_natDegree
#check @spectralValueTerms_bddAbove
#check @minpoly.monic
#check @MaximalSpectrum
-- MaxModulus.lean
#check @IsUltrametricDist.norm_natCast_le_one
#check @IsUltrametricDist.norm_add_eq_max_of_norm_ne_norm
#check @Polynomial.separable_X_pow_sub_C
#check @Polynomial.card_rootSet_eq_natDegree
#check @Polynomial.SplittingField.splits
#check @Polynomial.natDegree_X_pow_sub_C
#check @spectralNorm_extends
#check @isNonarchimedean_spectralNorm
#check @spectralAlgNorm_mul
#check @Polynomial.derivative_X_pow
#check @MvPolynomial.eq_zero_of_eval_zero_at_prod_finset
#check @MvPolynomial.map_injective
#check @MvPolynomial.degreeOf_le_iff
#check @spectralNorm.normedField
#check @spectralNorm.normedAlgebra
#check @spectralNorm.completeSpace
#check @IsUltrametricDist.isUltrametricDist_of_isNonarchimedean_norm
#check @Finset.card_image_of_injOn
