import Mathlib

/-! Mathlib names cited by the tickets of the board, checked by elaboration (batch 4: the names
added while the proof sketches were written). -/

-- Basic.lean
#check @charZero_of_injective_ringHom
#check @MvPowerSeries.constantCoeff_C
example {R σ : Type*} [Ring R] [NoZeroDivisors R] : NoZeroDivisors (MvPowerSeries σ R) := inferInstance
#check @Metric.denseRange_iff
-- Reduction.lean
#check @isUnit_map_iff
#check @MvPowerSeries.coeff_one
#check @MvPowerSeries.coeff_monomial
#check @MvPowerSeries.coeff_C
#check @MvPowerSeries.coeff_X
#check @MvPolynomial.coeff_coe
#check @Ideal.quotEquivOfEq_mk
-- Eval.lean
#check @Summable.mul_of_nonarchimedean
#check @tsum_mul_tsum_of_nonarchimedean
-- (no `NonarchimedeanRing` instance for an ultrametric normed ring at the pin: T015 uses the chain's
-- `IsUltrametricDist.summable_prod_map₂` instead of `Summable.mul_of_nonarchimedean`)
#check @Summable.tsum_mul_tsum_eq_tsum_sum_antidiagonal
#check @Finsupp.prod_single_index
#check @MvPolynomial.eval₂Hom
#check @MvPolynomial.eval₂_C
#check @MvPolynomial.eval₂_X
-- SupSeminorm.lean
#check @Module.Finite.of_injective
#check @Ideal.Quotient.eq_zero_iff_mem
#check @Ideal.Quotient.liftₐ
#check @NormedAlgebra.norm_eq_spectralNorm
#check @minpoly.algHom_eq
#check @spectralNorm.spectralNorm_eq_norm_coeff_zero_rpow
#check @AdjoinRoot.minpoly_root
#check @minpoly.natDegree_pos
#check @Polynomial.aeval_algHom_apply
#check @Ideal.eq_top_of_isUnit_mem
#check @norm_pow_le'
#check @pow_lt_pow_left₀
#check @spectralValue
#check @spectralValueTerms
-- MaxModulus.lean
#check @Polynomial.Splits.eval_root_derivative
#check @spectralNorm_extends
#check @spectralAlgNorm_mul
#check @isPowMul_spectralNorm
#check @Polynomial.card_rootSet_eq_natDegree
#check @Polynomial.separable_X_pow_sub_C
#check @MvPolynomial.eq_zero_of_eval_zero_at_prod_finset
#check @MvPolynomial.eval_map
#check @Algebra.IsAlgebraic.of_finite
-- Distinguished.lean / Finiteness.lean
#check @Polynomial.natDegree_le_iff_coeff_eq_zero
#check @Polynomial.coeff_eq_zero_of_natDegree_lt
#check @Polynomial.natDegree_eq_zero_of_isUnit
#check @Polynomial.natDegree_mul
#check @Polynomial.monic_X_pow
#check @Polynomial.coeff_X_pow
#check @Polynomial.natDegree_eq_of_degree_eq_some
#check @injective_iff_map_eq_zero
#check @Set.image_singleton
#check @Polynomial.Monic.finite_quotient
#check @Ideal.span_singleton_mul_left_unit
-- Chart.lean
#check @MvPolynomial.aeval_C
#check @MvPolynomial.monomial_eq
#check @Finsupp.prod_fintype
#check @Fin.prod_univ_succ
#check @Fin.sum_univ_succ
#check @Polynomial.natDegree_X_pow_add_C
#check @Polynomial.leadingCoeff_X_pow_add_C
#check @Polynomial.natDegree_prod
#check @Polynomial.leadingCoeff_prod
#check @MvPolynomial.finSuccEquiv_comp_C_eq_C
#check @Polynomial.degree_sum_le
#check @AlgEquiv.symm_apply_apply
-- Rueckert.lean
#check @ringKrullDim_quotient
#check @Order.coheight_eq_krullDim_Ici
#check @Order.rev_index_le_coheight
#check @PrimeSpectrum.zeroLocus
#check @Submodule.fg_of_fg_map_of_fg_inf_ker
#check @isNoetherian_of_tower
#check @Ideal.Quotient.isNoetherianRing
#check @Ideal.map_of_equiv
#check @Submodule.exists_mem_ne_zero_of_ne_bot
#check @Ideal.mem_map_of_mem
#check @Ideal.quotientMap_comp_mk
#check @RingEquiv.ofBijective
#check @Ideal.jacobson_mono
#check @Ideal.map_jacobson_of_bijective
#check @Ideal.map_isPrime_of_equiv
#check @RingHom.IsIntegral.trans
#check @RingHom.isIntegral_of_surjective
#check @Ideal.jacobson_eq_iff_jacobson_quotient_eq_bot
#check @Ideal.Quotient.factor
#check @Ideal.IsPrime.radical
#check @Polynomial.eq_of_monic_of_associated
#check @Polynomial.monic_multiset_prod_of_monic
#check @Ideal.quotientEquiv
#check @ringKrullDim_eq_bot_of_subsingleton
-- Bald.lean
#check @Subring.closure_mono
#check @Subring.closure_empty
#check @Subring.closure_eq
#check @Int.natAbs_eq
#check @Algebra.adjoin_eq_ring_closure
-- Orthonormal.lean / OrthonormalLift.lean
#check @Finset.sup_le
#check @tendsto_zero_iff_norm_tendsto_zero
#check @le_of_tendsto
#check @le_of_tendsto'
#check @hasSum_sum_of_ne_finset_zero
#check @mem_closure_iff_seq_limit
#check @Finsupp.onFinset
#check @LinearIndependent.ne_zero
#check @hasSum_sum
-- StrictlyClosed.lean
#check @linearIndepOn_empty
#check @MvPolynomial.as_sum
#check @Pi.norm_single
#check @Pi.hasSum
#check @Function.Injective.hasSum_iff
#check @Finset.equivFin
#check @LinearIndependent.disjoint_span_image
#check @HasSum.add_isCompl
#check @Metric.le_infDist
#check @Pi.norm_def
#check @Finset.exists_mem_eq_sup
-- WeaklyStable.lean / Japanese.lean
#check @spectralAlgNorm
#check @spectralNorm.normedField
#check @LinearMap.toContinuousLinearMap
#check @ContinuousLinearMap.le_opNorm
#check @IsFractionRing.injective
#check @IsIntegralClosure.finite
-- Examples.lean
#check @Padic.norm_p
#check @Polynomial.monic_X_pow_sub
#check @Polynomial.Monic.irreducible_iff_roots_eq_zero_of_degree_le_three
#check @Ideal.map_isMaximal_of_equiv
#check @MulEquiv.isField
#check @Padic.norm_eq_zpow_neg_valuation
#check @PrincipalIdealRing.isMaximal_of_irreducible
#check @Polynomial.mapEquiv
-- corrections and additions
#check @Ideal.fg_of_fg_map_of_fg_inf_ker_of_surjective
#check @Ideal.mk_ker
#check @isLocalHom_equiv
#check @exists_linearIndependent'
#check @Ideal.mem_map_iff_of_surjective
#check @Ideal.comap_lt_comap_of_integral_mem_sdiff
#check @Polynomial.Monic.isUnit_leadingCoeff_of_dvd
#check @PrimeSpectrum.mem_zeroLocus
#check @LTSeries.strictMono
#check @Ideal.Quotient.maximal_of_isField
#check @Polynomial.IsSplittingField.finiteDimensional
#check @FiniteDimensional.of_injective
#check @Finset.prod_le_prod
#check @IsUltrametricDist.norm_sum_le_of_forall_le_of_nonneg
#check @Finsupp.mem_span_range_iff_exists_finsupp
#check @Subring.closure_induction
#check @Polynomial.natDegree_C_mul_X_pow
#check @RingHom.Finite.of_surjective
#check @Polynomial.quotientSpanXSubCAlgEquiv
#check @Submodule.FG
#check @eq_inv_of_mul_eq_one_right
#check @Polynomial.irreducible_of_degree_eq_one
