import PhD.TauCeti.Code.RigidAnalyticGeometry.TateAlgebra.Examples

/-! Names of the restricted-series seam and of the `p`-adic functional analysis chain cited by the
tickets of the board, checked by elaboration. -/

open MvPowerSeries

#check @Restricted.norm_le_iff
#check @Restricted.norm_lt_iff
#check @Restricted.exists_coeff_ne_zero_norm_eq
#check @Restricted.hasSum_monomial
#check @Restricted.norm_monomial
#check @Restricted.norm_C
#check @Restricted.norm_X
#check @Restricted.norm_def
#check @Restricted.hasGaussNorm
#check @Restricted.exists_achievesGaussNorm
#check @Restricted.finite_setOfPred_achievesGaussNorm
#check @Restricted.gaussNorm_eq_zero_iff
#check @Restricted.isNonarchimedean_norm
#check @Restricted.ext
#check @Restricted.val_add
#check @Restricted.val_mul
#check @Restricted.val_one
#check @Restricted.val_sum
#check @Restricted.val_monomial
#check @Restricted.val_C
#check @Restricted.val_X
#check @Restricted.val_smul
#check @Restricted.algebraMap_apply
#check @Restricted.mapRetraction
#check @MvPolynomial.toRestricted
#check @MvPolynomial.toRestricted_monomial
#check @MvPolynomial.toRestricted_C
#check @MvPolynomial.toRestricted_X
#check @MvPolynomial.val_toRestricted
#check @MvPolynomial.toRestricted_injective
#check @Restricted.isUnit_iff
#check @Restricted.constantCoeff
#check @Restricted.constantCoeff_eq_coeff_zero
#check @Restricted.norm_coeff_lt_norm_constantCoeff_of_isUnit
#check @Restricted.isUnit_of_norm_lt_norm_constantCoeff
#check @Restricted.isEmptyEquiv
#check @Restricted.norm_isEmptyEquiv
#check @Restricted.finSuccEquiv
#check @Restricted.coeff_finSuccEquiv
#check @Restricted.norm_finSuccEquiv
#check @Restricted.IsMulDistinguishedX0
#check @Polynomial.toMvRestrictedX0
#check @Polynomial.coeff_toMvRestrictedX0
#check @Polynomial.norm_toMvRestrictedX0
#check @PowerSeries.IsMulDistinguished
#check @PowerSeries.Restricted.norm_le_iff
#check @PowerSeries.Restricted.norm_coeff_mul_pow_le
#check @Polynomial.toRestricted
#check @Polynomial.val_toRestricted
#check @IsNormMulUnit
#check @IsUnit.isNormMulUnit
#check @IsNormMulUnit.isUnit
#check @AddSubgroup.dense_of_infDist_le
#check @Subgroup.dense_of_infDist_le
#check @MvPowerSeries.exists_achievesGaussNorm_dominant
-- the p-adic functional analysis chain
#check @Subring.unitClosedBall
#check @Subring.mem_unitClosedBall
#check @Subring.norm_le_one
#check @NormedRing.openUnitBallIdeal
#check @NormedRing.mem_openUnitBallIdeal
#check @NormedRing.maximalIdeal_unitClosedBall
#check @NormedRing.isUnit_iff_isUnit_mk
#check @NormedRing.isUnit_iff_norm_eq_one
#check @NormedRing.instIsLocalRingUnitClosedBall
#check @NormedRing.isUnit_of_norm_one_sub_lt_one
#check @PowerBounded.isPowerBounded_iff_norm_le_one
#check @isTopologicallyNilpotent_iff_norm_lt_one
#check @IsUltrametricDist.norm_tsum_le_of_forall_le
-- the tower wrappers
#check @Affinoid.TateAlgebra.coeffX0
#check @Affinoid.TateAlgebra.coeff_coeffX0
#check @Affinoid.TateAlgebra.coeff_ofPolynomial
#check @Affinoid.TateAlgebra.coeffX0_ofPolynomial
#check @Affinoid.TateAlgebra.isMulDistinguishedX0_iff
#check @Affinoid.TateAlgebra.weierstrassDivision_exists
#check @Affinoid.TateAlgebra.weierstrassDivision_r_unique
#check @Affinoid.TateAlgebra.weierstrassDivision_q_unique
#check @Affinoid.TateAlgebra.weierstrassPreparation_exists
#check @Affinoid.TateAlgebra.weierstrassPreparation_omega_unique
#check @Affinoid.TateAlgebra.weierstrassPreparation_e_unique
-- added while the sketches were written
#check @IsUltrametricDist.summable_prod_map₂
#check @IsUltrametricDist.norm_tsum_lt_of_forall_lt
#check @IsUltrametricDist.norm_tsum_eq_of_forall_lt
#check @Filter.Tendsto.exists_forall_norm_le
#check @Filter.Tendsto.bddAbove_range_norm
#check @IsOrthonormalBasis.exists_hasSum
#check @IsOrthonormalFamily.norm_le_of_hasSum
#check @IsOrthonormalFamily.norm_coeff_le_of_hasSum
#check @Restricted.exists_norm_coeff_eq
#check @Restricted.norm_coeff_le
#check @Restricted.finite_setOf_le_norm_coeff
#check @Restricted.norm_smul_eq
#check @Restricted.reduction
#check @Restricted.aeval
#check @Restricted.eval₂
#check @Affinoid.evalNorm
#check @IsRueckert
#check @Subring.IsBald
#check @IsWeaklyStable
#check @IsJapaneseRing
