import Mathlib

/-! Mathlib names cited by the ticket sketches (batch 5: names introduced while the sketches were
written). -/

#check @MvPolynomial.degreeOf_lt_iff
#check @Polynomial.mem_rootSet
#check @pow_eq_one_iff_of_nonneg
#check @Ideal.Quotient.liftₐ_apply
#check @Ideal.Quotient.mkₐ
#check @MvPolynomial.map_C
#check @MvPolynomial.map_X
#check @MvPolynomial.coe_eval₂Hom
#check @RingHom.codRestrict
#check @AlgHom.coe_ringHom_injective
#check @Real.rpow_natCast
#check @Real.rpow_mul
#check @Finsupp.prod_zero_index
#check @MvPolynomial.coeff_sum
#check @AddSubmonoidClass.coe_finsetSum
#check @MvPolynomial.coeff_zero
#check @MvPolynomial.ext_iff
#check @isUnit_iff_exists_inv
#check @Finset.mem_antidiagonal
#check @mul_mul_mul_comm
#check @inv_smul_smul₀
#check @norm_sub_rev
#check @dist_eq_norm
#check @Finset.prod_const_one
#check @MvPolynomial.coeff_add
#check @RingHom.mem_ker
#check @MvPolynomial.coeff_monomial
#check @Finset.sum_ite_eq
#check @RingHom.quotientKerEquivOfSurjective_apply_mk
#check @tsum_congr
#check @Finsupp.prod_add_index'
#check @norm_smul_le
#check @Set.Finite.subset
#check @Polynomial.coeff_C_zero
#check @Finsupp.cons_zero_zero
#check @Finsupp.cons_ne_zero_iff
#check @mul_lt_mul_left
#check @Polynomial.le_natDegree_of_ne_zero
#check @le_mul_of_one_le_right
#check @Ideal.Quotient.eq
#check @Ideal.quotientMap_mk
#check @RingHom.finite_algebraMap
#check @Polynomial.C_eq_zero
#check @Ideal.Quotient.lift_comp_mk
#check @Module.Finite.fg_top
#check @Polynomial.as_sum_range'
#check @Nat.add_mul_mod_self_left
#check @Nat.mod_eq_of_lt
#check @Nat.eq_of_mul_eq_mul_left
#check @MvPolynomial.support_nonempty
#check @Finset.add_sum_erase
#check @Polynomial.leadingCoeff_add_of_degree_lt'
#check @MvPolynomial.coeff_X
#check @Nat.lt_succ_of_le
#check @norm_pos_iff
#check @Finset.sup_lt_iff
#check @Polynomial.natDegree_C
#check @Polynomial.natDegree_X_pow
#check @Polynomial.leadingCoeff_C
#check @Polynomial.leadingCoeff_X_pow
#check @Polynomial.natDegree_pow
#check @Polynomial.leadingCoeff_pow
#check @AlgEquiv.commutes
#check @Polynomial.Monic.coeff_natDegree
#check @Polynomial.Monic.mul
#check @spectralValueTerms_of_natDegree_le
#check @Polynomial.leadingCoeff_mul
#check @IsUnit.mul_iff
#check @Algebra.smul_def
#check @Polynomial.coeff_X
#check @Polynomial.coeff_C
#check @MvPolynomial.coeff_C
#check @Polynomial.derivative_X_pow
#check @RingHom.Finite.of_comp_finite
#check @SetLike.exists_of_lt
#check @PrimeSpectrum.asIdeal_le_asIdeal
#check @RingHom.comp_assoc
#check @Ideal.FG.map
#check @IsJacobsonRing.out
#check @Associated.prime
#check @MulEquiv.isDomain
#check @map_multiset_prod
#check @Multiset.induction_on
#check @mem_nonZeroDivisors_of_ne_zero
#check @Polynomial.X_ne_zero
#check @AlgEquiv.toRingEquiv
#check @Units.inv_mul_cancel_left
#check @div_add_div
#check @div_mul_div_comm
#check @norm_div
#check @inv_div
#check @Nat.find_min
#check @Nat.div_add_mod
#check @Polynomial.natDegree_modByMonic_lt
#check @Polynomial.aeval_X
#check @Polynomial.aeval_C
#check @Set.insert_eq
#check @Set.insert_subset_insert
#check @Set.Finite.image
#check @Real.coe_toNNReal
#check @ge_of_tendsto
#check @Filter.eventually_ge_atTop
#check @cauchySeq_tendsto_of_complete
#check @Filter.Tendsto.cauchySeq
#check @tendsto_nhds_unique
#check @Finsupp.smul_apply
#check @LinearMap.ker_eq_bot
#check @hasSum_ite_eq
#check @Submodule.sum_mem
#check @HasSum.const_smul
#check @Finset.sum_smul
#check @LinearIndepOn.notMem_span_of_insert
#check @LinearIndepOn.mono
#check @Module.Basis.span_eq
#check @MvPolynomial.monomial_mul
#check @Pi.basis_apply
#check @Pi.basis_repr
#check @sigma_mk_injective
#check @Dense.mono
#check @Finset.sum_apply
#check @Pi.single_apply
#check @Submodule.span_sdiff_singleton_zero
#check @Set.Finite.biUnion
#check @MvPowerSeries.coeff_monomial_mul
#check @LinearIndependent.map'
#check @Submodule.map_span
#check @HasSum.smul_const
#check @HasSum.unique
#check @smul_assoc
#check @squeeze_zero_norm
#check @Sum.inl_injective
#check @Submodule.disjoint_def
#check @isClosed_of_closure_subset
#check @Finset.sup_singleton
#check @LinearMap.proj
#check @Submodule.mem_dualCoannihilator
#check @Submodule.dualAnnihilator_bot
#check @Polynomial.nextCoeff_of_natDegree_pos
#check @Real.rpow_one
#check @LinearMap.mulRight
#check @div_eq_div_iff
#check @max_div_div_right
#check @Polynomial.monic_X_add_C
#check @Polynomial.natDegree_X_add_C
#check @Fin.succ_zero_eq_one
#check @inv_lt_one_of_one_lt₀
#check @Nat.Prime.one_lt
#check @Polynomial.degree_linear_le
#check @zpow_right_injective₀
#check @Polynomial.coeff_C_mul_X
#check @Ideal.mul_mem_left
#check @Submodule.span_induction
#check @Finsupp.sum_mapRange_index
#check @Polynomial.natDegree_X_pow_sub_C
#check @NormMulClass.toNormOneClass
#check @le_inv_mul_iff₀
#check @Ideal.span_le
#check @sub_sub_sub_cancel_right
#check @Finset.sum_mul
#check @Ideal.ext
#check @RingEquiv.trans_apply
#check @zero_smul
#check @inv_zero
#check @isUnit_one
