import Mathlib

/-! Mathlib names cited by the tickets of the board, checked by elaboration (batch 2). -/

-- corrections from batch 1
#check @Polynomial.Splits.eval_root_derivative
#check @MvPolynomial.degrees_map_le
#check @MvPolynomial.degreeOf_def
#check @trace_eq_finrank_mul_minpoly_nextCoeff
-- Distinguished.lean / Finiteness.lean
#check @Finsupp.cons_tail
#check @Finsupp.tail_cons
#check @Finsupp.cons_zero
#check @MvPolynomial.finSuccEquiv_coeff_coeff
#check @MvPolynomial.finSuccEquiv
#check @Polynomial.Monic.leadingCoeff
#check @Polynomial.modByMonic_add_div
#check @Polynomial.degree_modByMonic_lt
#check @Ideal.mem_span_singleton'
#check @Ideal.map_span
#check @RingHom.Finite.comp
#check @RingHom.Finite.of_comp_finite
#check @RingHom.Finite.of_surjective
#check @Module.Finite.of_surjective
#check @Polynomial.Monic.finite_quotient
#check @Ideal.Quotient.lift
#check @Ideal.quotientMap
#check @Ideal.le_comap_map
#check @Polynomial.degree_C_le
#check @Polynomial.degree_eq_natDegree
#check @MvPolynomial.isUnit_iff_eq_C_of_isReduced
#check @Polynomial.leadingCoeff
#check @Module.Finite.trans
-- Rueckert.lean
#check @isNoetherianRing_iff_ideal_fg
#check @Polynomial.isNoetherianRing
#check @isJacobsonRing_iff_prime_eq
#check @isJacobsonRing_of_isIntegral'
#check @Ideal.radical_eq_sInf
#check @Ideal.radical_le_jacobson
#check @RingHom.Finite.to_isIntegral
#check @UniqueFactorizationMonoid.of_exists_prime_factors
#check @UniqueFactorizationMonoid.exists_prime_factors
#check @Polynomial.leadingCoeff_mul
#check @Ideal.span_singleton_prime
#check @Ideal.Quotient.isDomain_iff_prime
#check @MulEquiv.prime_iff
#check @Ideal.comap_lt_comap_of_integral_mem_sdiff
#check @ringKrullDim_eq_of_ringEquiv
#check @ringKrullDim_quotient_succ_le_of_nonZeroDivisor
#check @ringKrullDim_eq_zero_of_field
#check @ringKrullDim_le_of_surjective
#check @Polynomial.quotientSpanXSubCAlgEquiv
#check @isNoetherianRing_of_ringEquiv
#check @isJacobsonRing_of_surjective
#check @MulEquiv.uniqueFactorizationMonoid
#check @Ideal.IsPrime.comap
#check @Ideal.isMaximal_comap_of_isIntegral_of_isMaximal
#check @Ideal.jacobson
#check @Polynomial.Monic.isUnit_leadingCoeff_of_dvd
#check @Polynomial.uniqueFactorizationMonoid
-- Chart.lean
#check @MvPolynomial.aeval_X
#check @MvPolynomial.algHom_ext
#check @AlgEquiv.ofAlgHom
#check @MvPolynomial.natDegree_finSuccEquiv
#check @Nat.ofDigits_inj_of_len_eq
#check @Polynomial.leadingCoeff_add_of_degree_lt
#check @MvPolynomial.support_sum_monomial_coeff
#check @MvPolynomial.finSuccEquiv_X_zero
#check @MvPolynomial.finSuccEquiv_X_succ
#check @MvPowerSeries.finSuccEquiv_X_zero
#check @MvPowerSeries.finSuccEquiv_X_succ
#check @MvPowerSeries.finSuccEquiv_C
#check @MvPolynomial.monomial_le_degreeOf
#check @Finset.exists_max_image
#check @Finset.sum_eq_add_sum_sdiff_singleton_of_mem
-- Bald.lean
#check @Subring.closure_induction
#check @Subring.mem_bot
#check @Subring.closure_union
#check @Subring.closure_le
#check @Subring.subset_closure
#check @Algebra.adjoin_singleton_eq_range_aeval
#check @IsUltrametricDist.norm_intCast_le_one
#check @Set.Finite.induction_on
#check @Nat.find
#check @IsUltrametricDist.norm_add_le_max
-- Orthonormal.lean / OrthonormalLift.lean
#check @Finset.le_sup
#check @nnnorm_smul
#check @linearIndependent_iff'
#check @Summable.tendsto_cofinite_zero
#check @HasSum.sub
#check @LinearMap.exists_leftInverse_of_injective
#check @Finsupp.mapRange.linearMap
#check @Submodule.span_induction
#check @Finsupp.mem_span_range_iff_exists_finsupp
