import PhD.ToPR.MvRestricted
import PhD.ToPR.Restricted

import Mathlib.RingTheory.MvPowerSeries.Rename
import Mathlib.Topology.Order.Basic

import PhD.Bryce.Equiv

open Filter
open scoped Topology

variable {R : Type*} [NormedCommRing R] [IsUltrametricDist R] (n : ℕ) (c : Fin (n + 1) → ℝ)
  [StrongPos c]

-- generated by claude after giving a proof outline; then cleaned up a lot
lemma finSuccEquiv_restricted_image_restricted
    (f : MvPowerSeries.Restricted R c) (i : ℕ): MvPowerSeries.IsRestricted (Fin.tail c)
    (PowerSeries.coeff i (MvPowerSeries.finSuccEquiv R n f.1)) := by
  have h := (f.2.comp (Finsupp.cons_right_injective i).tendsto_cofinite).const_mul (c 0 ^ i)⁻¹
  rw [mul_zero] at h
  refine h.congr (fun t ↦ ?_)
  simp only [MvPowerSeries.coeff_coeff_finSuccEquiv, Finsupp.prod_pow, Function.comp_apply,
    Fin.prod_univ_succ, Finsupp.cons_zero, mul_left_comm,
    inv_mul_cancel_left₀ (pow_ne_zero _ (StrongPos_pos c 0).ne')]
  rfl

lemma Finsupp.cons_injective (n : ℕ) (a : (Unit →₀ ℕ) → Fin n →₀ ℕ ) :
    Function.Injective (fun (t : Unit →₀ ℕ) ↦ Finsupp.cons (t ()) (a t)) := by
  intro s t hst
  suffices (Finsupp.cons (s ()) (a s)) 0 = (Finsupp.cons (t ()) (a t)) 0 by
    ext
    exact this
  congr
  -- looks similar to Finsupp.cons_right_injective, so need to work out if this is really new?

-- maybe they want this?
lemma Finsupp.cons_uncurry_injective {n : ℕ} {M : Type u_1} [Zero M] :
    Function.Injective (Function.uncurry (Finsupp.cons (n := n) (M := M))) :=
  Function.Injective2.uncurry (Finsupp.cons_injective2)

lemma Finsupp.cons_uncurry_surjective {n : ℕ} {M : Type u_1} [Zero M] :
    Function.Surjective (Function.uncurry (Finsupp.cons (n := n) (M := M))) :=
  fun s ↦ ⟨(s 0, Finsupp.tail s), Finsupp.cons_tail s⟩

lemma Finsupp.cons_uncurry_cofinite {n : ℕ} {M : Type u_1} [Zero M] :
    (cofinite : Filter (Fin (n + 1) →₀ M)) =
    Filter.map (Function.uncurry (Finsupp.cons (M := M) (n := n))) cofinite :=
  le_antisymm Finsupp.cons_uncurry_surjective.le_map_cofinite
      Finsupp.cons_uncurry_injective.tendsto_cofinite

lemma MvPowerSeries.funSuccEquivSymm_coeff {M : Type*} [CommRing M] (n : ℕ) (s : Fin (n + 1) →₀ ℕ)
    (f : PowerSeries (MvPowerSeries (Fin n) M)) :
    MvPowerSeries.coeff s ((MvPowerSeries.finSuccEquiv M n).symm f) =
    MvPowerSeries.coeff (Finsupp.tail s) (PowerSeries.coeff (s 0) f) := by
  rw [(Finsupp.cons_tail s).symm, ← MvPowerSeries.coeff_coeff_finSuccEquiv,
    AlgEquiv.apply_symm_apply]
  rfl

instance : StrongPos (Fin.tail c) where
  pos := by
    simp_rw [Fin.tail]
    exact fun i ↦ StrongPos.pos i.succ

-- proof generated mostly by claude
lemma finSuccEquiv_restricted_image :
    (MvPowerSeries.isSubring (R := R) c).map (MvPowerSeries.finSuccEquiv R n).toRingEquiv.toRingHom =
    (PowerSeries.isSubring (R := MvPowerSeries.Restricted R (Fin.tail c)) (c 0)).map
      (PowerSeries.map (MvPowerSeries.isSubring (R := R) (Fin.tail c)).subtype) := by
  ext
  constructor
  · rintro ⟨f, hf, rfl⟩
    set h : PowerSeries ↥(MvPowerSeries.isSubring (Fin.tail c)) :=
      PowerSeries.mk fun i ↦ ⟨PowerSeries.coeff i (MvPowerSeries.finSuccEquiv R n f),
      finSuccEquiv_restricted_image_restricted n c ⟨f, hf⟩ i⟩
    refine ⟨h, ?_, ?_⟩
    · show PowerSeries.IsRestricted (c 0) _
      choose a ha using fun t ↦ MvRestricted.gaussNorm_achieved (Fin.tail c)
        (fun _ ↦ (StrongPos_pos c _).le)
        (MvPowerSeries.coeff t h)
      refine (hf.comp (Finsupp.cons_injective n a).tendsto_cofinite).congr fun t ↦ ?_
      -- this could maybe be extracted? but not sure if it worth it
      have hat : ‖MvPowerSeries.coeff (a t) (PowerSeries.coeff (t ())
        (MvPowerSeries.finSuccEquiv R n f))‖ * (a t).prod (Fin.tail c · ^ ·) =
        MvPowerSeries.gaussNorm norm (Fin.tail c) (PowerSeries.coeff (t ())
        (MvPowerSeries.finSuccEquiv R n f)) := ha t
      simp_rw [Finsupp.prod_pow, Finset.univ_unique, Finset.prod_singleton, Function.comp_apply,
        ← MvPowerSeries.coeff_coeff_finSuccEquiv, Fin.tail, Fin.prod_univ_succ,
        Finsupp.cons_zero, Finsupp.cons_succ] at ⊢ hat
      change _ = MvPowerSeries.gaussNorm norm (Fin.tail c)
        (PowerSeries.coeff (t ()) (MvPowerSeries.finSuccEquiv R n f)) * c 0 ^ t ()
      -- this should be seen through?
      grind
    · ext; simp [h]
  · rintro ⟨h, hh, rfl⟩
    refine ⟨(MvPowerSeries.finSuccEquiv R n).symm
        (PowerSeries.map (MvPowerSeries.isSubring (Fin.tail c)).subtype h), ?_, ?_⟩
    · show MvPowerSeries.IsRestricted c _
      let h' : PowerSeries (MvPowerSeries.Restricted R (Fin.tail c)) := h
      have hh : PowerSeries.IsRestricted (c 0) h' := hh
      simp_rw [PowerSeries.isRestricted_iff] at hh
      set F : (Fin (n + 1) →₀ ℕ) → ℝ := fun s ↦
        ‖MvPowerSeries.coeff s ((MvPowerSeries.finSuccEquiv R n).symm
          (PowerSeries.map (MvPowerSeries.isSubring (R := R) (Fin.tail c)).subtype h))‖ *
          s.prod (c · ^ ·)
      have hFΦ : ∀ (p : ℕ × (Fin n →₀ ℕ)), (F ∘ (Function.uncurry (Finsupp.cons))) p =
          ‖MvPowerSeries.coeff p.2 (PowerSeries.coeff p.1 h).val‖ * p.2.prod (Fin.tail c · ^ ·) *
          c 0 ^ p.1 := by
        rintro ⟨k, x⟩
        unfold F
        simp only [MvPowerSeries.funSuccEquivSymm_coeff, PowerSeries.coeff_map,
          Subring.subtype_apply, Finsupp.prod_pow, Fin.prod_univ_succ, Function.comp_apply,
          Function.uncurry_apply_pair, Finsupp.tail_cons, Finsupp.cons_zero, Finsupp.cons_succ,
          Fin.tail]
        ring
      rw [MvPowerSeries.IsRestricted, Finsupp.cons_uncurry_cofinite, Filter.tendsto_map'_iff,
        Filter.coprod_cofinite.symm]
      apply Tendsto.coprod_of_prod_top_right
      · intro s hs
        have hψ : Tendsto (fun x ↦ ∑ j ∈ hs.toFinset, ‖MvPowerSeries.coeff x
            (PowerSeries.coeff j h).val‖ * x.prod (Fin.tail c · ^ ·) * c 0 ^ j) cofinite (𝓝 0) := by
          have htends : ∀ j, Tendsto (fun x ↦ ‖MvPowerSeries.coeff x (PowerSeries.coeff j h).val‖ *
              x.prod (Fin.tail c · ^ ·) * c 0 ^ j) cofinite (𝓝 0) := fun j ↦ by
            simpa using ((PowerSeries.coeff j h).2).mul_const (c 0 ^ j)
          simpa using tendsto_finsetSum hs.toFinset (fun j _ ↦ htends j)
        refine tendsto_of_tendsto_of_tendsto_of_le_of_le' tendsto_const_nhds (hψ.comp tendsto_snd)
          (Eventually.of_forall fun p ↦ ?_) ?_
        · rw [hFΦ]
          refine mul_nonneg (mul_nonneg (norm_nonneg _) ?_) (pow_nonneg (StrongPos_pos c 0).le _)
          exact Finset.prod_nonneg (fun i _ ↦ pow_nonneg (StrongPos_pos c i.succ).le _)
        · filter_upwards [tendsto_fst.eventually (eventually_principal.mpr fun _ ha ↦ ha)] with p hp
          rw [hFΦ]
          refine Finset.single_le_sum (f := fun j ↦ ‖MvPowerSeries.coeff p.2
            (PowerSeries.coeff j h).val‖ * p.2.prod (Fin.tail c · ^ ·) * c 0 ^ j) (fun j _ ↦ ?_)
            (hs.mem_toFinset.mpr hp)
          refine mul_nonneg (mul_nonneg (norm_nonneg _) ?_) (pow_nonneg (StrongPos_pos c 0).le _)
          exact Finset.prod_nonneg (fun i _ ↦ pow_nonneg (StrongPos_pos c _).le _)
      · refine tendsto_of_tendsto_of_tendsto_of_le_of_le tendsto_const_nhds (hh.comp tendsto_fst)
          ?_ ?_
        all_goals intro p; rw [hFΦ]
        · refine mul_nonneg (mul_nonneg (norm_nonneg _) ?_) (pow_nonneg (StrongPos_pos c 0).le _)
          exact Finset.prod_nonneg (fun i _ ↦ pow_nonneg (StrongPos_pos c i.succ).le _)
        · exact mul_le_mul_of_nonneg_right (MvPowerSeries.le_gaussNorm norm (Fin.tail c)
            (PowerSeries.coeff p.1 h').val (MvRestricted.hasGaussNorm (Fin.tail c)
            (PowerSeries.coeff p.1 h')) p.2) (pow_nonneg (StrongPos_pos c 0).le _)
    · simp [AlgEquiv.apply_symm_apply]

variable (R) in
noncomputable
def MvRestricted.finSuccEquiv :
    MvPowerSeries.Restricted R c ≃+*
    PowerSeries.Restricted (MvPowerSeries.Restricted R (Fin.tail c)) (c 0) := by
  have := RingEquiv.subringMap (s := (MvPowerSeries.isSubring (R := R) c))
    (MvPowerSeries.finSuccEquiv R n).toRingEquiv
  rw [finSuccEquiv_restricted_image n c] at this
  exact (this).trans (Subring.equivMapOfInjective
    (PowerSeries.isSubring (R := MvPowerSeries.Restricted R (Fin.tail c)) (c 0))
    (PowerSeries.map (MvPowerSeries.isSubring (R := R) (Fin.tail c)).subtype)
    (PowerSeries.map_injective _ Subtype.val_injective)).symm
