import PhD.ToPR.MvRestricted
import PhD.ToPR.Restricted

import Mathlib.RingTheory.MvPowerSeries.Rename
import Mathlib.Topology.Order.Basic

import PhD.Bryce.Equiv

open Filter
open scoped Topology

variable {R : Type*} [NormedCommRing R] [IsUltrametricDist R] (n : ℕ) (c : Fin (n + 1) → ℝ)
  [StrongPos c]

-- generated by claude after giving a proof outline; then cleaned up a lot
lemma finSuccEquiv_restricted_image_restricted
    (f : MvPowerSeries.Restricted R c) (i : ℕ): MvPowerSeries.IsRestricted (Fin.tail c)
    (PowerSeries.coeff i (MvPowerSeries.finSuccEquiv R n f.1)) := by
  have h := (f.2.comp (Finsupp.cons_right_injective i).tendsto_cofinite).const_mul (c 0 ^ i)⁻¹
  rw [mul_zero] at h
  refine h.congr (fun t ↦ ?_)
  simp only [MvPowerSeries.coeff_coeff_finSuccEquiv, Finsupp.prod_pow, Function.comp_apply,
    Fin.prod_univ_succ, Finsupp.cons_zero, mul_left_comm,
    inv_mul_cancel_left₀ (pow_ne_zero _ (StrongPos_pos c 0).ne')]
  rfl

lemma Finsupp.cons_injective (n : ℕ) (a : (Unit →₀ ℕ) → Fin n →₀ ℕ ) :
    Function.Injective (fun (t : Unit →₀ ℕ) ↦ Finsupp.cons (t ()) (a t)) := by
  intro s t hst
  suffices (Finsupp.cons (s ()) (a s)) 0 = (Finsupp.cons (t ()) (a t)) 0 by
    ext
    exact this
  congr
  -- looks similar to Finsupp.cons_right_injective, so need to work out if this is really new?

-- maybe they want this?
lemma Finsupp.cons_uncurry_injective {n : ℕ} {M : Type u_1} [Zero M] :
    Function.Injective (Function.uncurry (Finsupp.cons (n := n) (M := M))) :=
  Function.Injective2.uncurry (Finsupp.cons_injective2)

lemma Finsupp.cons_uncurry_surjective {n : ℕ} {M : Type u_1} [Zero M] :
    Function.Surjective (Function.uncurry (Finsupp.cons (n := n) (M := M))) :=
  fun s ↦ ⟨(s 0, Finsupp.tail s), Finsupp.cons_tail s⟩

lemma Finsupp.cons_uncurry_cofinite {n : ℕ} {M : Type u_1} [Zero M] :
    (cofinite : Filter (Fin (n + 1) →₀ M)) =
    Filter.map (Function.uncurry (Finsupp.cons (M := M) (n := n))) cofinite :=
  le_antisymm Finsupp.cons_uncurry_surjective.le_map_cofinite
      Finsupp.cons_uncurry_injective.tendsto_cofinite

lemma MvPowerSeries.funSuccEquivSymm_coeff {M : Type*} [CommRing M] (n : ℕ) (s : Fin (n + 1) →₀ ℕ)
    (f : PowerSeries (MvPowerSeries (Fin n) M)) :
    MvPowerSeries.coeff s ((MvPowerSeries.finSuccEquiv M n).symm f) =
    MvPowerSeries.coeff (Finsupp.tail s) (PowerSeries.coeff (s 0) f) := by
  rw [(Finsupp.cons_tail s).symm, ← MvPowerSeries.coeff_coeff_finSuccEquiv,
    AlgEquiv.apply_symm_apply]
  rfl

instance : StrongPos (Fin.tail c) where
  pos := by
    simp_rw [Fin.tail]
    exact fun i ↦ StrongPos.pos i.succ

-- proof generated mostly by claude
lemma finSuccEquiv_restricted_image :
    (MvPowerSeries.isSubring (R := R) c).map (MvPowerSeries.finSuccEquiv R n).toRingEquiv.toRingHom =
    (PowerSeries.isSubring (R := MvPowerSeries.Restricted R (Fin.tail c)) (c 0)).map
      (PowerSeries.map (MvPowerSeries.isSubring (R := R) (Fin.tail c)).subtype) := by
  ext
  constructor
  · rintro ⟨f, hf, rfl⟩
    set h : PowerSeries ↥(MvPowerSeries.isSubring (Fin.tail c)) :=
      PowerSeries.mk fun i ↦ ⟨PowerSeries.coeff i (MvPowerSeries.finSuccEquiv R n f),
      finSuccEquiv_restricted_image_restricted n c ⟨f, hf⟩ i⟩
    refine ⟨h, ?_, ?_⟩
    · show PowerSeries.IsRestricted (c 0) _
      choose a ha using fun t ↦ MvRestricted.gaussNorm_achieved (Fin.tail c)
        (fun _ ↦ (StrongPos_pos c _).le)
        (MvPowerSeries.coeff t h)
      refine (hf.comp (Finsupp.cons_injective n a).tendsto_cofinite).congr fun t ↦ ?_
      -- this could maybe be extracted? but not sure if it worth it
      have hat : ‖MvPowerSeries.coeff (a t) (PowerSeries.coeff (t ())
        (MvPowerSeries.finSuccEquiv R n f))‖ * (a t).prod (Fin.tail c · ^ ·) =
        MvPowerSeries.gaussNorm norm (Fin.tail c) (PowerSeries.coeff (t ())
        (MvPowerSeries.finSuccEquiv R n f)) := ha t
      simp_rw [Finsupp.prod_pow, Finset.univ_unique, Finset.prod_singleton, Function.comp_apply,
        ← MvPowerSeries.coeff_coeff_finSuccEquiv, Fin.tail, Fin.prod_univ_succ,
        Finsupp.cons_zero, Finsupp.cons_succ] at ⊢ hat
      change _ = MvPowerSeries.gaussNorm norm (Fin.tail c)
        (PowerSeries.coeff (t ()) (MvPowerSeries.finSuccEquiv R n f)) * c 0 ^ t ()
      -- this should be seen through?
      grind
    · ext; simp [h]
  · rintro ⟨h, hh, rfl⟩
    refine ⟨(MvPowerSeries.finSuccEquiv R n).symm
        (PowerSeries.map (MvPowerSeries.isSubring (Fin.tail c)).subtype h), ?_, ?_⟩
    · show MvPowerSeries.IsRestricted c _
      let h' : PowerSeries (MvPowerSeries.Restricted R (Fin.tail c)) := h
      have hh : PowerSeries.IsRestricted (c 0) h' := hh
      simp_rw [PowerSeries.isRestricted_iff] at hh
      set F : (Fin (n + 1) →₀ ℕ) → ℝ := fun s ↦
        ‖MvPowerSeries.coeff s ((MvPowerSeries.finSuccEquiv R n).symm
          (PowerSeries.map (MvPowerSeries.isSubring (R := R) (Fin.tail c)).subtype h))‖ *
          s.prod (c · ^ ·)
      have hFΦ : ∀ (p : ℕ × (Fin n →₀ ℕ)), (F ∘ (Function.uncurry (Finsupp.cons))) p =
          ‖MvPowerSeries.coeff p.2 (PowerSeries.coeff p.1 h).val‖ * p.2.prod (Fin.tail c · ^ ·) *
          c 0 ^ p.1 := by
        rintro ⟨k, x⟩
        unfold F
        simp only [MvPowerSeries.funSuccEquivSymm_coeff, PowerSeries.coeff_map,
          Subring.subtype_apply, Finsupp.prod_pow, Fin.prod_univ_succ, Function.comp_apply,
          Function.uncurry_apply_pair, Finsupp.tail_cons, Finsupp.cons_zero, Finsupp.cons_succ,
          Fin.tail]
        ring
      rw [MvPowerSeries.IsRestricted, Finsupp.cons_uncurry_cofinite, Filter.tendsto_map'_iff,
        Filter.coprod_cofinite.symm]
      apply Tendsto.coprod_of_prod_top_right
      · intro s hs
        have hψ : Tendsto (fun x ↦ ∑ j ∈ hs.toFinset, ‖MvPowerSeries.coeff x
            (PowerSeries.coeff j h).val‖ * x.prod (Fin.tail c · ^ ·) * c 0 ^ j) cofinite (𝓝 0) := by
          have htends : ∀ j, Tendsto (fun x ↦ ‖MvPowerSeries.coeff x (PowerSeries.coeff j h).val‖ *
              x.prod (Fin.tail c · ^ ·) * c 0 ^ j) cofinite (𝓝 0) := fun j ↦ by
            simpa using ((PowerSeries.coeff j h).2).mul_const (c 0 ^ j)
          simpa using tendsto_finsetSum hs.toFinset (fun j _ ↦ htends j)
        refine tendsto_of_tendsto_of_tendsto_of_le_of_le' tendsto_const_nhds (hψ.comp tendsto_snd)
          (Eventually.of_forall fun p ↦ ?_) ?_
        · rw [hFΦ]
          refine mul_nonneg (mul_nonneg (norm_nonneg _) ?_) (pow_nonneg (StrongPos_pos c 0).le _)
          exact Finset.prod_nonneg (fun i _ ↦ pow_nonneg (StrongPos_pos c i.succ).le _)
        · filter_upwards [tendsto_fst.eventually (eventually_principal.mpr fun _ ha ↦ ha)] with p hp
          rw [hFΦ]
          refine Finset.single_le_sum (f := fun j ↦ ‖MvPowerSeries.coeff p.2
            (PowerSeries.coeff j h).val‖ * p.2.prod (Fin.tail c · ^ ·) * c 0 ^ j) (fun j _ ↦ ?_)
            (hs.mem_toFinset.mpr hp)
          refine mul_nonneg (mul_nonneg (norm_nonneg _) ?_) (pow_nonneg (StrongPos_pos c 0).le _)
          exact Finset.prod_nonneg (fun i _ ↦ pow_nonneg (StrongPos_pos c _).le _)
      · refine tendsto_of_tendsto_of_tendsto_of_le_of_le tendsto_const_nhds (hh.comp tendsto_fst)
          ?_ ?_
        all_goals intro p; rw [hFΦ]
        · refine mul_nonneg (mul_nonneg (norm_nonneg _) ?_) (pow_nonneg (StrongPos_pos c 0).le _)
          exact Finset.prod_nonneg (fun i _ ↦ pow_nonneg (StrongPos_pos c i.succ).le _)
        · exact mul_le_mul_of_nonneg_right (MvPowerSeries.le_gaussNorm norm (Fin.tail c)
            (PowerSeries.coeff p.1 h').val (MvRestricted.hasGaussNorm (Fin.tail c)
            (PowerSeries.coeff p.1 h')) p.2) (pow_nonneg (StrongPos_pos c 0).le _)
    · simp [AlgEquiv.apply_symm_apply]

variable (R) in
noncomputable
def MvRestricted.finSuccEquiv : MvPowerSeries.Restricted R c ≃+*
    PowerSeries.Restricted (MvPowerSeries.Restricted R (Fin.tail c)) (c 0) :=
  ((RingEquiv.subringMap (s := (MvPowerSeries.isSubring (R := R) c))
  (MvPowerSeries.finSuccEquiv R n).toRingEquiv).trans
  (RingEquiv.subringCongr (finSuccEquiv_restricted_image n c))).trans
  (Subring.equivMapOfInjective _ _ (PowerSeries.map_injective _ Subtype.val_injective)).symm

instance : StrongPos (fun _ : Unit ↦ c 0) where
  pos := by simpa using StrongPos.pos 0

lemma MvRestricted.map_finSuccEquiv (f : MvPowerSeries.Restricted R c) :
    PowerSeries.map (MvPowerSeries.isSubring (R := R) (Fin.tail c)).subtype
        (MvRestricted.finSuccEquiv R n c f).1 = MvPowerSeries.finSuccEquiv R n f.1 := by
  let e2 := Subring.equivMapOfInjective
    (PowerSeries.isSubring (R := MvPowerSeries.Restricted R (Fin.tail c)) (c 0))
    (PowerSeries.map (MvPowerSeries.isSubring (R := R) (Fin.tail c)).subtype)
    (PowerSeries.map_injective _ Subtype.val_injective)
  show (e2 (e2.symm ((RingEquiv.subringCongr (finSuccEquiv_restricted_image n c))
    (RingEquiv.subringMap (MvPowerSeries.finSuccEquiv R n).toRingEquiv f)))).1 = _
  aesop -- proof done by Claude magic?

-- this is an important lemma to have... perhaps I can do it without the above statement though?
lemma MvRestricted.coeff_finSuccEquiv (f : MvPowerSeries.Restricted R c) (i : ℕ) :
    (PowerSeries.coeff i (MvRestricted.finSuccEquiv R n c f).1).1 =
    PowerSeries.coeff i (MvPowerSeries.finSuccEquiv R n f.1) := by
  have := MvRestricted.map_finSuccEquiv n c f
  apply_fun PowerSeries.coeff i at this
  simpa using this

-- Claude proof after initial simps to prompt in right direction
variable (R) in
lemma MvRestricted_finSuccEquiv_norm_eq_norm (f : MvPowerSeries.Restricted R c) :
    Restricted.gaussNorm _ (c 0) (MvRestricted.finSuccEquiv R n c f) =
    MvRestricted.gaussNorm R c f := by
  simp_rw [Restricted.gaussNorm, MvRestricted.gaussNorm, MvPowerSeries.gaussNorm]
  simp only [Finsupp.prod_pow, Finset.univ_unique, PUnit.default_eq_unit, Finset.prod_singleton]
  simp_rw [MvRestricted.norm_eq, MvPowerSeries.gaussNorm]
  simp_rw [Real.iSup_mul_of_nonneg (pow_nonneg ((StrongPos_pos c 0).le) _)]
  -- Pointwise identity relating the LHS expression to the RHS expression under the cons bijection
  have hpointwise : ∀ (t : Unit →₀ ℕ) (i : Fin n →₀ ℕ),
      (‖MvPowerSeries.coeff i (MvPowerSeries.coeff t (MvRestricted.finSuccEquiv R n c f).1).1‖ *
        i.prod (fun x1 x2 => Fin.tail c x1 ^ x2)) * c 0 ^ t PUnit.unit =
      ‖MvPowerSeries.coeff (Finsupp.cons (t ()) i) f.1‖ *
        ∏ a, c a ^ (Finsupp.cons (t ()) i) a := by
    intro t i
    have ht : MvPowerSeries.coeff t (MvRestricted.finSuccEquiv R n c f).1 =
        PowerSeries.coeff (t ()) (MvRestricted.finSuccEquiv R n c f).1 := by
      conv_lhs => rw [show t = Finsupp.single () (t ()) from Finsupp.unique_single t]
      rfl
    rw [ht, MvRestricted.coeff_finSuccEquiv, MvPowerSeries.coeff_coeff_finSuccEquiv,
      Fin.prod_univ_succ, Finsupp.prod_pow]
    simp only [Finsupp.cons_zero, Finsupp.cons_succ, Fin.tail]
    ring
  -- The LHS function (over the product) is bounded above by the gaussNorm of f
  have hbd : BddAbove (Set.range (fun (p : (Unit →₀ ℕ) × (Fin n →₀ ℕ)) =>
      (‖MvPowerSeries.coeff p.2
          (MvPowerSeries.coeff p.1 (MvRestricted.finSuccEquiv R n c f).1).1‖ *
        p.2.prod (fun x1 x2 => Fin.tail c x1 ^ x2)) * c 0 ^ p.1 PUnit.unit)) := by
    obtain ⟨B, hB⟩ := MvRestricted.hasGaussNorm c f
    refine ⟨B, ?_⟩
    rintro y ⟨⟨t, i⟩, rfl⟩
    show (‖MvPowerSeries.coeff i (MvPowerSeries.coeff t (MvRestricted.finSuccEquiv R n c f).1).1‖ *
        i.prod (fun x1 x2 => Fin.tail c x1 ^ x2)) * c 0 ^ t PUnit.unit ≤ B
    rw [hpointwise t i]
    exact hB ⟨Finsupp.cons (t ()) i, by simp [Finsupp.prod_pow]⟩
  -- Combine the iterated sup on the LHS into a single sup over the product
  rw [← ciSup_prod hbd]
  -- Reindex via the cons bijection
  let e : (Unit →₀ ℕ) × (Fin n →₀ ℕ) ≃ (Fin (n + 1) →₀ ℕ) :=
    { toFun := fun p => Finsupp.cons (p.1 ()) p.2
      invFun := fun s => (Finsupp.single () (s 0), Finsupp.tail s)
      left_inv := by
        rintro ⟨t, i⟩
        show (Finsupp.single () (Finsupp.cons (t ()) i 0),
            Finsupp.tail (Finsupp.cons (t ()) i)) = (t, i)
        rw [Finsupp.cons_zero, Finsupp.tail_cons, ← Finsupp.unique_single t]
      right_inv := by
        intro s
        show Finsupp.cons ((Finsupp.single () (s 0)) ()) (Finsupp.tail s) = s
        rw [Finsupp.single_eq_same, Finsupp.cons_tail] }
  refine e.iSup_congr ?_
  rintro ⟨t, i⟩
  exact (hpointwise t i).symm

variable (R) in
noncomputable
instance MvRestricted.finSuccIsometry' :
    RingHomIsometric (MvRestricted.finSuccEquiv R n c).toRingHom where
  norm_map := by convert MvRestricted_finSuccEquiv_norm_eq_norm R n c

variable (R) in
noncomputable
def MvRestricted.finSuccIsometry : MvPowerSeries.Restricted R c ≃ᵢ
    PowerSeries.Restricted (MvPowerSeries.Restricted R (Fin.tail c)) (c 0) := IsometryEquiv.mk
  (MvRestricted.finSuccEquiv R n c).toEquiv
  (RingHom.isometry (MvRestricted.finSuccEquiv R n c).toRingHom)

variable (R) in
noncomputable
def foo (c : Fin 0 → ℝ) [StrongPos c] : MvPowerSeries.Restricted R c ≃+* R := by
  have hSub : MvPowerSeries.isSubring (R := R) c = ⊤ := by
    refine SetLike.ext fun f => ⟨fun _ => trivial, fun _ => ?_⟩
    show MvPowerSeries.IsRestricted c f
    rw [MvPowerSeries.IsRestricted, Filter.cofinite_eq_bot]
    exact tendsto_bot
  exact ((RingEquiv.subringCongr hSub).trans Subring.topEquiv).trans
    (RingEquiv.ofBijective MvPowerSeries.C
      ⟨MvPowerSeries.C_injective, MvPowerSeries.C_surjective⟩).symm

variable (R) in
noncomputable
instance foo_isom' (c : Fin 0 → ℝ) [StrongPos c] :
    RingHomIsometric (foo R c).toRingHom where
  norm_map := by
    intro f
    have hSub : MvPowerSeries.isSubring (R := R) c = ⊤ := by
      refine SetLike.ext fun g => ⟨fun _ => trivial, fun _ => ?_⟩
      show MvPowerSeries.IsRestricted c g
      rw [MvPowerSeries.IsRestricted, Filter.cofinite_eq_bot]
      exact tendsto_bot
    have hf : MvPowerSeries.C (foo R c f) = f.1 := by
      change (RingEquiv.ofBijective MvPowerSeries.C
          ⟨MvPowerSeries.C_injective, MvPowerSeries.C_surjective⟩)
        ((RingEquiv.ofBijective MvPowerSeries.C
          ⟨MvPowerSeries.C_injective, MvPowerSeries.C_surjective⟩).symm
          (Subring.topEquiv ((RingEquiv.subringCongr hSub) f))) = f.1
      rw [RingEquiv.apply_symm_apply]
      rfl
    show ‖foo R c f‖ = MvPowerSeries.gaussNorm norm c f.1
    show ‖foo R c f‖ = ⨆ t : Fin 0 →₀ ℕ, ‖MvPowerSeries.coeff t f.1‖ * t.prod (c · ^ ·)
    rw [ciSup_subsingleton (0 : Fin 0 →₀ ℕ), Finsupp.prod_zero_index, mul_one, ← hf,
      MvPowerSeries.coeff_zero_C]

noncomputable
def foo_isom (c : Fin 0 → ℝ) [StrongPos c] : MvPowerSeries.Restricted R c ≃ᵢ R := IsometryEquiv.mk
  (foo R c).toEquiv (RingHom.isometry (foo R c).toRingHom)

variable (R) in
lemma MvRestricted.isCompleteSpace' [CompleteSpace R] :
    CompleteSpace (PowerSeries.Restricted (MvPowerSeries.Restricted R (Fin.tail c)) (c 0)) := by
  induction n with
  | zero =>
    haveI : CompleteSpace (MvPowerSeries.Restricted R (Fin.tail c)) := IsometryEquiv.completeSpace
      (foo_isom _)
    exact Restricted.isCompleteSpace _
  | succ n ih =>
    haveI : CompleteSpace (MvPowerSeries.Restricted R (Fin.tail c)) :=
      IsometryEquiv.completeSpace (MvRestricted.finSuccIsometry _ _ _)
    exact Restricted.isCompleteSpace _


-- this should be moved to MvRestricted!
instance MvRestricted.isCompleteSpace [CompleteSpace R] :
    CompleteSpace (MvPowerSeries.Restricted R c) := by
  exact @IsometryEquiv.completeSpace _ _ _ _ (MvRestricted.isCompleteSpace' R n c)
    (MvRestricted.finSuccIsometry R n c)
