/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import PhD.TauCeti.Code.PadicFunctionalAnalysis.ModelSpace.Truncation
import PhD.TauCeti.Code.PadicFunctionalAnalysis.ModelSpace.Matrix
import PhD.TauCeti.Code.PadicFunctionalAnalysis.Operator.Finite

/-!
# Truncations and finitely generated submodules of the model space

If `P ⊆ C₀(I, R)` is a finitely generated *closed* submodule over a Banach–Tate ring, then for every
`ε > 0` some finite truncation moves every `p ∈ P` by at most `ε ‖p‖` (Bellaïche, Lemma 3.1.12): the
open mapping theorem bounds the coefficients of `p` in the generators, and the generators are
approximated by their truncations. ⚠ Without closedness this is false (the roadmap's counterexample
is `ZeroAtInftyContinuousMap.Examples.geomDelta` in `ModelSpace/Examples.lean`). Over a Noetherian
Banach–Tate ring some truncation is injective on any finitely generated submodule, and every
finitely generated submodule of `C₀(I, R)` is closed (Buzzard, Lemma 2.3; Ludwig, Lemma 2.26) —
the statement that §1.4.3 of the roadmap defers to this layer.

Roadmap: `PhD/TauCeti/Roadmaps/PadicFunctionalAnalysis/README.md`, §2.6.4–2.6.5.
Tau Ceti home: `TauCeti/Analysis/Normed/Module/Ultra/ModelSpace/Closed.lean`.
-/

open Filter Topology Function
open scoped ZeroAtInfty ContinuousLinearMap.Ultra

namespace ZeroAtInftyContinuousMap

open NormedRing

variable {R : Type*} [NormedCommRing R] [NormOneClass R] [IsUltrametricDist R] [IsTate R]
  [CompleteSpace R] {I : Type*} [TopologicalSpace I] [DiscreteTopology I] [DecidableEq I]

/-- **Approximation of finitely generated closed submodules** (Bellaïche, Lemma 3.1.12): for a
finitely generated closed `P ⊆ C₀(I, R)` and `ε > 0` there is a finite `S` with
`‖π_S p − p‖ ≤ ε ‖p‖` for all `p ∈ P`. Source: roadmap §2.6.4 ("The proof is the open mapping
theorem applied to a surjection `R ^ r → P`, which is why closedness is a hypothesis"); Bellaïche,
Lemma 3.1.12. -/
theorem exists_truncation_near (P : Submodule R C₀(I, R)) (hP : P.FG)
    (hclosed : IsClosed (P : Set C₀(I, R))) {ε : ℝ} (hε : 0 < ε) :
    ∃ S : Finset I, ∀ p ∈ P, ‖truncation (↑S : Set I) p - p‖ ≤ ε * ‖p‖ := by
  sorry

variable [IsNoetherianRing R]

/-- Over a Noetherian ring some finite truncation is injective on any finitely generated
submodule: the column vectors `(g₁ i, …, g_r i) ∈ R ^ r` generate a finitely generated submodule,
hence are generated by finitely many of them. Source: roadmap §2.6.5 ("If `R` is Noetherian, some
truncation is injective on any finitely generated submodule of `C₀(I, R)`"); Buzzard, Lemma 2.3. -/
theorem exists_truncation_injOn (P : Submodule R C₀(I, R)) (hP : P.FG) :
    ∃ S : Finset I, Set.InjOn (truncation (R := R) (↑S : Set I)) (P : Set C₀(I, R)) := by
  sorry

/-- **Finitely generated submodules of the model space are closed over a Noetherian Banach–Tate
ring**: the injective truncation identifies `P` with a submodule of a finite free module, which is
closed by Layer 1's `Submodule.isClosed_of_isNoetherianRing`, and the inverse is continuous by
Buzzard's Lemma 2.2. Source: roadmap §2.6.5 ("every finitely generated submodule of `C₀(I, R)` is
closed (Buzzard, Lemma 2.3; Ludwig, Lemma 2.26)"). -/
theorem isClosed_of_fg (P : Submodule R C₀(I, R)) (hP : P.FG) : IsClosed (P : Set C₀(I, R)) := by
  sorry

end ZeroAtInftyContinuousMap
