/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import Mathlib.NumberTheory.Padics.Complex
import Mathlib.NumberTheory.Padics.ProperSpace
import Mathlib.Topology.ContinuousMap.Compact
import PhD.TauCeti.Code.NewtonPolygons.AddVal.Padic
import PhD.TauCeti.Code.PadicFunctionalAnalysis.Operator.Examples
import PhD.TauCeti.Code.PadicFunctionalAnalysis.CountableType
import PhD.TauCeti.Code.PadicFunctionalAnalysis.ModelSpace.Dual
import PhD.TauCeti.Code.PadicFunctionalAnalysis.ModelSpace.Closed
import PhD.TauCeti.Code.PadicFunctionalAnalysis.Unitriangular

/-!
# Examples for the model space and orthonormal bases

The roadmap's worked examples for Layer 2: `C₀(ℕ, ℚ_p)` with its canonical basis and its dual
`ℓ^∞(ℕ, ℚ_p)`; `C(ℤ_p, ℚ_p)` is orthonormalisable by Serre's theorem (Layer 3 exhibits the basis);
`ℂ_p` with the norm `2‖·‖` is potentially but not literally orthonormalisable, and so is `ℚ_p` with
the norm `2‖·‖` for odd `p` — a one-dimensional space with a norm whose values are not in `‖K‖`;
the matrix of the shift on `C₀(ℕ, R)`; the unitriangular perturbation `1 + N` with `N` strictly
lower triangular of norm `q`, and a matrix with entries in `ℤ_p`, unit diagonal and lower entries
in `pℤ_p`; and the roadmap's counterexample to §2.6.4 without closedness: the principal submodule of
`C₀(ℕ, ℓ^∞(ℕ, ℚ_p))` generated by `n ↦ pⁿ δₙ`, which is not closed and which no finite truncation
approximates.

⚠ The value group of `ℂ_p` (`‖ℂ_p^×‖ = p^ℚ`, which excludes `1/2` for odd `p`) is not in Mathlib;
the `ℂ_p` statement takes it as a hypothesis (plan erratum E23).

Roadmap: `PhD/TauCeti/Roadmaps/PadicFunctionalAnalysis/README.md`, Layer 2 Examples.
-/

open Filter Topology Function Module NormedRing
open scoped ZeroAtInfty ENNReal PadicComplex
open ZeroAtInftyContinuousMap

namespace ZeroAtInftyContinuousMap.Examples

variable (p : ℕ) [Fact p.Prime]

/-! ### `C₀(ℕ, ℚ_p)` and its dual -/

/-- Source: roadmap Layer 2 Examples ("`C₀(ℕ, ℚ_p)` with its canonical basis"). -/
theorem isOrthonormalBasis_single_padic :
    IsOrthonormalBasis ℚ_[p] fun n : ℕ ↦ single n (1 : ℚ_[p]) :=
  isOrthonormalBasis_single

/-- The dual of `C₀(ℕ, ℚ_p)` is `ℓ^∞(ℕ, ℚ_p)`, for Mathlib's operator norm on the dual: the
isometry `dualEquivLp` for the scoped norm of Layer 1, which agrees with Mathlib's over a field
(`ContinuousLinearMap.Ultra.norm_eq_opNorm`). Source: roadmap Layer 2 Examples ("and its dual
`ℓ^∞(ℕ, ℚ_p)`"). -/
theorem nonempty_dual_linearIsometryEquiv_lp_padic :
    Nonempty ((C₀(ℕ, ℚ_[p]) →L[ℚ_[p]] ℚ_[p]) ≃ₗᵢ[ℚ_[p]] lp (fun _ : ℕ ↦ ℚ_[p]) ∞) := by
  sorry

/-! ### `C(ℤ_p, ℚ_p)` is orthonormalisable -/

/-- The sup norm on `C(ℤ_p, ℚ_p)` takes values in `‖ℚ_p‖`, so `C(ℤ_p, ℚ_p)` is orthonormalisable
by Serre's theorem. Source: roadmap Layer 2 Examples ("the Banach space `C(ℤ_p, ℚ_p)` is
orthonormalisable (Layer 3 exhibits the basis, this layer only knows it from Serre's theorem)"). -/
theorem isONable_continuousMap_padic : IsONable ℚ_[p] C(ℤ_[p], ℚ_[p]) := by
  sorry

/-! ### A norm whose values are not in `‖K‖` -/

/-- A nonzero orthonormalisable module has an element of norm `1`. -/
theorem _root_.Module.not_isONable_of_forall_norm_ne_one {R : Type*} [NormedRing R] [NormOneClass R]
    {M : Type*} [NormedAddCommGroup M] [Module R M] [Nontrivial M] (h : ∀ m : M, ‖m‖ ≠ 1) :
    ¬ IsONable R M := by
  sorry

end ZeroAtInftyContinuousMap.Examples

/-- A normed field with its norm doubled: `‖x‖ = 2 * ‖x‖_K`, a one-dimensional Banach space whose
norm does not take values in `‖K‖`. Source: roadmap §2.3.5 and Layer 2 Examples ("`ℂ_p` with the
norm `2‖·‖` (`p` odd) is potentially but not literally orthonormalisable"). -/
def NormedField.Doubled (K : Type*) : Type _ := K

namespace NormedField.Doubled

variable {K : Type*} [NontriviallyNormedField K]

instance : AddCommGroup (Doubled K) := inferInstanceAs (AddCommGroup K)

instance : Module K (Doubled K) := inferInstanceAs (Module K K)

/-- The identity `K → Doubled K`, as a linear equivalence. -/
def toDoubled : K ≃ₗ[K] Doubled K := LinearEquiv.refl K K

noncomputable instance : NormedAddCommGroup (Doubled K) :=
  AddGroupNorm.toNormedAddCommGroup
    { toFun := fun x ↦ 2 * ‖(toDoubled.symm x : K)‖
      map_zero' := by sorry
      add_le' := by sorry
      neg' := by sorry
      eq_zero_of_map_eq_zero' := by sorry }

theorem norm_def (x : Doubled K) : ‖x‖ = 2 * ‖(toDoubled.symm x : K)‖ := rfl

instance : IsBoundedSMul K (Doubled K) := .of_norm_smul_le (by sorry)

instance [IsUltrametricDist K] : IsUltrametricDist (Doubled K) := by
  sorry

instance [CompleteSpace K] : CompleteSpace (Doubled K) := by
  sorry

/-- `Doubled K` is potentially orthonormalisable over any `K`: it is `K = C₀(Unit, K)` with an
equivalent norm. Source: roadmap §2.3.5 ("the potential statement"). -/
theorem isPotentiallyONable [IsUltrametricDist K] [CompleteSpace K] :
    IsPotentiallyONable K (Doubled K) := by
  sorry

/-- `Doubled K` is not orthonormalisable when `1/2 ∉ ‖K‖`. Source: roadmap §2.3.5 ("`ℂ_p` itself
with the norm `2‖·‖` has no orthonormal basis, since `‖ℂ_p‖ = p^ℚ` does not contain `1/2`"). -/
theorem not_isONable (hK : ∀ x : K, ‖x‖ ≠ 2⁻¹) : ¬ IsONable K (Doubled K) := by
  sorry

end NormedField.Doubled

namespace ZeroAtInftyContinuousMap.Examples

variable (p : ℕ) [Fact p.Prime]

/-- For odd `p`, `ℚ_p` with the doubled norm is not orthonormalisable, although potentially so by
Serre's theorem: `1/2 ∉ p^ℤ`. Source: roadmap Layer 2 Examples ("a finite-dimensional … space with
a norm whose values are not in `p^ℚ`"), the discretely valued instance. -/
theorem not_isONable_doubled_padic (hp : p ≠ 2) : ¬ IsONable ℚ_[p] (NormedField.Doubled ℚ_[p]) := by
  sorry

theorem isPotentiallyONable_doubled_padic : IsPotentiallyONable ℚ_[p] (NormedField.Doubled ℚ_[p]) :=
  NormedField.Doubled.isPotentiallyONable

/-- **The discreteness hypothesis of Serre's theorem cannot be dropped**: `ℂ_p` with the norm
`2‖·‖` has no orthonormal basis, granted that `‖ℂ_p‖` does not contain `1/2` (`‖ℂ_p^×‖ = p^ℚ`, not
in Mathlib). Source: roadmap §2.3.5. -/
theorem not_isONable_doubled_padicComplex (h : ∀ x : ℂ_[p], ‖x‖ ≠ 2⁻¹) :
    ¬ IsONable ℂ_[p] (NormedField.Doubled ℂ_[p]) :=
  NormedField.Doubled.not_isONable h

theorem isPotentiallyONable_doubled_padicComplex :
    IsPotentiallyONable ℂ_[p] (NormedField.Doubled ℂ_[p]) :=
  NormedField.Doubled.isPotentiallyONable

/-! ### The shift -/

variable {R : Type*} [NormedCommRing R]

/-- The shift `f ↦ (n ↦ f (n + 1))` on `C₀(ℕ, R)`. Source: roadmap Layer 2 Examples ("the matrix of
the shift on `C₀(ℕ, R)`"). -/
noncomputable def shift : C₀(ℕ, R) →L[R] C₀(ℕ, R) :=
  LinearMap.mkContinuous
    { toFun := fun f ↦ ofTendsto (fun n ↦ f (n + 1)) (by sorry)
      map_add' := by sorry
      map_smul' := by sorry }
    1 (by sorry)

@[simp]
theorem shift_apply (f : C₀(ℕ, R)) (n : ℕ) : shift f n = f (n + 1) := rfl

/-- The matrix of the shift has `1` on the superdiagonal and `0` elsewhere. -/
theorem matrixCoeff_shift (i j : ℕ) : matrixCoeff (shift : C₀(ℕ, R) →L[R] C₀(ℕ, R)) i j =
    if j = i + 1 then 1 else 0 := by
  sorry

/-! ### Unitriangular perturbations -/

variable [NormOneClass R] [IsUltrametricDist R] [CompleteSpace R]

/-- `1 + N` with `N` strictly lower triangular of norm at most `q < 1` and finitely supported
columns is a unitriangular perturbation. Source: roadmap Layer 2 Examples ("the unitriangular
perturbation `1 + N` with `N` strictly lower triangular of norm `q`"). -/
theorem isUnitriangularPerturbation_one_add (N : ℕ → ℕ → R) {q : ℝ} (hq : q < 1)
    (hN : ∀ i j, ‖N i j‖ ≤ q) (hlower : ∀ i j, ¬ j < i → N i j = 0)
    (hfin : ∀ j, {i | N i j ≠ 0}.Finite) :
    IsUnitriangularPerturbation (fun i j ↦ (if i = j then (1 : R) else 0) + N i j) q := by
  sorry

/-- A matrix with entries in `ℤ_p`, unit diagonal, lower entries in `pℤ_p` and finitely supported
columns is a unitriangular perturbation of level `p⁻¹`. Source: roadmap Layer 2 Examples ("a matrix
with entries in `ℤ_p`, unit diagonal, and lower entries in `pℤ_p`"). -/
theorem isUnitriangularPerturbation_padicInt (a : ℕ → ℕ → ℤ_[p]) (hdiag : ∀ i, IsUnit (a i i))
    (hlow : ∀ i j, j < i → (p : ℤ_[p]) ∣ a i j) (hfin : ∀ j, {i | a i j ≠ 0}.Finite) :
    IsUnitriangularPerturbation a ((p : ℝ)⁻¹) := by
  sorry

/-! ### The counterexample to §2.6.4 without closedness -/

/-- `ℓ^∞(ℕ, ℚ_p)` is a Banach–Tate ring: the constant sequence `p` is a multiplicative
pseudo-uniformiser. -/
instance : IsTate (lp (fun _ : ℕ ↦ ℚ_[p]) ∞) := by
  sorry

/-- The family `n ↦ pⁿ δₙ` in `ℓ^∞(ℕ, ℚ_p)`, an element of `C₀(ℕ, ℓ^∞(ℕ, ℚ_p))`. Source: roadmap
§2.6.4 ("⚠ Without closedness the statement is false; record the counterexample"). -/
noncomputable def geomDelta : C₀(ℕ, lp (fun _ : ℕ ↦ ℚ_[p]) ∞) :=
  ofTendsto (fun n ↦ (p : ℚ_[p]) ^ n • lp.single ∞ n (1 : ℚ_[p])) (by sorry)

@[simp]
theorem geomDelta_apply (n : ℕ) : geomDelta p n = (p : ℚ_[p]) ^ n • lp.single ∞ n (1 : ℚ_[p]) := rfl

/-- The principal submodule generated by `geomDelta` is not closed: its closure contains
`n ↦ p^{⌈n/2⌉} δₙ`, whose coefficient sequence `p^{⌈n/2⌉ - n}` is unbounded. -/
theorem not_isClosed_span_geomDelta :
    ¬ IsClosed (Submodule.span (lp (fun _ : ℕ ↦ ℚ_[p]) ∞) {geomDelta p} :
      Set C₀(ℕ, lp (fun _ : ℕ ↦ ℚ_[p]) ∞)) := by
  sorry

/-- No finite truncation approximates the principal submodule generated by `geomDelta` up to the
factor `1/2`: at `r • geomDelta` with `r = δ_m`, `m ∉ S`, the truncation error equals the norm.
Source: roadmap §2.6.4. -/
theorem exists_truncation_far_geomDelta (S : Finset ℕ) :
    ∃ f ∈ Submodule.span (lp (fun _ : ℕ ↦ ℚ_[p]) ∞) {geomDelta p},
      2⁻¹ * ‖f‖ < ‖truncation (↑S : Set ℕ) f - f‖ := by
  sorry

end ZeroAtInftyContinuousMap.Examples
