/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import PhD.Jacobs.U3.Level

/-!
# The in-repo fallback route to class number one (NOT on the live chain)

**SUPERSEDED 2026-08-10**: this route was executed (with a corrected right-handed
division `a = b * q + r` — the `a = q * b + r` stated below descends LEFT ideals) in
`PhD/JacobsSlash/CN1/`, board `.mathlib-quality/hurwitz-cn1/`, where
`JacobsSlash.hClassNumberOne` is now proven sorry-free.  Kept as history per the
legacy-file convention; still imported by nothing.

**This file is imported by nothing.**  The AG-B tranche's single external dependency is
`Jacobs.U3.hClassNumberOne` (`PhD/Jacobs/U3/Level.lean`) — the statement FLT is expected
to cover (`FLT/Data/HurwitzRatHat.lean: completed_units`; see the interface contract on
`hClassNumberOne`).  This file preserves the *skeleton of the in-repo proof route*
([Voight, GTM 288]: Hurwitz order norm-Euclidean → right ideals principal → idelic
dictionary), so that if FLT's proof does not land, or lands in an unportable form, the
fallback can be executed without replanning — board tickets B06/B18 (DEFERRED) point
here.

Decomposition: `.mathlib-quality/qmf/decomposition.md`, R-CN1 (prose proof, source
quotes, and the L6.5 sub-plan).
-/

open Quaternion IsDedekindDomain NumberField QMF

namespace Jacobs.U3

/-- **Euclidean division** ([Voight 11.3.1]; the classical Hurwitz argument): for
`a b : 𝓞` with `b ≠ 0` there are `q r` with `a = q * b + r` and `N(r) < N(b)`.
(Right-handed: `q` multiplies on the left of `b`; the nearest-Hurwitz-integer to `a·b⁻¹`
is at squared distance `≤ 1/2 < 1` — the half-lattice is what makes this strict.) -/
theorem exists_div_rem (a b : hurwitzOrder) (hb : b ≠ 0) :
    ∃ q r : hurwitzOrder, a = q * b + r ∧ hnorm r < hnorm b := sorry

/-- **Every right ideal of the Hurwitz order is principal** ([Voight 11.1.8]-style
descent on the Euclidean norm). -/
theorem right_ideal_principal (I : Submodule (hurwitzOrder)ᵐᵒᵖ hurwitzOrder) :
    ∃ x : hurwitzOrder, I = Submodule.span (hurwitzOrder)ᵐᵒᵖ {x} := sorry

/-- The right `𝓞`-ideal of denominators of an adelic point: `{x ∈ 𝓞 : ∀ w, x ∈ g_w · 𝓞_w}`
([Voight 27.6.8]'s dictionary, one direction). -/
noncomputable def latticeOf (g : Dfx ℚ D) :
    Submodule (hurwitzOrder)ᵐᵒᵖ hurwitzOrder := sorry

theorem latticeOf_ne_bot (g : Dfx ℚ D) : latticeOf g ≠ ⊥ := sorry

/-- Local recovery, packaged as what the dictionary consumes: if the denominator ideal
of `g` is generated by `x`, then `x⁻¹·g ∈ U₀(1)`.  (CRT approximation over the finitely
many places where `g` is not integrally invertible; see decomposition L6.5.) -/
theorem inv_generator_mul_mem_U0 (g : Dfx ℚ D) (x : hurwitzOrder) (hx0 : x ≠ 0)
    (hx : latticeOf g = Submodule.span (hurwitzOrder)ᵐᵒᵖ {x}) :
    (unitsIncl ℚ D (Units.mk0 (x : ℍ[ℚ]) (fun h => hx0 (Subtype.ext h))))⁻¹ * g
      ∈ U0 := sorry

/-- The fallback assembly: the dictionary + principality discharge `HClassNumberOne`.
(If executed, this proof replaces the `sorry` of `Jacobs.U3.hClassNumberOne`.) -/
theorem hClassNumberOne_of_dictionary : HClassNumberOne := sorry

end Jacobs.U3
