/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import Mathlib.NumberTheory.Padics.PadicNumbers
import PhD.TauCeti.Code.NewtonPolygons.AddVal.Normed

/-!
# `ℚ_p`: the machinery reproduces the `p`-adic valuation

The check on the additive-valuation development: on `ℚ_p` the abstract `NormedField.normAddValZ`
is exactly Mathlib's `Padic.addValuation`, and `‖x‖ = p ^ (-(normAddValZ ℚ_[p] x))`.

Along the way this file supplies the instance that makes `ℚ_p` a discretely valued normed field in
the sense of `Valuation.IsRankOneDiscrete` — that the value group of the `p`-adic norm is cyclic,
generated by `‖p‖₊ = p⁻¹` (it is nontrivial because the norm is nontrivial) — and identifies `p`
as a uniformiser, hence as a normalising element in the sense of `Valuation.IsCommensurable`.

Roadmap: `PhD/TauCeti/Roadmaps/NewtonPolygons/README.md`, §1.3.5 (the `ℚ_p` half). Tau Ceti
home: `TauCeti/NumberTheory/Padics/AddVal.lean`.

## Main results

* `Padic.isUniformizer_p`: `p` is a uniformiser of `NormedField.valuation` on `ℚ_[p]`;
* `NormedField.norm_eq_zpow_neg_normAddValZ_padic`: `‖x‖ = p ^ (-normAddValZ ℚ_[p] x)`;
* `NormedField.normAddValZ_padic`: `normAddValZ ℚ_[p] = Padic.addValuation`.
-/

open scoped NNReal WithZero

variable {p : ℕ} [Fact p.Prime]

namespace Padic

open NormedField Valuation MonoidWithZeroHom Valuation.IsRankOneDiscrete WithZero

lemma nnnorm_p_eq_inv : ‖(p : ℚ_[p])‖₊ = (p : ℝ≥0)⁻¹ := by
  rw [← NNReal.coe_inj]; push_cast; exact Padic.norm_p

lemma nnnorm_p_ne_zero : ‖(p : ℚ_[p])‖₊ ≠ 0 := by
  rw [nnnorm_p_eq_inv]; exact inv_ne_zero (Nat.cast_ne_zero.mpr (Fact.out : p.Prime).ne_zero)

/-- The generator `‖p‖₊ = p⁻¹` of the value group of the `p`-adic norm. -/
noncomputable def valueGroupGen : valueGroup (.ofClass (NormedField.valuation (K := ℚ_[p]))) :=
  ⟨Units.mk0 ‖(p : ℚ_[p])‖₊ nnnorm_p_ne_zero, mem_valueGroup _ ⟨(p : ℚ_[p]), rfl⟩⟩

lemma nnnorm_p_zpow_valuation {x : ℚ_[p]} (hx : x ≠ 0) :
    ‖(p : ℚ_[p])‖₊ ^ x.valuation = ‖x‖₊ := by
  rw [← NNReal.coe_inj]
  push_cast
  rw [Padic.norm_eq_zpow_neg_valuation hx,
    Padic.norm_eq_zpow_neg_valuation (Nat.cast_ne_zero.mpr (Fact.out : p.Prime).ne_zero),
    Padic.valuation_p, ← zpow_mul]
  ring_nf

lemma zpowers_valueGroupGen : Subgroup.zpowers (valueGroupGen (p := p)) = ⊤ := by
  rw [Subgroup.eq_top_iff']
  intro y
  rw [Subgroup.mem_zpowers_iff]
  have hy : (y : ℝ≥0ˣ).val ∈
      Units.val '' (valueGroup (.ofClass (NormedField.valuation (K := ℚ_[p])))) :=
    ⟨y, y.2, rfl⟩
  rw [valueGroup_eq_range] at hy
  obtain ⟨⟨x, hx⟩, hne⟩ := hy
  simp only [Set.mem_singleton_iff] at hne
  have hx0 : x ≠ 0 := by
    rintro rfl; exact hne (by rw [← hx]; simp)
  refine ⟨x.valuation, Subtype.ext (Units.ext ?_)⟩
  rw [SubgroupClass.coe_zpow, Units.val_zpow_eq_zpow_val,
    show ((valueGroupGen (p := p)) : ℝ≥0ˣ).val = ‖(p : ℚ_[p])‖₊ from rfl,
    nnnorm_p_zpow_valuation hx0, ← hx]
  rfl

instance isCyclic_valueGroup :
    IsCyclic (valueGroup (.ofClass (NormedField.valuation (K := ℚ_[p])))) :=
  isCyclic_iff_exists_zpowers_eq_top.mpr ⟨valueGroupGen, zpowers_valueGroupGen⟩

/-- The `p`-adic norm is a discrete rank-one valuation (through `IsRankOneDiscrete.mk'`: the value
group is cyclic by `isCyclic_valueGroup` and nontrivial because the norm is nontrivial). -/
theorem isRankOneDiscrete_valuation : (NormedField.valuation (K := ℚ_[p])).IsRankOneDiscrete :=
  inferInstance

lemma valueGroupGen_lt_one : valueGroupGen (p := p) < 1 := by
  have h : ‖(p : ℚ_[p])‖₊ < 1 := by exact_mod_cast Padic.norm_p_lt_one
  rw [← Subtype.coe_lt_coe]
  exact_mod_cast h

lemma generator'_eq_valueGroupGen :
    generator' (NormedField.valuation (K := ℚ_[p])) = valueGroupGen :=
  LinearOrderedCommGroup.Subgroup.genLTOne_unique_of_zpowers_eq
    (generator'_lt_one _) valueGroupGen_lt_one
    (by rw [generator'_zpowers_eq_top, zpowers_valueGroupGen])

/-- The generator of the value group of the `p`-adic norm is `p⁻¹`. -/
theorem coe_generator_eq :
    (generator (NormedField.valuation (K := ℚ_[p])) : ℝ≥0) = (p : ℝ≥0)⁻¹ := by
  have h : ((generator' (NormedField.valuation (K := ℚ_[p])) : ℝ≥0ˣ) : ℝ≥0)
      = ((valueGroupGen (p := p) : ℝ≥0ˣ) : ℝ≥0) := by rw [generator'_eq_valueGroupGen]
  rw [← nnnorm_p_eq_inv]
  exact h

/-- `p` is a uniformiser of `ℚ_p`. -/
theorem isUniformizer_p : IsUniformizer (NormedField.valuation (K := ℚ_[p])) (p : ℚ_[p]) := by
  rw [IsUniformizer.iff, valuation_apply, nnnorm_p_eq_inv, coe_generator_eq]

/-- `p` is a normalising element of `ℚ_p`: the `ℚ`-valued additive valuation `normAddValQ ℚ_[p] p`
exists (and is `normAddValZ` composed with `Int.cast`). -/
instance isCommensurable_p : (NormedField.valuation (K := ℚ_[p])).IsCommensurable (p : ℚ_[p]) :=
  IsRankOneDiscrete.isCommensurable _ isUniformizer_p

end Padic

namespace NormedField

open Valuation

/-- **The `p`-adic norm is `p` to the power of minus the `ℤ`-valued additive valuation.** -/
theorem norm_eq_zpow_neg_normAddValZ_padic {x : ℚ_[p]} {d : ℤ}
    (hd : normAddValZ ℚ_[p] x = (d : WithTop ℤ)) : ‖x‖ = (p : ℝ) ^ (-d) :=
  norm_eq_zpow_neg_normAddValZ_of_isUniformizer ℚ_[p] Padic.isUniformizer_p Padic.norm_p hd

/-- **The verification, pointwise.** On `ℚ_p`, `normAddValZ` is Mathlib's `Padic.addValuation`. -/
theorem normAddValZ_padic_apply (x : ℚ_[p]) : normAddValZ ℚ_[p] x = Padic.addValuation x := by
  by_cases hx : x = 0
  · subst hx; rw [normAddValZ_zero, AddValuation.map_zero]
  obtain ⟨d, hd⟩ := WithTop.ne_top_iff_exists.mp ((normAddValZ_eq_top ℚ_[p]).not.mpr hx)
  rw [← hd, Padic.addValuation.apply hx]
  congr 1
  have hn1 := norm_eq_zpow_neg_normAddValZ_padic hd.symm
  have hn2 := Padic.norm_eq_zpow_neg_valuation hx
  have hpp : (1 : ℝ) < p := by exact_mod_cast (Fact.out : p.Prime).one_lt
  have := (zpow_right_strictMono₀ hpp).injective (hn1.symm.trans hn2)
  omega

/-- **The verification.** On `ℚ_p`, `normAddValZ` is Mathlib's `Padic.addValuation`, as additive
valuations. -/
theorem normAddValZ_padic : normAddValZ ℚ_[p] = Padic.addValuation :=
  AddValuation.ext normAddValZ_padic_apply

end NormedField
