import PhD.TauCeti.Code.RigidAnalyticGeometry.Affinoid.Examples

#check @MvPowerSeries.isRestricted.smul'
#check @MvPowerSeries.Restricted.val_smul
#check @MvPowerSeries.Restricted.algebraMap_apply
#check @MvPowerSeries.Restricted.algebraMap_eq_C_comp
#check @MvPowerSeries.Restricted.norm_prod_pow_le_of_norm_le
#check @MvPowerSeries.Restricted.exists_forall_norm_prod_pow_le
#check @MvPowerSeries.Restricted.norm_map_mul_prod_pow_le
#check @MvPowerSeries.Restricted.tendsto_map_coeff_mul_prod_pow
#check @MvPowerSeries.Restricted.summable_map_coeff_mul_prod_pow
#check @MvPowerSeries.Restricted.eval₂Fun
#check @MvPowerSeries.Restricted.eval₂Fun_zero
#check @MvPowerSeries.Restricted.eval₂Fun_one
#check @MvPowerSeries.Restricted.eval₂Fun_add
#check @MvPowerSeries.Restricted.eval₂Fun_mul
#check @MvPowerSeries.Restricted.eval₂
#check @MvPowerSeries.Restricted.eval₂_apply
#check @MvPowerSeries.Restricted.hasSum_eval₂
#check @MvPowerSeries.Restricted.eval₂_monomial
#check @MvPowerSeries.Restricted.eval₂_C
#check @MvPowerSeries.Restricted.eval₂_X
#check @MvPowerSeries.Restricted.eval₂_toRestricted
#check @MvPowerSeries.Restricted.norm_eval₂_le_mul
#check @MvPowerSeries.Restricted.norm_eval₂_le
#check @MvPowerSeries.Restricted.continuous_eval₂
#check @MvPowerSeries.Restricted.ringHom_ext_of_continuous
#check @MvPowerSeries.Restricted.norm_algebraMap_le_one_mul
#check @MvPowerSeries.Restricted.aeval
#check @MvPowerSeries.Restricted.aeval_apply
#check @MvPowerSeries.Restricted.aeval_X
#check @MvPowerSeries.Restricted.aeval_toRestricted
#check @MvPowerSeries.Restricted.norm_aeval_le
#check @MvPowerSeries.Restricted.continuous_aeval
#check @MvPowerSeries.Restricted.algHom_ext_of_continuous
#check @TopologicalRing.IsBounded
#check @PowerBounded.IsPowerBounded
#check @norm_pow_succ_of_normMulClass
#check @TopologicalRing.isBounded_of_forall_norm_le
#check @TopologicalRing.IsBounded.exists_norm_le
#check @PowerBounded.isPowerBounded_of_norm_pow_le
#check @PowerBounded.isPowerBounded_of_norm_le_one
#check @PowerBounded.IsPowerBounded.norm_le_one
#check @PowerBounded.isPowerBounded_iff_norm_le_one
#check @TopologicalRing.IsBounded.exists_norm_le_of_normedAlgebra
#check @PowerBounded.IsPowerBounded.exists_norm_pow_le
#check @PowerBounded.isPowerBounded_iff_exists_norm_pow_le
#check @PowerBounded.IsPowerBounded.map
#check @IsTopologicallyNilpotent.of_norm_lt_one
#check @IsTopologicallyNilpotent.norm_lt_one
#check @isTopologicallyNilpotent_iff_norm_lt_one
#check @Ideal.Quotient.norm_mk_eq_norm_of_forall_le
#check @Ideal.Quotient.normOneClass_of_ne_top
#check @MvPowerSeries.Restricted.sumTuple
#check @MvPowerSeries.Restricted.norm_sumTuple_le
#check @MvPowerSeries.Restricted.sumToIter
#check @MvPowerSeries.Restricted.iterToSum
#check @MvPowerSeries.Restricted.iterToSum_comp_sumToIter
#check @MvPowerSeries.Restricted.sumToIter_comp_iterToSum
#check @MvPowerSeries.Restricted.sumEquiv
#check @MvPowerSeries.Restricted.sumEquiv_C
#check @MvPowerSeries.Restricted.sumEquiv_X_inl
#check @MvPowerSeries.Restricted.sumEquiv_X_inr
#check @MvPowerSeries.Restricted.norm_sumEquiv
#check @MvPowerSeries.Restricted.continuous_sumEquiv
#check @MvPowerSeries.Restricted.continuous_sumEquiv_symm
#check @MvPowerSeries.Restricted.renameEquiv
#check @MvPowerSeries.Restricted.renameEquiv_C
#check @MvPowerSeries.Restricted.renameEquiv_X
#check @MvPowerSeries.Restricted.norm_renameEquiv
#check @Affinoid.TateAlgebra.sumEquiv
#check @Affinoid.TateAlgebra.norm_sumEquiv
#check @Affinoid.TateAlgebra.sumEquiv_C
#check @Affinoid.TateAlgebra.sumEquiv_X
#check @MvPowerSeries.Restricted.is
#check @Affinoid.TateAlgebra.normOneClass_quotient
#check @Affinoid.TateAlgebra.norm_quotient_mk_le
#check @Affinoid.TateAlgebra.exists_norm_quotient_mk_eq
#check @Affinoid.TateAlgebra.isClosed_ideal_quotient
#check @Affinoid.TateAlgebra.norm_quotient_mem_range_norm
#check @Affinoid.TateAlgebra.exists_norm_smul_quotient_eq_one
#check @IsAffinoidAlgebra
#check @IsAffinoidAlgebra.tateAlgebra
#check @IsAffinoidAlgebra.of_surjective
#check @IsAffinoidAlgebra.quotient
#check @IsAffinoidAlgebra.of_algEquiv
#check @IsAffinoidAlgebra.tateAlgebra_quotient
#check @IsAffinoidAlgebra.exists_algEquiv_quotient
#check @IsAffinoidAlgebra.isNoetherianRing
#check @IsAffinoidAlgebra.isJacobsonRing
#check @IsAffinoidAlgebra.of_subsingleton
#check @MvPowerSeries.Restricted.norm_smul_le_of_normedAlgebra
#check @MvPowerSeries.Restricted.isPowerBounded_X
#check @MvPowerSeries.Restricted.exists_forall_norm_le_mul_of_continuous
#check @MvPowerSeries.Restricted.exists_forall_norm_prod_pow_le_of_isPowerBounded
#check @MvPowerSeries.Restricted.extendAlgHom
#check @MvPowerSeries.Restricted.extendAlgHom_apply
#check @MvPowerSeries.Restricted.extendAlgHom_C
#check @MvPowerSeries.Restricted.extendAlgHom_X
#check @MvPowerSeries.Restricted.extendAlgHom_comp_toAlgHom
#check @MvPowerSeries.Restricted.continuous_extendAlgHom
#check @MvPowerSeries.Restricted.exists_forall_norm_extendAlgHom_le
#check @MvPowerSeries.Restricted.extendAlgHom_unique
#check @MvPowerSeries.Restricted.existsUnique_extend
#check @MvPowerSeries.Restricted.extendAlgHom_ofId_eq_aeval
#check @MvPowerSeries.Restricted.IsAffinoidGeneratingSystem
#check @MvPowerSeries.Restricted.isAffinoidGeneratingSystem_of_forall_exists_sum
#check @MvPowerSeries.Restricted.exists_forall_norm_smul_le_one
#check @MvPowerSeries.Restricted.exists_isAffinoidGeneratingSystem_of_finite
#check @MvPowerSeries.Restricted.continuous_C
#check @MvPowerSeries.Restricted.continuous_algebraMap_restricted
#check @MvPowerSeries.Restricted.mapAlgHom
#check @MvPowerSeries.Restricted.mapAlgHom_C
#check @MvPowerSeries.Restricted.mapAlgHom_X
#check @MvPowerSeries.Restricted.coeff_mapAlgHom
#check @MvPowerSeries.Restricted.continuous_mapAlgHom
#check @MvPowerSeries.Restricted.surjective_mapAlgHom_of_surjective
#check @IsAffinoidAlgebra.of_isAffinoidGeneratingSystem
#check @IsAffinoidAlgebra.of_isAffinoidGeneratingSystem_tateAlgebra
#check @IsAffinoidAlgebra.of_finite_tateAlgebra
#check @Ideal.forall_mem_of_forall_exists_eq_add_sum_mul_of_norm_lt_one
#check @Ideal.exists_forall_exists_eq_sum_mul_norm_le
#check @Ideal.isClosed_coe_closure_restrictScalars
#check @Ideal.isClosed_of_fg_closure
#check @Ideal.isClosed_of_isNoetherianRing
#check @LinearMap.continuous_of_isClosed_ker_of_finiteDimensional
#check @AlgHom.continuous_quotient_mk_comp_of_isClosed
#check @`LinearMap.continuous_of_seq_closed_graph`.
#check @AlgHom.continuous_of_forall_isClosed_of_finiteDimensional
#check @AlgHom.continuous_of_isNoetherianRing
#check @AlgEquiv.continuous_of_isNoetherianRing
#check @AlgEquiv.continuous_symm_of_isNoetherianRing
#check @AlgEquiv.exists_forall_norm_le_mul_of_isNoetherianRing
#check @Affinoid.TateAlgebra.ofTailAlgHom
#check @Affinoid.TateAlgebra.ofTailAlgHom_apply
#check @Affinoid.TateAlgebra.finite_comp_ofTail_of_isMulDistinguishedX0
#check @Affinoid.TateAlgebra.injective_mk_comp_ofTail_of_isMulDistinguishedX0
#check @Affinoid.TateAlgebra.exists_finite_comp_shear_symm_comp_ofTail
#check @Affinoid.TateAlgebra.injective_of_nontrivial
#check @Affinoid.TateAlgebra.exists_finite_injective_comp
#check @IsAffinoidAlgebra.exists_finite_injective_comp
#check @IsAffinoidAlgebra.exists_finite_injective
#check @ringKrullDim_le_of_isIntegral_of_injective
#check @IsAffinoidAlgebra.ringKrullDim_eq_of_finite_injective
#check @IsAffinoidAlgebra.exists_ringKrullDim_eq
#check @IsAffinoidAlgebra.finiteDimensional_of_finite_zero
#check @IsAffinoidAlgebra.injective_factor_comp_of_injective
#check @Affinoid.TateAlgebra.eq_zero_of_isField
#check @IsAffinoidAlgebra.finiteDimensional_quotient_of_radical_isMaximal
#check @IsAffinoidAlgebra.finiteDimensional_quotient_of_isMaximal
#check @IsAffinoidAlgebra.finiteDimensional_quotient_pow
#check @Ideal.isMaximal_comap_of_isAffinoidAlgebra
#check @IsFractionRing.isLocalization_algebraMapSubmonoid_of_isIntegral
#check @FractionRing.finiteDimensional_of_finite
#check @IsAffinoidAlgebra.isJapaneseRing
#check @Ideal.maximalPowers
#check @Ideal.sInf_maximalPowers_eq_bot
#check @IsAffinoidAlgebra.sInf_maximalPowers_eq_bot
#check @IsAffinoidAlgebra.finiteDimensional_of_mem_maximalPowers
#check @AlgHom.continuous_of_isAffinoidAlgebra
#check @AlgHom.continuous_of_isAffinoidAlgebra'
#check @IsAffinoidAlgebra.continuous_presentation
#check @IsAffinoidAlgebra.isClosed_ideal
#check @AlgEquiv.continuous_symm_of_isAffinoidAlgebra
#check @AlgEquiv.exists_forall_norm_le_mul_of_isAffinoidAlgebra
#check @AlgEquiv.isPowerBounded_map_iff_of_isAffinoidAlgebra
#check @AlgEquiv.isTopologicallyNilpotent_map_iff_of_isAffinoidAlgebra
#check @AlgHom.ext_of_isAffinoidGeneratingSystem
#check @IsAffinoidAlgebra.exists_isAffinoidGeneratingSystem
#check @IsAffinoidAlgebra.of_finite_of_continuous
#check @IsAffinoidAlgebra.restricted
#check @IsAffinoidAlgebra.exists_algEquiv_quotient_norm_comp_le
#check @MvPowerSeries.Restricted.inlAlgHom
#check @MvPowerSeries.Restricted.inrAlgHom
#check @MvPowerSeries.Restricted.inlAlgHom_C
#check @MvPowerSeries.Restricted.inlAlgHom_X
#check @MvPowerSeries.Restricted.inrAlgHom_C
#check @MvPowerSeries.Restricted.inrAlgHom_X
#check @MvPowerSeries.Restricted.continuous_inlAlgHom
#check @MvPowerSeries.Restricted.continuous_inrAlgHom
#check @MvPowerSeries.Restricted.inlAlgHom_comp_toAlgHom
#check @MvPowerSeries.Restricted.inrAlgHom_comp_toAlgHom
#check @Affinoid.IsAffinoidTensorProduct
#check @Affinoid.IsAffinoidTensorProduct.exists_algEquiv
#check @Affinoid.IsAffinoidTensorProduct.of_algEquiv_left
#check @Affinoid.isAffinoidTensorProduct_quotient_map
#check @Affinoid.IsAffinoidTensorProduct.surjective_ι₂_of_surjective
#check @Affinoid.tensorIdeal
#check @Affinoid.TensorQuotient
#check @Affinoid.tensorInl
#check @Affinoid.tensorInr
#check @Affinoid.tensorInl_mk
#check @Affinoid.tensorInr_mk
#check @Affinoid.continuous_tensorInl
#check @Affinoid.continuous_tensorInr
#check @Affinoid.tensorInl_comp_eq_tensorInr_comp
#check @Affinoid.isAffinoidAlgebra_tensorQuotient
#check @Affinoid.isClosed_tensorIdeal
#check @Affinoid.isAffinoidTensorProduct_tensorQuotient
#check @Affinoid.tensorInlₐ
#check @Affinoid.tensorInrₐ
#check @Affinoid.tensorLift
#check @Affinoid.denseRange_tensorLift
#check @Affinoid.IsGeneralisedFractions
#check @Affinoid.IsRationalFractions
#check @Affinoid.IsGeneralisedFractions.exists_algEquiv
#check @Affinoid.IsGeneralisedFractions.trans
#check @Affinoid.IsGeneralisedFractions.of_isUnit
#check @Affinoid.IsRationalFractions.isGeneralisedFractions_of_one
#check @Affinoid.fractionIdeal
#check @Affinoid.GeneralisedFractions
#check @Affinoid.toFractions
#check @Affinoid.continuous_toFractions
#check @Affinoid.toFractions_mul_mk_X_inr
#check @Affinoid.isUnit_toFractions
#check @Affinoid.toFractions_f
#check @Affinoid.isPowerBounded_toFractions_f
#check @Affinoid.isPowerBounded_inv_toFractions
#check @Affinoid.isGeneralisedFractions_toFractions
#check @Affinoid.isAffinoidAlgebra_generalisedFractions
#check @Affinoid.rationalIdeal
#check @Affinoid.RationalFractions
#check @Affinoid.toRational
#check @Affinoid.continuous_toRational
#check @Affinoid.isUnit_toRational
#check @Affinoid.toRational_mul_inv
#check @Affinoid.isPowerBounded_toRational_div
#check @Affinoid.isRationalFractions_toRational
#check @Affinoid.isAffinoidAlgebra_rationalFractions
#check @Affinoid.awayLift
#check @Affinoid.denseRange_awayLift
#check @Affinoid.TateAlgebra.mapBase
#check @Affinoid.TateAlgebra.mapBase_apply
#check @Affinoid.TateAlgebra.norm_mapBase
#check @Affinoid.TateAlgebra.baseChangeAlgHom
#check @Affinoid.TateAlgebra.baseChangeAlgHom_tmul
#check @Affinoid.TateAlgebra.exists_sum_smul_mapBase
#check @Affinoid.TateAlgebra.bijective_baseChangeAlgHom
#check @Affinoid.TateAlgebra.baseChangeEquiv
#check @IsAffinoidAlgebra.completeSpace_of_finiteDimensional
#check @IsAffinoidAlgebra.baseChange
#check @IsAffinoidAlgebra.baseChange_quotient
#check @MvPowerSeries.Restricted.norm_smul_X_pow
#check @MvPowerSeries.Restricted.rescaleAlgHom
#check @MvPowerSeries.Restricted.rescaleAlgHom_X
#check @MvPowerSeries.Restricted.continuous_rescaleAlgHom
#check @MvPowerSeries.Restricted.injective_rescaleAlgHom
#check @MvPowerSeries.Restricted.isRestricted_shiftCoeff
#check @MvPowerSeries.Restricted.finite_rescaleAlgHom
#check @MvPowerSeries.Restricted.isAffinoidAlgebra_of_forall_exists_pow_eq_norm
#check @PowerSeries.exists_summable_not_isRestricted
#check @Affinoid.Examples.isAffinoidAlgebra_quotient_X_sq_sub
#check @Affinoid.Examples.finrank_quotient_X_sq_sub
#check @Affinoid.Examples.ker_aeval_eq_span
#check @Affinoid.Examples.nonempty_algEquiv_quotient_X_sub
#check @Affinoid.Examples.isUnit_C_mul_X_sub_one
#check @Affinoid.Examples.subsingleton_quotient_C_mul_X_sub_one
#check @Affinoid.Examples.isGeneralisedFractions_id_X
#check @Affinoid.Examples.nonempty_algEquiv_generalisedFractions_X
#check @Affinoid.Examples.isMulDistinguishedX0_cusp
#check @Affinoid.Examples.finite_injective_cusp
#check @Affinoid.Examples.exists_algEquiv_quotient_X_norm_eq
#check @Affinoid.Examples.isAffinoidAlgebra_polydisc
#check @Affinoid.Examples.subsingleton_quotient_p_mul_X_sub_one
#check @Affinoid.Examples.finrank_quotient_X_sq_sub_p
