#!/usr/bin/env python3
"""Extract every backticked identifier from the 'Mathlib lemmas needed' blocks of tickets_data.py and write
two Lean files that `#check` them: one against Mathlib alone, one against the board's leaf module (for the
floor, the chain and the board's own names)."""
import re, sys
sys.path.insert(0, '.')
import tickets_data as d
ident = re.compile(r"^[A-Za-z_][A-Za-z0-9_.'₀₁₂₃₄₅₆₇₈₉!?]*$")
ml, ch = [], []
# names that the blocks mention precisely because they do NOT exist at the pin
NONEXISTENT = {'Order.krullDim_le_iff', 'Module.Basis.baseChange', 'RingEquiv.ofHomInv', 'isUnit_of_mul_eq_one', 'Basis'}
for tk in d.T:
    s = tk['mathlib']
    parts = re.split(r'\b(Floor/board|Floor/chain|Chain/board|Board/floor|Floor|Chain|Tower|Board|Mathlib|Layer 0|PFA|Imports?):', s)
    # parts: [pre, label, text, label, text, ...]
    segs = [('Mathlib', parts[0])] + [(parts[i], parts[i + 1]) for i in range(1, len(parts), 2)]
    for lab, txt in segs:
        for tok in re.findall(r'`([^`]+)`', txt):
            if not ident.match(tok) or tok in NONEXISTENT or tok.startswith('Mathlib.') or tok.startswith('h.') or tok.endswith('.lean'):
                continue
            (ml if lab in ('Mathlib', 'Imports', 'Import') else ch).append((tk['id'], tok))
def uniq(xs):
    seen, out = set(), []
    for t_, n in xs:
        if n not in seen:
            seen.add(n); out.append((t_, n))
    return out
ml, ch = uniq(ml), uniq(ch)
with open('names_tickets_mathlib.lean', 'w') as f:
    f.write('import Mathlib\nimport PhD.TauCeti.Code.PadicFunctionalAnalysis.PowerBounded\n\n/-! Every Mathlib name in a "Mathlib lemmas needed" block of the board (generated by\n`extract_names.py`). -/\n\n')
    for t_, n in ml:
        f.write(f'#check @{n}  -- {t_}\n')
with open('names_tickets_chain.lean', 'w') as f:
    f.write('import PhD.TauCeti.Code.RigidAnalyticGeometry.Affinoid.Examples\n\n/-! Every floor, chain and board name in a "Mathlib lemmas needed" block (generated by\n`extract_names.py`). -/\n\nopen MvPowerSeries.Restricted Affinoid.TateAlgebra PowerBounded IsAffinoidAlgebra NormedRing Subring Affinoid\n\n')
    for t_, n in ch:
        f.write(f'#check @{n}  -- {t_}\n')
print(len(ml), 'Mathlib names;', len(ch), 'floor/chain/board names')
