import PhD.TauCeti.Code.NewtonPolygons.AddVal.Basic
import PhD.TauCeti.Code.NewtonPolygons.AddVal.Commensurable
import PhD.TauCeti.Code.NewtonPolygons.AddVal.Discrete
import PhD.TauCeti.Code.NewtonPolygons.AddVal.Examples
import PhD.TauCeti.Code.NewtonPolygons.AddVal.Extension
import PhD.TauCeti.Code.NewtonPolygons.AddVal.LaurentSeries
import PhD.TauCeti.Code.NewtonPolygons.AddVal.NegLog
import PhD.TauCeti.Code.NewtonPolygons.AddVal.Normed
import PhD.TauCeti.Code.NewtonPolygons.AddVal.Padic
import PhD.TauCeti.Code.NewtonPolygons.AddVal.PadicComplex
import PhD.TauCeti.Code.NewtonPolygons.AddVal.RankOne
import PhD.TauCeti.Code.NewtonPolygons.AddVal.RatLog
#print axioms WithZero.negLog_zero
#print axioms WithZero.negLog_exp
#print axioms WithZero.negLog_eq_top
#print axioms WithZero.negLog_one
#print axioms WithZero.negLog_eq_coe
#print axioms WithZero.negLog_mul
#print axioms WithZero.negLog_le_negLog
#print axioms WithZero.negLog_lt_negLog
#print axioms WithZero.orderAddIsoWithTop
#print axioms WithZero.orderAddIsoWithTop_apply
#print axioms WithZero.mapAddHom'_exp
#print axioms WithZero.mapAddHom'_strictMono
#print axioms WithZero.negLog_mapAddHom'
#print axioms NNReal.toRealMultZero
#print axioms NNReal.toRealMultZero_of_ne_zero
#print axioms NNReal.toRealMultZero_strictMono
#print axioms WithZeroMulReal.toNNReal
#print axioms WithZeroMulReal.toNNReal_exp
#print axioms WithZeroMulReal.toNNReal_strictMono
#print axioms AddCommGroup.ratLog
#print axioms AddCommGroup.ratLog_eq
#print axioms AddCommGroup.ratLog_self
#print axioms AddCommGroup.ratLog_strictMono
#print axioms AddCommGroup.ratLog_unique
#print axioms Valuation.addVal_apply
#print axioms Valuation.addVal_eq_top
#print axioms Valuation.addVal_eq_coe
#print axioms Valuation.addVal_le_addVal
#print axioms Valuation.addVal_map
#print axioms Valuation.addValValueGroup_apply
#print axioms Valuation.addValValueGroup_eq_top
#print axioms Valuation.RankOne.addVal_apply
#print axioms Valuation.RankOne.addVal_zero
#print axioms Valuation.RankOne.addVal_eq_top
#print axioms Valuation.RankOne.addVal_apply_of_val_ne_zero
#print axioms Valuation.RankOne.addVal_eq_of_hom_eq
#print axioms Valuation.IsCommensurable.val_ne_zero
#print axioms Valuation.IsCommensurable.of_forall_eq
#print axioms Valuation.IsCommensurable.isNontrivial
#print axioms Valuation.coe_commGen
#print axioms Valuation.ofMul_commGen_neg
#print axioms Valuation.isCommensurableWith_commGen
#print axioms Valuation.ratLog_strictMono
#print axioms Valuation.ratLog_commGen
#print axioms Valuation.ratLog_eq_of_zsmul
#print axioms Valuation.addValQ_apply
#print axioms Valuation.addValQ_zero
#print axioms Valuation.addValQ_eq_top
#print axioms Valuation.addValQ_eq_of_zpow
#print axioms Valuation.addValQ_eq_of_pow_eq_pow
#print axioms Valuation.addValQ_self
#print axioms Valuation.addValQ_ne_top
#print axioms Valuation.exists_zpow_eq_and_addValQ
#print axioms Valuation.addValQ_le_addValQ
#print axioms Valuation.addValQ_unique
#print axioms Valuation.IsCommensurable.toRankLeOne
#print axioms Valuation.IsCommensurable.toRankOne_hom_restrict
#print axioms Valuation.RankOne.addVal_eq_map_addValQ
#print axioms Valuation.RankOne.hom_eq_rpow_addValQ
#print axioms Valuation.IsRankOneDiscrete.exists_zpow_generator_eq
#print axioms Valuation.IsRankOneDiscrete.exists_zpow_eq_of_isUniformizer
#print axioms Valuation.IsRankOneDiscrete.isCommensurable_of_lt_one
#print axioms Valuation.IsRankOneDiscrete.isCommensurable
#print axioms Valuation.IsRankOneDiscrete.addValZ_apply
#print axioms Valuation.IsRankOneDiscrete.addValZ_zero
#print axioms Valuation.IsRankOneDiscrete.addValZ_eq_top
#print axioms Valuation.IsRankOneDiscrete.addValZ_eq_iff
#print axioms Valuation.IsRankOneDiscrete.addValZ_eq_of_zpow
#print axioms Valuation.IsRankOneDiscrete.addValZ_eq_iff_of_isUniformizer
#print axioms Valuation.IsRankOneDiscrete.addValZ_isUniformizer
#print axioms Valuation.IsRankOneDiscrete.addValZ_le_addValZ
#print axioms Valuation.addValQ_eq_map_addValZ
#print axioms Valuation.IsRankOneDiscrete.hom_eq_toNNReal_comp
#print axioms Valuation.IsRankOneDiscrete.hom_eq_zpow_neg_addValZ
#print axioms Valuation.IsRankOneDiscrete.hom_eq_zpow_neg_addValZ_of_isUniformizer
#print axioms Valuation.RankOne.addVal_apply_of_ne_zero
#print axioms NormedField.valuation_norm_eq
#print axioms NormedField.norm_eq_coe_hom
#print axioms NormedField.normAddVal_zero
#print axioms NormedField.normAddVal_eq_top
#print axioms NormedField.normAddVal_apply_of_ne_zero
#print axioms NormedField.exists_normAddVal_eq_and_norm_eq_exp_neg
#print axioms NormedField.normAddVal_le_normAddVal
#print axioms NormedField.normAddVal_unique
#print axioms NormedField.normAddValZ_zero
#print axioms NormedField.normAddValZ_eq_top
#print axioms NormedField.normAddValZ_eq_iff_of_isUniformizer
#print axioms NormedField.normAddValZ_isUniformizer
#print axioms NormedField.norm_eq_zpow_neg_normAddValZ
#print axioms NormedField.norm_eq_zpow_neg_normAddValZ_of_isUniformizer
#print axioms NormedField.normAddVal_eq_map_normAddValZ
#print axioms NormedField.normAddValQ_zero
#print axioms NormedField.normAddValQ_eq_top
#print axioms NormedField.normAddValQ_self
#print axioms NormedField.normAddValQ_eq_of_pow_eq_pow
#print axioms NormedField.norm_eq_norm_rpow_normAddValQ
#print axioms NormedField.normAddVal_eq_map_normAddValQ
#print axioms NormedField.normAddValQ_eq_map_normAddValZ
#print axioms Padic.nnnorm_p_eq_inv
#print axioms Padic.nnnorm_p_ne_zero
#print axioms Padic.nnnorm_p_zpow_valuation
#print axioms Padic.zpowers_valueGroupGen
#print axioms Padic.isCyclic_valueGroup
#print axioms Padic.isRankOneDiscrete_valuation
#print axioms Padic.coe_generator_eq
#print axioms Padic.isUniformizer_p
#print axioms Padic.isCommensurable_p
#print axioms NormedField.norm_eq_zpow_neg_normAddValZ_padic
#print axioms NormedField.normAddValZ_padic_apply
#print axioms NormedField.normAddValZ_padic
#print axioms LaurentSeries.valuation_eq_exp_neg_order
#print axioms LaurentSeries.isRankOneDiscrete_valued
#print axioms LaurentSeries.generator_valued_eq
#print axioms LaurentSeries.isUniformizer_X
#print axioms LaurentSeries.addValZ_X
#print axioms LaurentSeries.addValZ_single
#print axioms LaurentSeries.addValZ_eq_order
#print axioms Valued.isCommensurable_completion
#print axioms NormedField.normAddVal_algebraMap
#print axioms NormedField.exists_normAddValZ_algebraMap_eq
#print axioms NormedField.normAddValZ_algebraMap
#print axioms NormedField.isCommensurable_algebraMap_of_isRankOneDiscrete
#print axioms NormedField.map_intCast_normAddValZ_eq_map_normAddValQ
#print axioms NormedField.norm_pow_natDegree_minpoly
#print axioms NormedField.isCommensurable_algebraMap
#print axioms NormedField.normAddValQ_algebraMap
#print axioms NormedField.isCommensurable_natCast_prime
#print axioms PadicAlgCl.isCommensurable_p
#print axioms PadicComplex.valuation_eq_nnnorm
#print axioms PadicComplex.normedField_valuation_eq
#print axioms PadicComplex.isCommensurable_p
#print axioms PadicComplex.normAddValQ_p
#print axioms PadicComplex.normAddValQ_algebraMap_padic
#print axioms PadicComplex.norm_eq_rpow_neg_normAddValQ
#print axioms PadicComplex.exists_normAddValQ_eq
#print axioms PadicComplex.range_normAddValQ
#print axioms NormedField.normAddValZ_padic_p
#print axioms NormedField.normAddValZ_padic_inv_p_sq
#print axioms NormedField.normAddVal_padic
#print axioms NormedField.normAddValQ_of_sq_eq_prime
#print axioms NormedField.normAddValZ_prime_of_sq_eq_prime
#print axioms NormedField.normAddValQ_padicComplex_of_pow_three
#print axioms LaurentSeries.addValZ_X_pow
