import PhD.TauCeti.Code.NewtonPolygons.AddVal.Examples
#check @WithTop.map_eq_top_iff
#check @WithTop.map_le_iff
#check @Int.toNat_sub_toNat_neg
#check @zpow_add₀
#check @top_le_iff
#check @NNReal.rpow_neg_one
#check @Rat.cast_strictMono
#check @zpow_lt_one_iff_right_of_lt_one₀
#check @WithZero.exp_zsmul
#check @WithZero.exp_nsmul
#check @HahnSeries.coeff_order_ne_zero
#check @HahnSeries.order_single
#check @HahnSeries.single_zero_one
#check @inv_zpow'
#check @inv_zpow
#check @Real.rpow_inv_natCast_pow
#check @Real.inv_rpow
#check @Real.rpow_neg
#check @IsDedekindDomain.HeightOneSpectrum.valuation_le_one
#check @Padic.valuation_inv
#check @Padic.valuation_pow
#check @norm_pow
#check @nnnorm_pow
#check @nnnorm_algebraMap'
#check @Rat.num_div_den
#check @Rat.den_pos
#check @Real.log_inv
#check @WithTop.coe_one
#check @Valuation.exists_isUniformizer_of_isCyclic_of_nontrivial
#check @map_ne_zero
#check @Int.cast_natCast
#check @Nat.cast_pos
#check @Int.toNat_of_nonneg
#check @two_nsmul
#check @one_add_one_eq_two
#check @nsmul_eq_mul
#check @WithTop.coe_natCast
#check @Multiplicative.ofAdd_zsmul
#check @mul_div_cancel₀
#check @WithTop.top_ne_coe
#check @WithTop.top_add
#check @lt_iff_lt_of_le_iff_le
#check @neg_eq_iff_eq_neg
#check @neg_le_neg_iff
#check @map_zsmul
#check @eq_div_iff
#check @AddMonoidHom.ext
#check @StrictMono.le_iff_le
#check @MulEquivClass.toMonoidWithZeroHomClass
#check @Valuation.IsRankOneDiscrete.generator_lt_one
#check @Units.val_lt_val
#check @Set.mem_insert_iff
#check @Set.mem_range
#check @norm_pos_iff
#check @coe_nnnorm
#check @NNReal.coe_pow
#check @NNReal.coe_le_coe
#check @Valuation.restrict_lt_iff
#check @WithZero.lt_one_iff
#check @Int.lt_iff_add_one_le
#check @PadicComplex.charZero
#check @Nat.cast_ne_zero
#check @pow_ne_zero
#check @Valued.extensionValuation
#check @UniformSpace.Completion.coe_zero
#check @Valuation.map_zero
#check @map_zpow₀
#check @mul_comm
#check @zpow_natCast
#check @Int.toNat_eq_zero
#check @WithZero.coe_zpow
#check @WithZero.exp_neg
#check @Real.log_neg_eq_log
#check @Real.rpow_natCast
#check @IsOrderedAddMonoid.toIsAddTorsionFree
