import PhD.TauCeti.Code.NewtonPolygons.AddVal.Examples
#check @AddMonoidHom.coe_coe
#check @AddMonoidHom.comp_apply
#check @AddMonoidHom.ext
#check @AddMonoidHom.toMultiplicative
#check @AddMonoidHom.withTopMap
#check @AddValuation.ext
#check @AddValuation.map_apply
#check @AddValuation.map_mul
#check @AddValuation.map_pow
#check @AddValuation.map_zero
#check @Algebra.IsIntegral.isIntegral
#check @Fact.out
#check @HahnSeries.coeff_order_eq_zero
#check @Int.cast_natCast
#check @Int.cast_zero
#check @Int.lt_iff_add_one_le
#check @Int.toNat_of_nonneg
#check @Int.toNat_sub_toNat_neg
#check @IsAddTorsionFree.zsmul_eq_zero_iff_left
#check @IsAlgClosed.exists_pow_nat_eq
#check @IsDedekindDomain.HeightOneSpectrum.valuation_le_one
#check @LaurentSeries.intValuation_le_iff_coeff_lt_eq_zero
#check @LaurentSeries.powerSeriesPart_coeff
#check @LaurentSeries.single_order_mul_powerSeriesPart
#check @LaurentSeries.valuation_X_pow
#check @LaurentSeries.valuation_def
#check @LaurentSeries.valuation_single_zpow
#check @LaurentSeries.valuation_surjective
#check @LaurentSeries.valued
#check @LinearOrderedCommGroup.Subgroup.genLTOne_unique_of_zpowers_eq
#check @MonoidWithZeroHom.ValueGroup₀.embedding
#check @MonoidWithZeroHom.ValueGroup₀.embedding_injective
#check @MonoidWithZeroHom.ValueGroup₀.embedding_restrict₀
#check @MonoidWithZeroHom.ValueGroup₀.restrict₀
#check @MonoidWithZeroHom.coe_mk
#check @MonoidWithZeroHom.coe_ofClass
#check @MonoidWithZeroHom.comp_apply
#check @MonoidWithZeroHom.ext
#check @MonoidWithZeroHom.mem_valueGroup
#check @MonoidWithZeroHom.mem_valueGroup_iff_of_comm
#check @MonoidWithZeroHom.valueGroup
#check @MonoidWithZeroHom.valueGroup_eq_range
#check @MulEquiv.injective
#check @NNReal.coe_inj
#check @NNReal.coe_le_coe
#check @NNReal.coe_lt_coe
#check @NNReal.coe_mul
#check @NNReal.coe_one
#check @NNReal.coe_pos
#check @NNReal.coe_pow
#check @NNReal.coe_zpow
#check @NNReal.rpow_add
#check @NNReal.rpow_lt_rpow_of_exponent_lt
#check @NNReal.rpow_neg_one
#check @NNReal.rpow_pos
#check @NNReal.rpow_zero
#check @Nat.Prime.ne_zero
#check @Nat.Prime.one_lt
#check @Nat.cast_ne_zero
#check @Nat.cast_pos
#check @NormedAlgebra.norm_eq_spectralNorm
#check @NormedField.valuation_apply
#check @Padic.addValuation.apply
#check @Padic.norm_eq_zpow_neg_valuation
#check @Padic.norm_p
#check @Padic.norm_p_lt_one
#check @Padic.valuation_inv
#check @Padic.valuation_p
#check @Padic.valuation_pow
#check @PadicAlgCl.isAlgebraic
#check @PadicAlgCl.isUltrametricDist
#check @PadicAlgCl.nontriviallyNormedField
#check @PadicAlgCl.normedAlgebra
#check @PadicAlgCl.valuation_def
#check @PadicAlgCl.valued
#check @PadicComplex.RankOne.hom_eq_embedding
#check @PadicComplex.charZero
#check @PadicComplex.coe_eq
#check @PadicComplex.coe_natCast
#check @PadicComplex.isAlgClosed
#check @PadicComplex.nnnorm_extends'
#check @PadicComplex.norm_eq_norm
#check @PadicComplex.valuation_extends
#check @PadicComplex.valued
#check @PowerSeries.coe_pow
#check @Rat.castHom
#check @Rat.cast_neg
#check @Rat.cast_one
#check @Rat.cast_strictMono
#check @Rat.den_pos
#check @Rat.num_div_den
#check @Real.exp_log
#check @Real.inv_rpow
#check @Real.log_exp
#check @Real.log_inv
#check @Real.log_lt_log
#check @Real.log_mul
#check @Real.log_one
#check @Real.log_zpow
#check @Real.rpow_def_of_pos
#check @Real.rpow_inv_natCast_pow
#check @Real.rpow_neg
#check @RingHom.toAddMonoidHom_eq_coe
#check @Set.mem_insert_iff
#check @Set.mem_range
#check @StrictMono.le_iff_le
#check @Subgroup.eq_top_iff'
#check @Subgroup.isCyclic
#check @Subgroup.mem_top
#check @Subgroup.mem_zpowers_iff
#check @SubgroupClass.coe_zpow
#check @Subtype.coe_lt_coe
#check @Subtype.ext
#check @UniformSpace.Completion.coe'
#check @Units.ext
#check @Units.mk0
#check @Units.ne_zero
#check @Units.val_lt_val
#check @Units.val_mk0
#check @Units.val_one
#check @Units.val_zpow_eq_zpow_val
#check @Valuation.IsNontrivial
#check @Valuation.IsNontrivial.exists_val_nontrivial
#check @Valuation.IsRankOneDiscrete.embedding_generator'
#check @Valuation.IsRankOneDiscrete.generator'
#check @Valuation.IsRankOneDiscrete.generator'_lt_one
#check @Valuation.IsRankOneDiscrete.generator'_zpowers_eq_top
#check @Valuation.IsRankOneDiscrete.generator_eq_exp_neg_one_of_surjective
#check @Valuation.IsRankOneDiscrete.generator_lt_one
#check @Valuation.IsRankOneDiscrete.generator_ne_zero
#check @Valuation.IsRankOneDiscrete.generator_zpowers_eq_valueGroup
#check @Valuation.IsRankOneDiscrete.mk'
#check @Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt
#check @Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt_apply_zpow
#check @Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt_strictMono
#check @Valuation.IsUniformizer.iff
#check @Valuation.IsUniformizer.ne_zero
#check @Valuation.IsUniformizer.val
#check @Valuation.IsUniformizer.val_lt_one
#check @Valuation.IsUniformizer.val_ne_zero
#check @Valuation.IsUniformizer.zpowers_eq_valueGroup
#check @Valuation.RankOne.hom
#check @Valuation.RankOne.hom_eq_zero_iff
#check @Valuation.RankOne.strictMono
#check @Valuation.embedding_restrict
#check @Valuation.ext
#check @Valuation.map
#check @Valuation.map_apply
#check @Valuation.map_zero
#check @Valuation.ne_zero_iff
#check @Valuation.norm_def
#check @Valuation.restrict
#check @Valuation.restrict_def
#check @Valuation.restrict_eq_zero_iff
#check @Valuation.restrict_le_iff
#check @Valuation.toAddValuation_apply
#check @Valuation.zero_iff
#check @Valued.exists_coe_eq_v
#check @Valued.extensionValuation
#check @Valued.valuedCompletion
#check @Valued.valuedCompletion_apply
#check @WithTop.LinearOrderedAddCommGroup.coe_neg
#check @WithTop.add_top
#check @WithTop.coe_add
#check @WithTop.coe_inj
#check @WithTop.coe_le_coe
#check @WithTop.coe_natCast
#check @WithTop.coe_ne_top
#check @WithTop.coe_one
#check @WithTop.coe_zero
#check @WithTop.map_coe
#check @WithTop.map_eq_top_iff
#check @WithTop.map_le_iff
#check @WithTop.map_top
#check @WithTop.ne_top_iff_exists
#check @WithTop.recTopCoe
#check @WithTop.top_add
#check @WithZero.coe_unzero
#check @WithZero.coe_zpow
#check @WithZero.expRecOn
#check @WithZero.expRecOn_exp
#check @WithZero.expRecOn_zero
#check @WithZero.exp_add
#check @WithZero.exp_inj
#check @WithZero.exp_le_exp
#check @WithZero.exp_log
#check @WithZero.exp_lt_exp
#check @WithZero.exp_ne_zero
#check @WithZero.exp_pos
#check @WithZero.exp_zero
#check @WithZero.exp_zsmul
#check @WithZero.log_exp
#check @WithZero.log_mul
#check @WithZero.log_one
#check @WithZero.map'
#check @WithZero.map'_coe
#check @WithZero.map'_strictMono
#check @WithZero.recZeroCoe
#check @WithZero.unitsWithZeroEquiv
#check @WithZero.unzero
#check @WithZeroMulInt.toNNReal_neg_apply
#check @ZeroHom.coe_mk
#check @add_smul
#check @bot_le
#check @coe_nnnorm
#check @div_eq_div_iff
#check @div_neg_of_neg_of_pos
#check @div_zpow
#check @eq_div_iff
#check @inv_ne_zero
#check @inv_zpow
#check @inv_zpow'
#check @isCyclic_iff_exists_zpowers_eq_top
#check @isCyclic_multiplicative
#check @isCyclic_of_surjective
#check @le_antisymm
#check @le_top
#check @lt_iff_lt_of_le_iff_le
#check @lt_trichotomy
#check @map_eq_zero
#check @map_mul
#check @map_natCast
#check @map_ne_zero
#check @map_neg
#check @map_pow
#check @map_sub
#check @map_zero
#check @map_zpow₀
#check @map_zsmul
#check @minpoly.coeff_zero_ne_zero
#check @minpoly.natDegree_pos
#check @mul_comm
#check @mul_div_cancel₀
#check @mul_ne_zero
#check @mul_one
#check @mul_pos
#check @mul_smul
#check @neg_add
#check @neg_eq_iff_eq_neg
#check @neg_le_neg_iff
#check @neg_neg
#check @neg_pos
#check @neg_zero
#check @nnnorm_algebraMap'
#check @norm_algebraMap'
#check @norm_nonneg
#check @norm_pos_iff
#check @norm_pow
#check @nsmul_eq_mul
#check @one_add_one_eq_two
#check @one_div
#check @one_pos
#check @pow_ne_zero
#check @pow_one
#check @smul_add
#check @smul_eq_mul
#check @smul_neg
#check @spectralNorm.spectralNorm_eq_norm_coeff_zero_rpow
#check @sub_eq_zero
#check @sub_pos
#check @sub_smul
#check @top_le_iff
#check @two_nsmul
#check @two_pos
#check @zero_div
#check @zero_le'
#check @zero_lt_iff
#check @zero_pow
#check @zpow_add₀
#check @zpow_lt_one_iff_right_of_lt_one₀
#check @zpow_mul
#check @zpow_natCast
#check @zpow_ne_zero
#check @zpow_neg
#check @zpow_one
#check @zpow_right_strictMono₀
#check @zpow_sub₀
#check @zsmul_eq_mul
#check @zsmul_lt_zsmul_iff_left
#check @zsmul_one
