import PhD.TauCeti.Code.NewtonPolygons.AddVal.Examples
-- mathlib names the proof sketches will cite: each must elaborate
#check @WithZero.expRecOn
#check @WithZero.exp_add
#check @WithZero.exp_inj
#check @WithZero.exp_le_exp
#check @WithZero.exp_lt_exp
#check @WithZero.exp_ne_zero
#check @WithZero.exp_log
#check @WithZero.log_exp
#check @WithZero.log_mul
#check @WithZero.log_one
#check @WithZero.exp_zero
#check @WithZero.exp_pos
#check @WithZero.exp_neg
#check @WithZero.recZeroCoe
#check @WithZero.map'_strictMono
#check @WithZero.map'_coe
#check @WithZero.unzero
#check @WithZero.coe_unzero
#check @WithZero.coe_zpow
#check @WithZero.coe_inj
#check @WithZero.unitsWithZeroEquiv
#check @WithTop.recTopCoe
#check @WithTop.coe_inj
#check @WithTop.coe_le_coe
#check @WithTop.coe_lt_coe
#check @WithTop.coe_add
#check @WithTop.coe_zero
#check @WithTop.map_coe
#check @WithTop.map_top
#check @WithTop.ne_top_iff_exists
#check @WithTop.coe_ne_top
#check @WithTop.LinearOrderedAddCommGroup.coe_neg
#check @AddMonoidHom.withTopMap
#check @Monotone.withTop_map
#check @AddMonoidHom.toMultiplicative
#check @AddValuation.map_zero
#check @AddValuation.map_one
#check @AddValuation.map_mul
#check @AddValuation.map_pow
#check @AddValuation.ext
#check @AddValuation.top_iff
#check @AddValuation.ne_top_iff
#check @AddValuation.map_apply
#check @AddValuation.map_add
#check @Valuation.map_zpow
#check @Valuation.map_pow
#check @Valuation.map_mul
#check @Valuation.zero_iff
#check @Valuation.ne_zero_iff
#check @Valuation.restrict_eq_zero_iff
#check @Valuation.embedding_restrict
#check @Valuation.restrict_def
#check @Valuation.restrict_le_iff
#check @Valuation.ext
#check @Valuation.map_one
#check @Valuation.toAddValuation
#check @Valuation.toAddValuation_apply
#check @Valuation.map
#check @Valuation.IsNontrivial
#check @MonoidWithZeroHom.mem_valueGroup
#check @MonoidWithZeroHom.mem_valueGroup_iff_of_comm
#check @MonoidWithZeroHom.valueGroup_eq_range
#check @MonoidWithZeroHom.ValueGroup₀.embedding_injective
#check @MonoidWithZeroHom.ValueGroup₀.embedding_restrict₀
#check @MonoidWithZeroHom.ValueGroup₀.restrict₀_apply
#check @MonoidWithZeroHom.coe_ofClass
#check @MonoidWithZeroHom.ValueGroup₀.embedding
#check @MonoidWithZeroHom.ValueGroup₀.embedding_strictMono
#check @Valuation.RankOne.hom_eq_zero_iff
#check @Valuation.RankOne.strictMono
#check @Valuation.RankOne.hom
#check @Valuation.norm_def
#check @Valuation.norm
#check @Valuation.IsRankOneDiscrete.generator_zpowers_eq_valueGroup
#check @Valuation.IsRankOneDiscrete.generator'_zpowers_eq_top
#check @Valuation.IsRankOneDiscrete.embedding_generator'
#check @Valuation.IsRankOneDiscrete.generator_lt_one
#check @Valuation.IsRankOneDiscrete.generator'_lt_one
#check @Valuation.IsRankOneDiscrete.generator_ne_zero
#check @Valuation.IsRankOneDiscrete.valueGroup_genLTOne_eq_generator
#check @Valuation.IsRankOneDiscrete.generator_eq_exp_neg_one_of_surjective
#check @Valuation.IsRankOneDiscrete.generator_mem_valueGroup
#check @Valuation.IsUniformizer.zpowers_eq_valueGroup
#check @Valuation.IsUniformizer.val_pos
#check @Valuation.IsUniformizer.val_lt_one
#check @Valuation.IsUniformizer.val_ne_zero
#check @Valuation.IsUniformizer.iff
#check @Valuation.IsUniformizer.val
#check @Valuation.valueGroup₀_equiv_withZeroMulInt
#check @Valuation.valueGroup₀_equiv_withZeroMulInt_apply_zpow
#check @Valuation.valueGroup₀_equiv_withZeroMulInt_strictMono
#check @Valuation.valueGroup₀_equiv_withZeroMulInt_apply_zero
#check @Valuation.IsRankOneDiscrete.mk'
#check @LinearOrderedCommGroup.Subgroup.genLTOne_unique_of_zpowers_eq
#check @LinearOrderedCommGroup.Subgroup.genLTOne_unique
#check @Subgroup.mem_zpowers_iff
#check @Subgroup.eq_top_iff'
#check @Subgroup.mem_top
#check @isCyclic_iff_exists_zpowers_eq_top
#check @Subgroup.isCyclic
#check @isCyclic_multiplicative
#check @isCyclic_of_surjective
#check @WithZeroMulInt.toNNReal_neg_apply
#check @WithZeroMulInt.toNNReal
#check @WithZeroMulInt.toNNReal_strictMono
#check @NNReal.rpow_add
#check @NNReal.rpow_zero
#check @NNReal.rpow_pos
#check @NNReal.rpow_lt_rpow_of_exponent_lt
#check @NNReal.coe_zpow
#check @NNReal.coe_inj
#check @NNReal.coe_mul
#check @NNReal.coe_rpow
#check @Real.log_mul
#check @Real.log_lt_log
#check @Real.log_zpow
#check @Real.log_pow
#check @Real.rpow_def_of_pos
#check @Real.exp_log
#check @Real.log_exp
#check @Real.exp_neg
#check @Real.log_inv
#check @Real.log_rpow
#check @Real.rpow_natCast
#check @Real.rpow_inv_natCast_pow
#check @Real.rpow_neg
#check @Real.rpow_intCast
#check @Real.inv_rpow
#check @zpow_right_strictMono₀
#check @zpow_mul
#check @zpow_natCast
#check @zpow_one
#check @zpow_sub₀
#check @div_zpow
#check @inv_zpow
#check @zpow_neg
#check @map_zpow₀
#check @map_inv₀
#check @Units.val_zpow_eq_zpow_val
#check @Units.val_mk0
#check @Units.ext
#check @Units.ne_zero
#check @SubgroupClass.coe_zpow
#check @Subtype.ext
#check @Subtype.coe_lt_coe
#check @Units.val_lt_val
#check @IsAddTorsionFree.zsmul_eq_zero_iff_left
#check @zsmul_lt_zsmul_iff_left
#check @mul_smul
#check @sub_smul
#check @smul_add
#check @add_smul
#check @div_eq_div_iff
#check @Padic.norm_eq_zpow_neg_valuation
#check @Padic.valuation_p
#check @Padic.norm_p
#check @Padic.norm_p_lt_one
#check @Padic.addValuation.apply
#check @Padic.addValuationDef
#check @Padic.addValuation
#check @Padic.valuation_mul
#check @Padic.valuation_inv
#check @Padic.valuation_pow
#check @Padic.norm_p_zpow
#check @NormedField.valuation_apply
#check @NormedField.valuation
#check @NormedField.exists_one_lt_norm
#check @NontriviallyNormedField.non_trivial
#check @norm_algebraMap'
#check @IsUltrametricDist.of_normedAlgebra
#check @NormedAlgebra.norm_eq_spectralNorm
#check @spectralNorm.spectralNorm_eq_norm_coeff_zero_rpow
#check @spectralNorm_extends
#check @minpoly.natDegree_pos
#check @minpoly.coeff_zero_ne_zero
#check @Algebra.IsIntegral.isIntegral
#check @Algebra.IsAlgebraic.isAlgebraic
#check @Valued.exists_coe_eq_v
#check @Valued.valuedCompletion_apply
#check @Valued.extensionValuation_apply_coe
#check @Valued.extension_eq_zero_iff
#check @Valued.valuedCompletion
#check @IsAlgClosed.exists_pow_nat_eq
#check @PadicComplex.norm_eq_norm
#check @PadicComplex.RankOne.hom_eq_embedding
#check @PadicComplex.norm_extends'
#check @PadicComplex.nnnorm_extends'
#check @PadicComplex.valuation_p
#check @PadicComplex.valuation_extends
#check @PadicComplex.coe_natCast
#check @PadicComplex.coe_eq
#check @PadicAlgCl.valuation_def
#check @PadicAlgCl.norm_extends
#check @PadicAlgCl.valuation_p
#check @PadicAlgCl.isAlgebraic
#check @PadicAlgCl.normedAlgebra
#check @LaurentSeries.valuation_single_zpow
#check @LaurentSeries.valuation_X_pow
#check @LaurentSeries.valuation_surjective
#check @LaurentSeries.single_order_mul_powerSeriesPart
#check @LaurentSeries.intValuation_le_iff_coeff_lt_eq_zero
#check @LaurentSeries.powerSeriesPart_coeff
#check @LaurentSeries.valuation_def
#check @LaurentSeries.valued
#check @HahnSeries.coeff_order_ne_zero
#check @HahnSeries.order_single
#check @HahnSeries.ofPowerSeries_X_pow
#check @IsDedekindDomain.HeightOneSpectrum.valuation_le_one
#check @IsDedekindDomain.HeightOneSpectrum.valuation_of_algebraMap
#check @IsDedekindDomain.HeightOneSpectrum.intValuation_le_one
#check @PowerSeries.coeff_zero_eq_constantCoeff
#check @WithZero.log_le_iff_le_exp
#check @UniformSpace.Completion.denseRange_coe
#check @UniformSpace.Completion.induction_on
#check @map_natCast
#check @Rat.castHom
#check @Int.cast_natCast
#check @Nat.Prime.one_lt
#check @Nat.Prime.ne_zero
#check @Fact.out
#check @OrderAddMonoidIso.toAddEquiv_injective
#check @Valuation.RankLeOne.hom'
#check @Valuation.IsNontrivial.exists_val_nontrivial
#check @ne_zero_of_lt
#check @Valuation.map_neg
#check @Valuation.map_units_inv
#check @Multiplicative.ofAdd
#check @Additive.ofMul
#check @Additive.toMul
#check @ofMul_lt
#check @ofMul_le
#check @IsSplittingField
