import PhD.TauCeti.Code.NewtonPolygons.AddVal.Examples
set_option pp.proofs false
set_option linter.style.setOption false
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:50
#check @WithZero.negLog_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:52
#check @WithZero.negLog_exp
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:54
#check @WithZero.negLog_eq_top
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:56
#check @WithZero.negLog_one
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:59
#check @WithZero.negLog_eq_coe
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:61
#check @WithZero.negLog_mul
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:65
#check @WithZero.negLog_le_negLog
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:67
#check @WithZero.negLog_lt_negLog
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:73
#check @WithZero.orderAddIsoWithTop
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:81
#check @WithZero.orderAddIsoWithTop_apply
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:95
#check @WithZero.mapAddHom'_exp
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:97
#check @WithZero.mapAddHom'_strictMono
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:101
#check @WithZero.negLog_mapAddHom'
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:114
#check @NNReal.toRealMultZero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:120
#check @NNReal.toRealMultZero_of_ne_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:123
#check @NNReal.toRealMultZero_strictMono
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:133
#check @WithZeroMulReal.toNNReal
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:139
#check @WithZeroMulReal.toNNReal_exp
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/NegLog.lean:142
#check @WithZeroMulReal.toNNReal_strictMono
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/RatLog.lean:61
#check @AddCommGroup.ratLog
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/RatLog.lean:67
#check @AddCommGroup.ratLog_eq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/RatLog.lean:71
#check @AddCommGroup.ratLog_self
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/RatLog.lean:74
#check @AddCommGroup.ratLog_strictMono
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/RatLog.lean:78
#check @AddCommGroup.ratLog_unique
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Basic.lean:57
#check @Valuation.addVal_apply
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Basic.lean:59
#check @Valuation.addVal_eq_top
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Basic.lean:63
#check @Valuation.addVal_eq_coe
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Basic.lean:67
#check @Valuation.addVal_le_addVal
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Basic.lean:71
#check @Valuation.addVal_map
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Basic.lean:89
#check @Valuation.addValValueGroup_apply
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Basic.lean:93
#check @Valuation.addValValueGroup_eq_top
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/RankOne.lean:47
#check @Valuation.RankOne.addVal_apply
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/RankOne.lean:50
#check @Valuation.RankOne.addVal_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/RankOne.lean:52
#check @Valuation.RankOne.addVal_eq_top
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/RankOne.lean:55
#check @Valuation.RankOne.addVal_apply_of_val_ne_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/RankOne.lean:61
#check @Valuation.RankOne.addVal_eq_of_hom_eq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:67
#check @Valuation.IsCommensurable.val_ne_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:70
#check @Valuation.IsCommensurable.of_forall_eq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:75
#check @Valuation.IsCommensurable.isNontrivial
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:81
#check @Valuation.coe_commGen
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:83
#check @Valuation.ofMul_commGen_neg
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:86
#check @Valuation.isCommensurableWith_commGen
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:96
#check @Valuation.ratLog_strictMono
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:98
#check @Valuation.ratLog_commGen
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:100
#check @Valuation.ratLog_eq_of_zsmul
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:109
#check @Valuation.addValQ_apply
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:112
#check @Valuation.addValQ_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:114
#check @Valuation.addValQ_eq_top
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:117
#check @Valuation.addValQ_eq_of_zpow
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:122
#check @Valuation.addValQ_eq_of_pow_eq_pow
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:126
#check @Valuation.addValQ_self
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:128
#check @Valuation.addValQ_ne_top
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:130
#check @Valuation.exists_zpow_eq_and_addValQ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:134
#check @Valuation.addValQ_le_addValQ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:138
#check @Valuation.addValQ_unique
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:145
#check @Valuation.IsCommensurable.toRankLeOne
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:158
#check @Valuation.IsCommensurable.toRankOne_hom_restrict
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:172
#check @Valuation.RankOne.addVal_eq_map_addValQ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Commensurable.lean:179
#check @Valuation.RankOne.hom_eq_rpow_addValQ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:48
#check @Valuation.IsRankOneDiscrete.exists_zpow_generator_eq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:53
#check @Valuation.IsRankOneDiscrete.exists_zpow_eq_of_isUniformizer
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:58
#check @Valuation.IsRankOneDiscrete.isCommensurable_of_lt_one
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:63
#check @Valuation.IsRankOneDiscrete.isCommensurable
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:72
#check @Valuation.IsRankOneDiscrete.addValZ_apply
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:75
#check @Valuation.IsRankOneDiscrete.addValZ_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:77
#check @Valuation.IsRankOneDiscrete.addValZ_eq_top
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:80
#check @Valuation.IsRankOneDiscrete.addValZ_eq_iff
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:84
#check @Valuation.IsRankOneDiscrete.addValZ_eq_of_zpow
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:88
#check @Valuation.IsRankOneDiscrete.addValZ_eq_iff_of_isUniformizer
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:92
#check @Valuation.IsRankOneDiscrete.addValZ_isUniformizer
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:95
#check @Valuation.IsRankOneDiscrete.addValZ_le_addValZ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:100
#check @Valuation.addValQ_eq_map_addValZ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:107
#check @Valuation.IsRankOneDiscrete.hom_eq_toNNReal_comp
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:115
#check @Valuation.IsRankOneDiscrete.hom_eq_zpow_neg_addValZ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Discrete.lean:121
#check @Valuation.IsRankOneDiscrete.hom_eq_zpow_neg_addValZ_of_isUniformizer
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:47
#check @Valuation.RankOne.addVal_apply_of_ne_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:59
#check @NormedField.valuation_norm_eq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:62
#check @NormedField.norm_eq_coe_hom
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:70
#check @NormedField.normAddVal_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:72
#check @NormedField.normAddVal_eq_top
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:74
#check @NormedField.normAddVal_apply_of_ne_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:79
#check @NormedField.exists_normAddVal_eq_and_norm_eq_exp_neg
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:82
#check @NormedField.normAddVal_le_normAddVal
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:87
#check @NormedField.normAddVal_unique
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:101
#check @NormedField.normAddValZ_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:103
#check @NormedField.normAddValZ_eq_top
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:106
#check @NormedField.normAddValZ_eq_iff_of_isUniformizer
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:110
#check @NormedField.normAddValZ_isUniformizer
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:115
#check @NormedField.norm_eq_zpow_neg_normAddValZ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:124
#check @NormedField.norm_eq_zpow_neg_normAddValZ_of_isUniformizer
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:130
#check @NormedField.normAddVal_eq_map_normAddValZ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:148
#check @NormedField.normAddValQ_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:150
#check @NormedField.normAddValQ_eq_top
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:152
#check @NormedField.normAddValQ_self
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:155
#check @NormedField.normAddValQ_eq_of_pow_eq_pow
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:162
#check @NormedField.norm_eq_norm_rpow_normAddValQ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:168
#check @NormedField.normAddVal_eq_map_normAddValQ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Normed.lean:175
#check @NormedField.normAddValQ_eq_map_normAddValZ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:38
#check @Padic.nnnorm_p_eq_inv
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:40
#check @Padic.nnnorm_p_ne_zero
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:46
#check @Padic.nnnorm_p_zpow_valuation
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:49
#check @Padic.zpowers_valueGroupGen
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:51
#check @Padic.isCyclic_valueGroup
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:56
#check @Padic.isRankOneDiscrete_valuation
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:60
#check @Padic.coe_generator_eq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:64
#check @Padic.isUniformizer_p
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:69
#check @Padic.isCommensurable_p
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:79
#check @NormedField.norm_eq_zpow_neg_normAddValZ_padic
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:83
#check @NormedField.normAddValZ_padic_apply
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Padic.lean:88
#check @NormedField.normAddValZ_padic
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/LaurentSeries.lean:39
#check @LaurentSeries.valuation_eq_exp_neg_order
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/LaurentSeries.lean:43
#check @LaurentSeries.isRankOneDiscrete_valued
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/LaurentSeries.lean:47
#check @LaurentSeries.generator_valued_eq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/LaurentSeries.lean:52
#check @LaurentSeries.isUniformizer_X
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/LaurentSeries.lean:57
#check @LaurentSeries.addValZ_X
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/LaurentSeries.lean:62
#check @LaurentSeries.addValZ_single
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/LaurentSeries.lean:67
#check @LaurentSeries.addValZ_eq_order
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Extension.lean:44
#check @Valued.isCommensurable_completion
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Extension.lean:60
#check @NormedField.normAddVal_algebraMap
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Extension.lean:71
#check @NormedField.exists_normAddValZ_algebraMap_eq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Extension.lean:76
#check @NormedField.normAddValZ_algebraMap
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Extension.lean:82
#check @NormedField.isCommensurable_algebraMap_of_isRankOneDiscrete
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Extension.lean:88
#check @NormedField.map_intCast_normAddValZ_eq_map_normAddValQ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Extension.lean:106
#check @NormedField.norm_pow_natDegree_minpoly
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Extension.lean:111
#check @NormedField.isCommensurable_algebraMap
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Extension.lean:117
#check @NormedField.normAddValQ_algebraMap
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/PadicComplex.lean:37
#check @NormedField.isCommensurable_natCast_prime
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/PadicComplex.lean:48
#check @PadicAlgCl.isCommensurable_p
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/PadicComplex.lean:59
#check @PadicComplex.valuation_eq_nnnorm
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/PadicComplex.lean:61
#check @PadicComplex.normedField_valuation_eq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/PadicComplex.lean:66
#check @PadicComplex.isCommensurable_p
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/PadicComplex.lean:69
#check @PadicComplex.normAddValQ_p
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/PadicComplex.lean:73
#check @PadicComplex.normAddValQ_algebraMap_padic
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/PadicComplex.lean:78
#check @PadicComplex.norm_eq_rpow_neg_normAddValQ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/PadicComplex.lean:83
#check @PadicComplex.exists_normAddValQ_eq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/PadicComplex.lean:88
#check @PadicComplex.range_normAddValQ
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Examples.lean:35
#check @NormedField.normAddValZ_padic_p
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Examples.lean:38
#check @NormedField.normAddValZ_padic_inv_p_sq
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Examples.lean:42
#check @NormedField.normAddVal_padic
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Examples.lean:52
#check @NormedField.normAddValQ_of_sq_eq_prime
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Examples.lean:57
#check @NormedField.normAddValZ_prime_of_sq_eq_prime
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Examples.lean:63
#check @NormedField.normAddValQ_padicComplex_of_pow_three
-- PhD/TauCeti/Code/NewtonPolygons/AddVal/Examples.lean:75
#check @LaurentSeries.addValZ_X_pow
