import PhD.TauCeti.Code.NewtonPolygons.Coeff.Examples
set_option linter.style.setOption false
#check @AddValuation.map_add
#check @AddValuation.top_iff
#check @ConcaveOn.congr
#check @ConcaveOn.neg
#check @ConvexOn.add
#check @DFunLike.congr_fun
#check @EReal
#check @EReal.coe_add
#check @EReal.coe_eq_coe_iff
#check @EReal.coe_le_coe_iff
#check @EReal.coe_lt_coe_iff
#check @EReal.coe_ne_bot
#check @EReal.coe_ne_top
#check @EReal.coe_sub
#check @EReal.coe_toReal
#check @EReal.eq_bot_iff_forall_lt
#check @EReal.eq_top_iff_forall_lt
#check @EReal.rec
#check @EReal.sub_le_sub
#check @EReal.toReal_coe
#check @EReal.toReal_top
#check @EReal.top_add_coe
#check @EReal.top_ne_coe
#check @EReal.top_sub_coe
#check @Filter.Eventually.of_forall
#check @Filter.Tendsto.congr'
#check @Filter.Tendsto.const_mul
#check @Filter.eventually_atTop
#check @Finset.finite_toSet
#check @Finset.mem_coe
#check @Finset.mem_range
#check @Finset.sum_ite_eq'
#check @Function.Injective.eq_iff
#check @Iff.rfl
#check @Iff.symm
#check @Iff.trans
#check @Int.cast_natCast
#check @Int.cast_neg
#check @Int.cast_strictMono
#check @Int.coe_castAddHom
#check @Int.natCast_dvd_natCast
#check @IsUnit.isNormMulUnit
#check @LinearMap.convexOn
#check @Monotone.map_min
#check @Multiset.insert_eq_cons
#check @Multiset.map_cons
#check @Multiset.map_map
#check @Multiset.map_singleton
#check @Multiset.replicate_one
#check @Multiset.replicate_succ
#check @NNReal.coe_lt_coe
#check @NNReal.coe_pos
#check @Nat.Prime.dvd_choose_self
#check @Nat.Prime.ne_zero
#check @Nat.Prime.one_lt
#check @Nat.Prime.pos
#check @Nat.add_right_comm
#check @Nat.add_sub_cancel
#check @Nat.card_Ico
#check @Nat.cast_add
#check @Nat.cast_ne_zero
#check @Nat.cast_nonneg
#check @Nat.cast_pos
#check @Nat.cast_pow
#check @Nat.cast_sub
#check @Nat.cast_succ
#check @Nat.cast_zero
#check @Nat.choose_eq_zero_of_lt
#check @Nat.choose_one_right
#check @Nat.choose_self
#check @Nat.fact_prime_three
#check @Nat.find
#check @Nat.find_min'
#check @Nat.find_spec
#check @Nat.le_add_left
#check @Nat.le_zero
#check @Nat.lt_succ_self
#check @Nat.not_lt_zero
#check @Nat.one_le_cast
#check @Nat.one_lt_cast
#check @Nat.pos_iff_ne_zero
#check @Nat.sInf_eq_zero
#check @Nat.sInf_le
#check @Nat.sInf_mem
#check @Nat.sSup_mem
#check @Nat.sub_add_cancel
#check @Nat.sub_add_comm
#check @Nat.sub_le
#check @Nat.sub_le_sub_left
#check @Nat.sub_pos_of_lt
#check @Nat.sub_sub_self
#check @Nat.sub_zero
#check @Nat.succ_ne_zero
#check @Nat.totient_prime
#check @NewtonPolygon.HasFirstBreak
#check @NewtonPolygon.IsConvexSeq.add_nsmul_unitSlope_le
#check @NewtonPolygon.IsConvexSeq.eq_add_nsmul_of_isSegment
#check @NewtonPolygon.IsConvexSeq.eq_top_of_le
#check @NewtonPolygon.IsConvexSeq.faceLeft_line_le
#check @NewtonPolygon.IsConvexSeq.faceRight_line_le
#check @NewtonPolygon.IsConvexSeq.faceRight_line_lt
#check @NewtonPolygon.IsConvexSeq.le_add_nsmul_unitSlope_self
#check @NewtonPolygon.IsConvexSeq.le_chord
#check @NewtonPolygon.IsConvexSeq.line_le_iff
#check @NewtonPolygon.IsConvexSeq.monotoneOn
#check @NewtonPolygon.IsConvexSeq.ordConnected
#check @NewtonPolygon.IsConvexSeq.piecewise_top
#check @NewtonPolygon.IsConvexSeq.unitSlope_eq_of_isSegment
#check @NewtonPolygon.IsNewtonPolygonOf.anchor_eq
#check @NewtonPolygon.IsNewtonPolygonOf.anchor_eq_sInf
#check @NewtonPolygon.IsNewtonPolygonOf.convex
#check @NewtonPolygon.IsNewtonPolygonOf.eq_newtonPolygon
#check @NewtonPolygon.IsNewtonPolygonOf.eq_of_faceLeft
#check @NewtonPolygon.IsNewtonPolygonOf.eq_of_faceRight
#check @NewtonPolygon.IsNewtonPolygonOf.eq_of_isVertex
#check @NewtonPolygon.IsNewtonPolygonOf.eq_top_of_forall_eq_top
#check @NewtonPolygon.IsNewtonPolygonOf.eq_top_of_forall_le
#check @NewtonPolygon.IsNewtonPolygonOf.hasFirstBreak_iff
#check @NewtonPolygon.IsNewtonPolygonOf.le_points
#check @NewtonPolygon.IsNewtonPolygonOf.line_le
#check @NewtonPolygon.IsNewtonPolygonOf.ne_top_of_le_of_le
#check @NewtonPolygon.IsNewtonPolygonOf.slopeIndices_finite
#check @NewtonPolygon.IsNewtonPolygonOf.slopesUnbounded_of_forall_line
#check @NewtonPolygon.IsPure
#check @NewtonPolygon.IsSegment
#check @NewtonPolygon.IsVertex
#check @NewtonPolygon.IsVertical
#check @NewtonPolygon.SlopesUnbounded
#check @NewtonPolygon.affineFrom
#check @NewtonPolygon.affineFrom_of_le
#check @NewtonPolygon.anchor_le
#check @NewtonPolygon.anchor_mem
#check @NewtonPolygon.card_slopeMultiset
#check @NewtonPolygon.count_slopeMultiset
#check @NewtonPolygon.eq_add_nsmul_of_forall_unitSlope_eq
#check @NewtonPolygon.eq_add_sum_unitSlope
#check @NewtonPolygon.eq_top_of_lt_anchor
#check @NewtonPolygon.exists_isConvexMinorant_iff_isAdmissible
#check @NewtonPolygon.isAdmissible_iff_exists_line
#check @NewtonPolygon.isConvexSeq_affine
#check @NewtonPolygon.isConvexSeq_affineFrom
#check @NewtonPolygon.isConvexSeq_iff_midpoint
#check @NewtonPolygon.isConvexSeq_top
#check @NewtonPolygon.isConvexSeq_zero_fun
#check @NewtonPolygon.isPure_iff_slopeMultiset
#check @NewtonPolygon.isVertex_anchor
#check @NewtonPolygon.isVertex_of_succ_eq_top
#check @NewtonPolygon.mem_finiteSupport
#check @NewtonPolygon.mem_slopeIndices_iff
#check @NewtonPolygon.ne_top_faceLeft
#check @NewtonPolygon.ne_top_faceRight
#check @NewtonPolygon.newtonPolygon_add_affine
#check @NewtonPolygon.newtonPolygon_add_const
#check @NewtonPolygon.newtonPolygon_affine
#check @NewtonPolygon.newtonPolygon_eq_self
#check @NewtonPolygon.newtonPolygon_sq
#check @NewtonPolygon.slopeMultiset
#check @NewtonPolygon.slopesUnbounded_of_finite
#check @NewtonPolygon.unitSlope_affineFrom
#check @NewtonPolygon.unitSlope_coe
#check @NewtonPolygon.unitSlope_eq_top_iff
#check @NewtonPolygon.unitSlope_nat
#check @NewtonPolygon.unitSlope_ne_top
#check @NewtonPolygon.unitSlope_ne_top_iff
#check @NewtonPolygon.unitSlope_newtonPolygon_sq
#check @NewtonPolygon.unitSlope_sq
#check @NormedField.isCommensurable_algebraMap
#check @NormedField.normAddValQ_algebraMap
#check @NormedField.normAddValQ_self
#check @NormedField.normAddValZ_eq_iff_of_isUniformizer
#check @NormedField.normAddValZ_isUniformizer
#check @NormedField.normAddValZ_padic_apply
#check @NormedField.normAddVal_algebraMap
#check @NormedField.normAddVal_apply_of_ne_zero
#check @NormedField.normAddVal_eq_top
#check @NormedField.norm_eq_norm_rpow_normAddValQ
#check @NormedField.toAbsoluteValue
#check @NormedField.valuation_apply
#check @Padic.addValuation.apply
#check @Padic.isUniformizer_p
#check @Padic.norm_int_le_pow_iff_dvd
#check @Padic.norm_p
#check @Padic.norm_p_pow
#check @Padic.valuation_one
#check @Padic.valuation_p
#check @Padic.valuation_pow
#check @Polynomial.C_comp
#check @Polynomial.X_comp
#check @Polynomial.coeToPowerSeries.ringHom
#check @Polynomial.coe_C
#check @Polynomial.coe_X
#check @Polynomial.coe_mul
#check @Polynomial.coe_pow
#check @Polynomial.coeff_C_mul
#check @Polynomial.coeff_C_mul_X_pow
#check @Polynomial.coeff_X
#check @Polynomial.coeff_X_add_one_pow
#check @Polynomial.coeff_X_pow
#check @Polynomial.coeff_add
#check @Polynomial.coeff_coe
#check @Polynomial.coeff_eq_zero_of_lt_natTrailingDegree
#check @Polynomial.coeff_eq_zero_of_natDegree_lt
#check @Polynomial.coeff_map
#check @Polynomial.coeff_mul_X
#check @Polynomial.coeff_natDegree
#check @Polynomial.coeff_one
#check @Polynomial.coeff_reverse
#check @Polynomial.coeff_sub
#check @Polynomial.coeff_zero
#check @Polynomial.compRingHom
#check @Polynomial.cyclotomic_prime
#check @Polynomial.cyclotomic_prime_mul_X_sub_one
#check @Polynomial.exists_eq_gaussNorm
#check @Polynomial.finset_sum_coeff
#check @Polynomial.gaussNorm_coe_powerSeries
#check @Polynomial.isRestricted_toPowerSeries
#check @Polynomial.leadingCoeff_eq_zero
#check @Polynomial.mem_support_iff
#check @Polynomial.mul_comp
#check @Polynomial.natDegree_C_mul
#check @Polynomial.natDegree_C_mul_X
#check @Polynomial.natDegree_C_mul_X_pow
#check @Polynomial.natDegree_X
#check @Polynomial.natDegree_X_add_C
#check @Polynomial.natDegree_add_eq_right_of_natDegree_lt
#check @Polynomial.natDegree_comp
#check @Polynomial.natDegree_cyclotomic
#check @Polynomial.natDegree_one
#check @Polynomial.natDegree_sub_eq_right_of_natDegree_lt
#check @Polynomial.natDegree_zero
#check @Polynomial.natTrailingDegree_le_natDegree
#check @Polynomial.natTrailingDegree_le_of_ne_zero
#check @Polynomial.natTrailingDegree_zero
#check @Polynomial.one_comp
#check @Polynomial.pow_comp
#check @Polynomial.revAt_eq_self_of_lt
#check @Polynomial.revAt_le
#check @Polynomial.ringHom_ext
#check @Polynomial.sub_comp
#check @Polynomial.trailingCoeff
#check @Polynomial.trailingCoeff_eq_zero
#check @PowerSeries.HasGaussNorm
#check @PowerSeries.IsMulDistinguished
#check @PowerSeries.IsMulDistinguished.gaussNorm_eq
#check @PowerSeries.IsMulDistinguished.gaussTerm_lt
#check @PowerSeries.IsMulDistinguished.isNormMulUnit_coeff
#check @PowerSeries.IsRestricted.hasGaussNorm
#check @PowerSeries.coeff_C
#check @PowerSeries.coeff_C_mul
#check @PowerSeries.coeff_X_pow_mul'
#check @PowerSeries.coeff_map
#check @PowerSeries.coeff_mk
#check @PowerSeries.coeff_rescale
#check @PowerSeries.ext
#check @PowerSeries.ext_iff
#check @PowerSeries.gaussNorm_eq
#check @PowerSeries.isRestricted_iff'
#check @PowerSeries.isRestricted_of_finite_support
#check @PowerSeries.le_gaussNorm
#check @PowerSeries.rescale_X
#check @Rat.cast_div
#check @Rat.cast_intCast
#check @Rat.cast_natCast
#check @Rat.cast_strictMono
#check @Rat.coe_castHom
#check @Real.exp_log
#check @Real.exp_one_rpow
#check @Real.inv_rpow
#check @Real.log_exp
#check @Real.log_inv
#check @Real.log_pos
#check @Real.log_rpow
#check @Real.logb_rpow
#check @Real.one_lt_exp_iff
#check @Real.rpow_add
#check @Real.rpow_intCast
#check @Real.rpow_le_one_of_one_le_of_nonpos
#check @Real.rpow_le_rpow_left_iff
#check @Real.rpow_lt_one_of_one_lt_of_neg
#check @Real.rpow_lt_rpow_left_iff
#check @Real.rpow_mul
#check @Real.rpow_natCast
#check @Real.rpow_neg
#check @Real.rpow_neg_one
#check @Real.rpow_nonneg
#check @Real.rpow_one
#check @Real.rpow_pos_of_pos
#check @Real.rpow_zero
#check @Real.sSup_neg
#check @Set.Finite.bddAbove
#check @Set.Finite.bddBelow
#check @Set.Finite.image
#check @Set.Finite.subset
#check @Set.Infinite.exists_gt
#check @Set.OrdConnected
#check @Set.OrdConnected.out
#check @Set.ext
#check @Set.finite_Iic
#check @Set.forall_mem_range
#check @Set.mem_Ico
#check @Set.ncard_empty
#check @Set.ncard_eq_toFinset_card'
#check @Set.ordConnected_Iic
#check @Set.ordConnected_Iio
#check @Set.piecewise
#check @Set.piecewise_eq_of_mem
#check @Set.piecewise_eq_of_notMem
#check @Set.toFinset_Ico
#check @Set.toFinset_insert
#check @Set.toFinset_singleton
#check @StrictMono.injective
#check @StrictMono.le_iff_le
#check @StrictMono.monotone
#check @Units.ne_zero
#check @Valuation.IsCommensurable.val_lt_one
#check @Valuation.IsCommensurable.val_pos
#check @Valuation.IsRankOneDiscrete.generator_lt_one
#check @Valuation.IsUniformizer.iff
#check @WithBot.coe_injective
#check @WithBot.coe_le_coe
#check @WithBot.coe_lt_coe
#check @WithBot.coe_ne_bot
#check @WithTop.LinearOrderedAddCommGroup.coe_neg
#check @WithTop.LinearOrderedAddCommGroup.coe_sub
#check @WithTop.LinearOrderedAddCommGroup.neg_top
#check @WithTop.LinearOrderedAddCommGroup.sub_top
#check @WithTop.LinearOrderedAddCommGroup.top_sub
#check @WithTop.add_ne_top
#check @WithTop.add_top
#check @WithTop.coe_add
#check @WithTop.coe_inj
#check @WithTop.coe_le_coe
#check @WithTop.coe_lt_coe
#check @WithTop.coe_lt_top
#check @WithTop.coe_min
#check @WithTop.coe_ne_top
#check @WithTop.coe_nsmul
#check @WithTop.coe_untop₀_of_ne_top
#check @WithTop.coe_zero
#check @WithTop.map_add
#check @WithTop.map_coe
#check @WithTop.map_eq_top_iff
#check @WithTop.map_top
#check @WithTop.ne_top_iff_exists
#check @WithTop.strictMono_map_iff
#check @WithTop.tendsto_nhds_top_iff
#check @WithTop.top_add
#check @WithTop.top_ne_coe
#check @WithTop.untop₀
#check @WithTop.untop₀_coe
#check @add_comm
#check @add_le_add_right
#check @add_sub_cancel_left
#check @add_sub_cancel_right
#check @algebraMap
#check @bddAbove_def
#check @bot_le
#check @ciInf_le
#check @ciSup_le
#check @coe_nnnorm
#check @concaveOn_const
#check @convexOn_ciSup
#check @convexOn_const
#check @convexOn_iff_forall_pos
#check @convex_iff_ordConnected
#check @div_le_iff₀
#check @div_lt_one
#check @div_mul_cancel₀
#check @div_nonneg
#check @div_one
#check @div_pos
#check @div_pow
#check @eq_div_iff
#check @exists_between
#check @exists_comm
#check @exists_congr
#check @exists_nat_gt
#check @funext
#check @half_lt_self
#check @half_pos
#check @iInf_eq_top
#check @iInf_le
#check @iInf_lt_iff
#check @iInf_mono
#check @iSup_le
#check @if_neg
#check @if_pos
#check @inv_inv
#check @inv_le_one_of_one_le₀
#check @inv_mul_cancel_left₀
#check @inv_mul_cancel₀
#check @inv_mul_eq_div
#check @inv_pos
#check @inv_zpow'
#check @isUnit_iff_ne_zero
#check @le_antisymm
#check @le_antisymm_iff
#check @le_ciInf
#check @le_ciSup
#check @le_csSup
#check @le_iInf
#check @le_iInf_iff
#check @le_iSup
#check @le_max_left
#check @le_max_right
#check @le_of_forall_lt
#check @le_or_gt
#check @le_sub_iff_add_le
#check @le_top
#check @lt_add_one
#check @lt_irrefl
#check @lt_of_lt_of_le
#check @lt_trichotomy
#check @map_neg
#check @map_nsmul
#check @map_sub
#check @mul_add
#check @mul_comm
#check @mul_div_assoc
#check @mul_div_cancel₀
#check @mul_eq_zero
#check @mul_inv_cancel₀
#check @mul_le_mul_left
#check @mul_le_mul_of_nonneg_right
#check @mul_lt_mul_of_pos_left
#check @mul_neg_iff
#check @mul_nonneg
#check @mul_one
#check @mul_pos
#check @mul_sub
#check @mul_zero
#check @ne_of_gt
#check @ne_top_of_le_ne_top
#check @neg_convexOn_iff
#check @neg_le
#check @neg_le_neg
#check @neg_neg
#check @neg_sub
#check @norm_eq_zero
#check @norm_inv
#check @norm_mul
#check @norm_ne_zero_iff
#check @norm_neg
#check @norm_nonneg
#check @norm_one
#check @norm_pos_iff
#check @norm_zero
#check @not_and
#check @not_exists
#check @not_forall
#check @not_le
#check @not_lt
#check @not_or
#check @not_top_lt
#check @nsmul_eq_mul
#check @one_lt_inv_iff₀
#check @one_ne_zero
#check @one_pow
#check @pow_le_pow_left₀
#check @pow_le_pow_right₀
#check @pow_mul
#check @pow_ne_zero
#check @pow_nonneg
#check @pow_one
#check @pow_pos
#check @pow_succ
#check @pow_unbounded_of_one_lt
#check @pow_zero
#check @sq
#check @squeeze_zero
#check @squeeze_zero'
#check @strictMono_mul_left_of_pos
#check @sub_add_cancel
#check @sub_eq_add_neg
#check @sub_eq_iff_eq_add
#check @sub_eq_zero
#check @sub_ne_zero
#check @sub_neg
#check @sub_nonpos
#check @sub_zero
#check @tendsto_const_nhds
#check @tendsto_nhds_unique
#check @tendsto_pow_atTop_nhds_zero_of_lt_one
#check @top_le_iff
#check @zero_add
#check @zero_le
#check @zero_le_one
#check @zero_lt_one
#check @zero_mul
#check @zpow_natCast
#check @zpow_neg
#check @zpow_neg_one
