import PhD.TauCeti.Code.NewtonPolygons.Coeff.Examples
set_option linter.style.setOption false
-- WithTop
#check @WithTop.map_top
#check @WithTop.map_coe
#check @WithTop.coe_le_coe
#check @WithTop.coe_lt_coe
#check @WithTop.coe_inj
#check @WithTop.coe_add
#check @WithTop.coe_ne_top
#check @WithTop.ne_top_iff_exists
#check @WithTop.map_add
#check @WithTop.map_eq_top_iff
#check @WithTop.strictMono_map_iff
#check @WithTop.map_le_iff
#check @WithTop.untop₀_coe
#check @WithTop.coe_untop₀_of_ne_top
#check @WithTop.untop₀_top
#check @WithTop.tendsto_nhds_top_iff
#check @WithTop.coe_nsmul
#check @WithTop.coe_zero
#check @WithTop.top_add
#check @WithTop.add_top
#check @WithTop.LinearOrderedAddCommGroup.coe_sub
#check @WithTop.LinearOrderedAddCommGroup.top_sub
#check @WithTop.LinearOrderedAddCommGroup.sub_top
#check @WithTop.LinearOrderedAddCommGroup.coe_neg
#check @WithTop.LinearOrderedAddCommGroup.neg_top
#check @WithTop.map_injective
#check @WithTop.map_mono
#check @WithTop.coe_eq_coe
#check @WithTop.map_ne_top_iff
-- AddValuation
#check @AddValuation.map_zero
#check @AddValuation.map_one
#check @AddValuation.map_mul
#check @AddValuation.map_pow
#check @AddValuation.map_inv
#check @AddValuation.map_add
#check @AddValuation.top_iff
#check @AddValuation.ne_top_iff
#check @AddValuation.map_neg
-- Real
#check @Real.rpow_natCast
#check @Real.rpow_intCast
#check @Real.rpow_neg
#check @Real.rpow_add
#check @Real.rpow_sub
#check @Real.rpow_mul
#check @Real.inv_rpow
#check @Real.rpow_logb
#check @Real.logb_rpow
#check @Real.logb_self_eq_one
#check @Real.rpow_le_rpow_left_iff
#check @Real.rpow_lt_rpow_left_iff
#check @Real.rpow_pos_of_pos
#check @Real.rpow_nonneg
#check @Real.exp_one_rpow
#check @Real.one_lt_exp_iff
#check @Real.one_lt_exp_iff_pos
#check @Real.add_one_lt_exp
#check @Real.log_pos
#check @Real.log_rpow
#check @Real.log_inv
#check @Real.log_exp
#check @Real.log_lt_log
#check @Real.logb_eq_iff_rpow_eq
#check @Real.log_div_log
#check @Real.logb
#check @Real.rpow_le_rpow_of_exponent_le
#check @Real.rpow_lt_rpow_of_exponent_lt
#check @zpow_right_strictMono₀
#check @Real.rpow_neg_one
#check @Real.exp_log
#check @Real.log_zpow
#check @Real.log_pow
#check @Real.rpow_zero
#check @Real.rpow_one
#check @Real.rpow_le_one_iff_of_pos
#check @Real.one_lt_rpow_iff
#check @Real.rpow_inj
#check @Real.rpow_left_injective
#check @Real.logb_le_logb
#check @Real.logb_lt_logb
#check @Real.logb_mul
#check @Real.logb_pow
#check @Real.logb_inv
#check @Real.neg_logb
#check @Real.logb_one
#check @Real.rpow_logb_eq_one
#check @Real.log_ne_zero_of_pos_of_ne_one
#check @Real.exp_pos
#check @one_lt_inv_iff₀
#check @inv_pos
#check @Real.rpow_natCast_mul
#check @Real.rpow_mul_natCast
#check @Real.rpow_eq_rpow_left_iff
#check @Real.rpow_le_rpow_iff_left
-- EReal
#check @EReal.coe_sub
#check @EReal.coe_add
#check @EReal.coe_mul
#check @EReal.coe_le_coe_iff
#check @EReal.coe_lt_coe_iff
#check @EReal.coe_eq_coe_iff
#check @EReal.coe_ne_bot
#check @EReal.coe_ne_top
#check @EReal.bot_lt_coe
#check @EReal.coe_lt_top
#check @EReal.top_sub_coe
#check @EReal.toReal_coe
#check @EReal.coe_toReal
#check @EReal.toReal_sub
#check @EReal.toReal_le_toReal
#check @EReal.exists_rat_btwn_of_lt
#check @EReal.bot_add
#check @EReal.add_bot
#check @EReal.top_add_coe
#check @EReal.coe_add_top
#check @EReal.coe_nonneg
#check @EReal.toReal_add
#check @EReal.bot_sub
#check @EReal.sub_bot
#check @EReal.lt_iff_exists_real_btwn
#check @EReal.coe_sub_bot
#check @EReal.eq_bot_iff_forall_lt
#check @EReal.eq_top_iff_forall_lt
#check @EReal.toReal_bot
#check @EReal.toReal_top
#check @iInf_le
#check @le_iInf
#check @le_iInf_iff
#check @iInf_eq_bot
#check @iInf_eq_top
#check @le_iSup
#check @iSup_le
#check @iSup_le_iff
#check @WithBot.coe_le_coe
#check @WithBot.coe_lt_coe
#check @WithBot.coe_injective
#check @WithBot.coe_ne_bot
#check @WithBot.coe_eq_coe
#check @WithBot.coe_inj
-- Polynomial / PowerSeries
#check @Polynomial.coeff_coe
#check @Polynomial.coe_mul
#check @Polynomial.coe_X
#check @Polynomial.coe_C
#check @Polynomial.coe_monomial
#check @Polynomial.coe_add
#check @Polynomial.coe_sub
#check @Polynomial.coe_one
#check @Polynomial.coe_pow
#check @Polynomial.coeff_reverse
#check @Polynomial.revAt_le
#check @Polynomial.revAt_gt
#check @Polynomial.reverse_natDegree
#check @Polynomial.natTrailingDegree_le_of_ne_zero
#check @Polynomial.coeff_eq_zero_of_lt_natTrailingDegree
#check @Polynomial.coeff_eq_zero_of_natDegree_lt
#check @Polynomial.natTrailingDegree_le_natDegree
#check @Polynomial.trailingCoeff_eq_zero
#check @Polynomial.trailingCoeff
#check @Polynomial.natTrailingDegree_eq_support_min'
#check @Polynomial.natDegree_eq_support_max'
#check @Polynomial.le_natDegree_of_ne_zero
#check @Polynomial.coeff_natDegree
#check @Polynomial.leadingCoeff_eq_zero
#check @Polynomial.mem_support_iff
#check @Polynomial.coeff_C_mul
#check @Polynomial.coeff_X_pow_mul'
#check @Polynomial.coeff_map
#check @Polynomial.ringHom_ext
#check @Polynomial.coeff_X_add_one_pow
#check @Polynomial.cyclotomic_prime
#check @Polynomial.cyclotomic_prime_mul_X_sub_one
#check @Polynomial.coeff_one
#check @Polynomial.coeff_X
#check @Polynomial.coeff_sub
#check @Polynomial.coeff_add
#check @Polynomial.coeff_X_pow
#check @Polynomial.coeff_C_mul_X_pow
#check @Polynomial.coeff_C
#check @Polynomial.natDegree_comp
#check @Polynomial.mul_comp
#check @Polynomial.X_comp
#check @Polynomial.C_comp
#check @Polynomial.add_comp
#check @Polynomial.sub_comp
#check @Polynomial.pow_comp
#check @Polynomial.coe_inj
#check @Polynomial.coeToPowerSeries.ringHom
#check @Polynomial.coeToPowerSeries.ringHom_apply
#check @Polynomial.isRestricted_toPowerSeries
#check @Polynomial.gaussNorm_coe_powerSeries
#check @Polynomial.exists_eq_gaussNorm
#check @Polynomial.gaussNorm
#check @Polynomial.natDegree_pos_iff_degree_pos
#check @Polynomial.natDegree_eq_zero
#check @Polynomial.natDegree_lt_natDegree
#check @Polynomial.natDegree_sub_le
#check @Polynomial.natDegree_X_pow_mul
#check @Polynomial.natTrailingDegree_X_pow_mul
#check @Polynomial.natTrailingDegree_mul_X_pow
#check @Polynomial.coeff_mul_X_pow'
#check @Polynomial.cyclotomic.monic
#check @Polynomial.natDegree_cyclotomic
#check @Polynomial.cyclotomic_ne_zero
#check @Polynomial.coeff_comp_degree_mul_degree
#check @Polynomial.eval₂_at_apply
#check @Polynomial.comp_eq_sum_left
#check @Polynomial.coeff_sum
#check @Polynomial.ext_iff
#check @Polynomial.reverse_eq_zero
#check @Polynomial.reverse_leadingCoeff
#check @Polynomial.coeff_zero_reverse
#check @Polynomial.natDegree_eq_reverse_natDegree_add_natTrailingDegree
#check @Polynomial.support_C_mul_X_pow'
#check @PowerSeries.coeff_mk
#check @PowerSeries.coeff_C_mul
#check @PowerSeries.coeff_rescale
#check @PowerSeries.coeff_X_pow_mul'
#check @PowerSeries.coeff_map
#check @PowerSeries.rescale_X
#check @PowerSeries.rescale_C
#check @PowerSeries.coeff_zero_eq_constantCoeff
#check @PowerSeries.ext
#check @PowerSeries.gaussNorm_eq
#check @PowerSeries.le_gaussNorm
#check @PowerSeries.HasGaussNorm
#check @PowerSeries.gaussNorm_nonneg
#check @PowerSeries.isRestricted_iff
#check @PowerSeries.isRestricted_iff'
#check @PowerSeries.IsRestricted.hasGaussNorm
#check @PowerSeries.IsRestricted.exists_achievesGaussNorm
#check @PowerSeries.AchievesGaussNorm
#check @PowerSeries.isRestricted_of_finite_support
#check @PowerSeries.IsMulDistinguished
#check @PowerSeries.IsMulDistinguished.gaussNorm_eq
#check @PowerSeries.IsMulDistinguished.gaussTerm_lt
#check @PowerSeries.IsMulDistinguished.isNormMulUnit_coeff
#check @IsUnit.isNormMulUnit
#check @IsNormMulUnit.isUnit
#check @PowerSeries.coeff_X_pow
#check @PowerSeries.coeff_one
#check @PowerSeries.coeff_X
#check @PowerSeries.coeff_C
#check @PowerSeries.coeff_zero_C
#check @PowerSeries.coeff_X_pow_mul
#check @PowerSeries.hasGaussNorm_of_finite_support
#check @PowerSeries.gaussNorm_zero
#check @PowerSeries.gaussNorm_eq_zero_iff
#check @PowerSeries.rescale
#check @PowerSeries.map
#check @PowerSeries.coe_X
#check @PowerSeries.isRestricted_mk
#check @PowerSeries.isRestricted_map
#check @PowerSeries.isRestricted_zero
#check @PowerSeries.coeff_C_mul_X_pow
#check @PowerSeries.X_pow_eq
#check @PowerSeries.coeff_zero_X_pow_mul
#check @PowerSeries.ext_iff
#check @PowerSeries.rescale_zero
#check @PowerSeries.coeff_rescale
-- filters, limits
#check @Filter.Tendsto
#check @Metric.tendsto_atTop
#check @NormedAddCommGroup.tendsto_atTop
#check @tendsto_nhds_unique
#check @Filter.Tendsto.bddAbove_range_of_cofinite
#check @Filter.Tendsto.bddAbove_range
#check @tendsto_pow_atTop_nhds_zero_of_lt_one
#check @squeeze_zero
#check @squeeze_zero_norm
#check @Filter.eventually_atTop
#check @Filter.Tendsto.congr'
#check @tendsto_const_nhds
#check @tendsto_nhds_of_eventually_eq
#check @Filter.EventuallyEq
#check @Nat.cofinite_eq_atTop
#check @Filter.Tendsto.eventually_gt_atTop
#check @Filter.tendsto_atTop_atTop
#check @tendsto_atTop_of_geom_le
#check @Real.tendsto_pow_mul_exp_neg_atTop_nhds_zero
#check @tendsto_natCast_atTop_atTop
#check @Filter.Tendsto.atTop_add
#check @Filter.tendsto_atTop_mono
#check @Filter.Tendsto.comp
#check @Filter.tendsto_atTop
#check @Filter.Eventually.exists
#check @Filter.Tendsto.eventually
#check @Filter.Frequently
#check @Filter.frequently_atTop
#check @Filter.not_tendsto_iff_exists_frequently_nmem
-- order / sets
#check @Nat.sInf_mem
#check @Nat.sInf_le
#check @Nat.sSup_mem
#check @Set.Finite.bddAbove
#check @Set.Finite.bddBelow
#check @Set.ncard
#check @Set.ncard_eq_toFinset_card'
#check @Set.Infinite
#check @Set.infinite_of_not_bddAbove
#check @Set.Finite.subset
#check @Set.finite_Iic
#check @Finset.finite_toSet
#check @le_ciSup
#check @ciSup_le
#check @Real.iSup_of_not_bddAbove
#check @Real.sSup_of_not_bddAbove
#check @csSup_le
#check @le_csSup
#check @ciSup_le_iff
#check @ciInf_le
#check @le_ciInf
#check @Real.iInf_of_not_bddBelow
#check @exists_lt_of_lt_ciSup
#check @exists_lt_of_ciInf_lt
#check @Set.Finite.exists_maximal_wrt
#check @Set.Finite.exists_le
#check @Set.Finite.toFinset
#check @Set.Finite.image
#check @Nat.find
#check @Nat.find_spec
#check @Nat.find_min'
#check @Set.Infinite.exists_gt
#check @Set.infinite_coe_iff
#check @Set.Infinite.exists_nat_lt
#check @Set.not_infinite
-- Multiset
#check @Multiset.replicate
#check @Multiset.map_replicate
#check @Multiset.card_replicate
#check @Multiset.count_replicate
#check @Multiset.map_map
#check @Multiset.card_map
#check @Multiset.map_singleton
#check @Multiset.insert_eq_cons
#check @Multiset.card_eq_one
#check @Multiset.card_eq_two
#check @Multiset.ext
#check @Multiset.count_singleton
#check @Multiset.eq_replicate
#check @Multiset.eq_replicate_card
#check @Multiset.ext'
#check @Multiset.count_cons
#check @Multiset.count_map
#check @Multiset.replicate_one
#check @Multiset.replicate_succ
-- convexity
#check @convexOn_ciSup
#check @ConcaveOn
#check @neg_convexOn_iff
#check @neg_concaveOn_iff
#check @ConvexOn.sup
#check @ConcaveOn.inf
#check @convexOn_const
#check @concaveOn_const
#check @ConvexOn.add
#check @ConcaveOn.add
#check @convexOn_id
#check @ConcaveOn.neg
#check @ConvexOn.neg
#check @convex_Iio
#check @convex_Iic
#check @Convex
#check @convex_iff_ordConnected
#check @Set.OrdConnected
#check @ConvexOn.congr
#check @ConcaveOn.congr
#check @ConvexOn.subset
#check @ConcaveOn.subset
#check @concaveOn_iff_forall_pos
#check @LinearMap.concaveOn
#check @ConcaveOn.smul
#check @ConcaveOn.sub
-- p-adic
#check @Padic.addValuation.apply
#check @Padic.valuation_p
#check @Padic.valuation_pow
#check @Padic.valuation_natCast
#check @Padic.valuation_mul
#check @Padic.norm_p
#check @Padic.norm_p_pow
#check @Padic.norm_natCast_lt_one_iff
#check @Padic.norm_natCast_eq_one_iff
#check @padicNormE.norm_int_le_one
#check @Padic.norm_eq_zpow_neg_valuation
#check @Padic.valuation_one
#check @Padic.valuation_inv
#check @Padic.valuation_zpow
#check @Padic.addValuation
#check @Padic.valuation_ratCast
#check @Nat.Prime.dvd_choose_self
#check @Nat.Prime.emultiplicity_choose_prime_pow
#check @Nat.fact_prime_three
#check @NormedField.normAddValZ_padic_apply
#check @NormedField.normAddValZ_padic
#check @NormedField.norm_eq_zpow_neg_normAddValZ_padic
#check @Padic.isUniformizer_p
#check @Padic.nnnorm_p_eq_inv
#check @Padic.norm_natCast_le_one
#check @padicNormE.norm_int_lt_one_iff_dvd
#check @Padic.norm_le_one_iff_val_nonneg
#check @padicValNat_eq_emultiplicity
#check @Nat.choose_symm_diff
#check @Nat.choose_self
#check @Nat.choose_one_right
#check @Nat.choose_eq_zero_of_lt
#check @Nat.succ_sub_one
-- Layer 1
#check @NormedField.normAddVal_apply_of_ne_zero
#check @NormedField.normAddVal_eq_top
#check @NormedField.normAddVal_zero
#check @NormedField.normAddValZ_eq_iff_of_isUniformizer
#check @NormedField.normAddValZ_isUniformizer
#check @NormedField.norm_eq_zpow_neg_normAddValZ_of_isUniformizer
#check @NormedField.normAddValZ_eq_top
#check @NormedField.normAddValQ_self
#check @NormedField.norm_eq_norm_rpow_normAddValQ
#check @NormedField.normAddValQ_eq_top
#check @NormedField.normAddVal_eq_map_normAddValZ
#check @NormedField.normAddVal_eq_map_normAddValQ
#check @NormedField.normAddValQ_eq_map_normAddValZ
#check @NormedField.normAddVal_algebraMap
#check @NormedField.normAddValQ_algebraMap
#check @NormedField.isCommensurable_algebraMap
#check @NormedField.exists_normAddVal_eq_and_norm_eq_exp_neg
#check @NormedField.valuation_norm_eq
#check @NormedField.norm_eq_coe_hom
#check @NormedField.valuation_apply
#check @Valuation.IsUniformizer
#check @Valuation.IsCommensurable.val_lt_one
#check @Valuation.IsCommensurable.val_pos
#check @Valuation.IsCommensurable.val_ne_zero
#check @Valuation.IsUniformizer.iff
#check @Valuation.IsRankOneDiscrete.generator_lt_one
#check @Valuation.IsUniformizer.ne_zero
#check @Valuation.IsUniformizer.val_lt_one
#check @Valuation.IsUniformizer.val_ne_zero
#check @Valuation.IsRankOneDiscrete.coe_generator_lt_one
#check @Valuation.generator_lt_one
#check @Valuation.generator_ne_zero
#check @Valuation.zero_iff
#check @Valuation.ne_zero_iff
#check @Padic.norm_p_lt_one
-- Layer 0
#check @NewtonPolygon.isAdmissible_of_line
#check @NewtonPolygon.IsAdmissible.exists_line
#check @NewtonPolygon.isAdmissible_iff_exists_line
#check @NewtonPolygon.isAdmissible_iff_bddBelow
#check @NewtonPolygon.IsNewtonPolygonOf.line_le
#check @NewtonPolygon.IsNewtonPolygonOf.eq_of_isVertex
#check @NewtonPolygon.IsNewtonPolygonOf.anchor_eq
#check @NewtonPolygon.IsNewtonPolygonOf.eq_top_of_forall_eq_top
#check @NewtonPolygon.IsNewtonPolygonOf.eq_top_of_forall_le
#check @NewtonPolygon.IsNewtonPolygonOf.ne_top_of_le_of_le
#check @NewtonPolygon.IsNewtonPolygonOf.ne_top_of_ne_top
#check @NewtonPolygon.IsNewtonPolygonOf.slopeIndices_finite
#check @NewtonPolygon.IsNewtonPolygonOf.slopesUnbounded_of_finite
#check @NewtonPolygon.IsNewtonPolygonOf.slopesUnbounded_of_forall_line
#check @NewtonPolygon.IsNewtonPolygonOf.slopesUnbounded_of_tendsto
#check @NewtonPolygon.IsNewtonPolygonOf.eq_newtonPolygon
#check @NewtonPolygon.IsNewtonPolygonOf.unique
#check @NewtonPolygon.IsNewtonPolygonOf.apply_anchor
#check @NewtonPolygon.IsNewtonPolygonOf.anchor_eq_sInf
#check @NewtonPolygon.IsNewtonPolygonOf.hasFirstBreak_iff
#check @NewtonPolygon.IsNewtonPolygonOf.eq_of_faceLeft
#check @NewtonPolygon.IsNewtonPolygonOf.eq_of_faceRight
#check @NewtonPolygon.IsNewtonPolygonOf.isConvexMinorant
#check @NewtonPolygon.IsNewtonPolygonOf.isAdmissible
#check @NewtonPolygon.IsNewtonPolygonOf.twoSlope_le
#check @NewtonPolygon.IsNewtonPolygonOf.convex
#check @NewtonPolygon.IsNewtonPolygonOf.le_points
#check @NewtonPolygon.IsNewtonPolygonOf.greatest
#check @NewtonPolygon.isNewtonPolygonOf_newtonPolygon
#check @NewtonPolygon.newtonPolygon_le
#check @NewtonPolygon.le_newtonPolygon
#check @NewtonPolygon.newtonPolygon_eq_self
#check @NewtonPolygon.newtonPolygon_add_const
#check @NewtonPolygon.newtonPolygon_add_affine
#check @NewtonPolygon.newtonPolygon_mono
#check @NewtonPolygon.exists_isConvexMinorant_iff_isAdmissible
#check @NewtonPolygon.exists_isNewtonPolygonOf_iff_isAdmissible
#check @NewtonPolygon.exists_isNewtonPolygonOf_or_isVertical
#check @NewtonPolygon.isVertical_iff_not_exists_isConvexMinorant
#check @NewtonPolygon.IsConvexSeq.le_chord
#check @NewtonPolygon.IsConvexSeq.line_le_iff
#check @NewtonPolygon.IsConvexSeq.line_lt_of_unitSlope_lt
#check @NewtonPolygon.IsConvexSeq.line_lt_of_lt_unitSlope
#check @NewtonPolygon.IsConvexSeq.faceRight_line_le
#check @NewtonPolygon.IsConvexSeq.faceRight_line_lt
#check @NewtonPolygon.IsConvexSeq.faceLeft_line_le
#check @NewtonPolygon.IsConvexSeq.faceLeft_line_lt
#check @NewtonPolygon.IsConvexSeq.eq_add_nsmul_of_mem_face
#check @NewtonPolygon.IsConvexSeq.le_unitSlope_of_faceLeft_le
#check @NewtonPolygon.IsConvexSeq.lt_unitSlope_of_faceRight_le
#check @NewtonPolygon.IsConvexSeq.faceRight_sub_faceLeft
#check @NewtonPolygon.IsConvexSeq.faceLeft_eq_faceRight_iff
#check @NewtonPolygon.IsConvexSeq.faceLeft_eq_ncard
#check @NewtonPolygon.IsConvexSeq.faceRight_eq_ncard
#check @NewtonPolygon.IsConvexSeq.count_slopeMultiset_eq
#check @NewtonPolygon.IsConvexSeq.unitSlope_eq_of_isSegment
#check @NewtonPolygon.IsConvexSeq.eq_add_nsmul_of_isSegment
#check @NewtonPolygon.IsConvexSeq.slopeIndices_eq_Ico
#check @NewtonPolygon.IsConvexSeq.anchor_add_sum_slopeMultiset
#check @NewtonPolygon.IsConvexSeq.add_nsmul_unitSlope_le
#check @NewtonPolygon.IsConvexSeq.le_add_nsmul_unitSlope
#check @NewtonPolygon.IsConvexSeq.le_add_nsmul_unitSlope_self
#check @NewtonPolygon.IsConvexSeq.untop₀_add_mul_le
#check @NewtonPolygon.IsConvexSeq.isAdmissible
#check @NewtonPolygon.IsConvexSeq.extend_affine
#check @NewtonPolygon.IsConvexSeq.eq_of_unitSlope_eq
#check @NewtonPolygon.IsConvexSeq.midpoint
#check @NewtonPolygon.isConvexSeq_iff_midpoint
#check @NewtonPolygon.IsConvexSeq.ne_top_of_le_of_le
#check @NewtonPolygon.IsConvexSeq.eq_top_of_le
#check @NewtonPolygon.IsConvexSeq.eq_top_of_unitSlope_eq_top
#check @NewtonPolygon.IsConvexSeq.slopesUnbounded_or_endsInRay_or_tendsto
#check @NewtonPolygon.IsConvexSeq.monotoneOn
#check @NewtonPolygon.IsConvexSeq.ordConnected
#check @NewtonPolygon.IsConvexSeq.tendsto_unitSlope
#check @NewtonPolygon.IsConvexSeq.finiteSupport_subset_of_unitSlope_eq
#check @NewtonPolygon.IsConvexSeq.succ_add_le_add_succ
#check @NewtonPolygon.isConvexSeq_affine
#check @NewtonPolygon.isConvexSeq_affine_sub
#check @NewtonPolygon.isConvexSeq_affineFrom
#check @NewtonPolygon.affineFrom
#check @NewtonPolygon.affineFrom_of_le
#check @NewtonPolygon.affineFrom_of_lt
#check @NewtonPolygon.unitSlope_affineFrom
#check @NewtonPolygon.isConvexSeq_top
#check @NewtonPolygon.isConvexSeq_coe_iff
#check @NewtonPolygon.unitSlope_nat
#check @NewtonPolygon.unitSlope_coe
#check @NewtonPolygon.unitSlope_eq_top_iff
#check @NewtonPolygon.unitSlope_ne_top_iff
#check @NewtonPolygon.unitSlope_of_ne_top
#check @NewtonPolygon.add_unitSlope
#check @NewtonPolygon.unitSlope_eq_of_succ_eq_add
#check @NewtonPolygon.unitSlope_add
#check @NewtonPolygon.mem_finiteSupport
#check @NewtonPolygon.anchor_le
#check @NewtonPolygon.anchor_mem
#check @NewtonPolygon.eq_top_of_lt_anchor
#check @NewtonPolygon.isVertex_anchor
#check @NewtonPolygon.isVertex_of_succ_eq_top
#check @NewtonPolygon.mem_slopeIndices_iff
#check @NewtonPolygon.card_slopeMultiset
#check @NewtonPolygon.count_slopeMultiset
#check @NewtonPolygon.isPure_iff_slopeMultiset
#check @NewtonPolygon.slopesUnbounded_of_finite
#check @NewtonPolygon.le_unitSlope_faceLeft
#check @NewtonPolygon.lt_unitSlope_faceRight
#check @NewtonPolygon.unitSlope_lt_of_lt_faceLeft
#check @NewtonPolygon.unitSlope_le_of_lt_faceRight
#check @NewtonPolygon.faceLeft_le_faceRight
#check @NewtonPolygon.ne_top_faceLeft
#check @NewtonPolygon.ne_top_faceRight
#check @NewtonPolygon.isAdmissible_of_bddBelow
#check @NewtonPolygon.IsAdmissible.mono
#check @NewtonPolygon.IsAdmissible.bddBelow_slopeSet
#check @NewtonPolygon.newtonPolygon_sq
#check @NewtonPolygon.unitSlope_newtonPolygon_sq
#check @NewtonPolygon.isConvexSeq_sq
#check @NewtonPolygon.exists_faceRight_eq
#check @NewtonPolygon.EndsInRay
#check @NewtonPolygon.IsConvexSeq.endsInRay_iff
#check @NewtonPolygon.EndsInRay.not_slopesUnbounded
#check @NewtonPolygon.slopesUnbounded_iff_forall_lt_unitSlope_faceRight
#check @NewtonPolygon.finiteSupport_coe
#check @NewtonPolygon.finiteSupport_add
#check @NewtonPolygon.IsConvexMinorant
#check @NewtonPolygon.IsConvexMinorant.add_affine
#check @NewtonPolygon.IsConvexMinorant.isAdmissible
#check @NewtonPolygon.add_coe_add_coe_of_add_eq_zero
#check @NewtonPolygon.IsConvexSeq.add_affine
#check @NewtonPolygon.IsConvexSeq.piecewise_top
#check @NewtonPolygon.IsConvexSeq.sup
#check @NewtonPolygon.IsConvexSeq.iSup
#check @NewtonPolygon.IsConvexSeq.add
#check @NewtonPolygon.slopeTo
#check @NewtonPolygon.slopeSet
#check @NewtonPolygon.truncate
#check @NewtonPolygon.newtonPolygon_truncate_eq
#check @NewtonPolygon.collinearExample
#check @NewtonPolygon.IsVertex
#check @NewtonPolygon.HasFirstBreak
#check @NewtonPolygon.IsPure
#check @NewtonPolygon.IsSegment
#check @NewtonPolygon.slopeMultiset
#check @NewtonPolygon.slopeIndices
#check @NewtonPolygon.anchor
#check @NewtonPolygon.unitSlope
#check @NewtonPolygon.finiteSupport
#check @NewtonPolygon.isConvexSeq_zero_fun
#check @NewtonPolygon.unitSlope_zero_fun
#check @Order.succ_eq_add_one
#check @Nat.card_Ico
#check @Nat.cast_sub
#check @Nat.cast_lt
#check @Nat.cast_le
#check @Int.cast_natCast
#check @Rat.cast_div
#check @Rat.cast_intCast
#check @Rat.cast_natCast
#check @Int.castAddHom_apply
#check @Rat.castHom_apply
#check @AddMonoidHom.id_apply
#check @StrictMono.injective
#check @Int.cast_strictMono
#check @Rat.cast_strictMono
#check @IsUltrametricDist.isNonarchimedean_norm
#check @IsUltrametricDist.norm_add_le_max
#check @norm_add_le_max
#check @norm_mul
#check @norm_pow
#check @norm_inv
#check @norm_eq_zero
#check @norm_pos_iff
#check @norm_nonneg
#check @mul_pow
#check @Function.support
#check @Function.mem_support
#check @Set.finite_coe_iff
#check @Finsupp.uniqueEquiv
