import PhD.TauCeti.Code.NewtonPolygons.Coeff.Examples
set_option pp.proofs false
set_option linter.style.setOption false
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:85
#check @NormedField.NormedAddValuation.map_zero
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:87
#check @NormedField.NormedAddValuation.map_one
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:89
#check @NormedField.NormedAddValuation.map_mul
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:91
#check @NormedField.NormedAddValuation.map_pow
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:93
#check @NormedField.NormedAddValuation.map_inv
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:95
#check @NormedField.NormedAddValuation.min_le_map_add
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:97
#check @NormedField.NormedAddValuation.eq_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:99
#check @NormedField.NormedAddValuation.ne_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:101
#check @NormedField.NormedAddValuation.exists_eq_coe
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:105
#check @NormedField.NormedAddValuation.base_pos
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:107
#check @NormedField.NormedAddValuation.log_base_pos
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:110
#check @NormedField.NormedAddValuation.norm_eq_rpow
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:114
#check @NormedField.NormedAddValuation.embed_eq_neg_logb
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:118
#check @NormedField.NormedAddValuation.norm_add_le_max
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:121
#check @NormedField.NormedAddValuation.rpow_logb
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:131
#check @NormedField.NormedAddValuation.embedTop_top
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:133
#check @NormedField.NormedAddValuation.embedTop_coe
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:136
#check @NormedField.NormedAddValuation.embedTop_eq_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:138
#check @NormedField.NormedAddValuation.embedTop_strictMono
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:140
#check @NormedField.NormedAddValuation.embedTop_le_embedTop
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:142
#check @NormedField.NormedAddValuation.embedTop_add
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:145
#check @NormedField.NormedAddValuation.embedTop_apply_eq_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:147
#check @NormedField.NormedAddValuation.embedTop_map_one
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:156
#check @NormedField.NormedAddValuation.norm_mul_rpow_pow_eq_rpow
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:161
#check @NormedField.NormedAddValuation.norm_mul_rpow_pow_le_one_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:165
#check @NormedField.NormedAddValuation.norm_mul_rpow_pow_lt_one_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:169
#check @NormedField.NormedAddValuation.norm_mul_rpow_pow_eq_one_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:174
#check @NormedField.NormedAddValuation.norm_mul_rpow_pow_le_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:179
#check @NormedField.NormedAddValuation.norm_mul_rpow_pow_lt_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:184
#check @NormedField.NormedAddValuation.norm_mul_rpow_pow_eq_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:196
#check @NormedField.NormedAddValuation.scale_pos
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:199
#check @NormedField.NormedAddValuation.embed_eq_scale_mul_embed
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:204
#check @NormedField.NormedAddValuation.embedTop_apply_eq_map
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:218
#check @NormedField.NormedAddValuation.ofNormAddVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:232
#check @NormedField.NormedAddValuation.ofNormAddVal_apply_of_ne_zero
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:240
#check @NormedField.NormedAddValuation.ofNormAddValZ
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:258
#check @NormedField.NormedAddValuation.ofNormAddValZ_apply_isUniformizer
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:262
#check @NormedField.NormedAddValuation.scale_ofNormAddValZ_ofNormAddVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:272
#check @NormedField.NormedAddValuation.ofNormAddValQ
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/NormedAddValuation.lean:287
#check @NormedField.NormedAddValuation.ofNormAddValQ_self
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:46
#check @NewtonPolygon.isAdmissible_of_finite
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:54
#check @NewtonPolygon.shiftRight_add
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:57
#check @NewtonPolygon.shiftRight_of_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:60
#check @NewtonPolygon.shiftRight_of_lt
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:63
#check @NewtonPolygon.shiftRight_zero
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:65
#check @NewtonPolygon.unitSlope_shiftRight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:68
#check @NewtonPolygon.isConvexSeq_shiftRight_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:71
#check @NewtonPolygon.isNewtonPolygonOf_shiftRight_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:74
#check @NewtonPolygon.isAdmissible_shiftRight_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:78
#check @NewtonPolygon.newtonPolygon_shiftRight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:87
#check @NewtonPolygon.reflect_of_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:90
#check @NewtonPolygon.reflect_of_lt
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:92
#check @NewtonPolygon.reflect_reflect
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:96
#check @NewtonPolygon.unitSlope_reflect
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:99
#check @NewtonPolygon.IsConvexSeq.reflect
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:102
#check @NewtonPolygon.IsNewtonPolygonOf.reflect
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:107
#check @NewtonPolygon.newtonPolygon_reflect
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:119
#check @NewtonPolygon.scaleHeight_eq_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:121
#check @NewtonPolygon.finiteSupport_scaleHeight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:124
#check @NewtonPolygon.unitSlope_scaleHeight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:127
#check @NewtonPolygon.isConvexSeq_scaleHeight_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:130
#check @NewtonPolygon.isNewtonPolygonOf_scaleHeight_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:133
#check @NewtonPolygon.isAdmissible_scaleHeight_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:137
#check @NewtonPolygon.newtonPolygon_scaleHeight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:140
#check @NewtonPolygon.slopeMultiset_scaleHeight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:147
#check @NewtonPolygon.exists_isSegment_of_mem_slopeIndices
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Generic.lean:151
#check @NewtonPolygon.IsConvexSeq.unitSlope_eq_div_of_isSegment
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:61
#check @PowerSeries.coeffVal_eq_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:63
#check @PowerSeries.coeffVal_ne_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:65
#check @PowerSeries.coeffVal_eq_coe_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:68
#check @PowerSeries.finiteSupport_coeffVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:70
#check @PowerSeries.coeffVal_zero
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:72
#check @PowerSeries.coeffVal_zero_of_coeff_zero_eq_one
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:74
#check @PowerSeries.exists_coeffVal_ne_top
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:78
#check @PowerSeries.norm_coeff_mul_rpow_pow_le_one_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:81
#check @PowerSeries.norm_coeff_mul_rpow_pow_lt_one_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:84
#check @PowerSeries.norm_coeff_mul_rpow_pow_eq_one_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:91
#check @PowerSeries.hasGaussNorm_rpow_iff_exists_line
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:97
#check @PowerSeries.isAdmissible_coeffVal_iff_exists_hasGaussNorm
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:101
#check @PowerSeries.isRestricted_of_hasGaussNorm
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:105
#check @PowerSeries.isAdmissible_coeffVal_iff_exists_isRestricted
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:109
#check @PowerSeries.IsRestricted.isAdmissible_coeffVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:113
#check @PowerSeries.isVertical_coeffVal_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:129
#check @Polynomial.coeffVal_eq_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:131
#check @Polynomial.coeffVal_ne_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:133
#check @Polynomial.coeffVal_eq_coe_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:137
#check @Polynomial.finiteSupport_coeffVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:140
#check @Polynomial.finiteSupport_coeffVal_finite
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:143
#check @Polynomial.coeffVal_coe
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:146
#check @Polynomial.isAdmissible_coeffVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/CoeffVal.lean:149
#check @Polynomial.hasGaussNorm_coe
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:64
#check @PowerSeries.isNewtonPolygonOf_newtonPolygon
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:68
#check @PowerSeries.isNewtonPolygonOf_newtonPolygon_of_isRestricted
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:71
#check @PowerSeries.newtonPolygon_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:74
#check @PowerSeries.isConvexSeq_newtonPolygon
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:77
#check @PowerSeries.newtonPolygon_zero
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:80
#check @PowerSeries.newtonPolygon_zero_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:84
#check @PowerSeries.newtonPolygon_zero_of_coeff_zero_eq_one
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:90
#check @PowerSeries.exists_eq_embed_of_isVertex
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:97
#check @PowerSeries.exists_unitSlope_eq_div_of_isSegment
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:104
#check @PowerSeries.exists_int_unitSlope_eq_div_of_isSegment
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:112
#check @PowerSeries.slopesUnbounded_newtonPolygon_of_forall_isRestricted
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:116
#check @PowerSeries.tendsto_unitSlope_newtonPolygon
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:121
#check @PowerSeries.isRestricted_rpow_of_lt_unitSlope
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:127
#check @PowerSeries.unitSlope_le_of_not_isRestricted
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:133
#check @PowerSeries.coeffVal_C_mul
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:137
#check @PowerSeries.newtonPolygon_C_mul
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:141
#check @PowerSeries.coeff_zero_C_inv_mul
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:145
#check @PowerSeries.newtonPolygon_C_inv_mul
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:152
#check @PowerSeries.coeffVal_rescale
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:157
#check @PowerSeries.newtonPolygon_rescale
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:162
#check @PowerSeries.coeffVal_X_pow_mul
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:166
#check @PowerSeries.newtonPolygon_X_pow_mul
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:173
#check @PowerSeries.coeffVal_map
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:177
#check @PowerSeries.newtonPolygon_map
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:185
#check @PowerSeries.coeffVal_eq_scaleHeight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:188
#check @PowerSeries.isAdmissible_coeffVal_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/PowerSeries.lean:193
#check @PowerSeries.newtonPolygon_eq_scaleHeight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:57
#check @Polynomial.newtonPolygon_coe
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:61
#check @Polynomial.isNewtonPolygonOf_newtonPolygon
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:64
#check @Polynomial.newtonPolygon_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:66
#check @Polynomial.isConvexSeq_newtonPolygon
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:68
#check @Polynomial.newtonPolygon_zero
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:72
#check @Polynomial.newtonPolygon_eq_top_of_lt_natTrailingDegree
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:75
#check @Polynomial.newtonPolygon_eq_top_of_natDegree_lt
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:78
#check @Polynomial.newtonPolygon_ne_top
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:82
#check @Polynomial.newtonPolygon_eq_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:86
#check @Polynomial.newtonPolygon_natTrailingDegree
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:90
#check @Polynomial.newtonPolygon_natDegree
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:93
#check @Polynomial.anchor_newtonPolygon
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:96
#check @Polynomial.isVertex_natTrailingDegree
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:100
#check @Polynomial.isVertex_natDegree
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:103
#check @Polynomial.slopeIndices_newtonPolygon
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:106
#check @Polynomial.slopeIndices_newtonPolygon_finite
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:109
#check @Polynomial.slopesUnbounded_newtonPolygon
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:112
#check @Polynomial.newtonPolygon_zero_of_coeff_zero_eq_one
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:124
#check @Polynomial.card_newtonSlopes
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:126
#check @Polynomial.count_newtonSlopes
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:132
#check @Polynomial.exists_isSegment_of_mem_slopeIndices
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:137
#check @Polynomial.exists_unitSlope_eq_div
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:143
#check @Polynomial.exists_int_unitSlope_eq_div
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:150
#check @Polynomial.coeffVal_reverse
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:153
#check @Polynomial.newtonPolygon_reverse
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:159
#check @Polynomial.coe_comp_C_mul_X
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:164
#check @Polynomial.newtonPolygon_comp_C_mul_X
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:169
#check @Polynomial.newtonPolygon_X_pow_mul
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:172
#check @Polynomial.newtonPolygon_C_mul
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:176
#check @Polynomial.newtonPolygon_C_inv_mul
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:183
#check @Polynomial.newtonPolygon_map
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:190
#check @Polynomial.newtonPolygon_eq_scaleHeight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Polynomial.lean:194
#check @Polynomial.newtonSlopes_eq_map
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Extension.lean:40
#check @NormedField.NormedAddValuation.ofNormAddVal_algebraMap
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Extension.lean:43
#check @NormedField.NormedAddValuation.ofNormAddVal_embed_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Extension.lean:51
#check @NormedField.NormedAddValuation.ofNormAddValQ_algebraMap
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Extension.lean:54
#check @NormedField.NormedAddValuation.ofNormAddValQ_embed_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Extension.lean:64
#check @Polynomial.newtonPolygon_ofNormAddVal_map
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Extension.lean:69
#check @PowerSeries.newtonPolygon_ofNormAddVal_map
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Extension.lean:79
#check @Polynomial.newtonPolygon_ofNormAddValQ_map
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Extension.lean:85
#check @PowerSeries.newtonPolygon_ofNormAddValQ_map
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:52
#check @NewtonPolygon.toEReal_ne_bot
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:54
#check @NewtonPolygon.toEReal_le_toEReal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:56
#check @NewtonPolygon.toEReal_lt_toEReal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:58
#check @NewtonPolygon.toEReal_injective
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:60
#check @NewtonPolygon.toEReal_eq_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:62
#check @NewtonPolygon.toEReal_of_ne_top
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:72
#check @NewtonPolygon.supportValue_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:75
#check @NewtonPolygon.le_supportValue_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:80
#check @NewtonPolygon.coe_le_supportValue_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:85
#check @NewtonPolygon.supportValue_ne_bot_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:89
#check @NewtonPolygon.supportValue_eq_top_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:91
#check @NewtonPolygon.supportValue_mono
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:95
#check @NewtonPolygon.isAdmissible_iff_exists_supportValue_ne_bot
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:99
#check @NewtonPolygon.supportValue_newtonPolygon
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:106
#check @NewtonPolygon.supportValue_eq_of_line_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:111
#check @NewtonPolygon.IsConvexSeq.supportValue_eq_of_unitSlope
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:117
#check @NewtonPolygon.IsConvexSeq.supportValue_eq_of_unitSlope_le_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:122
#check @NewtonPolygon.IsConvexSeq.supportValue_eq_faceRight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:127
#check @NewtonPolygon.IsConvexSeq.supportValue_eq_faceLeft
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:131
#check @NewtonPolygon.IsConvexSeq.supportValue_ne_bot
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:135
#check @NewtonPolygon.IsNewtonPolygonOf.exists_eq_supportValue_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:143
#check @NewtonPolygon.convex_setOf_supportValue_ne_bot
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:146
#check @NewtonPolygon.concaveOn_toReal_supportValue
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/SupportValue.lean:151
#check @NewtonPolygon.iSup_supportValue_add
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:52
#check @Polynomial.gaussNorm_toAbsoluteValue
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:56
#check @Polynomial.exists_gaussNorm_coe_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:66
#check @PowerSeries.norm_coeff_mul_rpow_pow_eq_rpow
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:72
#check @PowerSeries.hasGaussNorm_rpow_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:77
#check @PowerSeries.hasGaussNorm_iff_supportValue_ne_bot
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:84
#check @PowerSeries.gaussNorm_rpow_eq_of_supportValue_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:88
#check @PowerSeries.gaussNorm_rpow_eq_rpow_neg_toReal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:92
#check @PowerSeries.supportValue_coeffVal_eq_neg_logb
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:97
#check @PowerSeries.supportValue_newtonPolygon_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:102
#check @PowerSeries.gaussNorm_rpow_eq_norm_coeff_faceRight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:109
#check @PowerSeries.gaussNorm_rpow_eq_norm_coeff_faceLeft
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:119
#check @PowerSeries.exists_gaussNorm_rpow_eq_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:128
#check @PowerSeries.concaveOn_neg_logb_gaussNorm
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:134
#check @PowerSeries.neg_logb_gaussNorm_eq_of_unitSlope_le_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:142
#check @PowerSeries.toEReal_newtonPolygon_eq_iSup
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:153
#check @Polynomial.supportValue_coeffVal_ne_bot
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/GaussNorm.lean:158
#check @Polynomial.gaussNorm_rpow_eq_norm_coeff_faceRight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:58
#check @PowerSeries.IsPure.le_coeffVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:63
#check @PowerSeries.IsPure.norm_coeff_mul_rpow_pow_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:67
#check @PowerSeries.IsPure.gaussNorm_rpow_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:72
#check @PowerSeries.isPure_iff_of_infinite
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:80
#check @PowerSeries.HasFirstBreak.le_coeffVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:85
#check @PowerSeries.HasFirstBreak.coeffVal_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:91
#check @PowerSeries.HasFirstBreak.lt_coeffVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:95
#check @PowerSeries.HasFirstBreak.coeff_ne_zero
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:99
#check @PowerSeries.HasFirstBreak.norm_coeff_mul_rpow_pow_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:104
#check @PowerSeries.HasFirstBreak.norm_coeff_mul_rpow_pow_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:109
#check @PowerSeries.HasFirstBreak.norm_coeff_mul_rpow_pow_lt
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:114
#check @PowerSeries.HasFirstBreak.gaussNorm_rpow_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:131
#check @Polynomial.isPure_coe_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:133
#check @Polynomial.hasFirstBreak_coe_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:137
#check @Polynomial.IsPure.le_coeffVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:140
#check @Polynomial.IsPure.norm_coeff_mul_rpow_pow_le
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:144
#check @Polynomial.IsPure.norm_coeff_natDegree_mul_rpow_pow_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:149
#check @Polynomial.isPure_of_bounds
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:154
#check @Polynomial.isPure_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:159
#check @Polynomial.isPure_iff_gaussNorm
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Pure.lean:167
#check @Polynomial.isPure_iff_hasFirstBreak
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Distinguished.lean:45
#check @PowerSeries.isMulDistinguished_iff
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Distinguished.lean:52
#check @PowerSeries.HasFirstBreak.isMulDistinguished
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Distinguished.lean:56
#check @PowerSeries.isMulDistinguished_rpow_iff_faceRight_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Distinguished.lean:68
#check @Polynomial.HasFirstBreak.isMulDistinguished
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Distinguished.lean:72
#check @Polynomial.IsPure.isMulDistinguished
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Distinguished.lean:77
#check @Polynomial.isMulDistinguished_rpow_iff_faceRight_eq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Padic.lean:33
#check @Padic.normedAddValuation_apply
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Padic.lean:36
#check @Padic.normedAddValuation_embed
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Padic.lean:39
#check @Padic.normedAddValuation_embed_apply
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Padic.lean:41
#check @Padic.normedAddValuation_base
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Padic.lean:44
#check @Padic.normedAddValuation_natCast_prime
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Padic.lean:47
#check @Padic.scale_normedAddValuation_ofNormAddVal
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:41
#check @Polynomial.isPure_one_sub_X
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:44
#check @Polynomial.newtonSlopes_one_sub_X
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:47
#check @Polynomial.isPure_one_sub_p_mul_X
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:50
#check @Polynomial.newtonSlopes_one_sub_p_mul_X
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:55
#check @Polynomial.newtonSlopes_one_add_p_mul_X_add_p_cube_mul_X_sq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:59
#check @Polynomial.newtonPolygon_one_add_p_mul_X_add_p_sq_mul_X_sq_one
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:64
#check @Polynomial.not_isVertex_one_add_p_mul_X_add_p_sq_mul_X_sq_one
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:68
#check @Polynomial.newtonSlopes_one_add_p_mul_X_add_p_sq_mul_X_sq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:74
#check @Polynomial.isPure_one_add_three_pow_mul_X_sq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:79
#check @Polynomial.newtonSlopes_one_add_three_pow_mul_X_sq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:86
#check @Polynomial.newtonPolygon_cyclotomic
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:90
#check @Polynomial.isPure_cyclotomic
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:93
#check @Polynomial.coeff_cyclotomic_comp_X_add_one
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:97
#check @Polynomial.isPure_C_inv_mul_cyclotomic_comp_X_add_one
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:103
#check @Polynomial.newtonPolygon_ofNormAddVal_eq_scaleHeight
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:114
#check @PowerSeries.isPure_mk_p_pow
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:119
#check @PowerSeries.isRestricted_mk_p_pow_sq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:123
#check @PowerSeries.coeffVal_mk_p_pow_sq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:128
#check @PowerSeries.newtonPolygon_mk_p_pow_sq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:133
#check @PowerSeries.unitSlope_newtonPolygon_mk_p_pow_sq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:137
#check @PowerSeries.slopesUnbounded_newtonPolygon_mk_p_pow_sq
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:143
#check @PowerSeries.hasGaussNorm_one_mk_ite
-- PhD/TauCeti/Code/NewtonPolygons/Coeff/Examples.lean:147
#check @PowerSeries.not_isRestricted_one_mk_ite
