/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import Mathlib.Algebra.Polynomial.AlgebraMap
import Mathlib.Algebra.Polynomial.Div
import Mathlib.Algebra.Polynomial.Monic
import Mathlib.Analysis.Normed.Field.Basic
import Mathlib.Analysis.Normed.Group.Ultra
import Mathlib.Analysis.Normed.Ring.Ultra
import Mathlib.Order.Filter.Cofinite

/-!
# Bald subrings of a nonarchimedean field

A subring `S` of the unit ball of a normed field is *bald* if the norms of its elements of norm
less than one are bounded away from one, and a *B-ring* if its elements of norm one are invertible
in `S`. The unit ball of a discretely valued field is bald; the unit ball of a densely valued field
is not. Bosch's observation is that the subring generated by a zero sequence is always bald, which
is what makes approximation arguments converge over an arbitrary complete nonarchimedean field.

Roadmap: `PhD/TauCeti/Roadmaps/RigidAnalyticGeometry/README.md`, §0.3.1 (Bosch 1.3/1–3). Tau Ceti
home: `TauCeti/Analysis/Normed/Field/Bald.lean`.

## Main definitions

* `Subring.IsBRing S` — the elements of `S` have norm at most one, and those of norm one are
  invertible in `S` (Bosch 1.3/2 (i)).
* `Subring.IsBald S` — the elements of `S` have norm at most one, and those of norm less than one
  have norm at most some `ε < 1` (Bosch 1.3/2 (ii)).
* `Subring.unitLocalization S` — the localisation of `S` at its elements of norm one.

## Main results

* `Subring.isBald_closure_range` — the subring generated by a null family of the unit ball is bald
  (Bosch 1.3/3).
-/

open Filter Topology
open scoped Polynomial

namespace Subring

variable {K : Type*} [NormedField K]

/-- A subring of a normed field is a **B-ring** if its elements have norm at most one and those of
norm one are invertible in it. Source: Bosch 1.3/2 (i). -/
structure IsBRing (S : Subring K) : Prop where
  norm_le_one : ∀ a ∈ S, ‖a‖ ≤ 1
  inv_mem : ∀ a ∈ S, ‖a‖ = 1 → a⁻¹ ∈ S

/-- A subring of a normed field is **bald** if its elements have norm at most one and the norms of
its elements of norm less than one are bounded away from one. Source: Bosch 1.3/2 (ii). -/
structure IsBald (S : Subring K) : Prop where
  norm_le_one : ∀ a ∈ S, ‖a‖ ≤ 1
  exists_norm_le : ∃ ε : ℝ, ε < 1 ∧ ∀ a ∈ S, ‖a‖ < 1 → ‖a‖ ≤ ε

/-- A subring of a bald subring is bald. -/
theorem IsBald.mono {S S' : Subring K} (h : S ≤ S') (hS' : S'.IsBald) : S.IsBald :=
  ⟨fun a ha ↦ hS'.norm_le_one a (h ha),
    hS'.exists_norm_le.imp fun _ hε ↦ ⟨hε.1, fun a ha ↦ hε.2 a (h ha)⟩⟩

/-- The localisation of a subring at its elements of norm one, inside the field. Source: Bosch 1.3
("we may localize `S` by all elements of value `1` and thereby assume that `S` is a B-ring"). -/
def unitLocalization (S : Subring K) : Subring K :=
  closure ((S : Set K) ∪ {x | ∃ u ∈ S, ‖u‖ = 1 ∧ x = u⁻¹})

theorem le_unitLocalization (S : Subring K) : S ≤ S.unitLocalization :=
  fun _ hx ↦ subset_closure (Or.inl hx)

/-- The elements of the localisation are the fractions with denominator of norm one. -/
theorem mem_unitLocalization_iff {S : Subring K} {x : K} :
    x ∈ S.unitLocalization ↔ ∃ s ∈ S, ∃ u ∈ S, ‖u‖ = 1 ∧ x = s / u := by
  have hne {u : K} (hu : ‖u‖ = 1) : u ≠ 0 := norm_ne_zero_iff.1 (by rw [hu]; exact one_ne_zero)
  constructor
  · intro hx
    induction hx using Subring.closure_induction with
    | mem x hx =>
      rcases hx with hx | ⟨u, hu, hu1, rfl⟩
      · exact ⟨x, hx, 1, S.one_mem, norm_one, (div_one x).symm⟩
      · exact ⟨1, S.one_mem, u, hu, hu1, (one_div u).symm⟩
    | zero => exact ⟨0, S.zero_mem, 1, S.one_mem, norm_one, (zero_div 1).symm⟩
    | one => exact ⟨1, S.one_mem, 1, S.one_mem, norm_one, (div_one 1).symm⟩
    | add x y _ _ hx hy =>
      obtain ⟨s₁, hs₁, u₁, hu₁, hu₁1, rfl⟩ := hx
      obtain ⟨s₂, hs₂, u₂, hu₂, hu₂1, rfl⟩ := hy
      exact ⟨s₁ * u₂ + u₁ * s₂, S.add_mem (S.mul_mem hs₁ hu₂) (S.mul_mem hu₁ hs₂), u₁ * u₂,
        S.mul_mem hu₁ hu₂, by rw [norm_mul, hu₁1, hu₂1, one_mul],
        div_add_div _ _ (hne hu₁1) (hne hu₂1)⟩
    | neg x _ hx =>
      obtain ⟨s, hs, u, hu, hu1, rfl⟩ := hx
      exact ⟨-s, S.neg_mem hs, u, hu, hu1, (neg_div u s).symm⟩
    | mul x y _ _ hx hy =>
      obtain ⟨s₁, hs₁, u₁, hu₁, hu₁1, rfl⟩ := hx
      obtain ⟨s₂, hs₂, u₂, hu₂, hu₂1, rfl⟩ := hy
      exact ⟨s₁ * s₂, S.mul_mem hs₁ hs₂, u₁ * u₂, S.mul_mem hu₁ hu₂,
        by rw [norm_mul, hu₁1, hu₂1, one_mul], div_mul_div_comm _ _ _ _⟩
  · rintro ⟨s, hs, u, hu, hu1, rfl⟩
    rw [div_eq_mul_inv]
    exact mul_mem (subset_closure (Or.inl hs)) (subset_closure (Or.inr ⟨u, hu, hu1, rfl⟩))

/-- The localisation of a bald subring at its elements of norm one is bald. -/
theorem IsBald.unitLocalization {S : Subring K} (hS : S.IsBald) : S.unitLocalization.IsBald := by
  have hnorm {x : K} (hx : x ∈ S.unitLocalization) : ∃ s ∈ S, ‖x‖ = ‖s‖ := by
    obtain ⟨s, hs, u, hu, hu1, rfl⟩ := mem_unitLocalization_iff.1 hx
    exact ⟨s, hs, by rw [norm_div, hu1, div_one]⟩
  obtain ⟨ε, hε, hε'⟩ := hS.exists_norm_le
  refine ⟨fun a ha ↦ ?_, ⟨ε, hε, fun a ha ha1 ↦ ?_⟩⟩
  · obtain ⟨s, hs, h⟩ := hnorm ha
    rw [h]
    exact hS.norm_le_one s hs
  · obtain ⟨s, hs, h⟩ := hnorm ha
    rw [h] at ha1 ⊢
    exact hε' s hs ha1

/-- The localisation at the elements of norm one is a B-ring. -/
theorem isBRing_unitLocalization {S : Subring K} (hS : ∀ a ∈ S, ‖a‖ ≤ 1) :
    S.unitLocalization.IsBRing := by
  refine ⟨fun a ha ↦ ?_, fun a ha ha1 ↦ ?_⟩
  · obtain ⟨s, hs, u, hu, hu1, rfl⟩ := mem_unitLocalization_iff.1 ha
    rw [norm_div, hu1, div_one]
    exact hS s hs
  · obtain ⟨s, hs, u, hu, hu1, rfl⟩ := mem_unitLocalization_iff.1 ha
    have hs1 : ‖s‖ = 1 := by rwa [norm_div, hu1, div_one] at ha1
    rw [inv_div]
    exact mem_unitLocalization_iff.2 ⟨u, hu, s, hs, hs1, rfl⟩

variable [IsUltrametricDist K]

/-- The prime subring of a nonarchimedean field is bald. Source: Bosch 1.3/3 ("The smallest subring
`S ⊂ R` equals either `ℤ/pℤ` for some prime `p`, or `ℤ`. It is bald"). -/
theorem isBald_bot : (⊥ : Subring K).IsBald := by
  classical
  have hnat (z : ℤ) : ‖(z : K)‖ = ‖((z.natAbs : ℕ) : K)‖ := by
    rw [← Int.cast_natCast, Int.natCast_natAbs]
    rcases abs_choice z with h | h <;> rw [h]
    rw [Int.cast_neg, norm_neg]
  refine ⟨fun a ha ↦ ?_, ?_⟩
  · obtain ⟨z, rfl⟩ := Subring.mem_bot.1 ha
    exact IsUltrametricDist.norm_intCast_le_one K z
  by_cases hex : ∃ g : ℕ, 0 < g ∧ ‖(g : K)‖ < 1
  · have hg : 0 < Nat.find hex ∧ ‖(Nat.find hex : K)‖ < 1 := Nat.find_spec hex
    refine ⟨‖(Nat.find hex : K)‖, hg.2, fun a ha ha1 ↦ ?_⟩
    obtain ⟨z, rfl⟩ := Subring.mem_bot.1 ha
    rw [hnat] at ha1 ⊢
    have hmod : z.natAbs % Nat.find hex = 0 := by
      by_contra hne
      have hlt : z.natAbs % Nat.find hex < Nat.find hex := Nat.mod_lt _ hg.1
      have hnorm : ‖((z.natAbs % Nat.find hex : ℕ) : K)‖ < 1 := by
        have hcast := congrArg (Nat.cast : ℕ → K) (Nat.div_add_mod z.natAbs (Nat.find hex))
        rw [Nat.cast_add, Nat.cast_mul] at hcast
        have heq : ((z.natAbs % Nat.find hex : ℕ) : K) =
            (z.natAbs : K) + -((Nat.find hex : K) * ((z.natAbs / Nat.find hex : ℕ) : K)) := by
          rw [← hcast]
          ring
        rw [heq]
        refine (IsUltrametricDist.norm_add_le_max _ _).trans_lt (max_lt ha1 ?_)
        rw [norm_neg, norm_mul]
        exact (mul_le_of_le_one_right (norm_nonneg _)
          (IsUltrametricDist.norm_natCast_le_one K _)).trans_lt hg.2
      exact Nat.find_min hex hlt ⟨Nat.pos_of_ne_zero hne, hnorm⟩
    have hm : (z.natAbs : K) = (Nat.find hex : K) * ((z.natAbs / Nat.find hex : ℕ) : K) := by
      have h := Nat.div_add_mod z.natAbs (Nat.find hex)
      rw [hmod, add_zero] at h
      rw [← Nat.cast_mul, h]
    rw [hm, norm_mul]
    exact mul_le_of_le_one_right (norm_nonneg _) (IsUltrametricDist.norm_natCast_le_one K _)
  · simp only [not_exists, not_and, not_lt] at hex
    refine ⟨0, zero_lt_one, fun a ha ha1 ↦ ?_⟩
    obtain ⟨z, rfl⟩ := Subring.mem_bot.1 ha
    rw [hnat] at ha1 ⊢
    rcases Nat.eq_zero_or_pos z.natAbs with h0 | hpos
    · rw [h0, Nat.cast_zero, norm_zero]
    · exact absurd ha1 (not_lt.2 (hex _ hpos))

/-- Adjoining elements of norm at most `ε < 1` to a bald subring gives a bald subring.
Source: Bosch 1.3/3 ("If there is an `ε ∈ R` such that `|aₙ| ≤ ε < 1` for all `n`, we see for
trivial reasons that `S[a₀, a₁, …]` is bald"). -/
theorem IsBald.closure_union_of_norm_le {S : Subring K} (hS : S.IsBald) {T : Set K} {ε : ℝ}
    (hε : ε < 1) (hT : ∀ x ∈ T, ‖x‖ ≤ ε) : (closure ((S : Set K) ∪ T)).IsBald := by
  obtain ⟨εS, hεS, hS'⟩ := hS.exists_norm_le
  have hδ1 : max ε 0 < 1 := max_lt hε zero_lt_one
  have hδ0 : 0 ≤ max ε 0 := le_max_right _ _
  have h0 : ‖(0 : K)‖ ≤ max ε 0 := by rw [norm_zero]; exact hδ0
  have key : ∀ x ∈ closure ((S : Set K) ∪ T), ∃ s ∈ S, ∃ z : K, ‖z‖ ≤ max ε 0 ∧ x = s + z := by
    intro x hx
    induction hx using Subring.closure_induction with
    | mem x hx =>
      rcases hx with hx | hx
      · exact ⟨x, hx, 0, h0, (add_zero x).symm⟩
      · exact ⟨0, S.zero_mem, x, (hT x hx).trans (le_max_left _ _), (zero_add x).symm⟩
    | zero => exact ⟨0, S.zero_mem, 0, h0, (add_zero 0).symm⟩
    | one => exact ⟨1, S.one_mem, 0, h0, (add_zero 1).symm⟩
    | add x y _ _ hx hy =>
      obtain ⟨s₁, hs₁, z₁, hz₁, rfl⟩ := hx
      obtain ⟨s₂, hs₂, z₂, hz₂, rfl⟩ := hy
      exact ⟨s₁ + s₂, S.add_mem hs₁ hs₂, z₁ + z₂,
        (IsUltrametricDist.norm_add_le_max _ _).trans (max_le hz₁ hz₂), by ring⟩
    | neg x _ hx =>
      obtain ⟨s, hs, z, hz, rfl⟩ := hx
      exact ⟨-s, S.neg_mem hs, -z, by rwa [norm_neg], by ring⟩
    | mul x y _ _ hx hy =>
      obtain ⟨s₁, hs₁, z₁, hz₁, rfl⟩ := hx
      obtain ⟨s₂, hs₂, z₂, hz₂, rfl⟩ := hy
      refine ⟨s₁ * s₂, S.mul_mem hs₁ hs₂, s₁ * z₂ + z₁ * s₂ + z₁ * z₂, ?_, by ring⟩
      have h1 := hS.norm_le_one s₁ hs₁
      have h2 := hS.norm_le_one s₂ hs₂
      refine (IsUltrametricDist.norm_add_le_max _ _).trans (max_le
        ((IsUltrametricDist.norm_add_le_max _ _).trans (max_le ?_ ?_)) ?_)
      · rw [norm_mul]
        exact (mul_le_of_le_one_left (norm_nonneg _) h1).trans hz₂
      · rw [norm_mul]
        exact (mul_le_of_le_one_right (norm_nonneg _) h2).trans hz₁
      · rw [norm_mul]
        exact (mul_le_of_le_one_right (norm_nonneg _) (hz₂.trans hδ1.le)).trans hz₁
  refine ⟨fun a ha ↦ ?_, ⟨max εS (max ε 0), max_lt hεS hδ1, fun a ha ha1 ↦ ?_⟩⟩
  · obtain ⟨s, hs, z, hz, rfl⟩ := key a ha
    exact (IsUltrametricDist.norm_add_le_max _ _).trans
      (max_le (hS.norm_le_one s hs) (hz.trans hδ1.le))
  · obtain ⟨s, hs, z, hz, rfl⟩ := key a ha
    have hs1 : ‖s‖ < 1 := by
      by_contra hcon
      have hs1 : ‖s‖ = 1 := le_antisymm (hS.norm_le_one s hs) (not_lt.1 hcon)
      have hne : ‖s‖ ≠ ‖z‖ := by
        rw [hs1]
        exact (hz.trans_lt hδ1).ne'
      rw [IsUltrametricDist.norm_add_eq_max_of_norm_ne_norm hne, hs1] at ha1
      exact lt_irrefl _ ((le_max_left _ _).trans_lt ha1)
    exact (IsUltrametricDist.norm_add_le_max _ _).trans (max_le_max (hS' s hs hs1) hz)

/-- The value of a polynomial over `S` at an element of the unit ball is bounded by any common
bound of the coefficients. -/
private lemma norm_aeval_le {S : Subring K} {a : K} (ha : ‖a‖ ≤ 1) {q : Polynomial S} {C : ℝ}
    (hC : 0 ≤ C) (hq : ∀ i, ‖(q.coeff i : K)‖ ≤ C) : ‖Polynomial.aeval a q‖ ≤ C := by
  rw [Polynomial.aeval_eq_sum_range]
  refine IsUltrametricDist.norm_sum_le_of_forall_le_of_nonneg hC fun i _ ↦ ?_
  rw [Subring.smul_def, smul_eq_mul, norm_mul, norm_pow]
  exact (mul_le_of_le_one_right (norm_nonneg _) (pow_le_one₀ (norm_nonneg _) ha)).trans (hq i)

/-- A polynomial over `S` all of whose coefficients have norm less than one takes a value of norm
less than one at every element of the unit ball. -/
private lemma norm_aeval_lt_one {S : Subring K} {a : K} (ha : ‖a‖ ≤ 1) {q : Polynomial S}
    (hq : ∀ i, ‖(q.coeff i : K)‖ < 1) : ‖Polynomial.aeval a q‖ < 1 := by
  rw [Polynomial.aeval_eq_sum_range]
  obtain ⟨i, -, hi⟩ := IsUltrametricDist.exists_norm_finsetSum_le_of_nonempty
    Finset.nonempty_range_add_one fun i ↦ q.coeff i • a ^ i
  refine hi.trans_lt ?_
  rw [Subring.smul_def, smul_eq_mul, norm_mul, norm_pow]
  exact (mul_le_of_le_one_right (norm_nonneg _) (pow_le_one₀ (norm_nonneg _) ha)).trans_lt (hq i)

/-- In a B-ring `S`, a polynomial with a coefficient of norm one whose value at an element `a` of
norm one is small gives a monic polynomial of no larger degree with the same property. -/
theorem IsBRing.exists_monic_norm_aeval_lt_one {S : Subring K} (hS : S.IsBRing) {a : K}
    (ha : ‖a‖ = 1) {p : Polynomial S} (hp : ‖Polynomial.aeval a p‖ < 1)
    (hc : ∃ i, ‖(p.coeff i : K)‖ = 1) :
    ∃ g : Polynomial S, g.Monic ∧ g.natDegree ≤ p.natDegree ∧ ‖Polynomial.aeval a g‖ < 1 := by
  classical
  have hDne : ((Finset.range (p.natDegree + 1)).filter
      fun i ↦ ‖(p.coeff i : K)‖ = 1).Nonempty := by
    obtain ⟨i, hi⟩ := hc
    refine ⟨i, Finset.mem_filter.2 ⟨Finset.mem_range.2
      (Nat.lt_succ_of_le (Polynomial.le_natDegree_of_ne_zero fun h0 ↦ ?_)), hi⟩⟩
    rw [h0, ZeroMemClass.coe_zero, norm_zero] at hi
    exact zero_ne_one hi
  obtain ⟨d, hdD, hdmax⟩ := Finset.exists_max_image _ id hDne
  obtain ⟨hdr, hd1⟩ := Finset.mem_filter.1 hdD
  have hdle : d ≤ p.natDegree := Nat.lt_succ_iff.1 (Finset.mem_range.1 hdr)
  let low : Polynomial S :=
    ∑ i ∈ Finset.range (d + 1), Polynomial.C (p.coeff i) * Polynomial.X ^ i
  have hlow (i : ℕ) : low.coeff i = if i ≤ d then p.coeff i else 0 := by
    simp only [low, Polynomial.finsetSum_coeff, Polynomial.coeff_C_mul_X_pow, Finset.sum_ite_eq,
      Finset.mem_range, Nat.lt_succ_iff]
  have hhigh (i : ℕ) : ‖((p - low).coeff i : K)‖ < 1 := by
    rw [Polynomial.coeff_sub, hlow]
    split_ifs with hi
    · simp
    · rw [sub_zero]
      by_cases hip : i ≤ p.natDegree
      · refine lt_of_le_of_ne (hS.norm_le_one _ (p.coeff i).2) fun h1 ↦ hi ?_
        exact hdmax i (Finset.mem_filter.2 ⟨Finset.mem_range.2 (Nat.lt_succ_of_le hip), h1⟩)
      · rw [Polynomial.coeff_eq_zero_of_natDegree_lt (not_le.1 hip)]
        simp
  have hlowlt : ‖Polynomial.aeval a low‖ < 1 := by
    have h1 := norm_aeval_lt_one ha.le hhigh
    have heq : Polynomial.aeval a low =
        Polynomial.aeval a p + -Polynomial.aeval a (p - low) := by
      rw [map_sub]
      ring
    rw [heq]
    exact (IsUltrametricDist.norm_add_le_max _ _).trans_lt (max_lt hp (by rwa [norm_neg]))
  have hcd : (p.coeff d : K) ≠ 0 := fun h0 ↦ by
    rw [h0, norm_zero] at hd1
    exact zero_ne_one hd1
  let u : S := ⟨(p.coeff d : K)⁻¹, hS.inv_mem _ (p.coeff d).2 hd1⟩
  have hdeg : low.natDegree ≤ d := Polynomial.natDegree_le_iff_coeff_eq_zero.2 fun i hi ↦ by
    rw [hlow, if_neg (not_le.2 hi)]
  refine ⟨Polynomial.C u * low, ?_, (Polynomial.natDegree_C_mul_le _ _).trans (hdeg.trans hdle),
    ?_⟩
  · refine Polynomial.monic_of_natDegree_le_of_coeff_eq_one d
      ((Polynomial.natDegree_C_mul_le _ _).trans hdeg) ?_
    rw [Polynomial.coeff_C_mul, hlow, if_pos le_rfl]
    exact Subtype.ext (inv_mul_cancel₀ hcd)
  · rw [map_mul, Polynomial.aeval_C, norm_mul]
    have hu : ‖algebraMap S K u‖ = 1 := by
      change ‖(p.coeff d : K)⁻¹‖ = 1
      rw [norm_inv, hd1, inv_one]
    rw [hu, one_mul]
    exact hlowlt

/-- Adjoining an element of norm one to a bald B-ring gives a bald subring. Source: Bosch 1.3/3
(the transcendental and the algebraic case). -/
theorem IsBRing.isBald_closure_insert {S : Subring K} (hB : S.IsBRing) (hS : S.IsBald) {a : K}
    (ha : ‖a‖ = 1) : (closure (insert a (S : Set K))).IsBald := by
  classical
  have hrep : ∀ x ∈ closure (insert a (S : Set K)), ∃ p : Polynomial S,
      Polynomial.aeval a p = x := by
    intro x hx
    induction hx using Subring.closure_induction with
    | mem x hx =>
      rcases hx with rfl | hx
      · exact ⟨Polynomial.X, Polynomial.aeval_X _⟩
      · exact ⟨Polynomial.C ⟨x, hx⟩, by rw [Polynomial.aeval_C]; rfl⟩
    | zero => exact ⟨0, map_zero _⟩
    | one => exact ⟨1, map_one _⟩
    | add x y _ _ hx hy =>
      obtain ⟨p, rfl⟩ := hx
      obtain ⟨q, rfl⟩ := hy
      exact ⟨p + q, map_add _ _ _⟩
    | neg x _ hx =>
      obtain ⟨p, rfl⟩ := hx
      exact ⟨-p, map_neg _ _⟩
    | mul x y _ _ hx hy =>
      obtain ⟨p, rfl⟩ := hx
      obtain ⟨q, rfl⟩ := hy
      exact ⟨p * q, map_mul _ _ _⟩
  have hle1 (p : Polynomial S) : ‖Polynomial.aeval a p‖ ≤ 1 :=
    norm_aeval_le ha.le zero_le_one fun i ↦ hB.norm_le_one _ (p.coeff i).2
  obtain ⟨εS, hεS, hS'⟩ := hS.exists_norm_le
  have hsmall (r : Polynomial S) (hr : ∀ i, ‖(r.coeff i : K)‖ ≠ 1) :
      ‖Polynomial.aeval a r‖ ≤ max εS 0 :=
    norm_aeval_le ha.le (le_max_right _ _) fun i ↦
      (hS' _ (r.coeff i).2 (lt_of_le_of_ne (hS.norm_le_one _ (r.coeff i).2) (hr i))).trans
        (le_max_left _ _)
  by_cases hex : ∃ g : Polynomial S, g.Monic ∧ ‖Polynomial.aeval a g‖ < 1
  · have hexn : ∃ n, ∃ g : Polynomial S, g.Monic ∧ ‖Polynomial.aeval a g‖ < 1 ∧
        g.natDegree = n := by
      obtain ⟨g, hg⟩ := hex
      exact ⟨g.natDegree, g, hg.1, hg.2, rfl⟩
    obtain ⟨g, hgm, hgl, hgd⟩ := Nat.find_spec hexn
    have hgmin (g' : Polynomial S) (hm : g'.Monic) (hl : ‖Polynomial.aeval a g'‖ < 1) :
        g.natDegree ≤ g'.natDegree := by
      rw [hgd]
      exact Nat.find_min' hexn ⟨g', hm, hl, rfl⟩
    have hg1 : g ≠ 1 := fun h1 ↦ by
      rw [h1, map_one, norm_one] at hgl
      exact lt_irrefl _ hgl
    refine ⟨fun x hx ↦ ?_, ⟨max ‖Polynomial.aeval a g‖ (max εS 0),
      max_lt hgl (max_lt hεS zero_lt_one), fun x hx hx1 ↦ ?_⟩⟩
    · obtain ⟨p, rfl⟩ := hrep x hx
      exact hle1 p
    · obtain ⟨f, rfl⟩ := hrep x hx
      have hdecomp : Polynomial.aeval a f =
          Polynomial.aeval a g * Polynomial.aeval a (f /ₘ g) + Polynomial.aeval a (f %ₘ g) := by
        have h := congrArg (Polynomial.aeval a) (Polynomial.modByMonic_add_div f g)
        rw [map_add, map_mul] at h
        rw [← h, add_comm]
      have hr_lt : ‖Polynomial.aeval a (f %ₘ g)‖ < 1 := by
        have heq : Polynomial.aeval a (f %ₘ g) =
            Polynomial.aeval a f + -(Polynomial.aeval a g * Polynomial.aeval a (f /ₘ g)) := by
          rw [hdecomp]
          ring
        rw [heq]
        refine (IsUltrametricDist.norm_add_le_max _ _).trans_lt (max_lt hx1 ?_)
        rw [norm_neg, norm_mul]
        exact (mul_le_of_le_one_right (norm_nonneg _) (hle1 _)).trans_lt hgl
      have hr_small : ‖Polynomial.aeval a (f %ₘ g)‖ ≤ max εS 0 := by
        refine hsmall _ fun i hi ↦ ?_
        obtain ⟨g', hg'm, hg'd, hg'l⟩ := hB.exists_monic_norm_aeval_lt_one ha hr_lt ⟨i, hi⟩
        have h1 := hgmin g' hg'm hg'l
        have h2 := Polynomial.natDegree_modByMonic_lt f hgm hg1
        omega
      rw [hdecomp]
      refine (IsUltrametricDist.norm_add_le_max _ _).trans (max_le_max ?_ hr_small)
      rw [norm_mul]
      exact mul_le_of_le_one_right (norm_nonneg _) (hle1 _)
  · simp only [not_exists, not_and, not_lt] at hex
    refine ⟨fun x hx ↦ ?_, ⟨max εS 0, max_lt hεS zero_lt_one, fun x hx hx1 ↦ ?_⟩⟩
    · obtain ⟨p, rfl⟩ := hrep x hx
      exact hle1 p
    · obtain ⟨f, rfl⟩ := hrep x hx
      refine hsmall _ fun i hi ↦ ?_
      obtain ⟨g', hg'm, -, hg'l⟩ := hB.exists_monic_norm_aeval_lt_one ha hx1 ⟨i, hi⟩
      exact absurd hg'l (not_lt.2 (hex g' hg'm))

/-- Adjoining an element of the unit ball to a bald subring gives a bald subring.
Source: Bosch 1.3/3 ("it is enough to show that, for a bald subring `S ⊂ R` and an element
`a ∈ R` of value `|a| = 1`, the ring `S[a]` is bald"). -/
theorem IsBald.closure_insert {S : Subring K} (hS : S.IsBald) {a : K} (ha : ‖a‖ ≤ 1) :
    (closure (insert a (S : Set K))).IsBald := by
  rcases ha.lt_or_eq with ha1 | ha1
  · have h := hS.closure_union_of_norm_le ha1 (T := {a}) fun x hx ↦
      (Set.mem_singleton_iff.1 hx).symm ▸ le_rfl
    rwa [Set.union_singleton] at h
  · exact ((isBRing_unitLocalization hS.norm_le_one).isBald_closure_insert hS.unitLocalization
      ha1).mono (closure_mono (Set.insert_subset_insert (le_unitLocalization S)))

/-- The subring generated by finitely many elements of the unit ball is bald. -/
private lemma isBald_closure_finset (s : Finset K) (hs : ∀ x ∈ s, ‖x‖ ≤ 1) :
    (closure (s : Set K)).IsBald := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    rw [Finset.coe_empty, closure_empty]
    exact isBald_bot
  | insert x s _ ih =>
    have h := (ih fun y hy ↦ hs y (Finset.mem_insert_of_mem hy)).closure_insert
      (hs x (Finset.mem_insert_self x s))
    rw [Finset.coe_insert]
    exact h.mono (closure_mono (Set.insert_subset_insert subset_closure))

/-- **The subring generated by a null family of the unit ball is bald.** Source: Bosch 1.3/3. -/
theorem isBald_closure_range {ι : Type*} {a : ι → K} (ha : ∀ i, ‖a i‖ ≤ 1)
    (ha0 : Tendsto a cofinite (𝓝 0)) : (closure (Set.range a)).IsBald := by
  classical
  have hfin : {i | ¬ dist (a i) 0 < 1 / 2}.Finite :=
    Filter.eventually_cofinite.1 (Metric.tendsto_nhds.1 ha0 (1 / 2) (by norm_num))
  have hS₀ := isBald_closure_finset (hfin.toFinset.image a) fun x hx ↦ by
    obtain ⟨i, -, rfl⟩ := Finset.mem_image.1 hx
    exact ha i
  have h := hS₀.closure_union_of_norm_le (T := {x | ∃ i, dist (a i) 0 < 1 / 2 ∧ x = a i})
    (ε := 1 / 2) (by norm_num) fun x ⟨i, hi, hx⟩ ↦ by
      rw [hx, ← dist_zero_right]
      exact hi.le
  refine h.mono (closure_le.2 ?_)
  rintro _ ⟨i, rfl⟩
  by_cases hi : dist (a i) 0 < 1 / 2
  · exact subset_closure (Or.inr ⟨i, hi, rfl⟩)
  · exact subset_closure (Or.inl (subset_closure (Finset.mem_coe.2
      (Finset.mem_image_of_mem a (hfin.mem_toFinset.2 hi)))))

end Subring
