/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import PhD.Main.TateFredholm.HandClean.«00_TateRings»

/-!
# Minimal Huber input for the converse of `isTateRing_of_isTate`

**Archive / staging file.**  See `PhD/Main/TateFredholm/HandClean/TateConverse.md`.

This is the complete dependency closure of **Wedhorn Lemma 6.14**
(`IsTateRing.exists_principal_pairOfDefinition`: a Tate ring admits a pair of definition whose
ideal of definition is principal, generated by a unit of `A`), extracted verbatim from the
`«Adic spaces»` Huber ring development.  It is the only Huber-side input the converse
construction needs — the gauge norm `‖a‖ = (1/2)^{v(a)}`, `v(a) = sup {n : ℤ | a ∈ πⁿ·A₀}`, is
built on top of a principal pair and nothing else.

`PairOfDefinition`, `IsHuberRing` and `IsTateRing` come from
`PhD/Main/TateFredholm/HandClean/00_TateRings.lean`, where they are already quoted.

Everything below is lifted **unchanged** from the original file: these are exactly the
declarations that needed no porting onto this repository's `ForMathlib` API.  In particular
nothing here touches `TopologicalRing.IsBounded`, the power-bounded subring,
`topologicalNilradical`, `PairOfDefinition.adjoin` or Proposition 6.25 — the full ported
development, if it is wanted, is in `PhD/Main/Test/HuberRings.lean`.

## Contents

* `PairOfDefinition.pow_isOpen`, `pow_image_isOpen`, `hasBasis_nhds_zero`
* `PairOfDefinition.exists_pow_mem_I`, `exists_pow_I_le_span_unit`
* `PairOfDefinition.isAdic_of_interleaving` (Wedhorn 6.12)
* `isTopologicallyNilpotent_pow`
* `PairOfDefinition.withPrincipal`
* `PrincipalPairOfDefinition`, `IsTateRing.exists_principal_pairOfDefinition` (Wedhorn 6.14),
  `IsTateRing.principalPair`

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn2019adic], §6
-/

open Filter Topology Pointwise

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

namespace PairOfDefinition

/-- Each power `Iⁿ` is open in `A₀` (in the subspace topology). -/
theorem pow_isOpen (P : PairOfDefinition A) (n : ℕ) :
    IsOpen ((P.I ^ n : Ideal P.A₀) : Set P.A₀) :=
  (isAdic_iff.mp P.isAdic).1 n

/-- The image of `Iⁿ` in `A` is open. -/
theorem pow_image_isOpen (P : PairOfDefinition A) (n : ℕ) :
    IsOpen (Subtype.val '' ((P.I ^ n : Ideal P.A₀) : Set P.A₀) : Set A) :=
  P.isOpen.isOpenMap_subtype_val _ (P.pow_isOpen n)

/-- The images of `Iⁿ` in `A` form a neighborhood basis of `0`. -/
theorem hasBasis_nhds_zero (P : PairOfDefinition A) :
    (𝓝 (0 : A)).HasBasis (fun _ : ℕ ↦ True)
      (fun n ↦ Subtype.val '' ((P.I ^ n : Ideal P.A₀) : Set P.A₀)) :=
  Filter.HasBasis.mk fun U ↦ by
    constructor
    · intro hU
      have hU' : Subtype.val ⁻¹' U ∈ 𝓝 (0 : ↥P.A₀) :=
        continuous_subtype_val.continuousAt.preimage_mem_nhds (by simpa using hU)
      obtain ⟨n, -, hn⟩ := P.isAdic.hasBasis_nhds_zero.mem_iff.mp hU'
      exact ⟨n, trivial, (Set.image_mono hn).trans (Set.image_preimage_subset _ _)⟩
    · rintro ⟨n, -, hn⟩
      exact mem_nhds_iff.mpr
        ⟨_, hn, P.pow_image_isOpen n, Set.mem_image_of_mem _ (P.I ^ n).zero_mem⟩

end PairOfDefinition

/-- If `u ∈ A₀` is topologically nilpotent in `A`, then `u^N ∈ I` for some `N`. -/
theorem PairOfDefinition.exists_pow_mem_I (P : PairOfDefinition A) {u : A}
    (hu_mem : u ∈ P.A₀) (hu_nil : IsTopologicallyNilpotent u) :
    ∃ N : ℕ, (⟨u, hu_mem⟩ : P.A₀) ^ N ∈ P.I := by
  have h_nhds : P.A₀.subtype '' ((P.I : Ideal P.A₀) : Set P.A₀) ∈ 𝓝 (0 : A) :=
    (pow_one P.I ▸ P.pow_image_isOpen 1).mem_nhds
      ⟨0, P.I.zero_mem, rfl⟩
  obtain ⟨N, ⟨⟨y, hy_mem⟩, hy_I, hval⟩⟩ := hu_nil.exists_pow_mem_of_mem_nhds h_nhds
  exact ⟨N, by rwa [show (⟨u, hu_mem⟩ : P.A₀) ^ N = ⟨y, hy_mem⟩ from
    Subtype.ext (by simpa [SubmonoidClass.coe_pow] using hval.symm)]⟩

/-- If `u` is a unit in `A` with `u ∈ A₀`, then `I^m ≤ Ideal.span {u_A₀ ^ N}`
for some `m`. -/
theorem PairOfDefinition.exists_pow_I_le_span_unit (P : PairOfDefinition A) {u : Aˣ}
    (hu_mem : (u : A) ∈ P.A₀) (N : ℕ) :
    ∃ m : ℕ, P.I ^ m ≤ Ideal.span {(⟨(u : A), hu_mem⟩ : P.A₀) ^ N} := by
  have h_open : IsOpen ((u ^ N : Aˣ) • (P.A₀ : Set A)) := isOpenMap_smul (u ^ N) _ P.isOpen
  obtain ⟨m, -, hm⟩ := P.hasBasis_nhds_zero.mem_iff.mp
    (h_open.mem_nhds ⟨0, P.A₀.zero_mem, smul_zero _⟩)
  refine ⟨m, fun x hx ↦ ?_⟩
  obtain ⟨b, hb_mem, hb_eq⟩ := hm ⟨x, hx, rfl⟩
  have hval : (↑x : A) = (↑u) ^ N * b := by
    have : (↑(u ^ N : Aˣ) : A) * b = ↑x := by rw [← smul_eq_mul]; exact hb_eq
    rw [Units.val_pow_eq_pow_val] at this; exact this.symm
  exact (show x = (⟨(u : A), hu_mem⟩ : P.A₀) ^ N * ⟨b, hb_mem⟩ from
    Subtype.ext (by simpa using hval)).symm ▸
    Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)

/-- If `J ≤ I` and `I^m ≤ J`, then the `I`-adic topology is also `J`-adic
(Remark 6.12 of Wedhorn). -/
theorem PairOfDefinition.isAdic_of_interleaving (P : PairOfDefinition A) {J : Ideal P.A₀}
    (hJ_le : J ≤ P.I) {m : ℕ} (hI_le : P.I ^ m ≤ J) : IsAdic J := by
  have hJ_pow_le : ∀ n, J ^ n ≤ P.I ^ n := fun n ↦ pow_le_pow_left' hJ_le n
  have hI_pow_le : ∀ n, P.I ^ (m * n) ≤ J ^ n := fun n ↦
    pow_mul P.I m n ▸ pow_le_pow_left' hI_le n
  rw [isAdic_iff]
  constructor
  · intro n
    change IsOpen ((J ^ n).toAddSubgroup : Set P.A₀)
    exact AddSubgroup.isOpen_of_mem_nhds _
      (Filter.mem_of_superset
        ((P.pow_isOpen (m * n)).mem_nhds (P.I ^ (m * n)).zero_mem)
        ((Submodule.coe_toAddSubgroup (J ^ n)).symm ▸ (hI_pow_le n)))
  · intro s hs
    obtain ⟨k, -, hk⟩ := P.isAdic.hasBasis_nhds_zero.mem_iff.mp hs
    exact ⟨k, fun x hx ↦ hk (hJ_pow_le k hx)⟩

/-- A positive power of a topologically nilpotent element is topologically nilpotent. -/
theorem isTopologicallyNilpotent_pow {A : Type*} [TopologicalSpace A] [MonoidWithZero A] {a : A}
    (ha : IsTopologicallyNilpotent a) {K : ℕ} (hK : 0 < K) :
    IsTopologicallyNilpotent (a ^ K) := by
  change Filter.Tendsto (fun n ↦ (a ^ K) ^ n) Filter.atTop (nhds 0)
  simp_rw [← pow_mul]
  exact ha.comp (Filter.tendsto_atTop_atTop_of_monotone
    (fun _ _ h ↦ Nat.mul_le_mul_left K h)
    (fun b ↦ ⟨b, le_mul_of_one_le_left (Nat.zero_le b) hK⟩))

/-- Replace the ideal of definition with a principal ideal `span{a}`, keeping the same `A₀`. -/
def PairOfDefinition.withPrincipal (P : PairOfDefinition A) {a : P.A₀} (ha : a ∈ P.I) {m : ℕ}
    (hm : P.I ^ m ≤ Ideal.span {a}) : PairOfDefinition A where
  A₀ := P.A₀
  I := Ideal.span {a}
  isOpen := P.isOpen
  fg := ⟨{a}, by simp [Finset.coe_singleton]⟩
  isAdic := P.isAdic_of_interleaving
    (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr ha)) hm

/-- The ring of definition of `withPrincipal` equals the original. -/
@[simp]
theorem PairOfDefinition.withPrincipal_A₀ (P : PairOfDefinition A) {a : P.A₀} (ha : a ∈ P.I)
    {m : ℕ} (hm : P.I ^ m ≤ Ideal.span {a}) : (P.withPrincipal ha hm).A₀ = P.A₀ := rfl

/-- The ideal of definition of `withPrincipal` is `span {a}`. -/
@[simp]
theorem PairOfDefinition.withPrincipal_I (P : PairOfDefinition A) {a : P.A₀} (ha : a ∈ P.I)
    {m : ℕ} (hm : P.I ^ m ≤ Ideal.span {a}) : (P.withPrincipal ha hm).I = Ideal.span {a} := rfl

/-- A **principal pair of definition** for a topological ring `A`: a pair of
definition `(A₀, I)` together with a generator `π ∈ A₀` such that `I = (π)` and
`π` is a unit in `A`. In a Tate ring, principal pairs exist (Wedhorn 6.14). -/
structure PrincipalPairOfDefinition (A : Type*) [CommRing A] [TopologicalSpace A]
    extends PairOfDefinition A where
  /-- The generator of `I`. -/
  π : toPairOfDefinition.A₀
  /-- `I` is the principal ideal generated by `π`. -/
  I_eq_span : toPairOfDefinition.I = Ideal.span {π}
  /-- `π` is a unit in `A`. -/
  π_isUnit : IsUnit ((π : A))

/-- **Wedhorn Lemma 6.14 (our version):** a Tate ring admits a pair of definition
whose ideal of definition is principal and whose generator (viewed in `A`) is a
topologically nilpotent unit.

The generator is constructed from the topologically nilpotent unit `u ∈ Aˣ`: some
positive power `u^k` of `u` lies in any given `A₀` (since `A₀` is open), and then
by Wedhorn 6.4 some further power `(u^k)^N ∈ P.I`. Taking `π := (u^k)^N` and
refining `P` to `P.withPrincipal` gives the principal pair, and `π` is a unit in
`A` since it is a positive power of a unit. -/
theorem IsTateRing.exists_principal_pairOfDefinition
    (A : Type*) [CommRing A] [TopologicalSpace A] [IsTateRing A] :
    ∃ (P : PairOfDefinition A) (π : P.A₀),
      P.I = Ideal.span {π} ∧ IsUnit ((π : A)) := by
  obtain ⟨u, hu_nilp⟩ := ‹IsTateRing A›.exists_topologicallyNilpotent_unit
  obtain ⟨P⟩ := (‹IsTateRing A›.toIsHuberRing).exists_pairOfDefinition
  obtain ⟨K, hK⟩ := Filter.eventually_atTop.mp
    (hu_nilp (P.isOpen.mem_nhds P.A₀.zero_mem))
  set k : ℕ := K + 1
  have hk_pos : 0 < k := Nat.succ_pos K
  have hu_k_mem : ((u : A) ^ k) ∈ P.A₀ := hK k (Nat.le_succ K)
  have hu_k_nilp : IsTopologicallyNilpotent ((u : A) ^ k) :=
    isTopologicallyNilpotent_pow hu_nilp hk_pos
  set u_k : P.A₀ := ⟨((u : A) ^ k), hu_k_mem⟩ with hu_k_def
  have hu_k_val : (u_k : A) = (u : A) ^ k := rfl
  obtain ⟨N, hN_mem⟩ : ∃ N : ℕ, u_k ^ N ∈ P.I :=
    P.exists_pow_mem_I (u := (u : A) ^ k) hu_k_mem hu_k_nilp
  set π : P.A₀ := u_k ^ N with hπ_def
  have hπ_mem_I : π ∈ P.I := hN_mem
  have hu_k_unit_val : ((u ^ k : Aˣ) : A) ∈ P.A₀ := by
    rw [Units.val_pow_eq_pow_val]; exact hu_k_mem
  obtain ⟨m, hm_le⟩ := P.exists_pow_I_le_span_unit (u := u ^ k) hu_k_unit_val N
  have hgen_eq :
      (⟨((u ^ k : Aˣ) : A), hu_k_unit_val⟩ : P.A₀) ^ N = π := by
    rw [hπ_def, hu_k_def]
    apply congr_arg (· ^ N)
    exact Subtype.ext (Units.val_pow_eq_pow_val u k)
  rw [hgen_eq] at hm_le
  refine ⟨P.withPrincipal hπ_mem_I hm_le, π, rfl, ?_⟩
  have : (π : A) = ((u ^ (k * N) : Aˣ) : A) := by
    rw [hπ_def]
    show ((u_k ^ N : P.A₀) : A) = _
    rw [SubmonoidClass.coe_pow, hu_k_val, ← pow_mul, Units.val_pow_eq_pow_val]
  rw [this]
  exact Units.isUnit _

/-- A canonical principal pair of definition for a Tate ring, obtained via
`IsTateRing.exists_principal_pairOfDefinition` and `Classical.choice`. -/
noncomputable def IsTateRing.principalPair (A : Type*) [CommRing A] [TopologicalSpace A]
    [IsTateRing A] : PrincipalPairOfDefinition A :=
  let h := IsTateRing.exists_principal_pairOfDefinition A
  { toPairOfDefinition := h.choose
    π := h.choose_spec.choose
    I_eq_span := h.choose_spec.choose_spec.1
    π_isUnit := h.choose_spec.choose_spec.2 }
