/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import Mathlib.Algebra.Module.Torsion.Basic
import PhD.TauCeti.Code.PadicFunctionalAnalysis.Tate
import PhD.TauCeti.Code.PadicFunctionalAnalysis.UnitBall

/-!
# Residue rings and residue modules

For a pseudo-uniformiser `ϖ` of a nonarchimedean normed commutative ring `R` with `‖1‖ = 1`, the
element `ϖ` lies in the unit ball `R⁰` and generates the ideal `(ϖ) = {a ∈ R⁰ | ‖a‖ ≤ ‖ϖ‖}`. For a
normed `R`-module `M`, the unit ball `M⁰` is an `R⁰`-submodule of `M`, and `ϖ M⁰` is the closed ball
of radius `‖ϖ‖`; when the norm of `M` takes its values in `‖ϖ‖ ^ ℤ ∪ {0}`, that is the open unit
ball, so that the *residue module* `M̃ = M⁰ / ϖ M⁰` over the *residue ring* `R̃ = R⁰ / ϖ R⁰` is the
reduction of the unit ball modulo its open ball. `M̃` is the module that Serre's theorem tests for
freeness.

Roadmap: `PhD/TauCeti/Roadmaps/PadicFunctionalAnalysis/README.md`, §0.3.4. Tau Ceti home:
`TauCeti/Analysis/Normed/Module/Ultra/Residue.lean`.

## Main definitions

* `NormedRing.PseudoUniformizer.toUnitClosedBall`, `NormedRing.PseudoUniformizer.ideal` — `ϖ` as
  an element of `R⁰`, and the ideal `(ϖ)` of `R⁰`.
* `Submodule.unitClosedBall R M` — the unit ball `M⁰`, as an `R⁰`-submodule of `M`.
* `NormedRing.PseudoUniformizer.ResidueRing`, `NormedRing.PseudoUniformizer.ResidueModule` —
  `R⁰ / ϖ R⁰` and `M⁰ / ϖ M⁰`.
-/

open Filter Topology NNReal

/-! ### The unit ball of a normed module -/

namespace Submodule

variable (R M : Type*) [SeminormedRing R] [NormOneClass R] [IsUltrametricDist R]
  [SeminormedAddCommGroup M] [Module R M] [IsBoundedSMul R M] [IsUltrametricDist M]

/-- The closed unit ball `M⁰ = {m | ‖m‖ ≤ 1}` of a nonarchimedean normed module, as a submodule
over the unit ball `R⁰` of the ring. Source: Bellaïche, §II.1.4 ("`M⁰ = {m ∈ M, |m| ≤ 1}`, which is
an `R⁰`-submodule of `M`"). -/
def unitClosedBall : Submodule (Subring.unitClosedBall R) M where
  carrier := {m | ‖m‖ ≤ 1}
  add_mem' {m n} hm hn := (IsUltrametricDist.norm_add_le_max m n).trans (max_le hm hn)
  zero_mem' := by simp
  smul_mem' r m hm := by
    change ‖(r : R) • m‖ ≤ 1
    exact (norm_smul_le (r : R) m).trans
      (mul_le_one₀ (Subring.norm_le_one r) (norm_nonneg m) hm)

variable {R M}

@[simp]
theorem mem_unitClosedBall {m : M} : m ∈ unitClosedBall R M ↔ ‖m‖ ≤ 1 := by
  exact Iff.rfl

end Submodule

namespace NormedRing.PseudoUniformizer

open Subring

variable {R : Type*} [NormedCommRing R] [NormOneClass R] [IsUltrametricDist R]
  (ϖ : PseudoUniformizer R)

/-! ### The ideal generated by a pseudo-uniformiser -/

/-- A pseudo-uniformiser, as an element of the unit ball. -/
def toUnitClosedBall : unitClosedBall R :=
  ⟨(ϖ : R), mem_unitClosedBall.2 ϖ.norm_lt_one.le⟩

@[simp]
theorem coe_toUnitClosedBall : ((ϖ.toUnitClosedBall : unitClosedBall R) : R) = (ϖ : R) := rfl

/-- The ideal `(ϖ)` of the unit ball `R⁰`. Source: roadmap §0.3.4, §0.4.5. -/
def ideal : Ideal (unitClosedBall R) := Ideal.span {ϖ.toUnitClosedBall}

theorem toUnitClosedBall_mem_ideal : ϖ.toUnitClosedBall ∈ ϖ.ideal := by
  exact Ideal.mem_span_singleton_self _

/-- Source: roadmap §0.4.5 at `n = 1` (`ϖ R⁰ = {r ∈ R⁰ | ‖r‖ ≤ ‖ϖ‖}`). -/
theorem mem_ideal_iff {a : unitClosedBall R} : a ∈ ϖ.ideal ↔ ‖(a : R)‖ ≤ ‖(ϖ : R)‖ := by
  rw [ideal, Ideal.mem_span_singleton']
  constructor
  · rintro ⟨b, rfl⟩
    calc ‖(b : R) * (ϖ : R)‖ ≤ ‖(b : R)‖ * ‖(ϖ : R)‖ := _root_.norm_mul_le _ _
      _ ≤ ‖(ϖ : R)‖ := mul_le_of_le_one_left (norm_nonneg _) (Subring.norm_le_one b)
  · intro h
    have hb : ((ϖ.unit⁻¹ : Rˣ) : R) * a ∈ unitClosedBall R := by
      rw [Subring.mem_unitClosedBall, ϖ.isMultiplicative.inv, ϖ.norm_inv]
      exact (inv_mul_le_iff₀ ϖ.norm_pos).2 (by rwa [mul_one])
    refine ⟨⟨_, hb⟩, Subtype.ext ?_⟩
    change ((ϖ.unit⁻¹ : Rˣ) : R) * a * (ϖ : R) = a
    rw [mul_right_comm, Units.inv_mul, one_mul]

theorem ideal_eq_closedBallIdeal : ϖ.ideal = closedBallIdeal R ‖(ϖ : R)‖₊ := by
  ext a
  rw [ϖ.mem_ideal_iff, mem_closedBallIdeal, coe_nnnorm]

theorem ideal_le_openUnitBallIdeal : ϖ.ideal ≤ openUnitBallIdeal R := by
  exact fun a ha ↦ mem_openUnitBallIdeal.2 ((ϖ.mem_ideal_iff.1 ha).trans_lt ϖ.norm_lt_one)

omit [IsUltrametricDist R] in
/-- A value `‖ϖ‖ ^ n` less than `1` is at most `‖ϖ‖`. -/
private theorem zpow_le_self_of_lt_one {n : ℤ} (h : ‖(ϖ : R)‖ ^ n < 1) :
    ‖(ϖ : R)‖ ^ n ≤ ‖(ϖ : R)‖ := by
  have hn := (zpow_lt_one_iff_right_of_lt_one₀ ϖ.norm_pos ϖ.norm_lt_one).1 h
  calc ‖(ϖ : R)‖ ^ n ≤ ‖(ϖ : R)‖ ^ (1 : ℤ) :=
        zpow_le_zpow_right_of_le_one₀ ϖ.norm_pos ϖ.norm_lt_one.le (by omega)
    _ = ‖(ϖ : R)‖ := zpow_one _

/-- When the norm of `R` takes its values in `‖ϖ‖ ^ ℤ ∪ {0}`, the ideal `(ϖ)` is the open unit
ball. Source: Bellaïche, Hypothesis II.1.11; Schneider, proof of Proposition 10.1
(`m · B₁(0) ⊆ B₁⁻(0)`). -/
theorem ideal_eq_openUnitBallIdeal (h : ∀ r : R, r ≠ 0 → ∃ n : ℤ, ‖r‖ = ‖(ϖ : R)‖ ^ n) :
    ϖ.ideal = openUnitBallIdeal R := by
  refine le_antisymm ϖ.ideal_le_openUnitBallIdeal fun a ha ↦ ?_
  rw [mem_openUnitBallIdeal] at ha
  rw [ϖ.mem_ideal_iff]
  rcases eq_or_ne (a : R) 0 with h0 | h0
  · rw [h0, norm_zero]
    exact norm_nonneg _
  obtain ⟨n, hn⟩ := h _ h0
  rw [hn] at ha ⊢
  exact ϖ.zpow_le_self_of_lt_one ha

/-- The residue ring `R̃ = R⁰ / ϖ R⁰`. Source: Bellaïche, §II.1.4 ("`R̃` the quotient ring
`R⁰/πR⁰`"). -/
abbrev ResidueRing : Type _ := unitClosedBall R ⧸ ϖ.ideal

/-! ### The residue module -/

section Module

variable (M : Type*) [NormedAddCommGroup M] [Module R M] [IsBoundedSMul R M]
  [IsUltrametricDist M]

/-- The residue module `M̃ = M⁰ / ϖ M⁰`, a module over the residue ring. Source: Bellaïche,
§II.1.4 ("`M̃ = M⁰/πM⁰`, which is a `R̃`-module"). -/
abbrev ResidueModule : Type _ :=
  Submodule.unitClosedBall R M ⧸
    (ϖ.ideal • ⊤ : Submodule (unitClosedBall R) (Submodule.unitClosedBall R M))

example : Module ϖ.ResidueRing (ϖ.ResidueModule M) := inferInstance

variable {M}

/-- Source: roadmap §0.3.4 (`π M⁰` is the closed ball of radius `‖π‖`). -/
theorem mem_ideal_smul_top_iff {m : Submodule.unitClosedBall R M} :
    m ∈ (ϖ.ideal • ⊤ : Submodule (unitClosedBall R) (Submodule.unitClosedBall R M)) ↔
      ‖(m : M)‖ ≤ ‖(ϖ : R)‖ := by
  constructor
  · intro hm
    refine Submodule.smul_induction_on hm (fun r hr n _ ↦ ?_) (fun x y hx hy ↦ ?_)
    · change ‖(r : R) • (n : M)‖ ≤ ‖(ϖ : R)‖
      calc ‖(r : R) • (n : M)‖ ≤ ‖(r : R)‖ * ‖(n : M)‖ := norm_smul_le _ _
        _ ≤ ‖(ϖ : R)‖ * 1 := mul_le_mul (ϖ.mem_ideal_iff.1 hr)
            (Submodule.mem_unitClosedBall.1 n.2) (norm_nonneg _) (norm_nonneg _)
        _ = ‖(ϖ : R)‖ := mul_one _
    · exact (IsUltrametricDist.norm_add_le_max (x : M) y).trans (max_le hx hy)
  · intro h
    have hn : ((ϖ.unit⁻¹ : Rˣ) : R) • (m : M) ∈ Submodule.unitClosedBall R M := by
      rw [Submodule.mem_unitClosedBall, ϖ.isMultiplicative.inv.norm_smul, ϖ.norm_inv]
      exact (inv_mul_le_iff₀ ϖ.norm_pos).2 (by rwa [mul_one])
    have hm : m = ϖ.toUnitClosedBall • (⟨_, hn⟩ : Submodule.unitClosedBall R M) := by
      apply Subtype.ext
      change (m : M) = (ϖ : R) • (((ϖ.unit⁻¹ : Rˣ) : R) • (m : M))
      rw [smul_smul, Units.mul_inv, one_smul]
    rw [hm]
    exact Submodule.smul_mem_smul ϖ.toUnitClosedBall_mem_ideal Submodule.mem_top

/-- Source: roadmap §0.3.4 (`π M⁰ = {m | ‖m‖ < 1}` when the norm of `M` takes values in
`‖π‖ ^ ℤ ∪ {0}`); Schneider, proof of Proposition 10.1; Bellaïche, Lemma II.1.12 (`|M| ⊂ |R|`). -/
theorem mem_ideal_smul_top_iff_norm_lt_one
    (h : ∀ m : M, m ≠ 0 → ∃ n : ℤ, ‖m‖ = ‖(ϖ : R)‖ ^ n) {m : Submodule.unitClosedBall R M} :
    m ∈ (ϖ.ideal • ⊤ : Submodule (unitClosedBall R) (Submodule.unitClosedBall R M)) ↔
      ‖(m : M)‖ < 1 := by
  rw [ϖ.mem_ideal_smul_top_iff]
  refine ⟨fun h' ↦ h'.trans_lt ϖ.norm_lt_one, fun h' ↦ ?_⟩
  rcases eq_or_ne (m : M) 0 with h0 | h0
  · rw [h0, norm_zero]
    exact norm_nonneg _
  obtain ⟨n, hn⟩ := h _ h0
  rw [hn] at h' ⊢
  exact ϖ.zpow_le_self_of_lt_one h'

end Module

end NormedRing.PseudoUniformizer
