/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import PhD.Main.ForMathlib.Topology.Algebra.Valued.AddVal
import Mathlib.NumberTheory.Padics.PadicNumbers

/-!
# `ℚ_p`: the machinery reproduces the `p`-adic valuation

The final check on the additive-valuation development: on `ℚ_p` the abstract
`NormedField.normAddValZ` is exactly `Padic.addValuationDef`.

Along the way this file supplies the instances that make `ℚ_p` a discretely valued normed field
in the sense of `Valuation.IsRankOneDiscrete` — that the value group of the `p`-adic norm is
cyclic and nontrivial, generated by `‖p‖₊ = p⁻¹`.

## Main results

* `padic_norm_eq_zpow_neg_normAddValZ`: `‖x‖ = p ^ (-normAddValZ ℚ_[p] x)`;
* `normAddValZ_padic`: `normAddValZ ℚ_[p] = Padic.addValuationDef`.

Everything here is meant to be redistributed into the relevant `Mathlib` files.
-/

open scoped NNReal WithZero

section Padic

open NormedField Valuation MonoidWithZeroHom Valuation.IsRankOneDiscrete WithZero

variable {p : ℕ} [Fact p.Prime]

private lemma padic_p_ne : (p : ℚ_[p]) ≠ 0 := by
  exact_mod_cast (Fact.out : p.Prime).ne_zero

private lemma padic_nnnorm_p_ne : ‖(p : ℚ_[p])‖₊ ≠ 0 := by simpa using padic_p_ne (p := p)

/-- The generator `‖p‖₊ = p⁻¹` of the value group of the `p`-adic norm. -/
private noncomputable def padicGen : valueGroup (.ofClass (valuation (K := ℚ_[p]))) :=
  ⟨Units.mk0 ‖(p : ℚ_[p])‖₊ padic_nnnorm_p_ne, mem_valueGroup _ ⟨(p : ℚ_[p]), rfl⟩⟩

private lemma padic_norm_zpow_valuation (x : ℚ_[p]) (hx : x ≠ 0) :
    ‖(p : ℚ_[p])‖₊ ^ x.valuation = ‖x‖₊ := by
  rw [← NNReal.coe_inj]
  push_cast
  rw [Padic.norm_eq_zpow_neg_valuation hx,
    Padic.norm_eq_zpow_neg_valuation (padic_p_ne (p := p)), Padic.valuation_p, ← zpow_mul]
  ring_nf

private lemma padic_zpowers_gen : Subgroup.zpowers (padicGen (p := p)) = ⊤ := by
  rw [Subgroup.eq_top_iff']
  intro y
  rw [Subgroup.mem_zpowers_iff]
  have hy : (y : ℝ≥0ˣ).val ∈ Units.val '' (valueGroup (.ofClass (valuation (K := ℚ_[p])))) :=
    ⟨y, y.2, rfl⟩
  rw [valueGroup_eq_range] at hy
  obtain ⟨⟨x, hx⟩, hne⟩ := hy
  simp only [Set.mem_singleton_iff] at hne
  have hx0 : x ≠ 0 := by
    rintro rfl; exact hne (by rw [← hx]; simp)
  refine ⟨x.valuation, Subtype.ext (Units.ext ?_)⟩
  rw [SubgroupClass.coe_zpow, Units.val_zpow_eq_zpow_val,
    show ((padicGen (p := p)) : ℝ≥0ˣ).val = ‖(p : ℚ_[p])‖₊ from rfl,
    padic_norm_zpow_valuation x hx0, ← hx]
  rfl

instance : IsCyclic (valueGroup (.ofClass (valuation (K := ℚ_[p])))) :=
  isCyclic_iff_exists_zpowers_eq_top.mpr ⟨padicGen, padic_zpowers_gen⟩

instance : Nontrivial (valueGroup (.ofClass (valuation (K := ℚ_[p])))) := by
  refine ⟨padicGen, 1, fun h ↦ ?_⟩
  have hval : ‖(p : ℚ_[p])‖₊ = 1 := by
    have := congrArg
      (fun z : valueGroup (.ofClass (valuation (K := ℚ_[p]))) ↦ ((z : ℝ≥0ˣ) : ℝ≥0)) h
    simpa [padicGen] using this
  exact absurd (by rw [← coe_nnnorm, hval, NNReal.coe_one] : ‖(p : ℚ_[p])‖ = 1)
    (ne_of_lt Padic.norm_p_lt_one)

private lemma padicGen_lt_one : padicGen (p := p) < 1 := by
  have h : ‖(p : ℚ_[p])‖₊ < 1 := by exact_mod_cast Padic.norm_p_lt_one
  rw [← Subtype.coe_lt_coe]
  exact_mod_cast h

private lemma padic_generator'_eq :
    generator' (valuation (K := ℚ_[p])) = padicGen :=
  LinearOrderedCommGroup.Subgroup.genLTOne_unique_of_zpowers_eq
    (generator'_lt_one _) padicGen_lt_one
    (by rw [generator'_zpowers_eq_top, padic_zpowers_gen])

private lemma padic_nnnorm_p : ‖(p : ℚ_[p])‖₊ = (p : ℝ≥0)⁻¹ := by
  rw [← NNReal.coe_inj]; push_cast; exact Padic.norm_p

private lemma padic_generator_eq :
    (generator (valuation (K := ℚ_[p])) : ℝ≥0) = (p : ℝ≥0)⁻¹ := by
  have h : ((generator' (valuation (K := ℚ_[p])) : ℝ≥0ˣ) : ℝ≥0)
      = ((padicGen (p := p) : ℝ≥0ˣ) : ℝ≥0) := by rw [padic_generator'_eq]
  rw [← padic_nnnorm_p]
  exact h

/-- **The scalar hypothesis, discharged for `ℚ_p`**: a uniformizer has norm `p⁻¹`.  This is
essentially `Padic.norm_p`. -/
private lemma hgen_padic :
    RankOne.hom (valuation (K := ℚ_[p]))
      (generator' (valuation (K := ℚ_[p])) :
        ValueGroup₀ (.ofClass (valuation (K := ℚ_[p])))) = (p : ℝ≥0)⁻¹ := by
  rw [show RankOne.hom (valuation (K := ℚ_[p]))
        (generator' (valuation (K := ℚ_[p])) :
          ValueGroup₀ (.ofClass (valuation (K := ℚ_[p]))))
        = (generator (valuation (K := ℚ_[p])) : ℝ≥0) from embedding_generator' _,
    padic_generator_eq]

/-- **The `p`-adic norm is `p` to the power of minus our additive valuation.** -/
theorem padic_norm_eq_zpow_neg_normAddValZ {x : ℚ_[p]} {d : ℤ}
    (hd : normAddValZ ℚ_[p] x = (d : WithTop ℤ)) : ‖x‖ = (p : ℝ) ^ (-d) := by
  have h := norm_eq_zpow_neg_normAddValZ (K := ℚ_[p]) (e := (p : ℝ≥0))
    (by exact_mod_cast (Fact.out : p.Prime).ne_zero) hgen_padic hd
  simpa using h

/-- **The verification.**  On `ℚ_p`, `normAddValZ` is exactly `Padic.addValuationDef`. -/
theorem normAddValZ_padic (x : ℚ_[p]) :
    normAddValZ ℚ_[p] x = Padic.addValuationDef x := by
  by_cases hx : x = 0
  · subst hx; rw [normAddValZ_zero, Padic.addValuationDef, if_pos rfl]
  · obtain ⟨d, hd⟩ := WithTop.ne_top_iff_exists.mp (show normAddValZ ℚ_[p] x ≠ ⊤ by
      rw [normAddValZ, IsRankOneDiscrete.addValZ_apply, ne_eq, negLog_eq_top, map_eq_zero,
        Valuation.restrict_eq_zero_iff, Valuation.zero_iff]
      exact hx)
    rw [← hd, Padic.addValuationDef, if_neg hx]
    congr 1
    have hn1 := padic_norm_eq_zpow_neg_normAddValZ hd.symm
    have hn2 := Padic.norm_eq_zpow_neg_valuation hx
    have hpp : (1 : ℝ) < p := by exact_mod_cast (Fact.out : p.Prime).one_lt
    have := (zpow_right_strictMono₀ hpp).injective (hn1.symm.trans hn2)
    omega

end Padic
