/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import Mathlib.NumberTheory.Padics.HeightOneSpectrum
import PhD.Main.ForMathlib.NumberTheory.NumberField.Completion.FinitePlace

/-!
# Mathlib's comparison `ℚ_[p] ≃ (𝓞 ℚ)_v` is an isometry

`Padic.adicCompletionEquiv R p : ℚ_[p] ≃A[ℚ] (primesEquiv.symm p).adicCompletion ℚ` is
mathlib's continuous `ℚ`-algebra isomorphism between the `p`-adic numbers and the `v`-adic
completion of `ℚ` at the place `v = (p)`.  With the finite-place norm on the completion
(`‖x‖ = (absNorm v)^{-v(x)}`, `PhD/Main/ForMathlib/…/Completion/FinitePlace.lean`) it is an isometry:
`absNorm (v.asIdeal) = p`, so `‖p‖ = p⁻¹` on both sides, and the closed unit balls correspond
(`PadicInt.adicCompletionIntegersEquiv`).  This generalises the `p = 3` computation
`JacobsSlash.norm_adicCompletionEquiv` (`PhD/Main/JacobsSlash/U3/2_PadicEmbedding.lean`) to every
prime.

## Main declarations

* `Padic.absNorm_asIdeal_primesEquiv_symm` — `absNorm ((primesEquiv.symm p).asIdeal) = p`.
* `Padic.norm_adicCompletionEquiv` — the comparison equivalence is an isometry.
-/

open IsDedekindDomain NumberField

namespace Padic

variable (p : Nat.Primes)

/-- Mathlib keeps this instance local (`Mathlib/NumberTheory/Padics/HeightOneSpectrum.lean`). -/
local instance (p : Nat.Primes) : Fact p.1.Prime := ⟨p.2⟩

/-- The place `(p)` of `ℚ` is generated by `p`. -/
theorem natGenerator_primesEquiv_symm :
    Rat.HeightOneSpectrum.natGenerator
      ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p) = (p : ℕ) :=
  congrArg Subtype.val (Rat.HeightOneSpectrum.primesEquiv.apply_symm_apply p)

/-- The place `(p)` of `ℚ` is the principal ideal `(p)`. -/
theorem asIdeal_primesEquiv_symm :
    ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).asIdeal
      = Ideal.span {((p : ℕ) : RingOfIntegers ℚ)} := by
  have hb := (Rat.IsIntegralClosure.intEquiv (RingOfIntegers ℚ)).bijective
  have h : ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).asIdeal.map
      (Rat.IsIntegralClosure.intEquiv (RingOfIntegers ℚ)) = Ideal.span {((p : ℕ) : ℤ)} := by
    rw [← natGenerator_primesEquiv_symm]
    exact (Rat.HeightOneSpectrum.span_natGenerator _).symm
  have h2 : (Ideal.span {((p : ℕ) : RingOfIntegers ℚ)}).map
      (Rat.IsIntegralClosure.intEquiv (RingOfIntegers ℚ)) = Ideal.span {((p : ℕ) : ℤ)} := by
    rw [Ideal.map_span, Set.image_singleton, map_natCast]
  rw [← ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm
    p).asIdeal.comap_map_of_bijective _ hb, h, ← h2, Ideal.comap_map_of_bijective _ hb]

/-- The place `(p)` of `ℚ` has residue cardinality `p`. -/
theorem absNorm_asIdeal_primesEquiv_symm :
    Ideal.absNorm ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).asIdeal
      = (p : ℕ) := by
  rw [asIdeal_primesEquiv_symm, Ideal.absNorm_span_singleton,
    show ((p : ℕ) : RingOfIntegers ℚ) = algebraMap ℤ (RingOfIntegers ℚ) ((p : ℕ) : ℤ) from
      (map_natCast _ _).symm,
    Algebra.norm_algebraMap, NumberField.RingOfIntegers.rank, Module.finrank_self, pow_one,
    Int.natAbs_natCast]

/-- `p` is a uniformiser at the place `(p)`: `v(p) = exp(−1)` on the integers. -/
theorem intValuation_natCast_primesEquiv_symm :
    ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).intValuation
      ((p : ℕ) : RingOfIntegers ℚ) = WithZero.exp (-1 : ℤ) := by
  have hmem : ((p : ℕ) : RingOfIntegers ℚ)
      ∈ ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).asIdeal := by
    rw [asIdeal_primesEquiv_symm]
    exact Ideal.mem_span_singleton_self _
  have hnmem : ((p : ℕ) : RingOfIntegers ℚ)
      ∉ ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).asIdeal ^ 2 := by
    rw [asIdeal_primesEquiv_symm, Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    intro h
    have hd := map_dvd Rat.ringOfIntegersEquiv h
    rw [map_pow, map_natCast] at hd
    have hd' : (p : ℕ) ^ 2 ∣ (p : ℕ) := by exact_mod_cast hd
    have hle := Nat.le_of_dvd p.2.pos hd'
    nlinarith [p.2.two_le]
  have hle : ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).intValuation
      ((p : ℕ) : RingOfIntegers ℚ) ≤ WithZero.exp (-1 : ℤ) := by
    simpa using (HeightOneSpectrum.intValuation_le_pow_iff_mem _ ((p : ℕ) : RingOfIntegers ℚ)
      1).mpr (by simpa using hmem)
  have hnle : ¬ ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).intValuation
      ((p : ℕ) : RingOfIntegers ℚ) ≤ WithZero.exp (-2 : ℤ) := fun h =>
    hnmem ((HeightOneSpectrum.intValuation_le_pow_iff_mem _ ((p : ℕ) : RingOfIntegers ℚ) 2).mp
      (by simpa using h))
  rcases eq_or_ne (((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm
    p).intValuation ((p : ℕ) : RingOfIntegers ℚ)) 0 with h0 | h0
  · exact absurd (h0 ▸ zero_le) hnle
  · obtain ⟨a, ha⟩ := WithZero.ne_zero_iff_exists.mp h0
    have hae : ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).intValuation
        ((p : ℕ) : RingOfIntegers ℚ) = WithZero.exp (Multiplicative.toAdd a) := by
      rw [← ha, WithZero.exp_eq_coe_ofAdd]
      simp
    rw [hae] at hle hnle ⊢
    rw [WithZero.exp_le_exp] at hle
    rw [WithZero.exp_le_exp] at hnle
    congr 1
    omega

/-- `p` is a uniformiser of the completion of `ℚ` at `(p)`: `v(p) = exp(−1)`. -/
theorem valued_natCast_adicCompletion :
    Valued.v (((p : ℕ) : ℕ) :
        ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)
      = WithZero.exp (-1 : ℤ) := by
  have key : Valued.v (algebraMap ℚ
      (((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)
        ((p : ℕ) : ℚ))
      = ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).valuation ℚ
        ((p : ℕ) : ℚ) :=
    HeightOneSpectrum.valuedAdicCompletion_eq_valuation'
      (v := (Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p) ((p : ℕ) : ℚ)
  rw [show (((p : ℕ) : ℕ) :
        ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)
      = algebraMap ℚ _ ((p : ℕ) : ℚ) from (map_natCast _ _).symm, key,
    show ((p : ℕ) : ℚ) = algebraMap (RingOfIntegers ℚ) ℚ ((p : ℕ) : RingOfIntegers ℚ) from
      (map_natCast _ _).symm,
    HeightOneSpectrum.valuation_of_algebraMap, intValuation_natCast_primesEquiv_symm]

/-- `‖p‖ = p⁻¹` in the completion of `ℚ` at `(p)`. -/
theorem norm_natCast_adicCompletion :
    ‖(((p : ℕ) : ℕ) :
        ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)‖
      = ((p : ℕ) : ℝ)⁻¹ := by
  rw [FinitePlace.norm_def, valued_natCast_adicCompletion,
    WithZeroMulInt.toNNReal_neg_apply _ WithZero.exp_ne_zero]
  have hval : (WithZero.unzero (WithZero.exp_ne_zero (a := (-1 : ℤ)))).toAdd = (-1 : ℤ) := rfl
  rw [hval, absNorm_asIdeal_primesEquiv_symm]
  simp

/-- **Mathlib's comparison equivalence `ℚ_[p] ≃A[ℚ] ℚ_v` is an isometry.** -/
theorem norm_adicCompletionEquiv (y : ℚ_[p]) :
    ‖(adicCompletionEquiv (RingOfIntegers ℚ) p y :
        ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)‖
      = ‖y‖ := by
  set E := adicCompletionEquiv (RingOfIntegers ℚ) p with hE
  have hle : ∀ {y : ℚ_[p]}, ‖y‖ ≤ 1 → ‖(E y : ((Rat.HeightOneSpectrum.primesEquiv
      (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)‖ ≤ 1 := by
    intro y hy
    refine Valued.toNormedField.norm_le_one_iff.mpr ?_
    have hmem : (E (⟨y, hy⟩ : ℤ_[p]) : ((Rat.HeightOneSpectrum.primesEquiv
        (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)
        ∈ ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm
          p).adicCompletionIntegers ℚ := by
      have h := PadicInt.coe_adicCompletionIntegersEquiv_apply (RingOfIntegers ℚ) p ⟨y, hy⟩
      have h2 := SetLike.coe_mem (PadicInt.adicCompletionIntegersEquiv (RingOfIntegers ℚ) p
        ⟨y, hy⟩)
      rw [h] at h2
      exact h2
    exact (HeightOneSpectrum.mem_adicCompletionIntegers (RingOfIntegers ℚ) ℚ _).mp hmem
  have hone : ∀ {y : ℚ_[p]}, ‖y‖ = 1 → ‖(E y : ((Rat.HeightOneSpectrum.primesEquiv
      (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)‖ = 1 := by
    intro y hy
    have hy0 : y ≠ 0 := fun h => by simp [h] at hy
    have h1 := hle hy.le
    have h2 := hle (y := y⁻¹) (by rw [norm_inv, hy, inv_one])
    have h3 : ‖(E y : ((Rat.HeightOneSpectrum.primesEquiv
        (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)‖⁻¹ ≤ 1 := by
      rw [← norm_inv]
      exact le_of_eq_of_le (congrArg norm (map_inv₀ _ y).symm) h2
    have h0 : (0 : ℝ) < ‖(E y : ((Rat.HeightOneSpectrum.primesEquiv
        (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)‖ :=
      norm_pos_iff.mpr ((map_ne_zero_iff _ (EquivLike.injective _)).mpr hy0)
    exact le_antisymm h1 ((inv_le_one₀ h0).mp h3)
  rcases eq_or_ne y 0 with rfl | hy0
  · rw [map_zero, norm_zero, norm_zero]
  · have hp0 : ((p : ℕ) : ℚ_[p]) ≠ 0 := Nat.cast_ne_zero.mpr p.2.ne_zero
    have hpn : ‖((p : ℕ) : ℚ_[p])‖ = ((p : ℕ) : ℝ)⁻¹ := Padic.norm_p
    obtain ⟨n, hn⟩ : ∃ n : ℤ, n = y.valuation := ⟨_, rfl⟩
    have hy : ‖y‖ = ((p : ℕ) : ℝ) ^ (-n) := by
      rw [hn]
      exact Padic.norm_eq_zpow_neg_valuation hy0
    have hu1 : ‖y * ((p : ℕ) : ℚ_[p]) ^ (-n)‖ = 1 := by
      rw [norm_mul, norm_zpow, hpn, inv_zpow, hy]
      exact mul_inv_cancel₀ (zpow_ne_zero _ (Nat.cast_ne_zero.mpr p.2.ne_zero))
    have hfact : y = y * ((p : ℕ) : ℚ_[p]) ^ (-n) * ((p : ℕ) : ℚ_[p]) ^ n := by
      rw [mul_assoc, ← zpow_add₀ hp0, neg_add_cancel, zpow_zero, mul_one]
    have hEp : (E ((p : ℕ) : ℚ_[p]) : ((Rat.HeightOneSpectrum.primesEquiv
        (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ) = ((p : ℕ) : _) := map_natCast _ _
    calc ‖(E y : ((Rat.HeightOneSpectrum.primesEquiv
          (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ)‖
        = ‖E (y * ((p : ℕ) : ℚ_[p]) ^ (-n)) * E (((p : ℕ) : ℚ_[p]) ^ n)‖ := by
          rw [← map_mul, ← hfact]
      _ = ‖E (y * ((p : ℕ) : ℚ_[p]) ^ (-n))‖ * ‖E (((p : ℕ) : ℚ_[p]) ^ n)‖ := norm_mul _ _
      _ = 1 * ‖((p : ℕ) : ((Rat.HeightOneSpectrum.primesEquiv
            (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ) ^ n‖ := by
          rw [hone hu1, map_zpow₀, hEp]
      _ = (((p : ℕ) : ℝ)⁻¹) ^ n := by rw [one_mul, norm_zpow, norm_natCast_adicCompletion]
      _ = ‖y‖ := by rw [hy, inv_zpow, zpow_neg]

/-- The inverse comparison equivalence is an isometry. -/
theorem norm_adicCompletionEquiv_symm
    (x : ((Rat.HeightOneSpectrum.primesEquiv (R := RingOfIntegers ℚ)).symm p).adicCompletion ℚ) :
    ‖(adicCompletionEquiv (RingOfIntegers ℚ) p).symm x‖ = ‖x‖ := by
  conv_rhs => rw [← (adicCompletionEquiv (RingOfIntegers ℚ) p).apply_symm_apply x]
  exact (norm_adicCompletionEquiv p _).symm

end Padic
