/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import PhD.JacobsSlash.U3.«1_Hurwitz»
import PhD.JacobsSlash.U3.«1_Setting»
import PhD.QMF.UpiElement

/-!
# The level structures `U₀(1)` and `U₁(9)`, and class number one

[Jacobs, Definition 1.20 pp. 15]: `U₀(1) = ∏_q X_q` with `X_q = GL₂(ℤ_q)` for `q ≠ 2`
(under the fixed identifications `θ_q`) and `X₂` the units of a maximal order of `D₂`;
`U₁(9)` refines the component at `3` to

> "W_p = {(a b; c d) ∈ GL₂(Z_p) : (a b; c d) ≡ (∗ ∗; 0 1) mod pⁿ}"  (p = 3, n = 2).

Both are `(𝓞_D ⊗ ẑ)`-unit groups away from the congruence: we define them
identification-free as the unit groups of the integral model `hurwitzOrder ⊗ 𝓞_v` inside
`D ⊗ F_v`, with the mod-`9` condition at `v₃` imposed through `toMatrix`/`Sigma1`.

The file also states the class-number-one input:

* `HClassNumberOne` — the statement `D_f^× = D^× · U₀(1)` ([Jacobs, Lemma 1.22 (1.4.4)]).
  The thesis proves it by Jacquet–Langlands ("we know that there are no cusp forms of
  weight 2"); that argument is out of scope.  It is instead **proven** in
  `PhD/JacobsSlash/CN1/` via the classical route ([Voight GTM 288]: the Hurwitz order is
  norm-Euclidean 11.3.2 → right ideals principal 11.3.4 → idelic dictionary 27.6.8):
  `JacobsSlash.hClassNumberOne` in `CN1/«4_Dictionary»` is sorry-free on standard
  axioms.  (History: a 2026-08-05 plan deferred this to FLT's `completed_units`; the FLT
  project dropped its Hurwitz material, so the in-repo proof was completed 2026-08-10 —
  board `.mathlib-quality/hurwitz-cn1/`.  The pre-existing sketch
  `PhD/Jacobs/U3/ClassNumberOneFallback.lean` is legacy, unimported.)  Consumers still
  take `HClassNumberOne` as an explicit hypothesis; discharge it with
  `JacobsSlash.hClassNumberOne`.

## Main definitions

* `JacobsSlash.localOrder`: the local integral model of the Hurwitz order at a finite place.
* `JacobsSlash.U0`, `JacobsSlash.U1_9`: the adelic level subgroups `U₀(1)` and `U₁(9)`
  [Jacobs, Def 1.20].
* `JacobsSlash.integralMatrices`: the `2×2` matrices over `K₃` with integral entries.

## Main results

* `JacobsSlash.theta_localOrder`: `θ₃` carries the local order at `3` onto the integral
  matrices.
* `JacobsSlash.mem_hurwitzOrder_of_forall_local`: integral at every place ⟹ Hurwitz-integral.
* `JacobsSlash.unitsIncl_mem_U0_iff`: [Jacobs, (1.4.7)] — `D^× ∩ U₀(1) = 𝓞_D^×`.
* `JacobsSlash.mem_U0_of_toMatrix`, `JacobsSlash.mem_U1_9_of_toMatrix`: the componentwise
  membership criteria the class-set argument consumes.
* `JacobsSlash.HClassNumberOne`: the class-number-one statement, as a `Prop`; the
  theorem `hClassNumberOne` proving it lives in `PhD/JacobsSlash/CN1/«4_Dictionary»`
  (the FLT deferral was cancelled 2026-08-10 — see the note at the end of this file).
-/

open Quaternion IsDedekindDomain NumberField QMF
open scoped TensorProduct

/- See `Setting.lean`: the adic `Algebra ℚ K₃` path is the one the `QMF` framework uses,
and pinning it here keeps `theta`'s domain syntactically equal to `localOrder v₃`'s. -/
attribute [local instance 2000]
  IsDedekindDomain.HeightOneSpectrum.instAlgebraAdicCompletion

namespace JacobsSlash

/-- The local integral model of the Hurwitz order at a finite place `w`: the subring of
`D ⊗[ℚ] F_w` generated by the image of `hurwitzOrder` together with the local integers
`𝓞_w`.  Equivalently `𝓞_D ⊗_ℤ 𝓞_w`, presented as a `Subring.closure` so that membership
proofs go through `Subring.closure_induction` / `Subring.subset_closure`. -/
noncomputable def localOrder (w : HeightOneSpectrum (RingOfIntegers ℚ)) :
    Subring (D ⊗[ℚ] w.adicCompletion ℚ) :=
  Subring.closure
    ((Algebra.TensorProduct.includeLeftRingHom : D →+* D ⊗[ℚ] w.adicCompletion ℚ) ''
        hurwitzOrder ∪
      Set.range (fun z : w.adicCompletionIntegers ℚ =>
        Algebra.TensorProduct.includeRight (R := ℚ) (A := D) ((z : w.adicCompletion ℚ))))

/-- The generators of `localOrder` lie in it: the image of a Hurwitz quaternion. -/
theorem includeLeft_mem_localOrder {w : HeightOneSpectrum (RingOfIntegers ℚ)}
    {d : D} (hd : d ∈ hurwitzOrder) :
    (Algebra.TensorProduct.includeLeftRingHom : D →+* D ⊗[ℚ] w.adicCompletion ℚ) d
      ∈ localOrder w :=
  Subring.subset_closure (Or.inl ⟨d, hd, rfl⟩)

/-- The generators of `localOrder` lie in it: a local integer. -/
theorem includeRight_mem_localOrder {w : HeightOneSpectrum (RingOfIntegers ℚ)}
    (z : w.adicCompletionIntegers ℚ) :
    Algebra.TensorProduct.includeRight (R := ℚ) (A := D) ((z : w.adicCompletion ℚ))
      ∈ localOrder w :=
  Subring.subset_closure (Or.inr ⟨z, rfl⟩)

/-- The generators `i`, `j`, `k` are Hurwitz quaternions (integral coordinates).  Stated
here rather than in `Hurwitz.lean`, which is deliberately kept independent of `Setting`. -/
@[simp] theorem qi_mem : qi ∈ hurwitzOrder :=
  ⟨0, 2, 0, 0, by simp, by simp, by simp, by simp, by norm_num, by norm_num, by norm_num⟩

@[simp] theorem qj_mem : qj ∈ hurwitzOrder :=
  ⟨0, 0, 2, 0, by simp, by simp, by simp, by simp, by norm_num, by norm_num, by norm_num⟩

@[simp] theorem qk_mem : qk ∈ hurwitzOrder :=
  ⟨0, 0, 0, 2, by simp, by simp, by simp, by simp, by norm_num, by norm_num, by norm_num⟩

/-- A pure tensor `d ⊗ z` with `d` Hurwitz and `z` a local integer lies in `localOrder`. -/
theorem tmul_mem_localOrder {w : HeightOneSpectrum (RingOfIntegers ℚ)} {d : D}
    (hd : d ∈ hurwitzOrder) (z : w.adicCompletionIntegers ℚ) :
    d ⊗ₜ[ℚ] ((z : w.adicCompletion ℚ)) ∈ localOrder w := by
  have h := (localOrder w).mul_mem (includeLeft_mem_localOrder (w := w) hd)
    (includeRight_mem_localOrder z)
  rwa [Algebra.TensorProduct.includeLeftRingHom_apply,
    Algebra.TensorProduct.includeRight_apply, Algebra.TensorProduct.tmul_mul_tmul,
    mul_one, one_mul] at h

/-- Norm `1` upgrades to valuation `1`.  (The `Valued`-to-norm bridge in the direction
the `Σ₀`/`Σ₁` unit conditions need; `Valued.toNormedField.norm_le_one_iff` supplies the
`≤` half in both directions.) -/
theorem valued_eq_one_of_norm_eq_one {x : K₃} (hx : ‖x‖ = 1) : Valued.v x = 1 := by
  refine le_antisymm (Valued.toNormedField.norm_le_one_iff.mp hx.le) ?_
  refine le_of_not_gt fun hlt => ?_
  have hn := Valued.toNormedField.norm_lt_one_iff.mpr hlt
  rw [hx] at hn
  exact lt_irrefl 1 hn

/-- The integral matrices over `𝓞₃` form a subring of `M₂(K₃)`.  Stated with the norm
(`‖·‖ ≤ 1`) rather than `Valued.v` so that the ultrametric API applies directly;
`mem_integralMatrices_iff` is the `adicCompletionIntegers` form. -/
def integralMatrices : Subring (Matrix (Fin 2) (Fin 2) K₃) where
  carrier := {g | ∀ i j, ‖g i j‖ ≤ 1}
  zero_mem' i j := by simp
  one_mem' i j := by
    rcases eq_or_ne i j with rfl | h
    · simp [Matrix.one_apply_eq]
    · simp [Matrix.one_apply_ne h]
  add_mem' {a b} ha hb i j :=
    (IsUltrametricDist.norm_add_le_max _ _).trans (max_le (ha i j) (hb i j))
  neg_mem' {a} ha i j := by simpa [Matrix.neg_apply] using ha i j
  mul_mem' {a b} ha hb i j := by
    rw [Matrix.mul_apply, Fin.sum_univ_two]
    refine (IsUltrametricDist.norm_add_le_max _ _).trans (max_le ?_ ?_) <;>
      · rw [norm_mul]
        exact mul_le_one₀ (by first | exact ha i 0 | exact ha i 1) (norm_nonneg _)
          (by first | exact hb 0 j | exact hb 1 j)

/-- Membership in `integralMatrices` is entrywise membership of `𝓞₃`. -/
theorem mem_integralMatrices_iff {g : Matrix (Fin 2) (Fin 2) K₃} :
    g ∈ integralMatrices ↔ ∀ i j, g i j ∈ v₃.adicCompletionIntegers ℚ :=
  forall_congr' fun _ => forall_congr' fun _ => Valued.toNormedField.norm_le_one_iff

/-- Ultrametric bound for the three-term entries of `θ₃` on a quaternion. -/
private theorem norm_add₃_le_one {x y z : K₃} (hx : ‖x‖ ≤ 1) (hy : ‖y‖ ≤ 1)
    (hz : ‖z‖ ≤ 1) : ‖x + y + z‖ ≤ 1 :=
  (IsUltrametricDist.norm_add_le_max _ _).trans
    (max_le ((IsUltrametricDist.norm_add_le_max _ _).trans (max_le hx hy)) hz)

/-- `θ₃` as a plain ring homomorphism.  (`RigidificationAt.equiv` at `v₃` *is*
`theta ν₃ sq_ν₃` — see the instance in `Setting.lean` — so `theta3` computes.) -/
noncomputable def theta3 :=
  RingEquivClass.toRingEquiv (RigidificationAt.equiv (F := ℚ) (D := D) (v := v₃))

theorem theta3_apply (x : D ⊗[ℚ] K₃) : theta3 x = theta ν₃ sq_ν₃ x := rfl

/-- **B07a**: `θ₃` carries the local order into the integral matrices.

The preimage of a subring under a ring hom is a subring, so `Subring.closure_le` reduces
the statement to the two generator families of `localOrder`.  For a Hurwitz quaternion the
entries of `θ₃(d ⊗ 1)` are `ℤ`-combinations of `1` and `ν₃` with denominator `2`, integral
because `ν₃` and `2⁻¹` both are (`norm_ν₃`, `norm_algebraMap_half_le_one`); for a local
integer `z`, `θ₃(1 ⊗ z)` is the scalar matrix `z·1`. -/
theorem theta_localOrder_subset :
    ∀ x ∈ localOrder v₃, theta3 x ∈ integralMatrices := by
  have key : localOrder v₃ ≤ integralMatrices.comap theta3 := by
    rw [localOrder, Subring.closure_le]
    rintro y (⟨d, hd, rfl⟩ | ⟨z, rfl⟩)
    · obtain ⟨A, B, C, E, hre, himI, himJ, himK, -, -, -⟩ := hd
      have hA := norm_algebraMap_half_le_one A
      have hB := norm_algebraMap_half_le_one B
      have hC := norm_algebraMap_half_le_one C
      have hE := norm_algebraMap_half_le_one E
      rw [← hre] at hA
      rw [← himI] at hB
      rw [← himJ] at hC
      rw [← himK] at hE
      have hBν : ‖algebraMap ℚ K₃ d.imI * ν₃‖ ≤ 1 := by
        rw [norm_mul, norm_ν₃, mul_one]; exact hB
      have hEν : ‖algebraMap ℚ K₃ d.imK * ν₃‖ ≤ 1 := by
        rw [norm_mul, norm_ν₃, mul_one]; exact hE
      show theta ν₃ sq_ν₃ (d ⊗ₜ[ℚ] (1 : K₃)) ∈ integralMatrices
      rw [theta_tmul_one]
      intro r c
      fin_cases r <;> fin_cases c <;>
        simp only [Matrix.of_apply, Matrix.cons_val', Matrix.empty_val',
          Matrix.cons_val_fin_one, sub_eq_add_neg]
      · exact norm_add₃_le_one hA hBν hE
      · exact norm_add₃_le_one hB (by simpa using hC) (by simpa using hEν)
      · exact norm_add₃_le_one hB hC (by simpa using hEν)
      · exact norm_add₃_le_one hA (by simpa using hBν) (by simpa using hE)
    · have hz : ‖(z : K₃)‖ ≤ 1 := Valued.toNormedField.norm_le_one_iff.mpr z.2
      show theta ν₃ sq_ν₃ ((1 : D) ⊗ₜ[ℚ] (z : K₃)) ∈ integralMatrices
      rw [theta_one_tmul]
      intro r c
      fin_cases r <;> fin_cases c
      · simpa using hz
      · simp
      · simp
      · simpa using hz
  exact fun x hx => key hx

/-- `θ₃` on a general pure tensor: the right factor is central, so it comes out as a
scalar multiple of the quaternion matrix of `theta_tmul_one`. -/
private theorem theta_tmul (d : D) (z : K₃) :
    theta ν₃ sq_ν₃ (d ⊗ₜ[ℚ] z) =
      z • !![algebraMap ℚ K₃ d.re + algebraMap ℚ K₃ d.imI * ν₃ + algebraMap ℚ K₃ d.imK,
              algebraMap ℚ K₃ d.imI - algebraMap ℚ K₃ d.imJ - algebraMap ℚ K₃ d.imK * ν₃;
             algebraMap ℚ K₃ d.imI + algebraMap ℚ K₃ d.imJ - algebraMap ℚ K₃ d.imK * ν₃,
              algebraMap ℚ K₃ d.re - algebraMap ℚ K₃ d.imI * ν₃ - algebraMap ℚ K₃ d.imK]
        := by
  rw [show d ⊗ₜ[ℚ] z = (d ⊗ₜ[ℚ] (1 : K₃)) * ((1 : D) ⊗ₜ[ℚ] z) by
        rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul],
    map_mul, theta_one_tmul, theta_tmul_one]
  refine Matrix.ext fun r c => ?_
  fin_cases r <;> fin_cases c <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two, mul_comm]

/-- **Jacobs's explicit inverse** [§B.1 p. 44 `th1`, at `ξ = 1`]: the `θ₃`-preimage of a
matrix `m`, written in the `1, i, j, k` basis with coefficients in `K₃`.  Every coefficient
has denominator `2` and involves `ν₃` linearly — both units at `3`, which is why the
preimage of an *integral* matrix is again integral (`preimage_mem_localOrder`). -/
private noncomputable def preimage (m : Matrix (Fin 2) (Fin 2) K₃) : D ⊗[ℚ] K₃ :=
  (1 : D) ⊗ₜ[ℚ] ((m 0 0 + m 1 1) / 2)
    + qi ⊗ₜ[ℚ] (((m 1 1 - m 0 0) * ν₃ - (m 0 1 + m 1 0)) / 2)
    + qj ⊗ₜ[ℚ] ((m 1 0 - m 0 1) / 2)
    + qk ⊗ₜ[ℚ] (((m 1 1 - m 0 0) + (m 0 1 + m 1 0) * ν₃) / 2)

@[simp] private theorem one_re : (1 : D).re = 1 := rfl
@[simp] private theorem one_imI : (1 : D).imI = 0 := rfl
@[simp] private theorem one_imJ : (1 : D).imJ = 0 := rfl
@[simp] private theorem one_imK : (1 : D).imK = 0 := rfl

private theorem theta_preimage (m : Matrix (Fin 2) (Fin 2) K₃) :
    theta ν₃ sq_ν₃ (preimage m) = m := by
  simp only [preimage, map_add, theta_tmul]
  refine Matrix.ext fun r c => ?_
  fin_cases r <;> fin_cases c <;>
    simp only [Matrix.add_apply, Matrix.smul_apply, Matrix.of_apply, Matrix.cons_val',
      Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.empty_val',
      Matrix.cons_val_fin_one, Fin.zero_eta, Fin.mk_one, Fin.isValue,
      smul_eq_mul, qi_re, qi_imI, qi_imJ,
      qi_imK, qj_re, qj_imI, qj_imJ, qj_imK, qk_re, qk_imI, qk_imJ, qk_imK,
      one_re, one_imI, one_imJ, one_imK, map_zero, map_one, zero_mul, mul_zero, zero_add,
      add_zero, sub_zero, zero_sub, one_mul, mul_one]
  · linear_combination (m 1 1 - m 0 0) / 2 * sq_ν₃
  · linear_combination (-(m 0 1) - m 1 0) / 2 * sq_ν₃
  · linear_combination (-(m 0 1) - m 1 0) / 2 * sq_ν₃
  · linear_combination (m 0 0 - m 1 1) / 2 * sq_ν₃

private theorem norm_div_two_le_one {x : K₃} (hx : ‖x‖ ≤ 1) : ‖x / 2‖ ≤ 1 := by
  rw [norm_div, norm_two_eq_one, div_one]; exact hx

/-- **B07b**: the preimage of an integral matrix lies in the local order. -/
private theorem preimage_mem_localOrder {m : Matrix (Fin 2) (Fin 2) K₃}
    (hm : m ∈ integralMatrices) : preimage m ∈ localOrder v₃ := by
  have hmem : ∀ x : K₃, ‖x‖ ≤ 1 → x ∈ v₃.adicCompletionIntegers ℚ := fun _ h =>
    Valued.toNormedField.norm_le_one_iff.mp h
  have hmul : ∀ x : K₃, ‖x‖ ≤ 1 → ‖x * ν₃‖ ≤ 1 := fun x hx => by
    rw [norm_mul, norm_ν₃, mul_one]; exact hx
  have hadd := fun (x y : K₃) (hx : ‖x‖ ≤ 1) (hy : ‖y‖ ≤ 1) =>
    (IsUltrametricDist.norm_add_le_max x y).trans (max_le hx hy)
  have hsub := fun (x y : K₃) (hx : ‖x‖ ≤ 1) (hy : ‖y‖ ≤ 1) =>
    (JacobsSlash.norm_sub_le_max' x y).trans (max_le hx hy)
  refine (localOrder v₃).add_mem ((localOrder v₃).add_mem ((localOrder v₃).add_mem
    (tmul_mem_localOrder (Subring.one_mem _) ⟨_, hmem _ ?_⟩)
    (tmul_mem_localOrder qi_mem ⟨_, hmem _ ?_⟩))
    (tmul_mem_localOrder qj_mem ⟨_, hmem _ ?_⟩))
    (tmul_mem_localOrder qk_mem ⟨_, hmem _ ?_⟩)
  · exact norm_div_two_le_one (hadd _ _ (hm 0 0) (hm 1 1))
  · exact norm_div_two_le_one
      (hsub _ _ (hmul _ (hsub _ _ (hm 1 1) (hm 0 0))) (hadd _ _ (hm 0 1) (hm 1 0)))
  · exact norm_div_two_le_one (hsub _ _ (hm 1 0) (hm 0 1))
  · exact norm_div_two_le_one
      (hadd _ _ (hsub _ _ (hm 1 1) (hm 0 0)) (hmul _ (hadd _ _ (hm 0 1) (hm 1 0))))

/-- At `w = v₃`, the rigidification carries the local order **onto** `M₂(𝓞₃)`:
`θ₃ (localOrder v₃) = M₂(𝓞₃)`.  (This is what makes the `Σ₀`-conditions at `3` express
integrality; `θ₃` is integral because `ν₃ ∈ 𝓞₃` and `2` is a unit at `3`, and surjective
onto the integral matrices by Jacobs's inverse `th1`.) -/
theorem theta_localOrder :
    theta3 '' (localOrder v₃) = {g | ∀ i j, g i j ∈ v₃.adicCompletionIntegers ℚ} := by
  refine Set.Subset.antisymm ?_ fun m hm => ?_
  · rintro _ ⟨x, hx, rfl⟩
    exact mem_integralMatrices_iff.mp (theta_localOrder_subset x hx)
  · exact ⟨preimage m, preimage_mem_localOrder (mem_integralMatrices_iff.mpr hm),
      theta_preimage m⟩

/-- `U₀(1) ⊆ D_f^×` [Jacobs, Def 1.20]: adelic units integral at every place — the unit
group of the integral model `hurwitzOrder ⊗ ẑ`.  Component-wise: `g_w ∈ (localOrder w)ˣ`
for every `w`. -/
noncomputable def U0 : Subgroup (Dfx ℚ D) where
  carrier := {g | ∀ w : HeightOneSpectrum (RingOfIntegers ℚ),
    toLocal ℚ D w (g : D ⊗[ℚ] FiniteAdeleRing (RingOfIntegers ℚ) ℚ) ∈ localOrder w ∧
      toLocal ℚ D w ((g⁻¹ : Dfx ℚ D) : D ⊗[ℚ] FiniteAdeleRing (RingOfIntegers ℚ) ℚ)
        ∈ localOrder w}
  one_mem' w := by
    refine ⟨?_, ?_⟩ <;>
      · simp only [Units.val_one, inv_one, map_one]
        exact (localOrder w).one_mem
  mul_mem' {g h} hg hh w := by
    refine ⟨?_, ?_⟩
    · rw [Units.val_mul, map_mul]
      exact (localOrder w).mul_mem (hg w).1 (hh w).1
    · rw [mul_inv_rev, Units.val_mul, map_mul]
      exact (localOrder w).mul_mem (hh w).2 (hg w).2
  inv_mem' {g} hg w := ⟨(hg w).2, by simpa using (hg w).1⟩

/-- `U₁(9) ⊆ U₀(1)` [Jacobs, Def 1.20]: the mod-`9` congruence `≡ (∗ ∗; 0 1)` at `3`
(in the left-handed matrix picture: `toMatrix g ∈ Σ₁(9)` together with integral
invertibility at `3`).  (The underscore transcribes the thesis name `U₁(9)`; kept on
purpose — `nolint defsWithUnderscore`.) -/
@[nolint defsWithUnderscore]
noncomputable def U1_9 : Subgroup (Dfx ℚ D) where
  carrier := {g | g ∈ U0 ∧ toMatrix ℚ D v₃ g ∈ Sigma1 ∧ toMatrix ℚ D v₃ (g⁻¹) ∈ Sigma1}
  one_mem' := by
    refine ⟨U0.one_mem, ?_, ?_⟩
    · simp
    · rw [inv_one]; simp
  mul_mem' {g h} hg hh := by
    refine ⟨U0.mul_mem hg.1 hh.1, ?_, ?_⟩
    · rw [map_mul]; exact Sigma1.mul_mem hg.2.1 hh.2.1
    · rw [mul_inv_rev, map_mul]; exact Sigma1.mul_mem hh.2.2 hg.2.2
  inv_mem' {g} hg := ⟨U0.inv_mem hg.1, hg.2.2, by simpa using hg.2.1⟩

theorem U1_9_le_U0 : U1_9 ≤ U0 := fun _ hg => hg.1

/-- The wild-level inclusion required by the `QMF` framework: `U₁(9) ⊆ Δ' = levelMonoid'`,
i.e. the `3`-component of a level element lies in `Σ₀´(v(9))`. -/
theorem U1_9_subset_levelMonoid :
    (U1_9 : Set (Dfx ℚ D)) ⊆ levelMonoid' ℚ D v₃ γ₉ γ₉_lt_one :=
  fun _ hg => sigma1_le_sigma0' hg.2.1

/-- Sharper: the `3`-component of a level element lies in `Σ₁(9) ⊆ Σ₀` (the congruence
form the `κ`-action needs). -/
theorem toMatrix_mem_sigma1_of_mem_U1_9 {g : Dfx ℚ D} (hg : g ∈ U1_9) :
    toMatrix ℚ D v₃ g ∈ Sigma1 := hg.2.1

/-- Hurwitz's `ω = ½(1 + i + j + k)` [Jacobs p. 22]: the generator that distinguishes the
Hurwitz order from the Lipschitz order `ℤ⟨i,j⟩`. -/
def qomega : D := ⟨1 / 2, 1 / 2, 1 / 2, 1 / 2⟩

@[simp] theorem qomega_re : qomega.re = 1 / 2 := rfl
@[simp] theorem qomega_imI : qomega.imI = 1 / 2 := rfl
@[simp] theorem qomega_imJ : qomega.imJ = 1 / 2 := rfl
@[simp] theorem qomega_imK : qomega.imK = 1 / 2 := rfl

@[simp] theorem qomega_mem : qomega ∈ hurwitzOrder :=
  ⟨1, 1, 1, 1, by norm_num, by norm_num, by norm_num, by norm_num, rfl, rfl, rfl⟩

/-- The coordinates of a quaternion against `1, i, j, ω`. -/
def hurwitzCoord (d : D) : Fin 4 → ℚ :=
  ![d.re - d.imK, d.imI - d.imK, d.imJ - d.imK, 2 * d.imK]

/-- The Hurwitz condition in coordinate form: integrality of `d.re − d.imK`,
`d.imI − d.imK`, `d.imJ − d.imK` and `2 d.imK` — the coefficients of `d` against
`1, i, j, ω`.  (`IsHurwitz`'s equal-parity condition on `(A,B,C,E)/2` is exactly
integrality of the first three, with `c₃ = E`.) -/
theorem mem_hurwitzOrder_iff_isInt {d : D} :
    d ∈ hurwitzOrder ↔ (∃ z : ℤ, d.re - d.imK = (z : ℚ)) ∧ (∃ z : ℤ, d.imI - d.imK = (z : ℚ))
      ∧ (∃ z : ℤ, d.imJ - d.imK = (z : ℚ)) ∧ ∃ z : ℤ, 2 * d.imK = (z : ℚ) := by
  constructor
  · rintro ⟨A, B, C, E, hre, himI, himJ, himK, hAB, hBC, hCD⟩
    obtain ⟨a, ha⟩ : ∃ a : ℤ, A = 2 * a + E := ⟨(A - E) / 2, by omega⟩
    obtain ⟨b, hb⟩ : ∃ b : ℤ, B = 2 * b + E := ⟨(B - E) / 2, by omega⟩
    obtain ⟨c, hc⟩ : ∃ c : ℤ, C = 2 * c + E := ⟨(C - E) / 2, by omega⟩
    subst ha hb hc
    refine ⟨⟨a, ?_⟩, ⟨b, ?_⟩, ⟨c, ?_⟩, ⟨E, ?_⟩⟩
    · rw [hre, himK]; push_cast; ring
    · rw [himI, himK]; push_cast; ring
    · rw [himJ, himK]; push_cast; ring
    · rw [himK]; ring
  · rintro ⟨⟨a, ha⟩, ⟨b, hb⟩, ⟨c, hc⟩, ⟨e, he⟩⟩
    refine ⟨2 * a + e, 2 * b + e, 2 * c + e, e, ?_, ?_, ?_, ?_, by omega, by omega, by omega⟩
    · push_cast at he ⊢; linarith
    · push_cast; linarith
    · push_cast; linarith
    · linarith

/-- **B07c**: membership of the Hurwitz order is integrality of the `1, i, j, ω`
coordinates. -/
theorem mem_hurwitzOrder_iff_coords {d : D} :
    d ∈ hurwitzOrder ↔ ∀ n, ∃ z : ℤ, hurwitzCoord d n = (z : ℚ) := by
  rw [mem_hurwitzOrder_iff_isInt]
  constructor
  · rintro ⟨h0, h1, h2, h3⟩ n
    fin_cases n <;> simpa [hurwitzCoord]
  · intro h
    exact ⟨by simpa [hurwitzCoord] using h 0, by simpa [hurwitzCoord] using h 1,
      by simpa [hurwitzCoord] using h 2, by simpa [hurwitzCoord] using h 3⟩

/-- **B07e**: a rational that is integral at every finite place is a rational integer. -/
theorem isInt_of_forall_mem_adicCompletionIntegers {q : ℚ}
    (h : ∀ w : HeightOneSpectrum (RingOfIntegers ℚ),
      algebraMap ℚ (w.adicCompletion ℚ) q ∈ w.adicCompletionIntegers ℚ) :
    ∃ n : ℤ, q = (n : ℚ) := by
  have hval : ∀ w : HeightOneSpectrum (RingOfIntegers ℚ), w.valuation ℚ q ≤ 1 := fun w => by
    rw [← HeightOneSpectrum.valuedAdicCompletion_eq_valuation' (v := w) q,
      ← HeightOneSpectrum.mem_adicCompletionIntegers]
    exact h w
  obtain ⟨y, hy⟩ := HeightOneSpectrum.mem_integers_of_valuation_le_one (R := RingOfIntegers ℚ)
    (K := ℚ) q hval
  exact ⟨Rat.ringOfIntegersEquiv y, by rw [Rat.ringOfIntegersEquiv_apply_coe, hy]⟩

/-- The additive span of the pure tensors `d ⊗ z` with `d` Hurwitz and `z` a local
integer — i.e. `𝓞_D ⊗_ℤ 𝓞_w` written additively.  Presented as an `AddSubmonoid` rather
than a `Submodule` over `𝓞_w`, which would need an algebra structure on `D ⊗ K_w` over the
valuation subring; the only closure property that then needs proof is multiplicativity,
and that follows from `hurwitzOrder` and `𝓞_w` already being rings. -/
noncomputable def localSpan (w : HeightOneSpectrum (RingOfIntegers ℚ)) :
    AddSubmonoid (D ⊗[ℚ] w.adicCompletion ℚ) :=
  AddSubmonoid.closure {x | ∃ d ∈ hurwitzOrder, ∃ z ∈ w.adicCompletionIntegers ℚ,
    x = d ⊗ₜ[ℚ] z}

theorem tmul_mem_localSpan {w : HeightOneSpectrum (RingOfIntegers ℚ)} {d : D}
    (hd : d ∈ hurwitzOrder) {z : w.adicCompletion ℚ}
    (hz : z ∈ w.adicCompletionIntegers ℚ) : d ⊗ₜ[ℚ] z ∈ localSpan w :=
  AddSubmonoid.subset_closure ⟨d, hd, z, hz, rfl⟩

private theorem localSpan_neg {w : HeightOneSpectrum (RingOfIntegers ℚ)}
    {x : D ⊗[ℚ] w.adicCompletion ℚ} (hx : x ∈ localSpan w) : -x ∈ localSpan w := by
  induction hx using AddSubmonoid.closure_induction with
  | mem a ha =>
      obtain ⟨d, hd, z, hz, rfl⟩ := ha
      rw [← TensorProduct.neg_tmul]
      exact tmul_mem_localSpan (neg_mem hd) hz
  | zero => simp
  | add u v _ _ h1 h2 => rw [neg_add]; exact add_mem h1 h2

private theorem localSpan_mul {w : HeightOneSpectrum (RingOfIntegers ℚ)}
    {x y : D ⊗[ℚ] w.adicCompletion ℚ} (hx : x ∈ localSpan w) (hy : y ∈ localSpan w) :
    x * y ∈ localSpan w := by
  induction hx using AddSubmonoid.closure_induction with
  | mem a ha =>
      obtain ⟨d₁, hd₁, z₁, hz₁, rfl⟩ := ha
      induction hy using AddSubmonoid.closure_induction with
      | mem b hb =>
          obtain ⟨d₂, hd₂, z₂, hz₂, rfl⟩ := hb
          rw [Algebra.TensorProduct.tmul_mul_tmul]
          exact tmul_mem_localSpan (hurwitzOrder.mul_mem hd₁ hd₂) (mul_mem hz₁ hz₂)
      | zero => simp
      | add u v _ _ h1 h2 => rw [mul_add]; exact add_mem h1 h2
  | zero => simp
  | add u v _ _ h1 h2 => rw [add_mul]; exact add_mem h1 h2

private noncomputable def localSubring (w : HeightOneSpectrum (RingOfIntegers ℚ)) :
    Subring (D ⊗[ℚ] w.adicCompletion ℚ) where
  carrier := localSpan w
  zero_mem' := zero_mem _
  one_mem' := tmul_mem_localSpan (Subring.one_mem _) (one_mem _)
  add_mem' := add_mem
  neg_mem' := localSpan_neg
  mul_mem' := localSpan_mul

/-- **B07d**: `localOrder w` consists of `𝓞_w`-combinations of Hurwitz quaternions.  (The
reverse inclusion also holds but is not needed.) -/
theorem localOrder_le_localSpan (w : HeightOneSpectrum (RingOfIntegers ℚ)) :
    ∀ x ∈ localOrder w, x ∈ localSpan w := by
  have h : localOrder w ≤ localSubring w := by
    rw [localOrder, Subring.closure_le]
    rintro y (⟨d, hd, rfl⟩ | ⟨z, rfl⟩)
    · exact tmul_mem_localSpan hd (one_mem _)
    · exact tmul_mem_localSpan (Subring.one_mem _) z.2
  exact fun x hx => h hx

/-- The `K_w`-valued extension of a `ℚ`-linear coordinate functional on `D`. -/
noncomputable def coordMap (w : HeightOneSpectrum (RingOfIntegers ℚ))
    (φ : D →ₗ[ℚ] ℚ) : D ⊗[ℚ] w.adicCompletion ℚ →ₗ[ℚ] w.adicCompletion ℚ :=
  TensorProduct.lift ((LinearMap.mul ℚ (w.adicCompletion ℚ)).comp
    ((Algebra.linearMap ℚ (w.adicCompletion ℚ)).comp φ))

@[simp] theorem coordMap_tmul {w : HeightOneSpectrum (RingOfIntegers ℚ)}
    (φ : D →ₗ[ℚ] ℚ) (d : D) (z : w.adicCompletion ℚ) :
    coordMap w φ (d ⊗ₜ[ℚ] z) = algebraMap ℚ (w.adicCompletion ℚ) (φ d) * z := rfl

theorem coordMap_mem_of_mem_localSpan {w : HeightOneSpectrum (RingOfIntegers ℚ)}
    (φ : D →ₗ[ℚ] ℚ) (hφ : ∀ d ∈ hurwitzOrder, ∃ n : ℤ, φ d = (n : ℚ))
    {x : D ⊗[ℚ] w.adicCompletion ℚ} (hx : x ∈ localSpan w) :
    coordMap w φ x ∈ w.adicCompletionIntegers ℚ := by
  induction hx using AddSubmonoid.closure_induction with
  | mem a ha =>
      obtain ⟨d, hd, z, hz, rfl⟩ := ha
      obtain ⟨n, hn⟩ := hφ d hd
      rw [coordMap_tmul, hn, map_intCast]
      exact mul_mem (Valued.toNormedField.norm_le_one_iff.mp
        (IsUltrametricDist.norm_intCast_le_one (R := w.adicCompletion ℚ) n)) hz
  | zero => simp
  | add u v _ _ h1 h2 => rw [map_add]; exact add_mem h1 h2

private def coordLin (a b c e : ℚ) : D →ₗ[ℚ] ℚ where
  toFun d := a * d.re + b * d.imI + c * d.imJ + e * d.imK
  map_add' x y := by simp; ring
  map_smul' r x := by simp; ring

/-- The `w`-component of a global unit is the pure tensor `x ⊗ 1`. -/
theorem toLocal_unitsIncl (x : Dˣ) (w : HeightOneSpectrum (RingOfIntegers ℚ)) :
    toLocal ℚ D w ((unitsIncl ℚ D x : Dfx ℚ D) :
        D ⊗[ℚ] FiniteAdeleRing (RingOfIntegers ℚ) ℚ)
      = (x : D) ⊗ₜ[ℚ] (1 : w.adicCompletion ℚ) := by
  show toLocal ℚ D w (Algebra.TensorProduct.includeLeftRingHom (x : D)) = _
  rw [Algebra.TensorProduct.includeLeftRingHom_apply, toLocal_tmul, map_one]

/-- **The crux of (1.4.7)**: a quaternion that is integral at every finite place is a
Hurwitz quaternion.  Each of the four `1, i, j, ω` coordinates is pulled out by a
`ℚ`-linear functional, extended to `D ⊗ K_w`; the extension carries `localOrder w` into
`𝓞_w` because the order is the `𝓞_w`-span of `𝓞_D` (`localOrder_le_localSpan`) and the
functional is `ℤ`-valued on `𝓞_D`.  A rational integral at every place is a rational
integer (`isInt_of_forall_mem_adicCompletionIntegers`). -/
theorem mem_hurwitzOrder_of_forall_local {d : D}
    (h : ∀ w : HeightOneSpectrum (RingOfIntegers ℚ),
      d ⊗ₜ[ℚ] (1 : w.adicCompletion ℚ) ∈ localOrder w) :
    d ∈ hurwitzOrder := by
  have key : ∀ φ : D →ₗ[ℚ] ℚ, (∀ e ∈ hurwitzOrder, ∃ n : ℤ, φ e = (n : ℚ)) →
      ∃ n : ℤ, φ d = (n : ℚ) := by
    intro φ hφ
    refine isInt_of_forall_mem_adicCompletionIntegers (q := φ d) fun w => ?_
    have hx := coordMap_mem_of_mem_localSpan φ hφ (localOrder_le_localSpan w _ (h w))
    rwa [coordMap_tmul, mul_one] at hx
  rw [mem_hurwitzOrder_iff_isInt]
  refine ⟨?_, ?_, ?_, ?_⟩
  · simpa [coordLin, sub_eq_add_neg] using key (coordLin 1 0 0 (-1))
      fun f hf => by simpa [coordLin, sub_eq_add_neg] using (mem_hurwitzOrder_iff_isInt.mp hf).1
  · simpa [coordLin, sub_eq_add_neg] using key (coordLin 0 1 0 (-1))
      fun f hf => by
        simpa [coordLin, sub_eq_add_neg] using (mem_hurwitzOrder_iff_isInt.mp hf).2.1
  · simpa [coordLin, sub_eq_add_neg] using key (coordLin 0 0 1 (-1))
      fun f hf => by
        simpa [coordLin, sub_eq_add_neg] using (mem_hurwitzOrder_iff_isInt.mp hf).2.2.1
  · simpa [coordLin] using key (coordLin 0 0 0 2)
      fun f hf => by simpa [coordLin] using (mem_hurwitzOrder_iff_isInt.mp hf).2.2.2

/-- `D^× ∩ U₀(1) = 𝓞_D^×` ([Jacobs, (1.4.7)]: "One easily verifies that
`O_D^× = D^× ∩ U₀(1)`"): a global quaternion is adelically integral and adelically
integrally-invertible iff it is a unit of the Hurwitz order.  ("Integral everywhere
locally ⟹ integral" for the lattice `𝓞_D ⊆ D`.) -/
theorem unitsIncl_mem_U0_iff (x : Dˣ) :
    unitsIncl ℚ D x ∈ U0 ↔ ∃ u : (hurwitzOrder)ˣ, ((u : hurwitzOrder) : ℍ[ℚ]) = (x : D) := by
  constructor
  · intro hx
    have hloc : ∀ (y : Dˣ), (∀ w : HeightOneSpectrum (RingOfIntegers ℚ),
        toLocal ℚ D w ((unitsIncl ℚ D y : Dfx ℚ D) :
          D ⊗[ℚ] FiniteAdeleRing (RingOfIntegers ℚ) ℚ) ∈ localOrder w) →
        (y : D) ∈ hurwitzOrder := fun y hy =>
      mem_hurwitzOrder_of_forall_local fun w => by
        have := hy w; rwa [toLocal_unitsIncl] at this
    have h1 : (x : D) ∈ hurwitzOrder := hloc x fun w => (hx w).1
    have h2 : ((x⁻¹ : Dˣ) : D) ∈ hurwitzOrder := hloc x⁻¹ fun w => by
      have := (hx w).2
      rwa [show ((unitsIncl ℚ D x)⁻¹ : Dfx ℚ D) = unitsIncl ℚ D x⁻¹ from (map_inv _ _).symm]
        at this
    exact ⟨⟨⟨(x : D), h1⟩, ⟨((x⁻¹ : Dˣ) : D), h2⟩,
      Subtype.ext (by simp), Subtype.ext (by simp)⟩, rfl⟩
  · rintro ⟨u, hu⟩ w
    have hmem : ∀ d : D, d ∈ hurwitzOrder →
        d ⊗ₜ[ℚ] (1 : w.adicCompletion ℚ) ∈ localOrder w := fun d hd => by
      simpa using tmul_mem_localOrder (w := w) hd 1
    refine ⟨?_, ?_⟩
    · rw [toLocal_unitsIncl]
      exact hmem _ (hu ▸ (u : hurwitzOrder).2)
    · rw [show ((unitsIncl ℚ D x)⁻¹ : Dfx ℚ D) = unitsIncl ℚ D x⁻¹ from (map_inv _ _).symm,
        toLocal_unitsIncl]
      refine hmem _ ?_
      have hxu : x = Units.map (Subring.subtype hurwitzOrder).toMonoidHom u := Units.ext hu.symm
      have hxinv : ((x⁻¹ : Dˣ) : D) = (((u⁻¹ : (hurwitzOrder)ˣ) : hurwitzOrder) : D) := by
        rw [hxu, ← map_inv]; rfl
      rw [hxinv]
      exact (u⁻¹ : (hurwitzOrder)ˣ).1.2

/-- The `θ₃`-preimage of an integral matrix lies in the local order (the useful form of
`theta_localOrder`). -/
theorem symm_mem_localOrder {m : Matrix (Fin 2) (Fin 2) K₃} (hm : m ∈ integralMatrices) :
    (RigidificationAt.equiv (F := ℚ) (D := D) (v := v₃)).symm m ∈ localOrder v₃ := by
  obtain ⟨x, hx, rfl⟩ :=
    (Set.ext_iff.mp theta_localOrder m).mpr (mem_integralMatrices_iff.mp hm)
  rwa [show theta3 x = RigidificationAt.equiv (F := ℚ) (D := D) (v := v₃) x from rfl,
    AlgEquiv.symm_apply_apply]

/-- A single-place unit at `3` whose matrix and inverse matrix are integral lies in
`U₀(1)`.  This is where `theta_localOrder` (B07a/B07b) is actually consumed: integrality
of the `θ₃`-matrix is what certifies membership of the local order at `3`, and away from
`3` the component is `1`. -/
theorem unitAt_mem_U0 {m : (Matrix (Fin 2) (Fin 2) K₃)ˣ}
    (hm : (m : Matrix (Fin 2) (Fin 2) K₃) ∈ integralMatrices)
    (hm' : ((m⁻¹ : (Matrix (Fin 2) (Fin 2) K₃)ˣ) : Matrix (Fin 2) (Fin 2) K₃)
      ∈ integralMatrices) :
    unitAt ℚ D v₃ m ∈ U0 := by
  intro w
  rcases eq_or_ne w v₃ with rfl | hw
  · exact ⟨by rw [toLocal_unitAt]; exact symm_mem_localOrder hm,
      by rw [unitAt_inv, toLocal_unitAt]; exact symm_mem_localOrder hm'⟩
  · exact ⟨by rw [toLocal_unitAt_ne _ _ _ _ hw]; exact (localOrder w).one_mem,
      by rw [unitAt_inv, toLocal_unitAt_ne _ _ _ _ hw]; exact (localOrder w).one_mem⟩

/-- The `U₁(9)` criterion for a single-place unit at `3`: integrality of both matrices
plus the mod-`9` congruence on both. -/
theorem unitAt_mem_U1_9 {m : (Matrix (Fin 2) (Fin 2) K₃)ˣ}
    (hm : (m : Matrix (Fin 2) (Fin 2) K₃) ∈ integralMatrices)
    (hm' : ((m⁻¹ : (Matrix (Fin 2) (Fin 2) K₃)ˣ) : Matrix (Fin 2) (Fin 2) K₃)
      ∈ integralMatrices)
    (hs : (m : Matrix (Fin 2) (Fin 2) K₃) ∈ Sigma1)
    (hs' : ((m⁻¹ : (Matrix (Fin 2) (Fin 2) K₃)ˣ) : Matrix (Fin 2) (Fin 2) K₃) ∈ Sigma1) :
    unitAt ℚ D v₃ m ∈ U1_9 :=
  ⟨unitAt_mem_U0 hm hm', by rw [toMatrix_unitAt]; exact hs,
    by rw [unitAt_inv, toMatrix_unitAt]; exact hs'⟩

/-- Componentwise criterion for `U₀(1)` membership: integrality away from `3`, and at `3`
integrality of the matrix and its inverse.  (At `3` the local-order condition is read off
the matrix through `symm_mem_localOrder`.) -/
theorem mem_U0_of_toMatrix {g : Dfx ℚ D}
    (hne : ∀ w : HeightOneSpectrum (RingOfIntegers ℚ), w ≠ v₃ →
      toLocal ℚ D w (g : D ⊗[ℚ] FiniteAdeleRing (RingOfIntegers ℚ) ℚ) ∈ localOrder w ∧
        toLocal ℚ D w ((g⁻¹ : Dfx ℚ D) : D ⊗[ℚ] FiniteAdeleRing (RingOfIntegers ℚ) ℚ)
          ∈ localOrder w)
    (hint : toMatrix ℚ D v₃ g ∈ integralMatrices)
    (hint' : toMatrix ℚ D v₃ g⁻¹ ∈ integralMatrices) :
    g ∈ U0 := by
  intro w
  rcases eq_or_ne w v₃ with rfl | hw
  · constructor
    · have h := symm_mem_localOrder hint
      rwa [toMatrix_apply, AlgEquiv.symm_apply_apply] at h
    · have h := symm_mem_localOrder hint'
      rwa [toMatrix_apply, AlgEquiv.symm_apply_apply] at h
  · exact hne w hw

/-- Componentwise criterion for `U₁(9)` membership: integrality away from `3`, and at `3`
integrality plus the mod-`9` congruence for the element and its inverse.  (At `3` the
local-order condition is read off the matrix through `symm_mem_localOrder`.) -/
theorem mem_U1_9_of_toMatrix {g : Dfx ℚ D}
    (hne : ∀ w : HeightOneSpectrum (RingOfIntegers ℚ), w ≠ v₃ →
      toLocal ℚ D w (g : D ⊗[ℚ] FiniteAdeleRing (RingOfIntegers ℚ) ℚ) ∈ localOrder w ∧
        toLocal ℚ D w ((g⁻¹ : Dfx ℚ D) : D ⊗[ℚ] FiniteAdeleRing (RingOfIntegers ℚ) ℚ)
          ∈ localOrder w)
    (hint : toMatrix ℚ D v₃ g ∈ integralMatrices)
    (hint' : toMatrix ℚ D v₃ g⁻¹ ∈ integralMatrices)
    (hs : toMatrix ℚ D v₃ g ∈ Sigma1) (hs' : toMatrix ℚ D v₃ g⁻¹ ∈ Sigma1) :
    g ∈ U1_9 :=
  ⟨mem_U0_of_toMatrix hne hint hint', hs, hs'⟩

/-- **The class-set input (1.4.4)** [Jacobs, Lemma 1.22]: `D_f^× = D^× · U₀(1)`.
Stated as a `Prop` so that downstream results can take it as an explicit hypothesis
until `hClassNumberOne` discharges it (the `T016` pattern). -/
def HClassNumberOne : Prop :=
  ∀ g : Dfx ℚ D, ∃ d ∈ globalUnits ℚ D, ∃ u ∈ U0, g = d * u

/- The theorem `hClassNumberOne : HClassNumberOne` — formerly a deliberate `sorry`
here, contracted to FLT's `completed_units` — now lives in
`PhD/JacobsSlash/CN1/«4_Dictionary».lean`: the FLT deferral was cancelled 2026-08-10
(the FLT project is dropping its Hurwitz material), and the in-repo route
([Voight GTM 288]: norm-Euclidean → right ideals principal → idelic dictionary) is
developed in `PhD/JacobsSlash/CN1/` (board `.mathlib-quality/hurwitz-cn1/`). -/

end JacobsSlash
