/-
Copyright (c) 2026 William Coram. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Coram
-/
import PhD.JacobsSlash.U3.«1_Setting»
import Mathlib.NumberTheory.Padics.Complex
import Mathlib.RingTheory.Ideal.Norm.AbsNorm
import Mathlib.RingTheory.Norm.Basic

/-!
# The isometric embedding `ιC : K₃ →+* ℂ₃`

The eigenvalue endgame reads off eigenvalues of `U₃` over the algebraically closed complete
field `ℂ₃ = ℂ_[3]`, while the whole `U3` development lives over the completed field
`K₃ = v₃.adicCompletion ℚ`.  This file provides the bridge: a ring embedding
`ιC : K₃ →+* ℂ_[3]` which is an **isometry**, so that norms — hence Newton polygons, hence
slopes — transport verbatim along the base change.

## Route

The primary route of the ticket landed.  `ιC` is the inverse of mathlib's comparison
equivalence `Padic.adicCompletionEquiv : ℚ_[3] ≃A[ℚ] K₃`
(`Mathlib/NumberTheory/Padics/HeightOneSpectrum.lean`) followed by
`algebraMap ℚ_[3] ℂ_[3]`; the second leg is isometric by `PadicComplex.norm_extends'`.
The isometry of the equiv leg is proved by a *valuation squeeze* rather than by density:

* the commuting square `PadicInt.coe_adicCompletionIntegersEquiv_apply` shows the equiv
  maps the closed unit ball of `ℚ_[3]` into `v₃.adicCompletionIntegers ℚ`, so units of
  `ℤ_[3]` land in elements of norm `1` (`Valued.toNormedField.norm_le_one_iff`);
* an arbitrary `y ≠ 0` factors as `y = u · 3ⁿ` with `‖u‖ = 1`
  (`Padic.norm_eq_zpow_neg_valuation`), which reduces everything to the single
  normalisation fact `‖(3 : K₃)‖ = 3⁻¹`;
* that fact is `FinitePlace.norm_def` at `valued_three_eq` (`1_Setting`), given
  `absNorm v₃.asIdeal = 3`, computed from `v₃.asIdeal = (3)` via
  `Ideal.absNorm_span_singleton` and `finrank ℤ (𝓞 ℚ) = 1`.

## Main declarations

* `JacobsSlash.norm_three_eq` : `‖(3 : K₃)‖ = 3⁻¹` — the `K₃` normalisation agrees with
  the standard `3`-adic one;
* `JacobsSlash.norm_adicCompletionEquiv` : mathlib's `ℚ_[3] ≃A[ℚ] K₃` is an isometry;
* `JacobsSlash.ιC : K₃ →+* ℂ_[3]` and `JacobsSlash.norm_ιC` : the isometric embedding.
-/

open IsDedekindDomain NumberField

open scoped NNReal

namespace JacobsSlash

/-- Mathlib's comparison equivalence `ℚ_[3] ≃A[ℚ] v₃.adicCompletion ℚ` at the prime `3`.
(No type ascription: the `Algebra ℚ K₃` instance baked into the mathlib term is
`instAlgebraAdicCompletion`, definitionally but not syntactically `DivisionRing.toRatAlgebra`;
element-level uses unify fine.) -/
private noncomputable def E₃ :=
  Padic.adicCompletionEquiv (R := RingOfIntegers ℚ) (⟨3, Nat.prime_three⟩ : Nat.Primes)

/-- The place `v₃` is generated by `3` (numerically).  (Also proved, `private`ly, in
`1_Setting`.) -/
private theorem natGenerator_v₃ : Rat.HeightOneSpectrum.natGenerator v₃ = 3 :=
  congrArg Subtype.val
    (Rat.HeightOneSpectrum.primesEquiv.apply_symm_apply (⟨3, Nat.prime_three⟩ : Nat.Primes))

/-- The prime `v₃` is the principal ideal `(3)`.  (Also proved, `private`ly, in
`1_Setting`.) -/
private theorem asIdeal_v₃ : v₃.asIdeal = Ideal.span {(3 : RingOfIntegers ℚ)} := by
  have hb := (Rat.IsIntegralClosure.intEquiv (RingOfIntegers ℚ)).bijective
  have h : v₃.asIdeal.map (Rat.IsIntegralClosure.intEquiv (RingOfIntegers ℚ))
      = Ideal.span {((3 : ℕ) : ℤ)} := by
    rw [← natGenerator_v₃]
    exact (Rat.HeightOneSpectrum.span_natGenerator v₃).symm
  have h2 : (Ideal.span {(3 : RingOfIntegers ℚ)}).map
      (Rat.IsIntegralClosure.intEquiv (RingOfIntegers ℚ)) = Ideal.span {((3 : ℕ) : ℤ)} := by
    rw [Ideal.map_span]
    simp [map_ofNat]
  rw [← v₃.asIdeal.comap_map_of_bijective _ hb, h, ← h2,
    Ideal.comap_map_of_bijective _ hb]

/-- The residue cardinality of the place `3` is `3`. -/
private theorem absNorm_asIdeal_v₃ : Ideal.absNorm v₃.asIdeal = 3 := by
  rw [asIdeal_v₃, Ideal.absNorm_span_singleton,
    show (3 : RingOfIntegers ℚ) = algebraMap ℤ (RingOfIntegers ℚ) 3 from (map_ofNat _ 3).symm,
    Algebra.norm_algebraMap, NumberField.RingOfIntegers.rank, Module.finrank_self]
  norm_num

/-- **The norm of `3` in `K₃` is `3⁻¹`**: the normed-field normalisation of `K₃` (base:
the residue cardinality `absNorm v₃.asIdeal = 3`) agrees with the standard `3`-adic
absolute value. -/
theorem norm_three_eq : ‖(3 : K₃)‖ = (3 : ℝ)⁻¹ := by
  have h : ‖(3 : K₃)‖ = ((WithZeroMulInt.toNNReal (HeightOneSpectrum.absNorm_ne_zero v₃)
      (Valued.v (3 : K₃)) : ℝ≥0) : ℝ) := FinitePlace.norm_def (v := v₃) (3 : K₃)
  rw [valued_three_eq] at h
  rw [h]
  have hval : WithZeroMulInt.toNNReal (HeightOneSpectrum.absNorm_ne_zero v₃)
      (WithZero.exp (-1 : ℤ)) = ((Ideal.absNorm v₃.asIdeal : ℝ≥0)) ^ (-1 : ℤ) := by
    rw [WithZeroMulInt.toNNReal_neg_apply _ WithZero.exp_ne_zero]
    rfl
  rw [hval, absNorm_asIdeal_v₃]
  push_cast
  norm_num

/-- The comparison equivalence maps the closed unit ball of `ℚ_[3]` into the `v₃`-adic
integers: the commuting square with `PadicInt.adicCompletionIntegersEquiv`. -/
private theorem valued_E₃_le_one (z : ℤ_[3]) : Valued.v ((E₃ (z : ℚ_[3])) : K₃) ≤ 1 := by
  have hmem : (E₃ (z : ℚ_[3]) : K₃) ∈ v₃.adicCompletionIntegers ℚ := by
    have h := PadicInt.coe_adicCompletionIntegersEquiv_apply (RingOfIntegers ℚ)
      (⟨3, Nat.prime_three⟩ : Nat.Primes) z
    have h2 := SetLike.coe_mem (PadicInt.adicCompletionIntegersEquiv (RingOfIntegers ℚ)
      (⟨3, Nat.prime_three⟩ : Nat.Primes) z)
    rw [h] at h2
    exact h2
  exact (HeightOneSpectrum.mem_adicCompletionIntegers (RingOfIntegers ℚ) ℚ v₃).mp hmem

private theorem norm_E₃_le_one {y : ℚ_[3]} (hy : ‖y‖ ≤ 1) : ‖(E₃ y : K₃)‖ ≤ 1 :=
  Valued.toNormedField.norm_le_one_iff.mpr (valued_E₃_le_one ⟨y, hy⟩)

private theorem norm_E₃_eq_one {y : ℚ_[3]} (hy : ‖y‖ = 1) : ‖(E₃ y : K₃)‖ = 1 := by
  have hy0 : y ≠ 0 := fun h => by simp [h] at hy
  have h1 : ‖(E₃ y : K₃)‖ ≤ 1 := norm_E₃_le_one hy.le
  have h2 : ‖(E₃ y⁻¹ : K₃)‖ ≤ 1 := norm_E₃_le_one (by rw [norm_inv, hy, inv_one])
  have h3 : ‖(E₃ y : K₃)‖⁻¹ ≤ 1 := by
    rw [← norm_inv]
    exact le_of_eq_of_le (congrArg norm (map_inv₀ _ y).symm) h2
  have h0 : (0 : ℝ) < ‖(E₃ y : K₃)‖ :=
    norm_pos_iff.mpr ((map_ne_zero_iff _ (EquivLike.injective _)).mpr hy0)
  exact le_antisymm h1 ((inv_le_one₀ h0).mp h3)

private theorem E₃_three : (E₃ (3 : ℚ_[3]) : K₃) = (3 : K₃) := map_ofNat _ 3

/-- **Mathlib's comparison equivalence `ℚ_[3] ≃A[ℚ] K₃` is an isometry.** -/
theorem norm_adicCompletionEquiv (y : ℚ_[3]) : ‖(E₃ y : K₃)‖ = ‖y‖ := by
  rcases eq_or_ne y 0 with rfl | hy0
  · rw [map_zero, norm_zero, norm_zero]
  · have h30 : (3 : ℚ_[3]) ≠ 0 := three_ne_zero
    have h3n : ‖(3 : ℚ_[3])‖ = (3 : ℝ)⁻¹ := by simpa using Padic.norm_p (p := 3)
    set n : ℤ := y.valuation with hn
    have hy : ‖y‖ = (3 : ℝ) ^ (-n) := by
      simpa using Padic.norm_eq_zpow_neg_valuation hy0
    have hu1 : ‖y * (3 : ℚ_[3]) ^ (-n)‖ = 1 := by
      rw [norm_mul, norm_zpow, h3n, inv_zpow, hy]
      exact mul_inv_cancel₀ (by positivity)
    have hEu : ‖(E₃ (y * (3 : ℚ_[3]) ^ (-n)) : K₃)‖ = 1 := norm_E₃_eq_one hu1
    have hfact : y = y * (3 : ℚ_[3]) ^ (-n) * (3 : ℚ_[3]) ^ n := by
      rw [mul_assoc, ← zpow_add₀ h30, neg_add_cancel, zpow_zero, mul_one]
    have hsplit : (E₃ y : K₃)
        = (E₃ (y * (3 : ℚ_[3]) ^ (-n)) : K₃) * (E₃ ((3 : ℚ_[3]) ^ n) : K₃) :=
      (congrArg (E₃ ·) hfact).trans (map_mul _ _ _)
    have hE3n : (E₃ ((3 : ℚ_[3]) ^ n) : K₃) = (3 : K₃) ^ n :=
      (map_zpow₀ E₃ (3 : ℚ_[3]) n).trans (congrArg (· ^ n) E₃_three)
    calc ‖(E₃ y : K₃)‖
        = ‖(E₃ (y * (3 : ℚ_[3]) ^ (-n)) : K₃) * (E₃ ((3 : ℚ_[3]) ^ n) : K₃)‖ := by
          rw [hsplit]
      _ = ‖(E₃ (y * (3 : ℚ_[3]) ^ (-n)) : K₃)‖ * ‖(E₃ ((3 : ℚ_[3]) ^ n) : K₃)‖ :=
          norm_mul _ _
      _ = 1 * ‖(3 : K₃) ^ n‖ := by rw [hEu, hE3n]; exact rfl
      _ = ((3 : ℝ)⁻¹) ^ n := by rw [one_mul, norm_zpow, norm_three_eq]
      _ = ‖y‖ := by rw [hy, inv_zpow, zpow_neg]

/-- The norm on `ℂ_[3]` restricted along `algebraMap ℚ_[3] ℂ_[3]` is the norm of
`ℚ_[3]`: `PadicComplex.norm_extends'` in `algebraMap` form. -/
private theorem norm_algebraMap_padicComplex (y : ℚ_[3]) :
    ‖algebraMap ℚ_[3] ℂ_[3] y‖ = ‖y‖ :=
  PadicComplex.norm_extends' 3 y

/-- **The isometric embedding of `K₃` into the `3`-adic complex numbers**: the inverse of
mathlib's comparison equivalence `Padic.adicCompletionEquiv : ℚ_[3] ≃A[ℚ] K₃` followed by
the canonical `algebraMap ℚ_[3] ℂ_[3]`. -/
noncomputable def ιC : K₃ →+* ℂ_[3] :=
  (algebraMap ℚ_[3] ℂ_[3]).comp E₃.symm.toAlgEquiv.toAlgHom.toRingHom

/-- **`ιC` is an isometry**: norms — hence Newton polygons, hence slopes — transport
verbatim from `K₃` to `ℂ₃`. -/
theorem norm_ιC (x : K₃) : ‖ιC x‖ = ‖x‖ := by
  have h2 : ‖x‖ = ‖(E₃.symm x : ℚ_[3])‖ :=
    (congrArg (fun t : K₃ => ‖t‖) (E₃.apply_symm_apply x).symm).trans
      (norm_adicCompletionEquiv (E₃.symm x))
  calc ‖ιC x‖ = ‖(E₃.symm x : ℚ_[3])‖ := norm_algebraMap_padicComplex _
    _ = ‖x‖ := h2.symm

end JacobsSlash
